### ISSUE TITLE
Batch claim update command for soon to expire claim 

### ISSUE THREAD

**Issue by kaykurokawa** [lbryio/lbry#1001]
We will create a batch claim update API command for soon to expire claims , 

Something like this:

Update a claim without changing the content of the claim value , or creating a stream. (Might get tricky if certificates are involved .. ). 

update( days_till_expiration_threshold  )

days_till_expiration_threshold - only update claims that are expiring within X number of days (assuming 2.5 min per block) 

Returns:
(list) List of dictionary containing result of the updated claims
{
'name': (str) name of claim (note that this field is not returned by lbryum update command)
'tx' : (str) hex encoded transaction
'txid' : (str) txid of resulting claim
'nout' : (int) nout of the resulting claim
'fee' : (float) fee paid for the claim transaction
'claim_id' : (str) claim ID of the resulting claim
}

**Comment by kaykurokawa** [comment]
Proposed API function by jack/jeremy

claim_renew(claim_ids,  expiration_threshold_days)

claim_ids - a list or a single claim id to renew, if None, renew all claims 
expiration_threshold_days - only update claims that are within this many days of expiring. 

Returns:
(list) List of dictionary containing result of the updated claims
{
'name': (str) name of claim (note that this field is not returned by lbryum update command)
'tx' : (str) hex encoded transaction
'txid' : (str) txid of resulting claim
'nout' : (int) nout of the resulting claim
'fee' : (float) fee paid for the claim transaction
'claim_id' : (str) claim ID of the resulting claim
}

**Comment by kauffj** [comment]
My original proposal was `claim_renew(claim_ids)` and `claim_renew_all(expiration_threshold_date)` (or `claim_renew_all(height_delta)`.

If `claim_renew` has a dual signature as proposed above (which I'm ambivalent about), it ought to be considered what the interaction is when both values are provided, particularly when a claim_id is provided that is not within the specified date window.

**Comment by jackrobison** [comment]
The proposed pattern for these commands is `claim_renew(outpoint=None, height=None)` where either `height` is given to renew all claims expiring before the given height, or `outpoint` is given to renew a specific claim.

**Comment by jackrobison** [comment]
Additionally, we'll need a new setting in `conf.py` to support auto-renewal on startup and after (with a looping call). I propose a `AUTO_RENEW_CLAIM_HEIGHT_DELTA` field with an int value (0 to disable).

**Comment by kauffj** [comment]
@jackrobison I'm for keeping startup as light as possible. Can some of these checks be deferred to some time after launch? (IMO reflector should be deferred as well).

**Comment by jackrobison** [comment]
@kauffj 

Yes, by "on startup" I mean start the looping call at that time - it shouldn't block.

**Comment by jackrobison** [comment]
merged https://github.com/lbryio/lbry/pull/1009
