### ISSUE TITLE
SOCKS5 proxy support

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1002]
@aayanl commented on [Fri Nov 17 2017](https://github.com/lbryio/lbry-app/issues/757)

I know a lot of people who would appreciate this option and using a proxy system wide is less than ideal

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
@aayanl - moved this over to the daemon side as most of the work would be on the protocol level. Since LBRY is a P2P network, some of the port/connectivity related functions, this change won't be trivial and will most likely end up on the lower spectrum of the priority list for the dev team. I see other torrent applications have similar settings, so it should be doable - want to take a shot yourself?

**Comment by aayanl** [comment]
sure

**Comment by eukreign** [comment]
we're using `aiorpcx` for the wallet, it understands the SOCKS4, SOCKS4a and SOCKS5 protocols, what else needs to be done to resolve this issue? @shyba

**Comment by shyba** [comment]
@eukreign P2P, DHT, maybe more... but I think it's possible. I would separate it in the libs used to provide a data transport:
- treq (not supported, but we can switch to aiohttp)
- aiohttp (aiosocks? there are other ways too, like a protocol wrapper)
- raw sockers (`check_connection`, although we can do something else for SOCKS case where we check the health of the proxy instead)
- Twisted (p2p protocol, may use a wrapper, but I'm unsure if it supports)
- asyncio in general (DHT is being ported, but we can do the same aiorpcx did, a protocol wrapper)

**Comment by lyoshenka** [comment]
will reopen when this gets closer to the top of the priority list
