### ISSUE TITLE
No error message for zero amount on wallet_send

### ISSUE THREAD

**Issue by IGassmann** [lbryio/lbry#1004]
## The Issue
When calling `wallet_send` with an `amount` set to `0`, the API doesn't return a complete error.

### Steps to reproduce
1. Use API call `wallet_send` with `amount`set to `0`and a valid `claim_id`or `address`.

### Expected behavior
A verbose error should be thrown noticing that an amount set to zero is invalid.

### Actual behavior
The returned error message is only `ERROR:`.

## System Configuration

```
{
  "id": null,
  "jsonrpc": "2.0",
  "result": {
    "build": "release",
    "lbrynet_version": "0.18.0",
    "lbryschema_version": "0.0.14",
    "lbryum_version": "3.1.11",
    "os_release": "16.7.0",
    "os_system": "Darwin",
    "platform": "Darwin-16.7.0-x86_64-i386-64bit",
    "processor": "i386",
    "python_version": "2.7.13"
  }
}
```

## Anything Else
Check out [this line](https://github.com/lbryio/lbry/blob/d0b2de9850db8253fd63ab25d8fc28a530c71244/lbrynet/daemon/Daemon.py#L2391)

## Screenshots
<img width="693" alt="screen shot 2017-11-22 at 09 59 19" src="https://user-images.githubusercontent.com/4291707/33128625-d74d95b2-cf6b-11e7-85e1-8da25b099792.png">

**Comment by jackrobison** [comment]
https://github.com/lbryio/lbry/pull/1019 fixes error responses to follow http://www.jsonrpc.org/specification#error_object
