### ISSUE TITLE
list claim type

### ISSUE THREAD

**Issue by reillysmith** [lbryio/lbry#1005]
## The Issue
Channels cannot host content from other channels in playlists or on their own channel to share/curate/support fellow channels.
### Steps to reproduce
1.
2.
3.

### Expected behaviour
A support-type claim that enables a channel to "own" channel claims or content claims that already exist, but the key fee still pays to the original claimant.

AKA playlists at blockchain level.

### Actual behaviour
Tell us what happens instead

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by jackrobison** [comment]
Issue moved to [lbryio/lbryschema #35](https://github.com/lbryio/lbryschema/issues/35) via [**ZenHub**](https://www.zenhub.com/)
