### ISSUE TITLE
lbry crashed with sigsegv in __start_google_malloc()

### ISSUE THREAD

**Issue by yookoala** [lbryio/lbry#1014]
### Steps to reproduce
1. Install [LBRY_0.18.2_amd64.deb](https://github.com/lbryio/lbry-app/releases/download/v0.18.2/LBRY_0.18.2_amd64.deb) on Ubuntu 17.10.
2. Start it by dash or by command "lbry"

### Expected behaviour
The GUI show up.

### Actual behaviour
LBRY crashed immediately. 

## System Configuration
Ubuntu 17.10 (Desktop, amd64) with GNOME on Xorg.

## Related information
* Apport error message: 
   ```
   lbry crashed with sigsegv in __start_google_malloc()"
   ```

* Stacktrace Top:
  ```
  ??()
  __start_google_malloc()
  calloc()
  g_malloc0() from /lib/x86_64-linux-gnu/libglib-2.0.so.0
  ??() from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
  ```
* Stacktrace (screenshot of Apport)
    ![apport-screenshot-lbry](https://user-images.githubusercontent.com/91274/33559274-3bcc9026-d947-11e7-89a1-e942e0291a63.png)
* Core Dump: [core.gz](https://github.com/lbryio/lbry/files/1527505/core.gz)

**Comment by tzarebczan** [comment]
@yookoala thanks for submitting this. I'll get to get this version of Ubuntu loaded up on a VM to try. 

Do you have selinux or apparmor installed? Sometimes these can cause unexpected issues with the app / protocol.

**Comment by yookoala** [comment]
I'm using the desktop variant. AppArmor is enabled by default.

**Comment by tzarebczan** [comment]
Can you give it a try with it disabled temporarily?

**Comment by yookoala** [comment]
I tried to run `/etc/init.d/apparmor stop` and `systemctl stop apparmor`. Both commands run without error. And either of them should have stopped apparmor according to [man page](http://manpages.ubuntu.com/manpages/artful/en/man7/apparmor.7.html). then I tried to run `lbry` command. It still crashes in the same manner.

**Comment by tzarebczan** [comment]
Thanks for checking @yookoala !

Take a look at lbry.io/faq/tips :)

**Comment by tzarebczan** [comment]
@yookoala - I just loaded up a fresh VM of Ubuntu 17.10 with XORG option and was able to install/run LBRY without any issues. I did notice that it doesn't minimize to tray, but it does run in the background - could be related to https://github.com/lbryio/lbry-app/issues/740

**Comment by yookoala** [comment]
I tried to re-install my system without the Nvidia driver. It seems fine.

Probably a driver specific issue. Close for now.
