### ISSUE TITLE
Don't announce blobs unless daemon has peers and those peers can download blobs

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1016]
## The Issue
Running a peer list on a particular blob will return a peer that's not able to share blobs with the network.  

This could cause some downstream DHT/availability issues.

Here is one example (I know this user has not forwarded their ports):

brynet-cli peer_list 393cc3374036224b6fbc9507d359138cfdf5cbc947fa6afdf932bc9f0d586e34acd103c0390bd295f49bf46f64865c21
[
  [
    "201.17.16.114",
    3333,
    true
  ]
]

## System Configuration

 

- LBRY Daemon version: 0.18.0
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by lyoshenka** [comment]
The solution here is to for the daemon to detect whether it's externally connectable, and not announce its blobs if it isnt.

**Comment by eukreign** [comment]
@jackrobison is this still a valid issue with the new async DHT?

**Comment by alyssaoc** [comment]
closing reopen if needed
