### ISSUE TITLE
Pile ups in hash announce queue

### ISSUE THREAD

**Issue by kaykurokawa** [lbryio/lbry#1017]
There was a plie up in the announce queue on prism hosts , i.e, 

host 11 -  48838 blobs in queue, 13847 blobs to announce
host 10 - 55145 blobs in queue, 12833 blobs to announce
host 9  - 41396 blobs in queue, 12430 blobs to announce
host 4 -  43300 blobs in queue, 12177 blobs to announce

Restarted the hosts for now,  need to adjust the announce time parameter for now while this PR https://github.com/lbryio/lbry/pull/961 gets worked on

**Comment by kaykurokawa** [comment]
This is a temporary fix : https://github.com/lbryio/lbry/pull/1018

**Comment by lyoshenka** [comment]
Issue moved to [lbryio/reflector-cluster #37](https://github.com/lbryio/reflector-cluster/issues/37) via [**ZenHub**](https://www.zenhub.com/)
