### ISSUE TITLE
Refactor file_manager, stream_info_manager 

### ISSUE THREAD

**Issue by kaykurokawa** [lbryio/lbry#1020]
a) 
The file objects managed by file_manager ( EncryptedFileManager ) is hard to understand because it has some layers of unnecessary inheritance
( ManagedEncryptedFileDownloader -> EncryptedFileSaver -> EncryptedFiledDownloader -> CryptStreamDownloader )

b) 
Currently, the tasks that stream_info_manager (DBEncryptedFileMetadataManager) and file_manager (EncryptedFileManager) is supposed to perform is poorly organized.  stream_info_manager should be responsible for downloading streams. file_manager should be responsible for constructing files out of these streams. Currently file_manager both manages streams and the construction of files. stream_info_manager merely acts as a database to store stream information. 

The primary goal should be to have e a clear distinction between streams and files. As you can have streams without files.

**Comment by jackrobison** [comment]
>The primary goal should be to have a clear distinction between streams and files. As you can have streams without files.

https://github.com/lbryio/lbry/pull/1025 refactors the stream and file creation process and storage in the database to do this. It does not significantly change the confusing inheritance of the lbry file classes, however it does remove redundancy of many associated functions (which are now in `lbrynet.core.StreamDescriptor`). The lbry file classes should be further refactored later and shouldn't require more database changes, this pr is big enough already.
