### ISSUE TITLE
claim_abandon API docs incorrect

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry#1021]
https://lbryio.github.io/lbry/#claim_abandon specifies you can only pass a `claim_id`, but the app has been passing `txid` and `nout`.

(The app was recently updated to use `claim_id`)

**Comment by tzarebczan** [comment]
Don't think @jackrobison ever fixed the issue with api docs updating. Cli docs are updated though.

**Comment by lyoshenka** [comment]
related: #762
