### ISSUE TITLE
Batch resolve should return null or an appropriate error for unclaimed, abandoned, or expired URLs.

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1024]
## The Issue
In a batched resolution, the entire resolve command fails if one of the URLs errors out. This is happening on the homepage at the moment because of an expired claim in the resolve call.  

### Steps to reproduce
1. batch a URI resolution with a known bad URL
2. observe failure

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

## System Configuration

 

- LBRY Daemon version: 0.18.2
- LBRY App version: 0.19rc1
- LBRY Installation ID:
- Operating system:

**Comment by jackrobison** [comment]
`resolve` in lbrynet handles these cases, this error must be in the app handling of the response.

**Comment by jackrobison** [comment]
Issue moved to [lbryio/lbry-app #841](https://github.com/lbryio/lbry-app/issues/841) via [**ZenHub**](https://www.zenhub.com/)

**Comment by jackrobison** [comment]
Issue moved to [lbryio/lbry-app #840](https://github.com/lbryio/lbry-app/issues/840) via [**ZenHub**](https://www.zenhub.com/)

**Comment by kauffj** [comment]
This will be fixed app side when you return null for unclaimed, abandoned, or expired URLs.

**Comment by lyoshenka** [comment]
i believe https://github.com/lbryio/lbry-app/issues/842 can be closed when this is closed too

**Comment by lyoshenka** [comment]
@tzarebczan I have not been able to reproduce this. Can you please give it a try when you have some time and let me know if you can get this to happen?

**Comment by tzarebczan** [comment]
Per our convo, here's an example on 0.19.1:
```
lbrynet-cli resolve mindblown#02da15270141483a76a7b8372d69653b735fb0b9 one

ERROR: 'NoneType' object is not iterable
```

**Comment by lyoshenka** [comment]
To repro: `lbrynet-cli resolve mindblown#02da15270141483a76a7b8372d69653b735fb0b9` or `lbrynet-cli resolve xzxzx#34`

**Comment by tzarebczan** [comment]
Looks like this is now resolved: C:\Users\SoloDolo\Desktop\latest daemon>lbrynet-cli resolve mindblown#02da15270141483a76a7b8372d69653b735fb0b9 one
```
{
  "mindblown#02da15270141483a76a7b8372d69653b735fb0b9": {
    "error": "URI lbry://mindblown#02da15270141483a76a7b8372d69653b735fb0b9 cannot be resolved"
  },
  "one": {
    "claim": {
      "address": "bQANoB96HYDNhQXCGQEWVkTYt6C4JGrP6N",
      "amount": 50000.0,
      "claim_id": "008401a48cecef2a13cf5376b696169bb36b18c6",
      "claim_sequence": 9,
      "decoded_claim": true,
      "depth": 62822,
      "effective_amount": 50082.30000001,
      "has_signature": false,
      "height": 350499,
      "hex": "080110011aac02080112e401080410011a24486f6c6c792073696e67696e672054686520486170707920576f726b696e6720536f6e67226f5468616e6b7320666f7220616c6c20746865207469707320666f722074686520486f6c6c7920766964656f2e2053686520626f756768742061204e696e74656e646f20537769746368207769746820746865206d6f6e657920617420786d61732e0a0a5468616e6b7320616761696e2a003214416c6c207269676874732072657365727665642e38004a29687474703a2f2f7777772e746865746f79646973636f756e7465722e636f6d2f68617070792e6a706752005a001a41080110011a306a611e6f8ffb4920bf0679de6dee8bf9e56a473f43d8340233934eaf3b7e1211ee5a53c28e33693ca236c1408023d6cd2209766964656f2f6d7034",
      "name": "one",
      "nout": 0,
      "permanent_url": "one#008401a48cecef2a13cf5376b696169bb36b18c6",
      "supports": [
        {
          "amount": 1.0,
          "nout": 1,
          "txid": "e6c18215a613c393f8df26486dc659fc9753037f36809d553f4e5b1a55c145a5"
        },
        {
          "amount": 5.0,
          "nout": 1,
          "txid": "d61746c5ad2bffb54ec0519ee6b1541f2b290c228dca118ed849f42cae7e967f"
        },
        {
          "amount": 30.0,
          "nout": 0,
          "txid": "3c64a004abb964aac02244c31a7babc8da404c4674c9055eaa79f2a264365bc9"
        },
        {
          "amount": 1.0,
          "nout": 0,
          "txid": "b833835017c265240de00871cb32d8987b19fc68931169380d9d58220952e8c5"
        },
        {
          "amount": 1e-08,
          "nout": 0,
          "txid": "0d6f9dead92eb00a1ca0f32320e8a4fa4e6b53066388348f0bafca29684a4573"
        },
        {
          "amount": 1.0,
          "nout": 1,
          "txid": "1113571eadef51cceaaab94b4859a8185ad38e3f1dd74b36aee85850f759e097"
        },
        {
          "amount": 1.0,
          "nout": 1,
          "txid": "0bfe629b136d20afdcd5bc704c5c82a316b3988f33d0f874dd4c74b5313bab30"
        },
        {
          "amount": 1.0,
          "nout": 1,
          "txid": "87ee93ed7acec558f0fb1f71919e5ad5a35befb0785f231756f02af6be28320e"
        },
        {
          "amount": 1.0,
          "nout": 0,
          "txid": "71a3224a85403b91e26f0f9d5f59d4c996843f670910630a6b6afbfc016d0c1e"
        },
        {
          "amount": 2.0,
          "nout": 0,
          "txid": "c9568c471dd9849080a5fbd4de8c0ffcb1982c6d6e8e37f196a2182f307fd70b"
        },
        {
          "amount": 0.1,
          "nout": 0,
          "txid": "f086ec011431f5883db5a9d6de0c03b997a89c8e5252d7bfde2292d3e2ea8853"
        },
        {
          "amount": 1.0,
          "nout": 0,
          "txid": "679dc0cb80945d371d8f3cf5498157aac31d7621ea05eae8cefc5b32d6744901"
        },
        {
          "amount": 5.0,
          "nout": 1,
          "txid": "3eb0904ba2e9dbb41c6497e481d68462e99404b9803641a699899de9a62ea75a"
        },
        {
          "amount": 2.0,
          "nout": 1,
          "txid": "e56bcf7c643b27ee6a2d355af426fc73332093af0d8ffc318a80af0de4a5b07e"
        },
        {
          "amount": 0.1,
          "nout": 0,
          "txid": "f1b497e5ef84148637f61c2d257997af909ad2e864f655f4a5496d7b8989678d"
        },
        {
          "amount": 0.1,
          "nout": 0,
          "txid": "910a263504cc6561dcc2f2f26d62e9a799f52f01e8eb663ec0f6eb2ec7d88f48"
        },
        {
          "amount": 1.0,
          "nout": 0,
          "txid": "753623350e1f499d0217a5e5396a02b253ceabedb35e20ba70c6ec723d58ca6e"
        },
        {
          "amount": 1.0,
          "nout": 1,
          "txid": "4f609bb7efa467ffc20ef63ee47e1c153585be73086f27ba3db460946dcee561"
        },
        {
          "amount": 1.0,
          "nout": 1,
          "txid": "28c3eb2fdff90da92884ef2a126e7e854711886f7e333ac91618a01096d4f02d"
        },
        {
          "amount": 1.0,
          "nout": 1,
          "txid": "04b386da54645c1ef0ade974eefdb21d1ad81bad2cf2119b9425bf6bb510fb46"
        },
        {
          "amount": 5.0,
          "nout": 1,
          "txid": "f43ece7f9c42fb73c9e2bf1729f73a83f72d284e8c9f540a8a5f2be1581996e2"
        },
        {
          "amount": 1.0,
          "nout": 0,
          "txid": "9c6cb4c307610a51ca36e94cdcbc7827260400c332964b841ff3a2c0e2c1bb0c"
        },
        {
          "amount": 20.0,
          "nout": 0,
          "txid": "9f8ca4b44df924f08f739699b7a591627366477be46c4046ff9fe0d9cde29494"
        },
        {
          "amount": 1.0,
          "nout": 0,
          "txid": "b9407f592f1e8c9e5b3916d94f8130100186aaa5eead523ce9be3be098f8d735"
        }
      ],
      "txid": "37df9b05fb826c04b3cb341e69406b499884a551337c9654c51fb2305774efeb",
      "value": {
        "claimType": "streamType",
        "stream": {
          "metadata": {
            "author": "",
            "description": "Thanks for all the tips for the Holly video. She bought a Nintendo Switch with the money at xmas.\n\nThanks again",
            "language": "en",
            "license": "All rights reserved.",
            "licenseUrl": "",
            "nsfw": false,
            "preview": "",
            "thumbnail": "http://www.thetoydiscounter.com/happy.jpg",
            "title": "Holly singing The Happy Working Song",
            "version": "_0_1_0"
          },
          "source": {
            "contentType": "video/mp4",
            "source": "6a611e6f8ffb4920bf0679de6dee8bf9e56a473f43d8340233934eaf3b7e1211ee5a53c28e33693ca236c1408023d6cd",
            "sourceType": "lbry_sd_hash",
            "version": "_0_0_1"
          },
          "version": "_0_0_1"
        },
        "version": "_0_0_1"
      }
    }
  }
}
```

**Comment by tzarebczan** [comment]
```{  "mindblown#02da15270141483a76a7b8372d69653b735fb0b9": {    "error": "URI lbry://mindblown#02da15270141483a76a7b8372d69653b735fb0b9 cannot be resolved"  },  "one": {    "claim": {      "address": "bQANoB96HYDNhQXCGQEWVkTYt6C4JGrP6N",      "amount": 50000.0,      "claim_id": "008401a48cecef2a13cf5376b696169bb36b18c6",      "claim_sequence": 9,      "decoded_claim": true,      "depth": 62822,      "effective_amount": 50082.30000001,      "has_signature": false,      "height": 350499,      "hex": "080110011aac02080112e401080410011a24486f6c6c792073696e67696e672054686520486170707920576f726b696e6720536f6e67226f5468616e6b7320666f7220616c6c20746865207469707320666f722074686520486f6c6c7920766964656f2e2053686520626f756768742061204e696e74656e646f20537769746368207769746820746865206d6f6e657920617420786d61732e0a0a5468616e6b7320616761696e2a003214416c6c207269676874732072657365727665642e38004a29687474703a2f2f7777772e746865746f79646973636f756e7465722e636f6d2f68617070792e6a706752005a001a41080110011a306a611e6f8ffb4920bf0679de6dee8bf9e56a473f43d8340233934eaf3b7e1211ee5a53c28e33693ca236c1408023d6cd2209766964656f2f6d7034",      "name": "one",      "nout": 0,      "permanent_url": "one#008401a48cecef2a13cf5376b696169bb36b18c6",      "supports": [        {          "amount": 1.0,          "nout": 1,          "txid": "e6c18215a613c393f8df26486dc659fc9753037f36809d553f4e5b1a55c145a5"        },        {          "amount": 5.0,          "nout": 1,          "txid": "d61746c5ad2bffb54ec0519ee6b1541f2b290c228dca118ed849f42cae7e967f"        },        {          "amount": 30.0,          "nout": 0,          "txid": "3c64a004abb964aac02244c31a7babc8da404c4674c9055eaa79f2a264365bc9"        },        {          "amount": 1.0,          "nout": 0,          "txid": "b833835017c265240de00871cb32d8987b19fc68931169380d9d58220952e8c5"        },        {          "amount": 1e-08,          "nout": 0,          "txid": "0d6f9dead92eb00a1ca0f32320e8a4fa4e6b53066388348f0bafca29684a4573"        },        {          "amount": 1.0,          "nout": 1,          "txid": "1113571eadef51cceaaab94b4859a8185ad38e3f1dd74b36aee85850f759e097"        },        {          "amount": 1.0,          "nout": 1,          "txid": "0bfe629b136d20afdcd5bc704c5c82a316b3988f33d0f874dd4c74b5313bab30"        },        {          "amount": 1.0,          "nout": 1,          "txid": "87ee93ed7acec558f0fb1f71919e5ad5a35befb0785f231756f02af6be28320e"        },        {          "amount": 1.0,          "nout": 0,          "txid": "71a3224a85403b91e26f0f9d5f59d4c996843f670910630a6b6afbfc016d0c1e"        },        {          "amount": 2.0,          "nout": 0,          "txid": "c9568c471dd9849080a5fbd4de8c0ffcb1982c6d6e8e37f196a2182f307fd70b"        },        {          "amount": 0.1,          "nout": 0,          "txid": "f086ec011431f5883db5a9d6de0c03b997a89c8e5252d7bfde2292d3e2ea8853"        },        {          "amount": 1.0,          "nout": 0,          "txid": "679dc0cb80945d371d8f3cf5498157aac31d7621ea05eae8cefc5b32d6744901"        },        {          "amount": 5.0,          "nout": 1,          "txid": "3eb0904ba2e9dbb41c6497e481d68462e99404b9803641a699899de9a62ea75a"        },        {          "amount": 2.0,          "nout": 1,          "txid": "e56bcf7c643b27ee6a2d355af426fc73332093af0d8ffc318a80af0de4a5b07e"        },        {          "amount": 0.1,          "nout": 0,          "txid": "f1b497e5ef84148637f61c2d257997af909ad2e864f655f4a5496d7b8989678d"        },        {          "amount": 0.1,          "nout": 0,          "txid": "910a263504cc6561dcc2f2f26d62e9a799f52f01e8eb663ec0f6eb2ec7d88f48"        },        {          "amount": 1.0,          "nout": 0,          "txid": "753623350e1f499d0217a5e5396a02b253ceabedb35e20ba70c6ec723d58ca6e"        },        {          "amount": 1.0,          "nout": 1,          "txid": "4f609bb7efa467ffc20ef63ee47e1c153585be73086f27ba3db460946dcee561"        },        {          "amount": 1.0,          "nout": 1,          "txid": "28c3eb2fdff90da92884ef2a126e7e854711886f7e333ac91618a01096d4f02d"        },        {          "amount": 1.0,          "nout": 1,          "txid": "04b386da54645c1ef0ade974eefdb21d1ad81bad2cf2119b9425bf6bb510fb46"        },        {          "amount": 5.0,          "nout": 1,          "txid": "f43ece7f9c42fb73c9e2bf1729f73a83f72d284e8c9f540a8a5f2be1581996e2"        },        {          "amount": 1.0,          "nout": 0,          "txid": "9c6cb4c307610a51ca36e94cdcbc7827260400c332964b841ff3a2c0e2c1bb0c"        },        {          "amount": 20.0,          "nout": 0,          "txid": "9f8ca4b44df924f08f739699b7a591627366477be46c4046ff9fe0d9cde29494"        },        {          "amount": 1.0,          "nout": 0,          "txid": "b9407f592f1e8c9e5b3916d94f8130100186aaa5eead523ce9be3be098f8d735"        }      ],      "txid": "37df9b05fb826c04b3cb341e69406b499884a551337c9654c51fb2305774efeb",      "value": {        "claimType": "streamType",        "stream": {          "metadata": {            "author": "",            "description": "Thanks for all the tips for the Holly video. She bought a Nintendo Switch with the money at xmas.\n\nThanks again",            "language": "en",            "license": "All rights reserved.",            "licenseUrl": "",            "nsfw": false,            "preview": "",            "thumbnail": "http://www.thetoydiscounter.com/happy.jpg",            "title": "Holly singing The Happy Working Song",            "version": "_0_1_0"          },          "source": {            "contentType": "video/mp4",            "source": "6a611e6f8ffb4920bf0679de6dee8bf9e56a473f43d8340233934eaf3b7e1211ee5a53c28e33693ca236c1408023d6cd",            "sourceType": "lbry_sd_hash",            "version": "_0_0_1"          },          "version": "_0_0_1"        },        "version": "_0_0_1"      }    }  }}```
