### ISSUE TITLE
'is_mine': 'False' error

### ISSUE THREAD

**Issue by billbitt** [lbryio/lbry#1037]
## The Issue
I am getting the following error when publishing from spee.ch's daemon:

```{"error":{"code":-32500,"data":["  File \"site-packages/twisted/internet/defer.py\", line 1299, in _inlineCallbacks","    ","  File \"site-packages/lbrynet/core/Wallet.py\", line 800, in _handle_claim_result","    ","exceptions.AssertionError: result in unexpected format:{'is_mine': False}"],"message":"result in unexpected format:{'is_mine': False}"},"id":null,"jsonrpc":"2.0"}```

### Steps to reproduce
note, this does not happen every time.  I am not able to reproduce consistently atm.
1. visit spee.ch
2. upload a file
3. publish

### Expected behaviour
publish should go through and return the tx details

### Actual behaviour
I receive the above error

## System Configuration
```
$ curl 'http://localhost:5279/lbryapi' --data '{"method":
"version"}'
{
  "id": null,
  "jsonrpc": "2.0",
  "result": {
    "build": "qa",
    "ip": "******",
    "lbrynet_version": "0.19.0rc16",
    "lbryschema_version": "0.0.15rc2",
    "lbryum_version": "3.2.0rc4",
    "os_release": "4.4.0-97-generic",
    "os_system": "Linux",
    "platform": "Linux-4.4.0-97-generic-x86_64-with-Ubuntu-16.04-xenial",
    "processor": "x86_64",
    "python_version": "2.7.12"
  }
} 
```

**Comment by billbitt** [comment]
I believe this issue is happening when publishing to a channel, although I cannot confirm that at the moment

**Comment by blckchnprncss** [comment]
This issue has happened for me two or three times. Each time attempting to publish to channel "@CampusEngagement" - could not reproduce on any other channel. File was a 3.5MB JPEG.

**Comment by billbitt** [comment]
@jackrobison we are seeing this error again but with different traceback: 
``` {"error":{"code":-32500,"data":["  File \"/home/lbry/.virtualenvs/jack/local/lib/python2.7/site-packages/twisted/internet/defer.py\", line 1299, in _inlineCallbacks","    result = g.send(result)","  File \"/home/lbry/jack/lbry/lbrynet/core/Wallet.py\", line 803, in _handle_claim_result","    assert False, msg","exceptions.AssertionError: result in unexpected format:{'is_mine': False}"],"message":"result in unexpected format:{'is_mine': False}"},"id":null,"jsonrpc":"2.0"} ```
