### ISSUE TITLE
Installation ID points to the wrong email

### ISSUE THREAD

**Issue by nikooo777** [lbryio/lbry#1038]
## The Issue
I've been using LBRY on Ubuntu on this specific computer for at least 7 months and thus was verified long time ago.
I don't remember if at any point i had to add my email inside the app, however I received my code by email, however I now notice that if i go to settings->help->about I find my installation id, my token and an email that isn't mine.
Can you please verify why that is happening?

### Steps to reproduce
1. Be and old user (?)
2. Be approved for rewards through email tokens
3. Check your email in settings->help->about

### Expected behaviour
My email should show up

### Actual behaviour
Someone else's email shows up

## System Configuration

```
{
  "id": null,
  "jsonrpc": "2.0",
  "result": {
    "build": "release",
    "ip": "***.***.177.176",
    "lbrynet_version": "0.18.0",
    "lbryschema_version": "0.0.14",
    "lbryum_version": "3.1.11",
    "os_release": "4.13.13-041313-generic",
    "os_system": "Linux",
    "platform": "Linux-4.13.13-041313-generic-x86_64-with-Ubuntu-17.04-zesty",
    "processor": "x86_64",
    "python_version": "2.7.12"
  }
}
```

## Anything Else
My installation id is: `xp4V5G2c8CUBcZgh669TwSfJz5hCQUoVEKdXEhzQAFSm8oexiHfDjeFsakbZeDmdw`
the email shown to me is: `omely830@******`

## Screenshots
https://scrn.storni.info/2017-12-23_13-21-10-241442250.png

**Comment by kauffj** [comment]
This is very strange. I see that user, but nothing else matches (not even the `app_id`).

The most likely explanation would be a merge I thought, but that hasn't happened here either.

@tzarebczan you heard any other reports of this one?

**Comment by tzarebczan** [comment]
Nope haven't seen it before, that's a really strange one.  Maybe @grin would have a better idea.

**Comment by kauffj** [comment]
@lyoshenka I already went down the rabbit hole a bit on this since it's just so damn weird! I cannot think of an explanation other than the merge logic.

**Comment by kauffj** [comment]
@tzarebczan @grin is not the Grin that works for this company (that's @lyoshenka).

Sorry for the spurious mentions, @grin, but you should also come check out our sweet project :stuck_out_tongue:

**Comment by lyoshenka** [comment]
No idea what happened here. Cant really do much with this info. Niko, lemme know if you want me to fix your account manually.
