### ISSUE TITLE
Unify daemon, cli, and console into a single executable

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry#1040]
There is no reason to  have 3 executables that share 99% of the code with each other. We need one executable called `lbrynet` that has the following behavior.

- `lbrynet daemon_start` has the same effect as calling `lbrynet-daemon` now, and accepts all the same flags
- `lbrynet console` has the same effect as calling `lbrynet-console` now, and accepts all the same flags
- all other commands are assumed to be cli commands, and are handled as before

This will require unifying and standardizing some of the existing cli flags.

**Comment by kauffj** [comment]
Hmm, would it perhaps make sense for the plain `lbrynet` command to just be start/stop?

Is there other software to draw best practices from here?

To me, CLI/console based interactions are the special case.

**Comment by lyoshenka** [comment]
I don't think so. Running just `lbrynet` should show help info on how to use the command (should be the same thing as `lbrynet help`). 

I like how Keybase does their cli. They do it like this.

**Comment by kauffj** [comment]
@lyoshenka link is missing for keybase - is it this one? https://keybase.io/docs/command_line

**Comment by lyoshenka** [comment]
Yes. Looks like its changed a bit. They used to have commands like `keybase kbfs start` which starts the kbfs daemon.

**Comment by alyssaoc** [comment]
@lyoshenka Is this still an open issue? Priority?

**Comment by eukreign** [comment]
This is done.
