### ISSUE TITLE
Ability to turn off file hosting

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1041]
## The Issue
As a user, especially on mobile and bandwidth/cap limited network connections, I'd want the ability to turn off file hosting features. Currently, this is enabled by default and users cannot turn it off unless they block ports.

This might be related to https://github.com/lbryio/lbry/issues/798

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by kauffj** [comment]
I saw this looking for another issue. @eukreign can this be closed with components refactor?

**Comment by eukreign** [comment]
The components help with this but it hasn't been tested so we shouldn't close this.

**Comment by tzarebczan** [comment]
Previously we were doing it via this method, but it's broken.
https://github.com/lbryio/lbry/issues/1297

But yes, in the long term this should be done via components (don't think the current release supports turning components on/off)

**Comment by eukreign** [comment]
`master` does support turning components on and off, you add a new setting value called `components_to_skip` with list of components to skip, also turning off relfector is still supported with independent settings option:

https://github.com/lbryio/lbry/blob/88b8ca8a49922bd7f9b6fa90fa093bd5d0232dec/lbrynet/daemon/Daemon.py#L199-L201

**Comment by tzarebczan** [comment]
The reflector setting is different, it doesn't mean turning off file hosting.

The question is, can you disable just the sharing/announcing side of the dht without disabling the entire dht component?

**Comment by eukreign** [comment]
You are correct @tzarebczan , it's not possible with current `master`.

@shyba has a branch related to this though: https://github.com/lbryio/lbry/tree/disable_dht

**Comment by eukreign** [comment]
@jackrobison I believe you finalized this, right? We can close this issue?

**Comment by jackrobison** [comment]
The `hash_announcer` and `peer_protocol_server` components can be disabled together or separately
