### ISSUE TITLE
Add ability to import/export wallet through passphrase

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1044]
## The Issue
As a user of LBRY (especially on mobile), I'd want the ability to backup and restore LBC wallets through the use of a passphrase.  There should be a way to password secure the passphrase as an additional layer of security (BIP 38/39?).  

This functionality should already be available at the lbryum layer, but needs to be exposed on the daemon.

It should also be fully compatible with other wallets like Coinomi - https://coinomi.com/recovery-phrase-tool.html

**Comment by lyoshenka** [comment]
related: #773

**Comment by alyssaoc** [comment]
@eukreign Does the new wallet implement this?

**Comment by eukreign** [comment]
New wallet can restore a wallet (account) from a seed:

`lbrynet account "name of your account" --create --seed="provide the seed you used previously"`
