### ISSUE TITLE
Daemon should provide tx fee estimates for all transactions

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1045]
## The Issue
Currently, there is no way to estimate what the transaction fees are when sending LBC, creating channels or publishing files.  This is a cause of friction from the user experience for two main reasons: 1) they try to send (or publish with) their entire LBC balance withtout taking into account fees, so the transaction does not go through (https://github.com/lbryio/lbry-app/issues/903 / https://github.com/lbryio/lbry-app/issues/874). 2) Users are currently unaware that there is some unrecoverable fee associated with transactions/claims/publishes.

Jack mentioned that lbryum already has a fee estimator, so it just needs to be exposed to all daemon commands which interact with sending LBC.

Need to make sure this scenario is also taken into account: https://github.com/lbryio/lbry/issues/1102

**Comment by hellbeast222** [comment]
https://github.com/lbryio/lbry/labels/enhancement

**Comment by tzarebczan** [comment]
@lyoshenka I'm putting this on the user wish list because it causes UX friction in a few different scenariois, see below. It also may be related to: https://github.com/lbryio/lbry/issues/855

1) When creating a channel or publishing, some users may enter a value that's equal to their wallet balance and the result is https://github.com/lbryio/lbry-app/issues/874

2) When trying to send an amount that equal to your wallet balance, you may run into: https://github.com/lbryio/lbry-app/issues/873

3) When sending tips, you'll run into a similar issues because fees aren't taken into account.

**Comment by lyoshenka** [comment]
steps:
- [] make a lbryum command which takes an amount, creates a transaction, and figure out how big it is. then return estimateFeeForSize(tx_size)
- [] for a publish, add in claim info into the above command
- [] make lbrynet command that does these
- [] write tests
- [] pr review

**Comment by tzarebczan** [comment]
Now that https://github.com/lbryio/lbryum/pull/234 was implemented, we need to take this into account when calculating fees. 

I think it would make a lot of sense to work on this ASAP since the fees for claim txs has gone up considerably. Right now there are lots of edge cases where errors don't return properly if a user's balance doesn't cover the fee.

We also need to figure out how/when to run this function to update: https://github.com/lbryio/lbry/blob/master/lbrynet/daemon/Daemon.py#L97 in a way that is efficient as possible since it's called on each publish/update/channel creation.

**Comment by lyoshenka** [comment]
This is lower priority than improving availability and performance. Once those two are in a good place we'll look at this.

**Comment by alyssaoc** [comment]
@eukreign will the new wallet include this?

**Comment by eukreign** [comment]
This is available in new wallet by creating TXs and showing them but not broadcasting them, the JSON response includes the fees.
