### ISSUE TITLE
The following error occurred when attempting to publish your file: Cannot read property 'error' of undefined

### ISSUE THREAD

**Issue by RedbHawk** [lbryio/lbry#1046]
When I try to upload the video

App | 0.19.2
Daemon (lbrynet) | 0.18.0

**Comment by tzarebczan** [comment]
@RedbHawk we have this filed under the app https://github.com/lbryio/lbry-app/issues/874

Please try lowering your bid amount, see lbry.io/faq/how-to-publish for more info.
