### ISSUE TITLE
Prevent multiple daemons from running using the same wallet/db/conf

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry#1051]
When the daemon starts, it will check to see if there's another daemon process running, and refuse to start if this is the case. That check should be made more robust. Right now it only checks to see if it can call the `status` json-rpc command on a daemon running on the same host and port as itself (https://github.com/lbryio/lbry/blob/master/lbrynet/daemon/DaemonControl.py#L73). It should also check that no other daemons are using the following:

- the wallet file
- the sqlite db

One possible solution is to take out an OS-level exclusive lock on the appropriate files. SQLite also supports [its own locking](https://www.sqlite.org/lockingv3.html)

**Comment by lyoshenka** [comment]
if it does break things, fix it or file the appropriate issues

**Comment by ex0dus-0x** [comment]
Any tips on where code is for wallet and database file generation?

**Comment by tzarebczan** [comment]
@ex0dus-0x welcome to the LBRY repo! 

The wallet file path is set here: https://github.com/lbryio/lbry/blob/b3bf193188b1874748f42711dd512e4bac504c08/lbrynet/conf.py#L271 

The data dir (which contains the lbrynet.sqlite file), is set here: https://github.com/lbryio/lbry/blob/b3bf193188b1874748f42711dd512e4bac504c08/lbrynet/conf.py#L261

**Comment by eukreign** [comment]
This issue is unlikely to come up in regular use.

**Comment by kauffj** [comment]
If it's valid, why not leave it open? Seems relatively feasible for the daemon to obtain a lock?

**Comment by eukreign** [comment]
It would take very significant effort to implement this correctly to handle the sqlite database and config files we write to. Also, do you prevent the daemon from starting if another unrelated process has opened the sqlite database or only if another daemon has it opened? There are a lot of questions of how this locking should work.

Actually, in the simple case it already works, daemon won't start if you already have an existing daemon bound to the same port. This already covers 99% of scenarios.

Before we can reasonably act on an issue like this we should figure out what the 1% case is that reproduces this problem: How do you get into the situation where you have two daemons writing to the same sqlite database and what are the chances that situation can be triggered by a user unintentionally?
