### ISSUE TITLE
How long is Starting LBRY Upgrade ?

### ISSUE THREAD

**Issue by RedbHawk** [lbryio/lbry#1058]
Clicked "Upgrade LBRY" & after downloading - this upgrading stuck.

**Comment by tzarebczan** [comment]
@RedbHawk please see lbry.io/faq/support on how to get help, that would make more sense vs a github issue. 

What OS are you on? Can you try starting lbry again to see if it works a 2nd time?  If you are on windows, you'll receive a security prompt to allow the upgrade to continue.

**Comment by hellbeast222** [comment]
how do I get rid of this monster?

**Comment by tzarebczan** [comment]
@hellbeast222 please stop commenting randomly. If you don't want to be notified, unfollow the repo.
