### ISSUE TITLE
Publishing takes too long on wallet with many claims and/or channels

### ISSUE THREAD

**Issue by billbitt** [lbryio/lbry#1061]
## The Issue
When publishing via the daemon with many addresses in a wallet, the daemon takes too long to respond.  Sometimes over two minutes.

### Steps to reproduce
1. Create many claims and channels (see e.g. spee.ch's wallet)
2. publish without a channel (takes ~40 seconds on spee.ch)
3. publish from a channel (takes from 1.5 minutes on spee.ch)

### Expected behaviour
`publish` should return within a reasonable amount of time, so that if lbrynet is being used as a back end to carry out client requests, a timely response can be made to the client.

### Actual behaviour
publish without a channel takes ~40 seconds on spee.ch
publish from a channel takes can take up to 1.5 minutes  on spee.ch

## System Configuration
``` "id": null,
"jsonrpc": "2.0",
"result": {
  "build": "rc",
  "lbrynet_version": "0.19.0rc26",
  "lbryschema_version": "0.0.15rc2",
  "lbryum_version": "3.2.0rc10",
  "os_release": "4.4.0-97-generic",
  "os_system": "Linux",
  "platform": "Linux-4.4.0-97-generic-x86_64-with-Ubuntu-16.04-xenial",
  "processor": "x86_64",
  "python_version": "2.7.12" ```

**Comment by jackrobison** [comment]
The db refactor should not affect the speed of publishing substantially. The lag seen here is on the lbryum client <-> server level.

**Comment by eukreign** [comment]
@kauffj @billbitt @lyoshenka We've determined the culprit to be `channel_list()` function. The solution for `spee.ch` is to pass the `channel_id` instead of `channel_name`, thereby bypassing this branch in the conditional:

https://github.com/lbryio/lbry/blob/7862ee67153214c29079028c35fae706dd5621e2/lbrynet/daemon/Daemon.py#L2079-L2089

**Comment by kauffj** [comment]
@billbitt please change and deploy this today so we can verify it a positive effect.
