### ISSUE TITLE
Daemon Refactor

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry#1065]
Work so far: started designing how an ideal daemon should be organized. 

One way to think about it is a set of protocols and data types. Here are the protocols the daemon uses now:

### Stratum
- for talking to lbryum-server
- ideally should be just the list of functions, params, and return types
- should not care about data transport
- if we do this, we can do stratum over WebSockets for subscriptions and other push notifications

### Kademlia (DHT)
- for the dht

### Lbrynet Peer Protocol (peer exchange protocol)
- for requesting and exchanging blobs (and paying for them)

### Reflector (could be part of Lbrynet protocol, or could be standalone)
- for reflecting blobs

### JSONRPC, GRPC
- for providing the api

### however it talks to internal apis
- for whatever internal-apis needs

### analytics
- for analytics

---

here are the daemon components

![img-9450](https://user-images.githubusercontent.com/362784/35299280-c2935694-0052-11e8-9d39-711224a4a924.JPG)

**Comment by alyssaoc** [comment]
@lyoshenka Is this still something you want to do or modify? Priority?

**Comment by lyoshenka** [comment]
this is up to @eukreign. i think they're doing some refactoring already. idk if this is still useful, or can be closed

**Comment by eukreign** [comment]
I think this is more of a goal / direction than an actionable issue. We should keep this and refer to it but doesn't make sense to keep issue open.
