### ISSUE TITLE
BitTorrent Support

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry#1070]
Allow publishing to and downloading from the bittorrent DHT

**Comment by lyoshenka** [comment]
Related: #881

**Comment by KamilPiekutowski** [comment]
Can we open a discussion on how to tackle this one?
It looks very exciting.

**Comment by alyssaoc** [comment]
@lyoshenka Is this still a valid epic? What is the priority? They will need additional grooming. On-hold, icebox?

**Comment by lyoshenka** [comment]
we'll get to this eventually. ill reopen when we have more concrete plans
