### ISSUE TITLE
V0.19 - Add URL to reflector logs

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1071]
## The Issue
@jackrobison we discussed this on Slack:
In v0.18, reflector server logging would show both the sd-hash and URL but in 0.19, they only show the sd-hash. The URL is useful for debugging purposes and should be added back if possible. 

Before:
`Reflector has all blobs for lbry://ericsabstractartwork (f5e01063b0043ad4)`

After:
`Reflector has all blobs for f5e01063b0043ad4`

## System Configuration

 

- LBRY Daemon version: 0.19rc29
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by alyssaoc** [comment]
@tzarebczan Is this still an issue?

**Comment by eukreign** [comment]
production reflector server is in `go` now

**Comment by tzarebczan** [comment]
That has nothing to do with why this was closed, but fine, this probably isn't needed but would be nice for logging
