### ISSUE TITLE
connection to known DHT nodes attempted only once

### ISSUE THREAD

**Issue by ordex** [lbryio/lbry#1093]
A DHT node attempts to connect to the configured `known DHT nodes` during DHT startup, however, if something fails the node won't try to reconnect again.

This leads to the node printing something like this:
`2018-01-30 17:20:23,350 WARNING  lbrynet.dht.node:596: This node doesnt know any other nodes`
and won't resolve by itself - it needs a restart.

This behaviour should be changed so that the node periodically tries to recontact the known DHT nodes if the first attempt failed.

**Comment by tzarebczan** [comment]
Great find @ordex !
