### ISSUE TITLE
Implement SSL for daemon JSON RPC

### ISSUE THREAD

**Issue by akinwale** [lbryio/lbry#1094]
There needs to be a way to enable the daemon's JSON RPC server accept requests securely, with a configuration option to enable or disable SSL. The daemon can generate a self-signed certificate upon first run when SSL is enabled and use the certificate to handle requests securely.

**Comment by tzarebczan** [comment]
@hackrush01 - is this different from the authentication mechanism you have been looking into?

**Comment by hackrush01** [comment]
@tzarebczan Yes, this is different.
