### ISSUE TITLE
Claiming with exact amount in wallet produces confusing result

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1107]
## The Issue
This issue is related to https://github.com/lbryio/lbry/issues/855 and https://github.com/lbryio/lbry/issues/1045, but wanted to log it separately as the daemon is returning a confusing message - `Claimed a new channel` and then  `'success': False`.  On the app side, the channel is created but then a different error occurs when you try publishing because the channel does not exist. Will follow up with app side issue to address this while the daemon side is being worked on. 

When creating a channel with the exact amount in your wallet (not accounting for fees), you get this:
lbrynet.daemon.Daemon:1739: Claimed a new channel! Result: {'reason': 'Not enough funds', 'success': False} 

If you enter a really small amount like 0.00000001, you get: lbrynet.daemon.Daemon:1739: Claimed a new channel! Result: {'reason': 'Amount must be greater than 0', 'success': False}

### Steps to reproduce
1. Claim a channel for an amount that's exactly in your wallet
2. Claim a channel for 0.00000001 LBC
3. Check logs

### Expected behaviour
Daemon should not say the channel was claimed, but instead provide the correct warning/error to the app/user

### Actual behaviour
Channel looks like its claimed, but is not

## System Configuration

 

- LBRY Daemon version: 0.18.2
- LBRY App version: 0.20.0
- LBRY Installation ID:
- Operating system: Windows

**Comment by hackrush01** [comment]
PR #1137 fixes this.
Also claiming with very tiny amount (0.00000001) seems to be fixed in v19.
```
curl 'http://localhost:5279/lbryapi' --data '{"method":"channel_new", "params":{"channel_name":"@testC", "amount":0.00000001}}'
{
  "id": null,
  "jsonrpc": "2.0",
  "result": {
    "claim_address": "mqFq5v78c7QAYDZPYCFVeNu5BiVFvzf7tx",
    "claim_id": "54cf9fd1db6ceb8bc68fe22aa9033723493ac789",
    "fee": "0.000169",
    "nout": 0,
    "success": true,
    "tx": "010000000116d6de70011bfe04e0770f3c66ed70c8355806083f61d1c28e2774ee64a2f79d010000006a47304402202d4fa4c0bb132c6aee5ce42b6038e0a655c7b0044751a76a7eb092c8992c59d402204e6740cb563775c00243539f9735cc3abe81c309a4f6d126cdfbcb19c50f5a320121032b1f692f5581f474dd0decc26941ff40aa708a65b6735046ad58b4db1eb2b2c2ffffffff02010000000000000089b5064074657374434c6408011002225e0801100322583056301006072a8648ce3d020106052b8104000a03420004233714ead8b8d8b878798715bdf1a62d1e18374a9dbda4371720766ea88cb791c70814307dd19b5da8b96673035264eb45f0c9acb0005d15829ddcbfe75e2dff6d7576a9146ad5001b4a8fcda8bb4939751d07d33ffd07335c88ac5fea0000000000001976a914bea741a24e42c0c61695d3b03f370966903799fb88ac00000000",
    "txid": "5e05bce0897228748c5d6431a225ccec60e9b80a915197ae46aee5637778b40e",
    "value": "08011002225e0801100322583056301006072a8648ce3d020106052b8104000a03420004233714ead8b8d8b878798715bdf1a62d1e18374a9dbda4371720766ea88cb791c70814307dd19b5da8b96673035264eb45f0c9acb0005d15829ddcbfe75e2dff"
  }
}
```
Snippet of txn list
```
  {
    "abandon_info": [],
    "claim_info": [
      {
        "address": "mqFq5v78c7QAYDZPYCFVeNu5BiVFvzf7tx",
        "amount": 1e-08,
        "balance_delta": -1e-08,
        "claim_id": "54cf9fd1db6ceb8bc68fe22aa9033723493ac789",
        "claim_name": "@testC",
        "nout": 0
      }
    ],
    "confirmations": 50,
    "date": "2018-03-07 16:59",
    "fee": 0.000169,
    "support_info": [],
    "timestamp": 1520422153,
    "txid": "5e05bce0897228748c5d6431a225ccec60e9b80a915197ae46aee5637778b40e",
    "update_info": [],
    "value": -0.000169
  }
```
