### ISSUE TITLE
Add ability to lock wallet for security/seeding purposes

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1113]
@tzarebczan commented on [Tue Jan 16 2018](https://github.com/lbryio/lbryum/issues/197)

Currently, the wallet encryption process works as follows: Once the wallet is encrypted, it must be unlocked when the LBRY app is started.  Once it is unlocked, the wallet is a usable state where transactions can be created (publishing, sending, tipping, etc).  

As a user, I may want to run the lbry in the background or simply as a daemon process, but I wouldn't want the wallet to be in a transact-able state for security purposes. This will be common among users who will be seeding content on the network. An option to lock the wallet from creating transactions would be beneficial.

Another use case would be to auto-lock the wallet after a certain amount of inactivity (again, for security purposes).  

---

@kaykurokawa commented on [Fri Jan 19 2018](https://github.com/lbryio/lbryum/issues/197#issuecomment-359051872)

This is actually a lbry daemon issue. Lbryum can already lock and unlock itself at any time.  

The daemon always assumes that it has access to the wallet when it needs ot use it (when sending transactions, making claims, handling automatic payment for downloading) , which is why it halts startup when wallet is locked.  Thus, whenever the daemon uses the wallet it needs to handle the case when it is locked. 

---

@eukreign commented on [Tue Feb 13 2018](https://github.com/lbryio/lbryum/issues/197#issuecomment-365161210)

@tzarebczan Can this be closed since it's not a lbryum issue per @kaykurokawa last comment?

---

@tzarebczan commented on [Tue Feb 13 2018](https://github.com/lbryio/lbryum/issues/197#issuecomment-365251784)

@eukreign - I'll move this over to the daemon repo instead and adjust the the title/description.

**Comment by eukreign** [comment]
this is done via `account_lock` command.
