### ISSUE TITLE
CHANGELOG check on travis should not require ruby

### ISSUE THREAD

**Issue by eukreign** [lbryio/lbry#1119]
@eukreign commented on [Tue Feb 13 2018](https://github.com/lbryio/lbryum/issues/224)

We need a simpler/faster way to do the CHANGELOG checks when doing the travis builds. Currently travis has to download and install ruby and packages just to check the changelog, which takes significant time and produces a lot of log output.

**Comment by kauffj** [comment]
A decent number of repositories in a variety of languages could use this functionality, so it'd be nice if there was a language-agnostic way of providing this.

Isn't one alternative simply to keep the check happening in Ruby but do it somewhere other than the build server? I'm not actually sure how the check works currently, but it should be possible to have a git pre-commit hook happen some place other than the build service.

**Comment by alyssaoc** [comment]
@eukreign Is this still valid or has the new travis build solved this?

**Comment by eukreign** [comment]
This is still valid, someone needs to tackle this one.

The new build system is using multiple parallel travis build containers, so I think what @kauffj is suggesting is very doable, we could have a separate build process that uses a Ruby container (thus everything is already pre-installed) and does the changelog check only but in parallel to other checks.

**Comment by eukreign** [comment]
generating changelog from PRs, closing
