### ISSUE TITLE
Issue Streaming and Downloading Movie that I Published

### ISSUE THREAD

**Issue by jspicer15** [lbryio/lbry#112]
I published a video earlier (quite large around 960 MB) and I have been trying to watch it from my files. It said that it successfully published and shows up under my files. However when I click on "Watch" I get a black screen that says Download. After I click on that, Firefox stops responding for several minutes. It will then bring me to a blank screen with millions of lines of random text, I assume it is printing the video in text format. Sometimes the text will not appear and the screen will stay grayed out and non responsive. I am running Ubuntu 15.10 running the latest release of the .deb file. I have screenshots of the issue attached.
![screenshot from 2016-08-07 16-14-27](https://cloud.githubusercontent.com/assets/9704519/17465039/18ba16c2-5cba-11e6-892f-7cceaede366c.png)
![screenshot from 2016-08-07 16-11-01](https://cloud.githubusercontent.com/assets/9704519/17465038/18b5928c-5cba-11e6-9298-614b4bbda802.png)
![screenshot from 2016-08-07 16-14-27](https://cloud.githubusercontent.com/assets/9704519/17465042/26773e20-5cba-11e6-8f5e-ca333222cdb2.png)
![screenshot from 2016-08-07 16-11-01](https://cloud.githubusercontent.com/assets/9704519/17465041/26762756-5cba-11e6-8072-5102a086f2e4.png)
![img_20160807_122338](https://cloud.githubusercontent.com/assets/9704519/17465049/6cbc1ebe-5cba-11e6-93bf-c3ea58905e43.jpg)

**Comment by kaykurokawa** [comment]
what's the format of the video file?

**Comment by jobevers** [comment]
Closing this as its old; please re-open if it still persists on the most recent version
