### ISSUE TITLE
Merge or close #835 (improper use of floats)

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry#1131]
https://github.com/lbryio/lbry/pull/835

**Comment by tzarebczan** [comment]
@hackrush01 are you still working on this?

**Comment by hackrush01** [comment]
@eukreign Can this PR be the solution to the things related to float and decimal problems?

**Comment by eukreign** [comment]
We're going to switch to using dewies/satoshis in the API so this PR is no longer needed.
