### ISSUE TITLE
Support HTTP sources

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry#1133]
Changes to the issue by @hackrush01
First refer to [the comment below](https://github.com/lbryio/lbry/issues/1133#issuecomment-400011940) for details
- [ ] add relevant fields to lbryschema to support this
- [ ] Addition of HTTPDownloader interface in the daemon, refer to document for details of the methods provided
- [ ] Implementation of the Interface
- [ ] Changes to db(still not worked out)

Other things will be added to the list as they are found out.

**Comment by hackrush01** [comment]
# Details
## Goal
To able to provide a HTTP(S) URL as source while publishing and being able to ddownload that.

## Proposal

### LBRYSCHEMA
The lbryschema will be changed to do the following:
1. accept HTTP(S) URL/URI in the source field
2. add a new field for the hash(SHA-256?) of the content(undetermined: the uploader needs to download the content, hash it himself, and then publish?)

The changes will be similar to but not same as https://github.com/lbryio/lbryschema/pull/10. This serves as a good reference as to what the changes with point 1 will look like.

### LBRYUMX and WALLET(either lbryum or txlbryum)
No changes expected

### DAEMON
There are a lot of changes expected, and it might include other significant refactor which not be know at the time of writing this document(20 June, 2018 nearly 11:12 AM):
1. Addition of HTTPDownloaderInterface with methods for(but not limited to)
    * Downloading, provided just the URL/URI(path will be taken from the configs). Will include a writer method.
    * Stop downloading
    * Resume downloading(possibly from where it left off even after a daemon restart or network outage)
    * Redownloading(maybe an if condition inside download/resume) if the hash doesn't match the downloaded file. It will be automatically re-download only once per file(if needed) if we still didn't receive the file with the correct hash we will stop attempting and let the user decide
    * Tracking progress
2. Implementaition of HTTPDownloader(HTTPDownloaderInterface) to actually do all of the above stuff
3. Changes in file table, or addition of new table for files download from other sources(TBD, honestly haven't thought about it much, and have little knowledge of that would integrate with our system)
4. Implement all of that using treq(which is based on twisted)

**Comment by jackrobison** [comment]
This is the current schema for a `Source`


```
message Source {
    enum Version {
        UNKNOWN_VERSION = 0;
        _0_0_1 = 1;
    }
    required Version version = 1;
    enum SourceTypes {
        UNKNOWN_SOURCE_TYPE = 0;
        lbry_sd_hash = 1;
    }
    required SourceTypes sourceType = 2;
    required bytes source = 3;
    required string contentType = 4;
}
```

Proposed change:

```

message IntegrityCheckpoint {
    required int offset;
    required int length;
    required bytes checkSum;
}


message Source {
    enum Version {
        UNKNOWN_VERSION = 0;
        _0_0_1 = 1;
    }
    required Version version = 1;
    enum SourceTypes {
        UNKNOWN_SOURCE_TYPE = 0;
        lbry_sd_hash = 1;
        static_http = 2;
        dynamic_http = 3;
    }
    required SourceTypes sourceType = 2;
    required bytes source = 3; // a lbry sd hash or a url
    required string contentType = 4;
    required int contentLength = 5; // the length of the published file in bytes
    required bytes contentHash = 6; // the hash of the published file
    optional bytes SSLCertificateFingerprint
    optional repeated IntegrityCheckpoint
}
```

**Comment by kauffj** [comment]
@jackrobison why is some of that information part of the source?

**Comment by lyoshenka** [comment]
we tabled this for now. Documenting my thoughts:

I think we should start with a simpler addition: just a url, filesize, and hash. There was conversation about security tradeoffs around having to download a giant file before you find out that the hash doesn't match, etc. I would prefer to do something simple first. We regularly make the mistake of starting with too much complexity.
