### ISSUE TITLE
Cannot update channel claims larger than wallet balance

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1142]
## The Issue
In solving https://github.com/lbryio/lbry/issues/748, we added the ability to use an existing bid amount for a claim bid, but we also need to perform the same logic on the channel update side as well. Currently, if you create another channel with the same name as an existing one, it will update the channel claim. In the future, the app may also allow the ability to edit channels, so this will come into play. 

Spoke to @hackrush01 about this. 

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by hackrush01** [comment]
Fixed here #1137.

**Comment by tzarebczan** [comment]
My bad, didn't realize you fixed it already. Had it on my notes :)

**Comment by hackrush01** [comment]
This got merged today, after you opened the issue I guess :-)

Amit Tulshyan,
Software Engineering Intern,
LBRY, Inc
