### ISSUE TITLE
Add --sort option to file_list

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1143]
## The Issue
I've noticed previously that my Downloads items don't show in the correct order - not sure exactly what causes them to get out of sync in file_list. The question is - should file_list have a field which has the download date (or a better name?) for a particular file? There doesn't seem to be any information currently available which would help with sorting a user's downloads. 

## Jeremy's Revised Issue
- Add a `--sort` flag to `file_list`
- Sort should take the following options: name, date, price
- Sort can be ASC or DESC

**Comment by kafene** [comment]
Hello LBRYians, I'm working on implementing this feature.

For sorting files by date, the LBRY app seems to simply rely on the incoming order of files in [the fileList component](https://github.com/lbryio/lbry-app/blob/master/src/renderer/component/fileList/view.jsx) which is their order of insertion into the "file" table.

Any thoughts on whether the date a file was added should be stored in lbrynet.sqlite? I'd add a new column for this, and could also add it as an attribute of `ManagedEncryptedFileDownloader` instances so it would appear in the results of file_list.

**Comment by kauffj** [comment]
@jackrobison example 1 of ∞ why every table should have `created_at` and `updated_at`.
