### ISSUE TITLE
fix directory issues in 0.19

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry#1145]
@tzarebczan says:

After the db upgrade, all files go to a default downloads directory.  This causes a few issues: 1) when you go to your claim and try to play the file, it won't be able to find it and then re-creates it in the default directory (even though downloads directory is set to something else) 2) any pending/incomplete downloads you had will restart into the old directory.  

You'd only be able to tell if you changed your downloads directory.

**Comment by tzarebczan** [comment]
Fixed in: https://github.com/lbryio/lbry/commit/e94d10d3eb04c5c78fdfb31711a08ce0ab2a326e
