### ISSUE TITLE
file startup significantly slower in RCs post 0.19.0

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1151]
## The Issue
Post 0.19.0 release candidates result in an extremely slow file startup process. A PC with 500 files went from 7 seconds to 7 minutes.

## System Configuration

 

- LBRY Daemon version: 0.19.1RCx
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by lyoshenka** [comment]
fixed
