### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by goodthebest** [lbryio/lbry#1153]
I'm trying build from git repo

I've first run `./prebuild.sh`
then
running `./build` is giving errors

![image](https://user-images.githubusercontent.com/1715740/37688949-dbbe3018-2cbb-11e8-8e76-fba87abff9f8.png)

It's asking for `setuptools` ?
Could anyone guide how to compile or build it?

**Comment by tzarebczan** [comment]
Woohoo, we have someone trying this for the first time!

We'll get the notes updated with anything we missed. 

Try Sudo apt-get install python-setuptools

**Comment by goodthebest** [comment]
Well **build** worked. However running `./lbrynet-daemon`

![image](https://user-images.githubusercontent.com/1715740/37689532-f1472a9a-2cbe-11e8-8aa6-90cef9e3f89d.png)

**Comment by tzarebczan** [comment]
Try the suggestion here to uninstall and reinstall pyopenssl - you may have had an incompatible version installed: https://stackoverflow.com/questions/43267157/python-attributeerror-module-object-has-no-attribute-ssl-st-init/43267158

**Comment by lyoshenka** [comment]
@goodthebest have you tried the steps in https://github.com/lbryio/lbry/blob/master/INSTALL.md

**Comment by tzarebczan** [comment]
Going to close this because it looks like the install docs were not followed.
