### ISSUE TITLE
Use Write-Replace Pattern to Prevent Wallet Corruption

### ISSUE THREAD

**Issue by eukreign** [lbryio/lbry#1158]
Saving the wallet by writing directly to the original wallet file can lead to a corrupt file in case there is a crash event (in lbry or the operating system) where the entire file does not get written completely.

A good strategy around this problem is something called the "Write-Replace" pattern whereby you always write to a temporary file first and then move the temporary file over the original file. Such a move operation is usually very cheap and efficient on the file system because it's just updating pointers to disk location. In case of a crash, you'll have both the original file and the corrupt temporary file, not ideal but at least there is opportunity to try and re-create a good version.

For an example, search here for "Write-Replace":
https://blog.gocept.com/2013/07/15/reliable-file-updates-with-python/

**Comment by hackrush01** [comment]
Yes, this seems like a good step.

Amit Tulshyan,
Software Engineering Intern,
LBRY, Inc

**Comment by alyssaoc** [comment]
closed with new wallet
