### ISSUE TITLE
DHT RC releases - blob announcer brings daemon to a crawl

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1163]
## The Issue
@jackrobison is aware of this issue, but filing for awareness. The DHT announcer changes have bogged down the daemon to the point where it's responses are really slow or don't return at all.  

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by jackrobison** [comment]
@tzarebczan this should be fixed by https://github.com/lbryio/lbry/commit/b4b1f1a2c14b88020a694f2ea4f6b5ffdaf9ffc5
