### ISSUE TITLE
LBRY Default Download Directory

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1176]
@Invariant-Change commented on [Mon Apr 30 2018](https://github.com/lbryio/lbry-app/issues/1416)

The default download director would be better if it was `\Downloads\LBRY\`

This would help keep files in order and help prevent **accidental deletion** of seeded content.

![image](https://user-images.githubusercontent.com/29914179/39426255-7e62eb6c-4cc2-11e8-807b-4c1453c29602.png)

---

@tzarebczan commented on [Mon Apr 30 2018](https://github.com/lbryio/lbry-app/issues/1416#issuecomment-385380821)

This would be a lbry issue, not an app issue. Plus, the content is not seeded from this directory, it's seeded from the blob files folder.

I'll move it over to the other repo later and it can be discussed.

**Comment by tzarebczan** [comment]
If we did want to proceed with this, we'd need to determine if someone already has downloads at the current location, and if so, we wouldn't want to change the directory.

**Comment by kauffj** [comment]
@tzarebczan should be able to change the value only for new/future installs.

**Comment by lyoshenka** [comment]
please reopen if this is still valid
