### ISSUE TITLE
Degraded responsiveness of daemon while downloading content

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1187]
## The Issue
While the daemon is downloading content, the overall responsiveness degrades. This can be clearly seen when trying to download a few pieces of content via the LBRY app. Once these downloads have started, it takes a while to bring up new claims because the resolve calls are slower. Caching could be employed on the app side, but nevertheless, daemon responsiveness is degraded. 

### Steps to reproduce
1. Start downloading content
2. Browser other claims via app or send api calls to daemon

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by alyssaoc** [comment]
verify this fix with the new wallet

**Comment by tzarebczan** [comment]
This was filed before the resolve enhancements, so the experience now is much improved. If I continue to see this, will open a new issue related to multithreading/performance overall.
