### ISSUE TITLE
UTXOs remain stuck unconfirmed

### ISSUE THREAD

**Issue by nikooo777** [lbryio/lbry#1192]
## The Issue

when using wallet_prefill_addresses and waiting for utxo to confirm (checking the result of utxo_list where all entries must have height !=0) the height isn't updated after a block is mined.

### Steps to reproduce
1. use `wallet_prefill_addresses` to refill addresses
2. use `utxo_list` to wait for the transactions to confirm
3. repeat until at least one entry is stuck on
``` 
   "height": 0,
```
for at least 1 mined block

### Expected behaviour
the height should update after a block is mined and the transaction is confirmed

### Actual behaviour
the height never updates until the daemon is restarted

## System Configuration

```
{
  "id": null,
  "jsonrpc": "2.0",
  "result": {
    "build": "rc",
    "ip": "54.209.131.62",
    "lbrynet_version": "0.20.0rc9",
    "lbryschema_version": "0.0.15",
    "lbryum_version": "3.2.1",
    "os_release": "4.4.0-121-generic",
    "os_system": "Linux",
    "platform": "Linux-4.4.0-121-generic-x86_64-with-Ubuntu-16.04-xenial",
    "processor": "x86_64",
    "python_version": "2.7.12"
  }
}
```

**Comment by tzarebczan** [comment]
@nikooo777 were you able to find a workaround for this or is it still a big blocker for YouTube sync?

**Comment by tzarebczan** [comment]
@eukreign might be another to add to your list for "things to check with new wallet" :)

**Comment by nikooo777** [comment]
it wouldn't confirm after waiting for a whole day. though i haven't seen this one resurface while using lbryumx

**Comment by nikooo777** [comment]
This issue has just resurfaced yesterday. I really don't know what's wrong.

**Comment by tzarebczan** [comment]
@nikooo777 is this still happening on Victor's lbryumx server? Still not sure if it's lbryum or lbryumx related.

**Comment by nikooo777** [comment]
it appeared to be still happening, though i moved away from using utxo_list to check utxos, instead I just wait for a block and spend.

**Comment by eukreign** [comment]
we've switched to the new wallet, so this shouldn't be an issue anymore, please re-open or file new issue if this happens again
