### ISSUE TITLE
Investigate exporting API documentation to Swagger format

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry#1203]
(This ticket is possibly under- or incorrectly specified since I don't know very much about Swagger.)

lbry.tech will need to display the API documentation for lbry, lbrycrd, and potentially other projects like lighthouse.

Having all repositories that provide an API export their API signatures in a shared, open format will allow lbry.tech to display all APIs in a similar fashion.

**Comment by hackrush01** [comment]
Next Steps
 - [ ] Check what the output format for the documentation should be
 - [ ] Assess the difficulty for changing the current one

**Comment by tiger5226** [comment]
As a reference, just in case it is useful, swagger documentation is used for chainquery [here](https://github.com/lbryio/chainquery/blob/master/swagger/chainquery.yaml). It is not complete yet but might be helpful. 

Also it can be done really easily now with the [open api designer](https://openapi.design/)

**Comment by lyoshenka** [comment]
My understanding was that Swagger does not support JSONRPC, only REST. Is that true? Maybe that's not true anymore?

**Comment by tiger5226** [comment]
https://github.com/OAI/OpenAPI-Specification/issues/801
Looks like it didn't get into 3.0 spec.

**Comment by lyoshenka** [comment]
I saw that. It’s over a year old. Have you seen anything newer?

**Comment by tiger5226** [comment]
No I could not find anything on the status of that. There was communication where people said they hacked it in, but I didn't think we would want follow suite there.

**Comment by lyoshenka** [comment]
bitshares is having the same issue: https://github.com/bitshares/bitshares-core/issues/792
