### ISSUE TITLE
DHT nodes should re-store values they find to the nearest peer without the value

### ISSUE THREAD

**Issue by jackrobison** [lbryio/lbry#1205]
### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by jackrobison** [comment]
This is blocked by the `findValue` response not including the `age` or `originalPublisherID` fields (which are in the node datastore). Adding these fields will be a non backwards compatible change, and possibly should coincide with the introduction of a network version field.

**Comment by alyssaoc** [comment]
@jackrobison Is this issue still valid?

**Comment by eukreign** [comment]
@jackrobison does the new DHT do this?
