### ISSUE TITLE
daemon_settings lbryum_servers setting being corrupted

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1207]
## The Issue
This may only happen in windows, haven't tested on other OSes yet. If you have a custom lbryum_servers: config in your daemon_settings.yml such as:

```
{disable_max_key_fee: false, download_directory: 'C:\Users\testaccountclean\Desktop',
 share_usage_data: true,
 lbryum_servers: ["victor.lbry.tech:50001"]}
```

And then go into app settings to change any persistent settings, i.e. max key fee, the file is then saved as (notice missing curley braces and syntax):
```
disable_max_key_fee: false
download_directory: C:\Users\testaccountclean\Desktop
lbryum_servers:
- [victor.lbry.tech, 50001]
share_usage_data: true
```

When restarting the daemon, you get: 
```
Traceback (most recent call last):
  File "lbrynet-daemon-script.py", line 2, in <module>
  File "site-packages\lbrynet\daemon\DaemonControl.py", line 61, in start
  File "site-packages\lbrynet\conf.py", line 532, in load_conf_file_settings
  File "site-packages\lbrynet\conf.py", line 508, in _convert_conf_file_lists
  File "site-packages\lbrynet\conf.py", line 167, in server_list
  File "site-packages\lbrynet\conf.py", line 162, in server_port
AttributeError: 'list' object has no attribute 'split'
Failed to execute script lbrynet-daemon-script
```

The correct syntax would be: 
```
lbryum_servers:
- "victor.lbry.tech:50001"
```
or
`lbryum_servers: ["victor.lbry.tech:50001"]`
## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by hackrush01** [comment]
@tzarebczan is this issue the same as #1109? If yes we should close on or the other.

**Comment by tzarebczan** [comment]
@hackrush01 ah thanks, now I recall this but didn't realize it was very similar. Might still be different on Windows, so I'll add my notes to your ticket. Thanks!
