### ISSUE TITLE
peer_list API changed in V20 - Dependencies?

### ISSUE THREAD

**Issue by tiger5226** [lbryio/lbry#1214]
API change for v20 

https://github.com/lbryio/lbry/pull/966

I have made the adjustment for lbry.go [here](https://github.com/lbryio/lbry.go/blob/apiserver/jsonrpc/daemon.go#L234)

However, has anyone reviewed where else the `peer_list` API is used? The change in returned parameters could cause issues for applications using this API.

**Comment by tzarebczan** [comment]
@tiger5226 I don't think we are using this anywhere else as it's been quite unreliable. We used to have an availability function in the app, but that was removed until the functionality is more consistent.

Going to close this for now...
