### ISSUE TITLE
Played a nsfw video by accident and I can't cancel download

### ISSUE THREAD

**Issue by DaniNz** [lbryio/lbry#1215]
## The Issue
I'm new to the app and I was clicking around, then  I clicked by accident on a nsfw video and there is no way to cancel the download.
I tried to go back(clicked the back button) but the download continued and the video was saved on my pc. Which I didn't want anymore.

### Steps to reproduce
1. click on a video
2. try to stop the download/resume download or cancel the download

### Expected behaviour
I think that in this type of situation there should be a button that allows you to stop/resume downloading the video and even canceling it.
### Actual behaviour
By clicking on play, the download starts without any possibility of stopping it in the case of an unwanted download or miss clicked.
## System Configuration
- LBRY Daemon version: 0.19.3
- LBRY App version: 1.8.6
- LBRY Installation ID: 2jDC7VNTmY4ojVA3rSs7Kqvv6ycVTgU56HeXu4sQGRu6QbgAzeJpAow5ysYSNwwsP2
- Operating system: Linux (Linux-4.13.0-43-generic-x86_64-with-elementary-0.4.1-loki)

## Screenshots
![screenshot from 2018-05-24 00 13 55](https://user-images.githubusercontent.com/16692007/40520786-66297e50-5f9e-11e8-8dcd-de307c896507.png)

**Comment by tzarebczan** [comment]
@DaniNz thanks for filing! Please consider searching through github issues prior to creating new issues, or check with us on https://chat.lbry.io if you are unsure. Sometimes the terminology may not be the same so finding matches can be hit or miss. 

A similar issue is already logged under: https://github.com/lbryio/lbry/issues/1199 (I'll update the title so it mentions downloads)
