### ISSUE TITLE
Allow sorting of claim related functions

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1225]
## The Issue
Per discussion in https://github.com/lbryio/lbry/pull/1216#issuecomment-392835700, 
we should enable the ability to pass a sort parameter to claim related functions in order to control the sorting method. 

The original issue, which was addressed to provide a consistent sort by default for claim_list/claim_list_mine, can be found here: https://github.com/lbryio/lbry/issues/1098

file_list recently went through a similar enhancement, the PR can be found here: https://github.com/lbryio/lbry/pull/1174

Claim related functions:
https://lbryio.github.io/lbry/cli/#claim_list_by_channel
https://lbryio.github.io/lbry/cli/#channel_list
https://lbryio.github.io/lbry/cli/#claim_list
https://lbryio.github.io/lbry/cli/#claim_list_mine

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by lyoshenka** [comment]
i think @eukreign did this in 0.38

**Comment by tzarebczan** [comment]
No, but we can do it as part of https://github.com/lbryio/lbry/issues/1853
