### ISSUE TITLE
sort parameter to file_list should be split up into two parameters

### ISSUE THREAD

**Issue by jackrobison** [lbryio/lbry#1227]
The `sort` parameter is being parsed for a comma separated ordering argument (ascending or descending). This should be split into an argument of its own - `sort_order` - since this breaks the existing pattern of arguments. Additionally, the `sort` parameter could have a better name (like `sort_by`) since it sorts by a given field.

**Comment by kafene** [comment]
The current implementation allows multiple sorts so each one is done as a separate pass, so the list can be sorted by one thing, then another, not unlike using SQL `ORDER BY foo DESC, bar ASC`

A more concrete example:

    $ lbrynet-cli file_list --sort=channel_name --sort=points_paid,desc

You'll get the list sorted by `points_paid`, largest values first, and each set of items with the same cost would be further sorted by channel name (in ascending order).

The daemon uses [docopt](http://docopt.org/) for argument parsing, so flags that allow multiple values end up as lists of whatever was passed in. My first thought was to `zip()` together the `sort_by` and `sort_order` arguments to get the same effective result as parsing a single input of `$field, $direction` but that doesn't work if someone omits the direction in between two sort choices.

Assuming the new API as proposed in this issue:

    $ lbrynet-cli file_list --sort_by=channel_name --sort_by=points_paid --sort_order=desc

The parsed arguments are:

    {'--sort_by': ['channel_name', 'points_paid'],
     '--sort_order': ['desc']}

So I see no way to associate the directions and field names.

Should multiple sort criteria be dropped and only one sort field allowed?

**Comment by alyssaoc** [comment]
@jackrobison Is this still an issue?

**Comment by tzarebczan** [comment]
Related to: https://github.com/lbryio/lbry/issues/1228

**Comment by eukreign** [comment]
This is implemented in the newest version as `--reverse`.
