### ISSUE TITLE
Certificate not written to wallet file on import (until wallet tx)

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1231]
## The Issue
When a channel claim is imported to another wallet, the wallet does not write the claim certificate until there's some transaction to the wallet (incoming or outgoing). If you close the daemon and restart, the channel will no longer show in channel_list. 

### Steps to reproduce
1. Send a channel from one install to another
2. After importing, run channel_list_mine - confirmed there
3. Check default_wallet for claim - not there
4. Make a tx to the new wallet. 
5. Check default_wallet for claim - now it's there. 

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by kauffj** [comment]
This seems like a pretty large bug.
