### ISSUE TITLE
Improve communicability of release notes

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry#1237]
I :heart: the thoroughness of [https://github.com/lbryio/lbry/releases/tag/v0.20.0rc13](https://github.com/lbryio/lbry/releases/tag/v0.20.0rc13) and read every item.

But a lot of people won't. Things to consider:

- Putting more important items towards the top.
- Including a 1-3 sentence description/summary ("This release contains significant improvements to the DHT, in areas of functionality, testing, and organization. Additionally, blah).
- Using nested lists and/or sub-headers.

**Comment by eukreign** [comment]
We released v20.
