### ISSUE TITLE
Support channel updates, do not allow updates which invalidate signature

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1239]
## The Issue
Currently, if you create a new channel via the LBRY app UI or run the channel_new for a channel that already exists, it will update the channel but create a new public/private key which invalidates old publishes on the previous channel. We should prevent this from happening and instead support claim updates. 

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by lyoshenka** [comment]
closing in favor of https://github.com/lbryio/lbry/issues/1823
