### ISSUE TITLE
New Users can't Publish Anything Without Paying

### ISSUE THREAD

**Issue by martinvahi** [lbryio/lbry#1240]
I do not really know the lbry system, but according to 
what I have read from the

https://lbry.io/faq
(archival copy: https://archive.is/iOLJS )

users, who do not want to monetize their content, 
are banned from publishing their videos, unless they
pay for or earn LBRY specific cryptocoins to pay 
for the deposit of the "LBRY_domain/claim".  A solution
to that issue might be that there might be some 
set of "system domain prefixes" and one of those
prefixes is reserved for the free domains. The 
"claim"/LBRY_domain_URL would look like:

    lbry:/nonmonetizable_and_squattable_<sha256(acquisition date)>_<user chosen suffix>

Only an idiot would want to squat that kind of a domain, but 
those domains can be copy-pasted to letters/chat_rooms and 
used at bookmarks. It's interesting that You claim that LBRY 
must work for the "common man", yet You force the
"Jim and Jill" to start figuring out, where to get
the cryptocoins to get a domain to publish their cat
and dog videos.

Honestly, the alternative to the adoption of the 
freely available domains is that the LBRY will be
just another NETFLIX, with new technology
learning curve related hindrance and all of the
fun and freely accessible videos are on 

https://zeronet.io/

and other P2P networks, like the 

https://www.youtube.com/watch?v=pi-kreA52oI

and the 

https://ipfs.io/

I am NOT impressed.
Thank You for reading this text.

**Comment by kcseb** [comment]
You do realise, you don't have to spend a dime from your pocket to upload content, right? 
We have the rewards system for a reason. Users verify their account (totally free and easy) and earn FREE LBC to publish their content. 

It couldn't be easier.

**Comment by Invariant-Change** [comment]
Hi @martinvahi 

Users, who do not want to monetize their content are **NOT** banned. You can set any price to charge for your content or set it as free as seen in the screenshot below.

[![image](https://user-images.githubusercontent.com/29914179/41213091-3f30b26e-6d86-11e8-8964-3d7ad7e431a6.png)](https://lbry.io/get)

However, if you mean "people are forced to use LBRY Credits to upload content" to a **lbry://** URL, then yes, you are correct. This is how the system works to secure a claim on the blockchain where your content is registered. However, this amount is **microscopic**. With just **1 cent** you could upload a large amounts of content.

This is further offset with the **FREE** LBRY Credits you given via **rewards** for using the platform.

See more information about rewards [here](https://lbry.io/faq/rewards).

As for **Community** URL's, think of this like advertising space you bid for. Their price is determined by the market. See below for more details.

## The Naming System/URLS's

There are various types of URL's you can have with LBRY.
* * **Community**: These act like advertising space (that's my spin on it).
* * **Permanent**: These remain yours indefinitely.
* * **Channel**: This is like a _username_ for your content.
* * **Signed**:  Content published to a channel.

See __[here ](https://lbry.io/faq/naming)__ for more details about how naming works.

It's a new system that might not make sense to new people, but we are working to make it easier to understand.

## Find out More and Speak to us on Discord

Why not come and talk to use on the [Official Discord Server](https://t.co/P4nCGGqAUk). This is where all the magic happens.

We welcome all questions, all criticism and any feedback you have.

[![image](https://user-images.githubusercontent.com/29914179/41213549-5c1e255c-6d89-11e8-90ba-82e534ecd48d.png)](https://t.co/P4nCGGqAUk)

**Comment by martinvahi** [comment]
Thank You both for the answers, specially @Invariant-Change, 
who's thorough and detailed answer I specially like. 
Unfortunately I like the @Invariant-Change answer mainly because 
of the nice amount of details and effort made to give ma a really 
thorough answer _(I love, if people are thorough and "not so much", if they are superficial)_,
not because it would be able to convince me that I was wrong or on a wrong track. 
Namely, by using a citation from @kcseb answer:

> Users verify their account (totally free and easy) and earn FREE LBC to publish their content.

says it directly that new users are not able to _easily_ get LBC
WITHOUT GIVING UP PRIVACY. After all, authentication is what 
the verification/registration is all about. At the documentation there
were statements that YouTube/Google is nasty because it tracks 
people, but at the documentation it also said that the LBRY.io 
tracks people with the purpose of avoiding the abuse of the Rewards program.
If I remember it correctly, the policy was that only one account from
each house-hold is allowed to get the rewards. The Googe and Facebook
pretty much can infer, who lives with whom, but even they do not have
it as a policy enforcement goal to find out, who lives with whom.

To be direct, is it really Your goal to eliminate the creation of 
temporary, anonymous, accounts that are operated through Tor relays?
Obviously people with technical skills will find a way to do it 
even right now, but there is a reason, why the teams at

https://theintercept.com/
https://www.torproject.org/projects/torbrowser.html.en?
https://wikileaks.org/

try to make it easy for people to use their 
channels anonymously as easily as possible.
Honestly, I believe that the LBRY.io team should develop
a "version 2.0" of the protocol, before their money runs out.
If You do not, then Your competitors at 

https://zeronet.io/
https://beakerbrowser.com/
https://ipfs.io/

will make sure that the LBRY.io is just a P2P NETFLIX, 
not the distrubuted-web-locked-open what the founder
of the Internet Archive called for at his presentation at 

https://archive.org/details/bresterkahlenetgain

As far as I know, currently the ZeroNet does not yet scale, despite 
the P2P and BitTorrent, but that's actually fixable, not something
fundamental, specification level flaw, it just takes some extra coding, but
here's a ZeroNet version of a YouTube competitor, KopyKate:

http://127.0.0.1:43110/18Pfr2oswXvD352BbJvo59gZ3GbdbipSzh/
The same page through a WWW gateway:
https://www.zerogate.tk/18Pfr2oswXvD352BbJvo59gZ3GbdbipSzh

All fully anonymous, NO HASSLE FOR NEW USERS. The KopyKate
is just ONE WEB PAGE OUT OF MANY on ZeroNet and the LBRY.io
wants to compete with just one of the ZeroNet pages. Another awesome
application on ZeroNet is a GitHub clone that hosts Git repositories:

http://127.0.0.1:43110/gitcenter.bit
This page is NOT available through the 
https://www.zerogate.tk/gitcenter.bit
because the gateway was "abused"(quotes, because it is 
not possible to "abuse" a system that has been designed for unrestricted use) 
by pedophiles and the administrator of the WWW gateway decided that the
simplest way to stop the Police from finding his gateway to be interesting
is to stop downloading new ZeroNet pages to the gateway. 

ZeroNet web pages are basically composite documents like 
the Microsoft Word and LibreOffice documents are, except that
the document is a folder with plain HTML/JavaScript/CSS and
some manifest files. In general, the viewing of ZeroNet pages
is like with the Microsoft Word and LibreOffice documents:
one has to download the document to "open" and view it.
So, in ZeroNet, the composite documents are downloaded 
in a P2P fashion. The manifest files can declare some of the
files at that the folder that forms a ZeroNet page/document 
to be optional, so that a user has to explicitly
allow the download of those files. That makes it possible to 
host "huge"(whatever that means, 200GiB is is huge 4 me) files
on ZeroNet. 

ZeroNet pages/documents, are versioned and
a new version can be published only by the party that
has singed the previous version. The signing and key management
is done automatically, by the server, which is written in Python.
To move the identity data, including identity crypto keys, 
from one computer to another, the user has to copy a few files.
Forums, like the one at the 

http://127.0.0.1:43110/Talk.ZeroNetwork.bit/
https://www.zerogate.tk/Talk.ZeroNetwork.bit/

are essentially collectively editable documents, almost
as if a MicrosoftWord/LibreOffice document were shared at
some network drive and then different people make edits to it.
The owner of the document, who signs the initial version of the
document, determines the various access rights at settings/manifest file.
As with the MircosoftWord/LibreOffice documents, there is 
no need for an internet connection to edit them. The ZeroNet 
documents that are forums, are a collection of merged edits/posts
and the individual posts are published when the ZeroNet server
gets access to the Internet to publish the posts/additions. That
is to say, people may just make the edits/posts with their laptop
while being without any internet connection, just riding a train
or a bus/plane, and once the internet connection becomes available,
the edits get uploaded automatically.

And, as I said, the whole LBRY.io 

    COMPETES WITH ONLY A SINGLE ZeroNet PAGE

while adding a considerable amount of hindrances to the new users.

If that's not good enough of a reason for the LBRY.io development
team to start working on version 2.0 of the LBRY protocol, then
I do not know, what is. On the other hand, I admit that I have difficulties
understanding, why some technically crappy projects are financially
some of the most successful ones. Think of Microsoft Windows, which
was not unique or ahead of its time, because the Niklaus Wirth had its
very similar, end user oriented system, available literally at the same
time, when Windows had its popularity at rise:

https://en.wikipedia.org/wiki/Oberon_(operating_system)

The way I currently understand the financial success of the Microsoft,
the Bill Gates was innovative at sales channel development and beat 
its competition by selling in bulk to huge corporations, where a few people
at the top of the corporation decide, what the thousands of employees 
will use. Not only was it a very effective way to sell a lot of licenses, but
it also decoupled the buying decision maker from the people, who actually
use the product, so that when the product is crappy, the person, who 
has bad opinions about the product, does not make the buying decision. 

Can Your marketing team really beat ZeroNet, specially given that
the ZeroNet has been literally developed by the founders of ThePirateBay?

(The main author of the ZeroNet, Peter Sunde, talking 
about the history of ThePirateBay and his jail time.)
https://www.youtube.com/watch?v=3MjCM1e87kA

Still not considering a version 2.0 of the LBRY protocol ? :->

It's just that I want You people to succeed, but 
I'm not able to see, how You have any chance of succeeding
the way You are currently trying to do things. But, I'm truy
crappy at understanding social processes. Usually I'm mistaken
by considering other people to be more rational than they 
actually are and may be You can just pull off some 
marketing and psychology tricks, like the Apple has been
very successful at doing. Besides, who am I to give any
business advice, given that I'm self totally shoddy at business.
I tend to see only the technical aspects of projects. 

Thank You for Your answers and
thank You for reading this text.

**Comment by Invariant-Change** [comment]
I agree somewhat. Although my reason will be short as it's late night this side of the planet.

I believe that if the app came with something like 0.005 free LBC's (fuzzy logic in a fluctuating crypto market) using a unique anonymous token, to secure, it would allow a new user to use the application as soon as they download it and totally anonymously.

It would be hard to see a way for that microscopic amount of LBC to be abused especially if a few fail-safes were within the app to prevent abuse.

However, there could be some technical challenges they are still trying to overcome.

@tzarebczan Is this something that has been discussed? Getting LBRY to work straight out of the box, no sign-up/verification or crypto transfer required? I do see that as a selling point, making the concept less friction and more anonymous.

**Comment by Invariant-Change** [comment]
And before I drop off into the land of nod @martinvahi I see you are a **StackExchange** user.

You could put some of your questions here:  [LBRY Protocol - Proposal](https://area51.stackexchange.com/proposals/118455/lbry-protocol)

**Comment by martinvahi** [comment]
@Invariant-Change 
Thank You for yet another excellent answer. 
Please do not get me wrong in a sense that I use some irony here,
I really like the way You try to address the problem and the fix that
You proposed also makes sense to me, but the market does not
care, what we 2 think here and by paraphrasing Your statement

> However, there could be some technical challenges they are still trying to overcome.

I say/write that 

    the Titanic also had some technical challenges to overcome.

Not a good excuse, if You ask any of the passengers. :-D

But Your fix is nice, it's just that You probably will have a tough job 
selling Your fix to the team. But, as I described at my relatively long comment at 
https://gist.github.com/lyoshenka/0a43205aa9a072b196ff87e2c689a8b9
I would not fit into the LBRY team, so anything I propose is probably
not going to be taken well. People are different, have different preferences,
culture based requirements and may be I'm just not 
the target audience for an application like the LBRY is.

But, I emphasize that I'm glad for the answers I have received
here and I thank You all for reading my comments :-)

**Comment by Invariant-Change** [comment]
> The Titanic also had some technical challenges to overcome.

[Or did it?](https://youtu.be/STgBilaTDto) **Puts tinfoil hat away*.

Again, somewhat/mostly agree. **LBRY** is in **BETA**, so all passenger come fitted with life jacket and it's **feedback** like yours that helps **LBRY** become a better **ship** ready for launch :)

So many **thanks** for the time and effort you have also put in to give this feedback. It is very **important**!

My cabin awaits me. But I will be ready to answer any futher questions you may have when on deck in the morning (UTC+10).

![image](https://user-images.githubusercontent.com/29914179/41231731-6c96dc42-6dc7-11e8-9e3d-f7930f88dae2.png)

**Comment by tzarebczan** [comment]
@martinvahi thanks for your comments, suggestions and concerns. I think a bunch of it was already addressed by @Invariant-Change , but I'll leave a few more points:

1) Sure it may be difficult to acquire LBC at the moment, but we hope regulations/laws around cryptocurrencies will make this easier in the future.

2) If you use the manual verification method, we generally understand users' need for privacy and approve them even without real names/social media accounts.

3) One free alternative to publish videos/images on LBRY currently is https://spee.ch  - we foot the bill for publishing. 

Regarding the alternatives you speak of, I don't really have any comments. IPFS looks like a promising tech, but there's no monetization strategy at the moment - you are at the mercy of the hosts, which may mean data storage is temporary. LBRY's future goals will be to create a data market around sharing content, which will incentivize hosts to store data.

**Comment by martinvahi** [comment]
@tzarebczan 
Thank You for the answer.

> IPFS looks like a promising tech, but there's no monetization 
> strategy at the moment - you are at the mercy of the hosts, 
> which may mean data storage is temporary. 

Aren't we all at the mercy of the hosts, who host our current WWW pages?

The monetization policy of paying a yearly fee, in €/$, to the web hosting companies
seem to keep the web pages up pretty well. If P2P systems reduce the 
network traffic that the current, centralized, supermafia censored, hosting 
companies have to deliver, their costs at the network connection side go down.
As of 2018_06 I believe that the most critical hosting service that a P2P network
needs and where money is needed for keeping the servers running is

    SEEDING

That can be done with the old business model of paying to the hosting
companies, as is the case with Tor network hosting companies. 
Some examples that I was able to see with the TorBrowser:

(TorBrowser download site)
https://www.torproject.org/projects/torbrowser.html.en?

(Tor network pages of Tor network hosting companies,
semi-randomly picked from some Tor forum.)
http://kowloon5aibdbege.onion/
http://ezuwnhj5j6mtk4xr.onion/

To give You a quick idea, I created a screenshot 
https://temporary.softf1.com/2018/bugs/2018_06_11_screenshot_of_hostie65cxwr4tza_dot_onion.png
of this one:
http://hostie65cxwr4tza.onion/
_(The Tor "Hidden services" are really not hidden at all,
because if they were, then the Tor network itself
would not be able to find the servers in real-time for 
real-time communication. Only the clients of the servers
can have anonymity.)_

As a matter of fact, encrypted chunks that are salted, can be seeded/hosted
even by using the current censored web hosting companies, the 
ones that host the WWW, because if the supermafia("government")
can "ban" some of the use cases  of the classical "cloud" _(I hate that term)_, 
then they might as well "ban" certain type of traffic at ISP networks and
most of the current P2P traffic goes through centralized ISP networks,
which are vulnerable to the point that people can't buy food from 
grocery stores, as happened in Estonia, Tallinn, my home town:

(The Hollywood style graphics of the movie is an exaggeration,
just try to bare the graphics, but the talk, the statements, are not an exaggeration.)
https://www.youtube.com/watch?v=sWKgcxHyS10
(Part 2 of the clip.)
https://www.youtube.com/watch?v=O-odEtppUsk

    ---my--side--comment--start---
    Very subjectively speaking, I do not think that well
    of the NATO Cyber Defense Center in Tallinn, because
    they seem to put their focus on supermafia rules ("law" in 1984 new-speak/news-peak)
    in stead of the technical aspects. The list at the 
    https://ccdcoe.org/publication-library.html
    seem to have more to do with 
    social processes than the technical aspects of the matter.
    Hence my relatively poor opinion of them. May be
    I would think better of them, if they swapped their name to
    "NATO Center for Social Organization Research"
    ---my--side--comment--end----

That is to say, as long as P2P systems use centralized ISPs,
the supermafia("government") can easily take down any P2P
system and if they can take down any P2P system anyway, 
then it does not matter, whether those P2P systems depend
on centralized web hosting companies for seeding encrypted
and salted chunks. To spell it out: unless You are designing 
for citizen built 

    PHYSICAL P2P NETWORKS

then there already exists an excellent set of hosting
service providers, who have proven themselves to be
quite reliably available. For comparison, I tried to 
design my 

(Redirects to my softf1.com)
http://silktorrent.ch

for a situation, where the ISPs are DOWN and 
bits of information are delivered on USB/sticks, memory cards,
mail pigeon drones, vehicles, live pigeons at an environment where 
classical omnidirectional antenna based radio receivers 
fall victim to jammers. 

If you want an overview of different competing projects, then
You may find a list of different P2P-like solutions at my Silktorrent 
Fossil repository, at 

https://www.softf1.com/cgi-bin/tree1/technology/flaws/silktorrent.bash/wiki?name=List+of+Similar+Projects

I also have a collection of slightly "more interesting" scientific papers at

https://www.softf1.com/cgi-bin/tree1/technology/flaws/silktorrent.bash/wiki?name=Attic+001+for+Holding+Various+Files

If You wish, then You may clone 
the whole repository _(about 30GiB)_ 
by using the commands at 

https://www.softf1.com/cgi-bin/tree1/technology/flaws/silktorrent.bash/wiki?name=User+Guide

Thank You for reading my comment(s)/texts 
and thank You for the answer(s)     :-)

**Comment by tzarebczan** [comment]
Thanks again for your suggestions and thoughts. The data layer of LBRY can be extended to many of these other protocols, even IPFS down the road. Right now we are focusing on the LBRY P2P network and HTTPs, but will look support BitTorrent and others down the road.

**Comment by martinvahi** [comment]
@tzarebczan 
Thank You for the answer.
