### ISSUE TITLE
LBRY Protocol Inherits LBRY coin Crypto Related Flaws

### ISSUE THREAD

**Issue by martinvahi** [lbryio/lbry#1241]
The HTTP has been decoupled from all payment methods.
That allowed the HTTP to be used with different currencies
and also without paying anything at all. This decoupling
has allowed different "business models" for infrastructure
development. An Estonian example:

http://sange.fi/~ozone/Tigerleap.pdf

In the case of the HTTP people were able to 
pool money together, buy the hardware, install
the software and as long as there was electricity,
for running a LAN and some router that connected
it with WAN, everything just worked. In a limited
manner everything worked even, when the
WAN connection fell down. In contrast, in the case of the 
LBRY protocol, submariners, who want to 
set up their submarine-LAN, will fail to use the LBRY protocol, 
because either they have to start spending considerable time on 
mining for the LBRY coins or in the radio silence
they lack the internet connection to log on to 
some cryptoexchange to buy the LBRY coins.

The HTTP is VERY OLD. Do You really believe
that the crypto algorithms and hash algorithms
that the LBRY coin system depends on, will
last that long? If they do not last, then what will
happen with the LBRY protocol, if the crypto
behind the LBRY coin is broken/outdated?
My guess is that in that event the protocol will have to be changed 
and that will break compatibility with clients and
appliances that were installed with an assumption
that the appliances WILL ACTUALLY WORK
AFTER THEY HAVE BEEN INSTALLED!

I suspect that there might be a cultural mismatch
at the LBRY protocol specification level. Americans tend to think that 
it's OK to use temporary solutions, because if things break, then 
things will be thrown out and replaced with new ones.
Estonians, Japanese, Germans, people at Northern-Europe, 
tend to assume that things actually have to last and 
be reliably available. The way I see it, the LBRY protocol
is not something to be relied on with an assumption that
it will work after 20 years, WITHOUT ANY CHANGES TO 
THE CLIENT SOFTWARE and/or appliances that use it.
Given the advances in cryptography, the LBRY protocol 
will probably not last even 10 years, because it is so tightly
tied to cryptocoins, which depend on cryptography. 

An example of a truly old P2P system, which tends to be
morally outdated, but CAN STILL BE USED and IS STILL BEING USED 
is the 

(It's slow as hell, but at least it was made to last.)
https://freenetproject.org/

I hope that I'm hopelessly mistaken.
Thank You for reading this text and 
thank You for Your answers.

**Comment by lyoshenka** [comment]
Thanks @martinvahi for your question. You are right that you should not expect LBRY to work exactly the same way 20 years from now as it does today. If that's one of your requirements, then LBRY is not the right choice for you.

Our belief is that its almost impossible to create something new from scratch and get it right the first time. Even today's bitcoin is not compatible with bitcoin from a few years ago. Instead, we plan to take an iterative approach, learning as we go and improving the protocol over time. This may involve bug fixes, new features, changes in cryptography, or anything else that makes LBRY better.

If you absolutely must use LBRY and need to ensure that nothing changes, you are welcome to fork the project and modify it to suit your needs.

**Comment by martinvahi** [comment]
Thank You for the answer.
