### ISSUE TITLE
Change documentation build process to support lbry.tech

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry#1243]
- @Krisseck has a modified version of `gen_docs.py` that will work for usage with Slate.
- His script will create `api.md`, a markdown file that lbry.tech will use to generate documentation via Slate
- Script should be run automatically or by hand on all production releases.

**Comment by kauffj** [comment]
@Krisseck will update this ticket when he has opened a PR with his modification

**Comment by eukreign** [comment]
We have a script now to generate a JSON formatted API that feeds into lbry.tech.
