### ISSUE TITLE
Fix your floats

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1251]
## The Issue
When publishing with a 0.01 bid, the daemon shows: 
`2018-06-14 18:24:20,480 INFO     lbrynet.daemon.Daemon:2152: Publish: {'claim_address': None, 'channel_id': u'', 'name': u'2avzsi111', 'claim_dict': {'version': '_0_0_1', 'claimType': 'streamType', 'stream': {'version': '_0_0_1', 'metadata': {u'license': u'None', u'language': u'en', u'title': u'decimal test', 'version': '_0_1_0', u'nsfw': False, u'licenseUrl': u'', u'thumbnail': u''}}}, 'channel_name': None, 'bid': Decimal('0.01000000000000000020816681711721685132943093776702880859375'), 'file_path': u'C:\\Users\\SoloDolo\\Desktop\\2avzsi.jpg', 'change_address': None}`

Sample with 0.1: 
`2018-06-14 18:32:47,834 INFO     lbrynet.daemon.Daemon:2152: Publish: {'claim_address': None, 'channel_id': u'', 'name': u'html2', 'claim_dict': {'version': '_0_0_1', 'claimType': 'streamType', 'stream': {'version': '_0_0_1', 'metadata': {u'license': u'None', u'language': u'en', u'title': u'test 2', 'version': '_0_1_0', u'nsfw': False, u'licenseUrl': u'', u'thumbnail': u''}}}, 'channel_name': None, 'bid': Decimal('0.1000000000000000055511151231257827021181583404541015625'), 'file_path': u'C:\\Users\\SoloDolo\\Desktop\\html.html', 'change_address': None}`

The files are actually published with the correct value, but this doesn't look good for the logs.

### Steps to reproduce
1. Run daemon on master
2. Publish something with a bid value of less than 1

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by eukreign** [comment]
Seems correct to me. The 0.01 is probably being sent as a float and not a decimal in the JSON (then it's turned into a `Decimal` by the new code but by that point it's too late). If you want to have a nice looking '0.01' decimal it would have to be passed as a string and then parsed directly by `Decimal` bypassing any `float` stuff. `floats` are nasty business.

Can you try changing the app to send the decimal as a string and see if you get `Decimal('0.01')` in the log instead of the ugly `float` inside a `Decimal` you're getting now?

**Comment by eukreign** [comment]
One thing we could do is round the float after converting it into a decimal. But I would rather just depricate floats altogether instead of piling on hacks.

**Comment by tzarebczan** [comment]
We'll give this a try on the app side. The problem worsens when you publish something with a bid like .99:

`2018-06-14 18:37:56,551 INFO     lbrynet.core.Wallet:1187: Send claim: html3 for 0.9899999999999999911182158029987476766109466552734375: 080110011a650801121e080410011a0674657374203322002a0032044e6f6e6538004a0052005a001a41080110011a30bcbef283e927971b2d5150d499574239285dbd4e69840aa19f12d461a67ea6cfc29b0ba99c1b7041345667de985df4e72209746578742f68746d6c `

**Comment by eukreign** [comment]
@hackrush01 provides a work around in this pull request (i'm still on the fence if this is the best way but it does the job for now): https://github.com/lbryio/lbry/pull/1257
