### ISSUE TITLE
POW is wasted resources that could be used to power the service instead

### ISSUE THREAD

**Issue by lardnicus** [lbryio/lbry#1265]
The current system is centralised and wide open to being overtaken by a more advanced and decentralised implementation. It also uses wasteful PoW mining instead of allowing users to contribute those same resources to improving the speed and stability of the network.

### Expected behaviour

Content loads faster than YouTube
The app should leverage encrypted, peer to peer bandwidth and hosting and reward users for contributing "proof-of-bandwidth" and/or "proof-of-capacity" resources to the network in LBRY credits, instead of wasting those same resources doing PoW mining.

### Actual behaviour

Videos from the app are slow to arrive as they are hosted on centralised servers
The LBRY token comes from PoW mining which is wasteful of electricity
There is no incentive to contribute resources/bandwidth to the network

**Comment by tzarebczan** [comment]
Which parts do you think are centralized? 

The LBRY P2P network includes anyone who downloaded the file, not only our servers.
The long term plans include data markets / incentivized hosting.

**Comment by lardnicus** [comment]
Awesome!

(yes, bitcoin is absolutely a waste of resources, but it's a product of it's age. Newer cryptocurrencies have different proof methods that are less resource intensive)

**Comment by tzarebczan** [comment]
We have no plans to move away from PoW at the moment. If PoS tech improves in the future, we will consider it for the LBRY blockchain.
