### ISSUE TITLE
latest daemon blob announcement is slower than previous versions

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1270]
## The Issue
With iterative find added, announcements on 0.20.0 are much slower compared to previous versions. @jackrobison is aware of this issue, logging on GitHub for traceability. 

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by alyssaoc** [comment]
@jackrobison What are the next steps to improve this?

**Comment by jackrobison** [comment]
@tzarebczan is this still an issue on 0.21.2?

**Comment by alyssaoc** [comment]
@jackrobison assess the speed of this

**Comment by eukreign** [comment]
@jackrobison easy close?
