### ISSUE TITLE
Port Daemon to Python 3

### ISSUE THREAD

**Issue by hackrush01** [lbryio/lbry#1273]
Breakdown of steps:
- [x] Check which requirements are not compatible with python 3, and find their replacement libraries (3)
- [x] Illustrate Next Steps (1)

Helpful reference: https://medium.com/@boxed/moving-a-large-and-old-codebase-to-python3-33a5a13f8c99

**Update July 25**
Daemon starts with python 3 now and almost everthing works(dht, curl, wallet)
Things left for completion are
- [ ] check all the commands that they are running in python 3 (~10 points)
- [ ] port the current JSONRPC to aiorpcx as the older one is not available in python 3 (5 points)

**Comment by eukreign** [comment]
Some motivation on why py3 port is important (other than the fact that py2 is depricated very soon https://pythonclock.org):

> uvloop makes asyncio fast. In fact, it is at least 2x faster than nodejs, gevent, as well as any other Python asynchronous framework. The performance of uvloop-based **asyncio is close to that of Go programs**.

https://magic.io/blog/uvloop-blazing-fast-python-networking/

**Comment by eukreign** [comment]
This has been split into smaller issues.
