### ISSUE TITLE
Update pydocs to handle new API documentation format and display

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry#1276]
1. New header, `Example Response:` that includes the actual JSON of a real response.
1. New optional header, `Example Request:`, that includes a cURL version of a real request.
1. All descriptions should be audited.
1. All returns should be audited for consistency and actual abstract definitions of the returned data.

**Comment by NetOperatorWibby** [comment]
Depends on 
https://github.com/lbryio/lbry.tech/issues/42

**Comment by kauffj** [comment]
@eukreign I believe this is on you to update `gen_docs` to output the documentation in a JSON-schema matching what is described [here](https://github.com/lbryio/lbry.tech/issues/42#issuecomment-404944746).

**Comment by eukreign** [comment]
@NetOperatorWibby this should get you started, let me know if you have any issues with it:
https://github.com/lbryio/lbry/blob/html_gen_docs/docs/api.json

**Comment by BrannonKing** [comment]
@eukreign , that html_gen_docs link doesn't work for me.

**Comment by eukreign** [comment]
This is done: https://lbry.tech/api

I created another issue to track creating actual examples of API use: https://github.com/lbryio/lbry/issues/1334
