### ISSUE TITLE
Responding to notification JSON-RPC objects

### ISSUE THREAD

**Issue by ocornoc** [lbryio/lbry#1279]
## The Issue

The daemon, when sent a notification JSON-RPC object, will still respond, rendering the daemon not strictly compliant with JSON-RPC.

https://www.jsonrpc.org/specification#notification

### Steps to reproduce
1. Send a JSON-RPC notification object (equivalent to a request object with `id = null`).
(as an example, a `status` API call)

### Expected behaviour
The daemon shouldn't respond, as per the JSON-RPC specification.
https://www.jsonrpc.org/specification#notification
"The Server MUST NOT reply to a Notification, including those that are within a batch request."

### Actual behaviour
The daemon will respond to the notification as if it were a regular request.

## System Configuration

- LBRY Daemon version: v0.20.2
- Operating system: Ubuntu/Linux

## Anything Else

"Fixing" this is only necessary if LBRY's daemon is intended to be strictly JSON-RPC compliant. IMO, this likely is going to break potential 3rd-party interfaces that don't adhere to the JSON-RPC specifications when fixed. Though, if/when fixed, the daemon will have actual compliance *and* will be more deterministic for batch request objects that have notifications interspersed.

**Comment by eukreign** [comment]
I don't believe we have any `Notification` end points in the current API; all endpoints return some JSON response.

The jsonrpc.org v2.0 specification that you linked to presents the `JSON-RPC over HTTP` support "with some limitation" as an afterthought which sounds a bit strange to me. I would argue that single request/response HTTP style communication is the most common way that APIs are exposed while the JSON-RPC specification is heavily slanted towards something more suited for persistent full-duplex communication (such as via WebSockets).

We do have plans to add WebSocket support to the daemon and this will be conformant to the jsonrpc.org specification v2. There are no current plans to have the simple daemon HTTP JSON RPC API become conformant  (see previous paragraph), more likely in the long run the HTTP JSON RPC API would be dropped altogether in favor of a new REST API. For simple / command line use cases it would be encouraged to use the REST API and for anything requiring more complex interaction we'd encourage developers to use the WebSocket API.
