### ISSUE TITLE
Blocks til expiration / expiration height calculations in claim_list_mine

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1293]
## The Issue
Per @kaykurokawa, the blocks til expiration/expiration height that's calculated in claim_list_mine is hard coded in: https://github.com/lbryio/lbryum/blob/master/lbryum/wallet.py#L1034

We should either grab this from lbryumx or handle some other way. 

# System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by alyssaoc** [comment]
@eukreign How is this being handled in the new wallet?

**Comment by eukreign** [comment]
Figuring out when a claim expires still needs to be done in new wallet.
