### ISSUE TITLE
Reimplement blockchain header download status

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1295]
## The Issue
@akinwale will be reimplementing https://github.com/lbryio/lbry/pull/1266 per discussion on Slack. 
Believe this relies on https://github.com/lbryio/lbry/pull/1294

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by jackrobison** [comment]
https://github.com/lbryio/lbry/pull/1328
