### ISSUE TITLE
Fix build issues once and for all! 

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1298]
## The Issue
Appveyor running into limits so we are not getting builds for all OSes created on our releases pages (soon to be build page?). Need to figure out a path forward to solve this problem once and for all. 

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by nikooo777** [comment]
Alright We'll get rid of all those hosts then once travis works!

**Comment by eukreign** [comment]
This has been completed in `lbryum-refactor` branch, we can now build windows, linux and mac daemon binaries on travis.
