### ISSUE TITLE
--conf doesn't error when file doesn't exist

### ISSUE THREAD

**Issue by eukreign** [lbryio/lbry#1302]
When passing a custom settings file to `lbrynet-daemon` it should fail if the settings file doesn't exist, instead lbrynet-daemon starts anyways without any messages telling you that your config file isn't being used. On the other hand if the file (whether it exists or doesn't) does not end in `.yaml` then `lbrynet-daemon` does crash fast:

In the below examples the files `monkey` or `monkey.yml` don't exist.

No `.yml` fails:
```
[lbry]$ lbrynet-daemon --conf monkey
Traceback (most recent call last):
  File "/home/lex/.virtualenvs/lbry/bin/lbrynet-daemon", line 11, in <module>
    load_entry_point('lbrynet', 'console_scripts', 'lbrynet-daemon')()
  File "/home/lex/projects/lbry/lbrynet/daemon/DaemonControl.py", line 64, in start
    conf.settings.load_conf_file_settings()
  File "/home/lex/projects/lbry/lbrynet/conf.py", line 547, in load_conf_file_settings
    assert decoder is not False, 'Unknown settings format %s' % ext
AssertionError: Unknown settings format 
```

With `.yml` but still non-existent file works:
```
[lbry]$ lbrynet-daemon --conf monkey.yml
2018-07-13 11:10:33,184 INFO     lbrynet.daemon.DaemonControl:84: Starting lbrynet-daemon from command line
2018-07-13 11:10:39,249 INFO     lbrynet.daemon.DaemonServer:65: Using non-authenticated API
2018-07-13 11:10:39,251 INFO     lbrynet.daemon.DaemonServer:42: lbrynet API listening on TCP localhost:5279
2018-07-13 11:10:39,252 INFO     lbrynet.daemon.Daemon:208: Starting lbrynet-daemon
```

Expected behavior:
1. If it's easy, allow settings files with any extension (including no extension).
1. If you pass `--conf` to `lbrynet-daemon` and the settings file referenced doesn't exist, `lbrynet-daemon` should fail fast with useful error about file not being found.
1. Bonus: If user did something like: `lbrynet-daemon --conf ../../blahblah.yml` and this file doesn't exist (perhaps because they were wrong about their relative location to file) then in the error message expand the relative path to absolute path which will make it easier for the user to see their mistake (all paths can be expanded, no need to check if it's relative, there are Python built-in libs to expand paths to absolute).

**Comment by whatbatman** [comment]
Hello, I have a potential fix for this, but am having issues making a pull request. If you have a minute can you lend a hand?

**Comment by tzarebczan** [comment]
hey @whatbatman, thanks for taking a look at this! See https://gist.github.com/Chaser324/ce0505fbed06b947d962 on how to make a PR from a forked repo. Let us know if you have any questions.

**Comment by tzarebczan** [comment]
@whatbatman any updates? Looking forward to see a contribution from you :)

Let us know if we can help any further.

**Comment by eukreign** [comment]
PR related to this was merged.
