### ISSUE TITLE
Android Performance issue

### ISSUE THREAD

**Issue by alyssaoc** [lbryio/lbry#1304]
As a mobile app user, I would like the delay for the video player to be shorter. Currently, the delay is long enough to think that the system is hung or that the player is broken.

### Steps to reproduce
1. Jack is setting up a testing environment for Android
2. Android tests will be incorporated in the daemon testing
3. Jack will investigate and try to replicate performance issues

### Expected behavior
Videos should load and begin to play quickly on par with other user experiences

### Actual behaviour
Video does not play within 20 seconds and makes the user suspect that the player is broken

## System Configuration

build in android 8, minimum build 5

**Comment by alyssaoc** [comment]
@akinwale Is this still an issue or did the new daemon fix it?

**Comment by akinwale** [comment]
@alyssaoc Daemon 0.21 is performing a whole better than previous versions. One more thing I'd like to test is being able to disable DHT completely, so that downloads are done using only HTTP blob mirrors, but the daemon doesn't have the option to do that yet.
