### ISSUE TITLE
Add outpoint to claim information

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1306]
## The Issue
Currently, [outpoint](https://lbry.tech/glossary.html#outpoint) is an available field in [file info](https://lbryio.github.io/lbry/cli/#file_list). It should also be added to [claim information](https://lbryio.github.io/lbry/cli/#resolve) (including all API commands that include claim data). 

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by andrenogj** [comment]
Is anyone else assigned to this? Can I take it?

**Comment by tzarebczan** [comment]
@andrenogj I don't believe so, she's all yours! Let us know if you have any questions.

**Comment by daovist** [comment]
A claim's outpoint is just [txid]:[nout] or `${claim.txid}:${claim.nout}` in JavaScript so the necessary info is already there

**Comment by tzarebczan** [comment]
Yep, we know that, but others may not :)

**Comment by tzarebczan** [comment]
@andrenogj were you still planning to work on this? Looking forward to your contribution :)

**Comment by jessopb** [comment]
I'm happy to do this, and made a plan, but there's some debate as to whether it's necessary.
https://gist.github.com/jessopb/ebe6a6d1b401def755af756dd6061f75
