### ISSUE TITLE
Update failure rate metrics 

### ISSUE THREAD

**Issue by alyssaoc** [lbryio/lbry#1312]
Failure metrics on http://traction.lbry.io/dashboards are not representative and new metrics need to be identified
## The Issue

In order to achieve better insight into the performance of the daemon, 
as a LBRY team member, 
I want metrics that show failures per user, failures overall, unique failures and are representative of the user experience.

### Steps to reproduce
1. The failure metric can be moved by a single user who fails several hundred times.

**Comment by tzarebczan** [comment]
@shyba briefly looked into metabase/segment data and we do have the failure reason, so we can separate the data into true DHT related issues via other get failures (not being able to write file to disk/etc). The latter would most likely go into a separate card to track for support purposes.

**Comment by tzarebczan** [comment]
First take is completed on http://traction.lbry.io/question/114

This makes sure only to take into account DHT related failures and uses correct denominator for attempts (only those we knew failed/succeeded). 

Next step is to limit the impact a single user can have on the metrics.

**Comment by lyoshenka** [comment]
looks like Tom did work on this, so im reassigning to him. also @jackrobison owns metrics, so the two of you should work together on this. i'm happy to help with sql stuff or anything else.

**Comment by alyssaoc** [comment]
@lyoshenka Jack does need help with the sql. Tom and Jack have gone as far as they can without significant sql help from you. Apologies, I forgot to add that note in Github.

**Comment by lyoshenka** [comment]
What is needed from me? @tzarebczan please add details here or set a time to meet with me/jack
