### ISSUE TITLE
Account Deletion

### ISSUE THREAD

**Issue by MasterJames** [lbryio/lbry#1316]
The site does not have a clear way to delete a users account and all information.
This will be in violation of that new UK act for sure. It needs to be a BIG RED Button labelled "Delete".

Please explain how it is currently possible as well I can not find it anywhere?

**Comment by kauffj** [comment]
1) LBRY is United States based company and not subject to European law.
2) Fortunately we don't need a law to tell us to be respectful of your data - granting users more control and freedom is the premise of what we do.
3) I'm not sure what you mean by "account". If you mean an identity/channel created via the protocol, you can retract your claim, but there is no way to remove data that was written to the blockchain.
4) If you mean the email address you gave us to claim rewards, please email help@lbry.io from the address you provided explaining the issue and including a link to this ticket/comment.
