### ISSUE TITLE
Reflected content is incorrectly written to sqlite database

### ISSUE THREAD

**Issue by nikooo777** [lbryio/lbry#1320]
## The Issue

If I publish something, the daemon starts sending the blobs to reflector, it writes to the database that those streams are reflected without waiting for them to finish reflecting, 
In the case of an interruption or a daemon restart, the daemon believes that those blobs are reflected when in reality they're not.

### Steps to reproduce
1. Publish something
2. Immediately restart the daemon as the daemon is pushing the blobs to reflector
3. find the stream in the reflected_streams table
4. only some blobs were uploaded but the daemon will not push the others anymore

### Expected behaviour
The blobs are pushed to reflector and **then** the daemon writes to the database

### Actual behaviour
the database is written first

## System Configuration
```
{
  "id": null,
  "jsonrpc": "2.0",
  "result": {
    "build": "release",
    "desktop": "Unknown",
    "distro": {
      "codename": "Xenial Xerus",
      "id": "ubuntu",
      "like": "debian",
      "version": "16.04",
      "version_parts": {
        "build_number": "",
        "major": "16",
        "minor": "04"
      }
    },
    "ip": "34.239.118.206",
    "lbrynet_version": "0.20.4",
    "lbryschema_version": "0.0.16",
    "lbryum_version": "3.2.3",
    "os_release": "4.4.0-1061-aws",
    "os_system": "Linux",
    "platform": "Linux-4.4.0-1061-aws-x86_64-with-Ubuntu-16.04-xenial",
    "processor": "x86_64",
    "python_version": "2.7.12"
  }
}
```

**Comment by tzarebczan** [comment]
@nikooo777 per our discussion today, it should try to reflect them again at this interval, unless disabled: https://github.com/lbryio/lbry/blob/09f637496cc2e7cf7e73c47dbf3ffe994f87e1d2/lbrynet/conf.py#L292
