### ISSUE TITLE
Make console work in python 3 with asyncio

### ISSUE THREAD

**Issue by hackrush01** [lbryio/lbry#1329]
Related to #1317

**Comment by alyssaoc** [comment]
@hackrush01 if #1317 is closed, is this also done? or still open

**Comment by hackrush01** [comment]
This is still open, planning to do it soon

**Comment by hackrush01** [comment]
@alyssaoc This is still an issue, with Low Priority IMO.

**Comment by eukreign** [comment]
closing as really low priority, someone who really wants this will just implement it (scratching your own itch)
