### ISSUE TITLE
Ability to recover from database loss / corruption

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1335]
## The Issue
Currently, if your local sqlite database is corrupted or lost, the daemon loses visibility over your blob and file data. It would be nice to have some type of auto recover mode that the daemon would scan blobs and downloads folder in order to repopulate it's database. This would ensure that you can continue announcing blobs and that the file manager is aware of what's already been downloaded. 

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by lyoshenka** [comment]
will reopen when this gets closer to the top of the priority list

**Comment by tzarebczan** [comment]
Why close issues for the sake of closing them? This is a valid issue, even with the low priority. Just put in icebox instead...
