### ISSUE TITLE
DHT wire format: switch from integer keys to bytestring keys.

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry#1351]
The DHT is already compatible with both integer and bytestring keys. We should switch to using string keys when sending. Then after a few months, we can drop BC completely.

Before merging this, ensure that the Go version of the DHT will work correctly. I believe it will, but it needs to be tested. Also Go needs to switch to bytestrings as well (please file that when starting work on this).

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by alyssaoc** [comment]
closing, for @lyoshenka changes or redo it
