### ISSUE TITLE
Wallet locked/unlocked status missing

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1354]
## The Issue
Apps that use the new component startup process need to know if the wallet is in a locked or unlocked state. Previously, it was blocked on startup. Currently we only see `is_encrypted`.  We'd need another status to tell if the wallet needs to be unlocked in order to prompt the user for a password
## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by jackrobison** [comment]
fixed in 0.21.1
