### ISSUE TITLE
download_progress incorrect when resuming from s3

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1355]
## The Issue
Under blockchain_headers, download_progress is set to 100% when resuming headers from s3. See below for a screenshot while it was still downloading.  If you need an older blockchain headers file, please DM me. 

To test this, I limited my bandwidth during a resume and was able to capture this screenshot: 
![image](https://user-images.githubusercontent.com/8120721/43922938-3e125ed2-9bee-11e8-839f-548f66a2d95e.png)

Completion:
`2018-08-09 15:43:51,029 INFO     lbrynet.daemon.Components:218: fetched headers from s3 (s3 height: 417227), now verifying integrity after download.`

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by jackrobison** [comment]
fixed in 0.21.1
