### ISSUE TITLE
Test New Wallet Daemon w/ Desktop App

### ISSUE THREAD

**Issue by eukreign** [lbryio/lbry#1362]
Wallet Specific
- [ ] `transaction_list` returns empty result I'm sure I have some transactions (lex0
- [x] `wallet_send` raises `Daemon' object has no attribute 'jsonrpc_send_amount_to_address`
- [ ] `claim_list_mine` returns empty result (lex)
- [ ] `lbrynet wallet_is_address_mine "sdgasg"` returned true, it's not my address + it's not a valid address (lex)
- [x] `resolve` and `resolve_name` not working, potential fix: Adding `yield` [here](https://github.com/lbryio/lbry/blob/lbryum-refactor/lbrynet/wallet/manager.py#L154)
- [x] ^ also breaks `get`
- [x] `claim_show` returns `LbryWalletManager' object has no attribute 'get_claim_by_claim_id`
- [x] `channel_new` returns `builtins.TypeError: '<=' not supported between instances of 'str' and 'int'`
- [ ] `claim_new_support` returns `LbryWalletManager' object has no attribute 'support_claim'` (amit)
- [ ] `claim_list` returns `'LbryWalletManager' object has no attribute 'get_claims_for_name'` (lex)
- [x] `claim_list_by_channel` returns `{'message': 'Block not found', 'code': -5}`
- [ ] `transaction_show` returns `'LbryWalletManager' object has no attribute 'get_transaction'`(lex)
- [ ] `wallet_public_key` returns `'LbryWalletManager' object has no attribute 'get_pub_keys'` (lex)
- [ ] `wallet_send`(with claim_id) returns `'LbryWalletManager' object has no attribute 'tip_claim'`(amit)
- [X ] (updated) `wallet_prefill_addresses` returns `'LbryWalletManager' object has no attribute 'create_addresses_with_balance'` 
- [ ] `utxo_list` returns `'LbryWalletManager' object has no attribute 'list_unspent'` (lex)
- [x] `block_hash` returns `'LbryWalletManager' object has no attribute 'get_block'`
- [x] `publish` file is published but there is some traceback in the logs, see below comment for details
- [ ] wallet's unlock, encrypt, decrypt (jack)
- [ ] report_bug (dropping move to the app, Tom)
- [ ] channel_list(because I cannot claim a channel) (lex)
- [ ] channel_export/channel_import (lex)
- [ ] claim_abandon (amit)
- [ ] claim_renew (jack)
- [ ] claim_send_to_address (jack)

Blob/P2P/DHT
- [ ] `stream_cost_estimate` see the below comment for traceback (jack)
- [x] `blob_get` always fails to download the blob within timeout(network issue??) blob_hash used to test "d5169241150022f996fa7cd6a9a1c421937276a3275eb912790bd07ba7aec1fac5fd45431d226b8fb402691e79aeb24b"
- [x] `peer_list` didn't return any peers for the above block hash.
**Interestingly the above 2 problems were resolved after daemon restart**
- [x] `blob_list` returns `[]` empty list
- [ ] `blob_availability` fails to give proper results I think(details in the next comment) (jack)
- [ ] `stream_availability` errs(details below) (jack)
- [ ] file_reflect (victor)
- [ ] blob_reflect (victor)
- [ ] blob_reflect_all (victor)
- file list (victor) turn on full status

**Comment by hackrush01** [comment]
Commands not working(needed by app)
`transaction_list` returns empty result I'm sure I have some transactions
`wallet_send` raises `Daemon' object has no attribute 'jsonrpc_send_amount_to_address`
`claim_list_mine` returns empty result
`lbrynet wallet_is_address_mine "sdgasg"` returned true, it's not my address + it's not a valid address

**Comment by hackrush01** [comment]
This is a comment with more detailed errors:
---------
Error while running `get`
```
2018-08-17 10:07:06,919 WARNING  lbrynet.daemon.auth.server:312: error processing api request: {'message': 'Block not found', 'code': -5}
traceback:   File "/home/hackrush/git-repos/lbry-repos/py3-venv/lib/python3.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/hackrush/git-repos/lbry-repos/lbry/lbrynet/daemon/auth/server.py", line 93, in trap
    err.trap(*to_trap)
  File "/home/hackrush/git-repos/lbry-repos/py3-venv/lib/python3.7/site-packages/twisted/python/failure.py", line 439, in trap
    self.raiseException()
  File "/home/hackrush/git-repos/lbry-repos/py3-venv/lib/python3.7/site-packages/twisted/python/failure.py", line 467, in raiseException
    raise self.value.with_traceback(self.tb)
  File "/home/hackrush/git-repos/lbry-repos/lbry/lbrynet/daemon/auth/server.py", line 154, in _inner
    result = yield fn(*args, **kwargs)
  File "/home/hackrush/git-repos/lbry-repos/lbry/lbrynet/daemon/Daemon.py", line 1363, in jsonrpc_get
    resolved_result = yield self.wallet.resolve(uri)
  File "/home/hackrush/git-repos/lbry-repos/lbry/lbrynet/wallet/manager.py", line 154, in resolve
    results = yield ledger.resolve(page, page_size, *uris)
  File "/home/hackrush/git-repos/lbry-repos/lbry/lbrynet/wallet/ledger.py", line 59, in resolve
    resolutions = yield self.network.get_values_for_uris(self.headers.hash().decode(), *uris)
builtins.RuntimeError: {'message': 'Block not found', 'code': -5}
```
Calling it again worked
-----------

**Comment by shyba** [comment]
`blob_get` works. The issue with network/availability is unrelated to the command itself. Unless we want to add mirroring to `blob_get`, which I would say is another issue.

**Comment by shyba** [comment]
`blob_list` after getting `ethos` (20 blobs + some leftovers I had before):
```
(lbry3) ➜  lbry git:(master) ✗ lbrynet blob_list
[
  "39046886c5a5cf87ca44fa7e615f4597e4d36433341d16245e0225bc311788c276ac401b07ba97cb9993c0f7694cfaa1",
  "2acdb3ea242df91015f7cfea5cb734c1db8a84a0910192015a38cd8da47f131d390561a62419294d26a2cffe2b175a65",
  "d1cbadd2c69894dbf38ffbfb8e92c694d90431ff26d3e5b0b083e0acb6aaf95e6d9d5f3924507d1f46fa118538d63fd8",
  "f15be085f19bc7dabcaeb9dfd7d8b5b7c0c4bd2d991c09a9d18b37525b2501e9912d3337447f6fc9a8b98fa08496ea15",
  "8ab5b6cc0de7e9afd4fa6cc262996a42d843f0e2785cf365e3b6115334c95ea8289efd00aa05589a4ca7dfe325b394a5",
  "074964953e925ee9b404b9b829586cd4cf879c6d6f82b6f2ff4ca618882a8180a6f035a1e5112d2fe3deb374856b0a05",
  "c381f56cc86f92359d1ba6e984e097d36a14e4d9d5a9724e288f316e8a61323fbfb49eee15957d8420aa7104ef69c44e",
  "22a9e56c419c87db0b6a5a4d467d16a6b54214db15cea280b36efeb0cd7748160a87acf19217d60324c2d4e3850245ca",
  "80aa9614d9a8c6120c6bece325cfa48f6da7bf5f460295c96bccb1093d0b90d607d8a84d06384298b8c72a4c02ae107e",
  "d1fb8ba6f958e2eec8dd1137d62a923ef5e03d7af24ada2f2890248169a4975a58f65039305ba291891130e35c26f722",
  "6c3da82313bf444f47259789f9e2d6b5cee048eed9917ce8f10db4e96e1df0273b08526ef8c27a276e03c91754b1f35b",
  "bd6b502d40ab0a80e57456731244c1cae9330897e39ea3bfc37b4d9e22f7ef38e60043ace632d90c1c927bfb4fead68d",
  "ed18d3dd702d96464ee4a61b2565495aa40e824353f8469e7907752a5fbded10945dcd9245fcaee04ea8abc2f7b77c3b",
  "54ab3ab2b1169e9eb3fd4e7042d1fc0bd773febabcf5bcadc6b818550de1c23d475e344a22140ca16002da7a7f6e9964",
  "56e858858a5e9bdb9a2bf37b925c698d73638c32fb0e89b47d4801680dda615df81f040a5a4fa590f9d10a4db421c6b4",
  "18612b51a13fc66034efc2f6e6aa05104a8b65190d4de4d242c085e5ff437472579a1addd213be9e60e1cf2dc947d3af",
  "2f5b0fc0ae757f86350049dfa45b2d8992bccd11883f12a9d2159a9deed3cdd9d82c25957491b32026fada54f6deb963",
  "f7da29c0bc97ec595005e572f8dc86bb79b2b6dbd561a8500704faf063fea04bcebbdae98dc6e28d4bb0b7f2ccfb9087",
  "ba82d0802a1e646e0f47d278a9c9e976157f47898b64b4416bf1236bcdc899b90aa54c42e4080f777a09194ab9ae1830",
  "ebe7d0ef0806dc1bbf57f047dad6c98707e01bd1a4b2a993b9d5706ea036df67239db8c2a12ccb0e899fb79eb507f619",
  "c9a177c462e1c1919f1540c2e82bca40435774ba805bdbaccb1ad562107ad1957a78fdb6d272aae4a1495ed3a21bdd2a",
  "4f8beb9e27372ad4b406eb5679be95f09b72170cda72d0106cc77a50909daa9f4a7eb599a33aebd90328e832379a149b",
  "c0a95a90a72d6e72fb4423cf48a5ec1d7e4c02ad243451921b4c9669724e287fa1e8131c4b9d0c74cdafbb038c4eec5f"
]
```

**Comment by shyba** [comment]
`file_list` is giving me weird results on some fields:
```
  {
    "blobs_completed": null,
    "blobs_in_stream": null,
    "channel_claim_id": null,
    "channel_name": null,
    "claim_id": "1fc4daea63e9064e02cdf30085c48aa7ec05428a",
    "claim_name": "ethos",
    "completed": true,
    "download_directory": "/home/ful0n/Downloads",
    "download_path": "/home/ful0n/Downloads/ethos.mp4",
    "file_name": "ethos.mp4",
    "key": "acc07897e61c3b75e23374fd582ae8e6",
    "metadata": {
      "author": "PRO Mining",
      "description": "\u041c\u0410\u0419\u041d\u0418\u041d\u0413 ETHOS \u041a\u0410\u041a \u041f\u041e\u0412\u042b\u0421\u0418\u0422\u042c \u0425\u0415\u0428\u0420\u0415\u0419\u0422 \u0418 \u0423\u0412\u0415\u041b\u0418\u0427\u0418\u0422\u042c \u041f\u0420\u0418\u0411\u042b\u041b\u042c...https://youtu.be/vVRz4xcgwso\n\n\u0421\u0434\u0435\u043b\u0430\u0442\u044c Update Ethos: \"sudo ethos-update && sleep 5 && r\"\n\n\u0421\u0435\u043a\u0440\u0435\u0442\u043d\u044b\u0439 CRYPTO \u0447\u0430\u0442 PROMining: https://t.me/joinchat/DcA50UOSCdU4uq_vQDm6rQ\n\n\u041d\u0430\u0434\u0435\u0436\u043d\u044b\u0439 \u043e\u0431\u043b\u0430\u0447\u043d\u044b\u0439 \u043c\u0430\u0439\u043d\u0438\u043d\u0433 GS Mining: https://gsmining.com/invite/713388/\n\n\u0414\u043e\u0432\u0435\u0440\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u0435 \u0443\u043f\u0440\u0430\u0432\u043b\u0435\u043d\u0438\u0435 \u0438 \u043e\u0431\u0443\u0447\u0435\u043d\u0438\u0435: https://fct.academy/promo?ref=JY8A426r\n\n...\nhttps://www.youtube.com/watch?v=vVRz4xcgwso",
      "language": "en",
      "license": "Copyrighted (contact author)",
      "licenseUrl": "",
      "nsfw": false,
      "preview": "",
      "thumbnail": "https://berk.ninja/thumbnails/vVRz4xcgwso",
      "title": "\u041c\u0410\u0419\u041d\u0418\u041d\u0413 ETHOS \u041a\u0410\u041a \u041f\u041e\u0412\u042b\u0421\u0418\u0422\u042c \u0425\u0415\u0428\u0420\u0415\u0419\u0422 \u0418 \u0423\u0412\u0415\u041b\u0418\u0427\u0418\u0422\u042c \u041f\u0420\u0418\u0411\u042b\u041b\u042c",
      "version": "_0_1_0"
    },
    "mime_type": "video/mp4",
    "nout": 0,
    "outpoint": "d814a95f4537c20c20663ebdbc4fcf5d5ac896ce9783e7db48362f6eb55ba57c:0",
    "points_paid": 0.0,
    "sd_hash": "d1cbadd2c69894dbf38ffbfb8e92c694d90431ff26d3e5b0b083e0acb6aaf95e6d9d5f3924507d1f46fa118538d63fd8",
    "status": null,
    "stopped": true,
    "stream_hash": "21dde33b9892aa97a5b44de5fcd54fc4357bbedb1a428cf3441aafa12bff30e05fc3bc6516d7444302233b70a09dff78",
    "stream_name": "ethos.mp4",
    "suggested_file_name": "ethos.mp4",
    "total_bytes": null,
    "txid": "d814a95f4537c20c20663ebdbc4fcf5d5ac896ce9783e7db48362f6eb55ba57c",
    "written_bytes": 41051709
  }
```
I think fully checking this one will be harder since it has a lot of edge cases.

**Comment by shyba** [comment]
`claim_list_by_channel` also works. The above stack trace of `block not found` was caused by issues on the wallet servers.
