### ISSUE TITLE
daemon_settings.yml and data_dir configuration 

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1375]
## The Issue
If a user configures a data_dir setting in daemon_settings.yml, you end up with two daemon_settings.yml files - the one in the original location where the daemon looks by default and the one in the data_dir. The main location supersedes the data_dir one which might be confusing if other settings, like download_directory are configured in the main daemon_settings.yml because the daemon set_settings method will set them in the data_dir daemon_settings.yml. 

Not sure exactly what the solution to this is yet, but I know you can pass the config directory to the executable if you are calling the daemon separately, but not with the typical LBRY desktop app startup process. 

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by eukreign** [comment]
The new behavior is to respect the default `--config` unless explicitly overridden. Users can independently supply `--data-dir`, `--wallet-dir` and `--download-dir` in addition to `--config`.
