### ISSUE TITLE
wallet should not try to send txouts with an amount of 0

### ISSUE THREAD

**Issue by jimmykiselak** [lbryio/lbry#138]
https://github.com/lbryio/lbry/blob/master/lbrynet/core/LBRYWallet.py#L283

lbrycrdd will soon reject txouts with an amount less than 1. This block of code should only run if the amount is greater than 0 to avoid ever inadvertently creating an invalid txout.

**Comment by jackrobison** [comment]
https://github.com/lbryio/lbry/pull/142/files
