### ISSUE TITLE
revisit stream_availability command

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1387]
## The Issue
After checking out https://github.com/lbryio/lbry/issues/1150, noticed that the stream_availability command isn't returning the right results.  It should also probably take into account blob mirrors?

```
lbrynet-cli stream_availability one
{
  "did_decode": true,
  "did_resolve": true,
  "error": null,
  "head_blob_availability": {},
  "head_blob_hash": null,
  "is_available": false,
  "is_stream": true,
  "num_blobs_in_stream": null,
  "sd_blob_availability": {
    "is_available": false,
    "reachable_peers": [],
    "unreachable_peers": []
  },
  "sd_hash": "6a611e6f8ffb4920bf0679de6dee8bf9e56a473f43d8340233934eaf3b7e1211ee5a53c28e33693ca236c1408023d6cd",
  "upnp_redirect_is_set": 2,
  "use_upnp": true
}
```

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by eukreign** [comment]
The `stream_availability` has been removed.
