### ISSUE TITLE
Startup analytics missing since component refactor (0.21.x) release

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1420]
## The Issue
Looks like we lost startup analytics based on http://traction.lbry.io/question/19 when we refactored components. @shyba took a quick look and we are storing successes but not startups/failures. 

See: 
select * from segment.server_startup order by received_at desc limit 20;
select * from segment.server_startup_success order by received_at desc limit 20;
select * from segment.server_startup_error order by received_at desc limit 20;

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by shyba** [comment]
startup isnt being sent at all and I tried raising an error to check the event for errors and it failed badly instead. Analytics is started after the startup even is sent, so its not sent. Then something isnt so good with exception handling for the error case.
Try adding `log.hahaha()` here: https://github.com/lbryio/lbry/blob/v0.21.2/lbrynet/daemon/auth/server.py#L246
It fails and hangs.
But after this line it works: https://github.com/lbryio/lbry/blob/v0.21.2/lbrynet/daemon/auth/server.py#L224
