### ISSUE TITLE
Claim updates via publish require superfluous paramaters

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry#1423]
When performing a claim update via `publish`, only the parameters changing (plus a value to identify the claim), should be required.

Currently, `publish` requires many parameters even if they are not changing. This results in extra engineering effort at the application level.

As an example, spee.ch currently requests data from the daemon simply to pass it back to the daemon. This is rather absurd.

**Comment by daovist** [comment]
spee.ch could/should be storing this data when it saves a claim but it would be nice to avoid having to pass `source` data when updating existing claims, if possible

the code in question is still getting cleaned up but it gets used as follows:

`publishParams['sources'] = fullClaim.claim.value.stream.source;`

where `publishParams` is what will be sent in the request and `fullClaim` is the result of a `resolve` call to the daemon

**Comment by lyoshenka** [comment]
closing in favor of https://github.com/lbryio/lbry/issues/1823
