### ISSUE TITLE
Difference in price of the video and price to be paid

### ISSUE THREAD

**Issue by alyssaoc** [lbryio/lbry#1429]
@LavRadis commented on [Tue Nov 14 2017](https://github.com/lbryio/lbry-desktop/issues/742)

## The Issue
There is a different price on the video and when you want to download it and buy it. Not sure if it affects multiple videos, it probably does but I couldn't check due to my balance. It is probably some kind of a rounding issue. 

### Steps to reproduce
1. Open a video with price 0.58 LBC
2. When you try to pay for it, the price will be reported as 0.57

### Expected behaviour

Prices should be always the same.

### Actual behaviour
Prices are different.

## System Configuration

- LBRY Daemon version: 0.18.0
- LBRY App version: 0.18.0
- LBRY Installation ID: 7tYN144rHXrspzJG9xLP28fi1JztXnbpKro6DBJEQyzBmXTyDgqRLfYsUvHYFVmMe2
- Operating system: Win 10 

## Screenshots

![lbry price rounding difference](https://user-images.githubusercontent.com/10566738/32783633-b4699aac-c94c-11e7-897f-5f62bc3bfd08.jpg)

---

@LavRadis commented on [Tue Nov 14 2017](https://github.com/lbryio/lbry-desktop/issues/742#issuecomment-344287021)

After clearing the cache, both prices are 0.57. 

---

@liamcardenas commented on [Mon Dec 11 2017](https://github.com/lbryio/lbry-desktop/issues/742#issuecomment-350861176)

@tzarebczan do you think this is an issue with updating prices? i.e. if you make the price .58 but then lower it to .57 it doesn't update? has anyone had issues with that?

---

@kauffj commented on [Mon Dec 11 2017](https://github.com/lbryio/lbry-desktop/issues/742#issuecomment-350862995)

@liamcardenas I'm pretty much 100% sure I know the cause of this issue. The `cost_info` reducer caches costs separately from the `claims` reducer, and refreshing a claim _does not_ update the cost.

Both the claim and the cost info should be hard-refreshed at least when rendering a `<FilePage>`, and likely more frequently (consider a `<FilePage>` left open).

**Comment by tzarebczan** [comment]
I think this issue should be moved back to lbry-app. Even if the price between resolve/get calls is fixed, the issue on the app side is that the price loads once when the content page loads, and then again when the get call happens - this is either normal or the UX needs to be improved to show that the price updated  (due to exchange rates) during the time the claim was opened.

**Comment by tzarebczan** [comment]
Issue moved to [lbryio/lbry-desktop #1971](https://github.com/lbryio/lbry-desktop/issues/1971) via [**ZenHub**](https://www.zenhub.com/)

**Comment by kauffj** [comment]
There is no fix for this without a change to the daemon.

The app can fix it in the vast majority of cases, yes, but there needs to be a daemon change to fix it 100% of the time.

**Comment by tzarebczan** [comment]
@kauffj Isn't this issue already covered under https://github.com/lbryio/lbry/issues/1197 on the daemon side?

**Comment by alyssaoc** [comment]
yes, it is covered on #1197, closing
