### ISSUE TITLE
add unit tests for BlobAnnouncer

### ISSUE THREAD

**Issue by alyssaoc** [lbryio/lbry#1437]
@jackrobison commented on [Mon Jan 29 2018](https://github.com/lbryio/internal-issues/issues/106)
Add unit test for hash announcer concurrency
---

@kauffj commented on [Wed May 09 2018](https://github.com/lbryio/internal-issues/issues/106#issuecomment-387804911)

Can this be moved out of internal-issues?

---

@nikooo777 commented on [Wed May 09 2018](https://github.com/lbryio/internal-issues/issues/106#issuecomment-387858754)

can't move issues unfortunately. If I'm wrong please tell me how.

**Comment by eukreign** [comment]
@jackrobison does the new DHT have tests for hash announcement?
