### ISSUE TITLE
All commands which work with accounts should accept `--account=` argument.

### ISSUE THREAD

**Issue by eukreign** [lbryio/lbry#1441]
The web based lbry wallet will use lbrynet accounting / publishing commands by passing a different `--account=` to specify on which users behalf the command should be run; therefore all common commands which require blockchain interaction should accept a `--account=` argument.

- [ ] publish
- [ ] claim_list_mine
- [ ] ... add checkboxes for all of the other commands that need this update ...

**Comment by alyssaoc** [comment]
completed in #1456, closing
