### ISSUE TITLE
Add fees to claim trie transactions

### ISSUE THREAD

**Issue by alyssaoc** [lbryio/lbry#1442]
@kaykurokawa commented on [Wed Feb 28 2018](https://github.com/lbryio/lbryum/issues/232)

Fees should be added to claim trie transactions, the same way it is done in this lbrycrd PR: https://github.com/lbryio/lbrycrd/pull/95

---

@tzarebczan commented on [Sat Apr 21 2018](https://github.com/lbryio/lbryum/issues/232#issuecomment-383317020)

@kaykurokawa we can close this right?

---

@alyssaoc commented on [Wed Aug 22 2018](https://github.com/lbryio/lbryum/issues/232#issuecomment-415154864)

@kaykurokawa  Can we close this?

---

@kaykurokawa commented on [Mon Sep 17 2018](https://github.com/lbryio/lbryum/issues/232#issuecomment-422100056)

It does not look like torba fixes this, there will likely be problems with insufficient fees when publishing longer names

This can be moved to the lbry repo @alyssaoc

**Comment by alyssaoc** [comment]
..broadcast = false

**Comment by eukreign** [comment]
Fees are properly calculated taking into account the size of the output and the length of the name.
