### ISSUE TITLE
account name unclear, use default account with account commands?

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1454]
## The Issue
Didn't know I had to use the id here. Should it use the default if there is only one? Probably should be the same for other commands related to wallet also. 
C:\Users\thoma\Desktop\latestdaemomn\0.30daily>lbrynet account_max_address_gap
Usage:
            account_max_address_gap (<account_name> | --account=<account_name>)

C:\Users\thoma\Desktop\latestdaemomn\0.30daily>lbrynet account_max_address_gap --account default
"Extraneous parameters for account_max_address_gap command: account"

C:\Users\thoma\Desktop\latestdaemomn\0.30daily>lbrynet account_max_address_gap bRV4JchLF1Mp8eDdddD1neARVAWVtba3s1
{
  "max_change_gap": 6,
  "max_receiving_gap": 60
}

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by eukreign** [comment]
`--account=<account_name>` was renamed to `--account_id=<account_id>`.

Passing the account is required since this is an account specific query, it's also mostly for debugging and not intended for end users. I would like to drop this command after we release 0.30.0.
