### ISSUE TITLE
is_pending is not documented for claim_list_mine and seems to be returned inconsistently

### ISSUE THREAD

**Issue by 42degrees** [lbryio/lbry#1470]
## The Issue
On the claim_list_mine API, I am sometimes getting back a value called 'is_pending'.  I thought maybe this would be true when LBRY shows a new or edited upload as "pending..." but what I see from my program is that "claim_list_mine" doesn't return the pending item at all.  So, I either get "false" or null for is_pending.  The variable is missing from the documentation for "claim_list_mine" entirely as well as the old documentation in api.json.  Anyone know what this means and why I never see it as "true"?

Jiggytom reflected the following in dev, "yup, I'm seeing the same for is_pending, not sure exactly how it's used. Can you open an issue for this? I'll see if the devs think that claims waiting for confirmation should be in claim_list_mine, but I don't think so."

Note that if you edit an existing claim this happens as well (the edited item no longer appears in claim_list_mine until, I assume, it has fully committed to the blockchain).  So, a related question is, "What is the expected method for following a claim that is in the process of committing?"  LBRY shows the item as "Pending" in the Publishes list when it's in this state.  I haven't looked into how it is determining what is pending, but my assumption was that I would get the item back with is_pending set to true.

### Steps to reproduce
1. Run claim_list_mine in a loop.
2. Create a new item, or edit an existing item.
3. Watch the results from claim_list_mine to see that the new item doesn't appear until it has fully committed.  Watch the results to see that the edited item no longer appears in claim_list_mine and then reappears when it has committed.

### Expected behaviour
I expected is_pending to be set to true while the item was committing.

### Actual behaviour
The item no longer appears in the list.  When it does appear I have seen values of null for is_committed and "false".

## System Configuration
- LBRY Daemon version: 0.21.2
- LBRY App version: 0.25.1
- LBRY Installation ID: 8jTfoiRnN7Gux5LUhcAb5Twq3cU4XVhnoF4Y6nr6mVVjP6piiRwXBxt2stQc6xAKfE
- Operating system: Windows 10

**Comment by tzarebczan** [comment]
@42degrees thanks again for filing this issue. The pending claim status in the LBRY app is locally managed and waits until the claim is confirmed on the blockchain (and put into claim_list_mine) in order to update its status. If we were to show pending claims in claim_list_mine, this would need to be reworked to use the new status, but I'm not exactly sure how the protocol devs want to proceed here yet (cc: @jackrobison / @eukreign ). 

You referenced null/true values for is_commited - did you mean is_pending and false? Do you know the scenario in which this value is null? Does it change to false at any point?

**Comment by 42degrees** [comment]
> @42degrees thanks again for filing this issue. The pending claim status in the LBRY app is locally managed and waits until the claim is confirmed on the blockchain (and put into claim_list_mine) in order to update its status. If we were to show pending claims in claim_list_mine, this would need to be reworked to use the new status, but I'm not exactly sure how the protocol devs want to proceed here yet (cc: @jackrobison / @eukreign ).
> 
> You referenced null/true values for is_committed - did you mean is_pending and false? Do you know the scenario in which this value is null? Does it change to false at any point?

Sorry, in the main text I referred to false and null, but in the Actual Behavior I got it wrong.  I've updated it to be correct.  I either get "false" or null for is_pending.

Thanks for the catch.

**Comment by 42degrees** [comment]
Note that neither claim_list or claim_list_by_channel return is_pending at all.  claim_list_mine is the only API so far that returns it.  So, if is_pending is never true, then it seems that it could be removed from the results entirely.

**Comment by tzarebczan** [comment]
@42degrees in the latest version (0.30+), we've removed the is_pending status and are immediately adding published claims to claim_list_mine with a blockheight of -1 or 0 (based on if it made it to the blockchain mempool) which will then change to 1 one the transaction is confirmed. Closing this issue.
