### ISSUE TITLE
claim_sequence is returned inconsistently from different API calls

### ISSUE THREAD

**Issue by 42degrees** [lbryio/lbry#1471]
## The Issue
Some APIs return a claim with a claim_sequence and others don't.  The documentation just says "claim sequence number" which isn't very satisfying.  Why is it only returned sometimes and not other times?

Jiggytom replied in Discord, "claim sequence is the ordering in which the claim was created at a particular name, see https://lbry.tech/resources/uri. It should be included in all claim related calls - can you open a issue for this too? (please keep each issue separate)."

Given this, it is definitely not returned in every claim, specifically "claim_list_mine" does not include this value.  If I'm understanding this reponse the number is only useful relative to other claims with the same name value, so maybe returning it from claim_list_mine isn't terribly useful, but in my opinion it would be better to return consistent claim definitions from the API rather than picking and choosing which values to return (unless returning a value requires significant extra processing, then it should be documented why it is inconsistently returned).

## Unresolved questions
1. Can anyone expand further on what a claim sequence number is and when I should use it?  

### Expected behaviour
Claims returned from different APIs should return the same set of properties.

### Actual behaviour
Different API calls return different definitions of Claim.

**Comment by tzarebczan** [comment]
Thanks for opening this! Regarding your question, claim sequence is a way to tell which order a claim was created at a particular name, and a way to reference said claim. So if you were the first one to claim lbry://one, you could always reference your claim as lbry://one:1

**Comment by kauffj** [comment]
@tzarebczan *coughs* https://lbry.tech/glossary#claim_sequence 

(and yes, we should be returning this in every claim data)

**Comment by tzarebczan** [comment]
https://lbry.tech/glossary#claim-sequence :)

**Comment by 42degrees** [comment]
> https://lbry.tech/glossary#claim-sequence :)

I tried accessing that page and I got a warning from BitDefender:

Bitdefender blocked this page
A phishing attempt has been detected on this page.

I forced it to go to the URL and got this:
Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command heroku logs --tail

**Comment by 42degrees** [comment]
> Thanks for opening this! Regarding your question, claim sequence is a way to tell which order a claim was created at a particular name, and a way to reference said claim. So if you were the first one to claim lbry://one, you could always reference your claim as lbry://one:1

So, I actually tried that and :2 through :10 and it wasn't until I got to the current one, which is lbry://one:9 that I got any results.  Shouldn't I have seen something at those other sequence numbers?  So, I ran a claim_list on "one" and I got back 9 as the lowest sequence number, then it jumps to 12 and from there it is sequential.  

So, given all that, this is how I've documented it:
```
                            'claim_sequence': (int) 1-based claim sequence number defining the
                                              order in which the claims were submitted.
                                              The sequence may not be sequential (there may
                                              be gaps, and it may not start with 1, but
                                              will never be lower than 1).
```

**Comment by 42degrees** [comment]
> Thanks for opening this! Regarding your question, claim sequence is a way to tell which order a claim was created at a particular name, and a way to reference said claim. So if you were the first one to claim lbry://one, you could always reference your claim as lbry://one:1

Am I mistaken in that there doesn't appear to be a way to reference claim sequence numbers in spee.ch?

**Comment by tzarebczan** [comment]
Correct, spee.ch doesn't accept a claim sequence right now as it maintains other short urls using the : modifier. 

The lbry.tech site should wok now, it was down yesterday. 

Having gaps is normal if claims are abandoned, so your write up is correct.

**Comment by alyssaoc** [comment]
closing, resolved
