### ISSUE TITLE
`effective_amount` should not be 0 during claim takeover

### ISSUE THREAD

**Issue by seanyesmunt** [lbryio/lbry#1476]
## The Issue
If I have a claim that was overtaken, I might want to edit it and up my bid amount to try and take control. If I publish something, then decide I want to try and outbid someone (or realized I forgot to do it when publishing initially), I can't compare my `effective_amount` to a winning claim's `effective_amount` because mine will be `0`.

### Steps to reproduce
1. Make a publish to `lbry://one`
2. Resolve the claim
3. Notice that `effective_amount` is `0`

### Expected behaviour
`effective_amount` should always be the actual effective amount

Needed for https://github.com/lbryio/lbry-desktop/pull/1940

**Comment by tzarebczan** [comment]
Related discussions: https://github.com/lbryio/lbryum/issues/158 / https://github.com/lbryio/lbrycrd/issues/203 - which means this probably goes all the way back to the blockchain layer. 

@seanyesmunt - as a workaround, if the user's claim is returning 0, it means there is another claim (found by resolving the vanity URL) with a higher bid and correct effective amount - this is the bid they would need to beat. In the meantime, we could show their claim bid, not the effective amount, as the current bid (this would work in most situations, besides those that have supports).

**Comment by alyssaoc** [comment]
closing, reopen if still valid
