### ISSUE TITLE
documentation/responses related to values should be more specific

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1489]
## The Issue
With the recent changes to input/output amounts in the daemon (), both daemon responses for incorrect inputs and documentation should be clear about the expected input type - a string representation of a decimal number. 

Correct: `"1.0"`, `"2.34500"`, `"4534.4"`, `"2323434.0000"`
Not Correct: `1`, `123.32`, `"123"`, `"123."`, `"1.234232345234523454"`

Current message if passing 1 as a string `"1"` or just as a number `1`:  `"message": "Invalid value for 'bid' argument: 1"`

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by eukreign** [comment]
better error message added in #1508
