### ISSUE TITLE
send, tip and support commands should take LBRY URLs

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry#1494]
Any command that sends credits, tips publishers, or supports claims should take a parameter that allows passing a LBRY URL.

See https://github.com/lbryio/lbry.tech/issues/158 for some context, but there's plenty of other application contexts where it'd make sense to support this.

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
Does this also include vanity URLS? Or it has to include claim id? The vanity URL option might be interesting...you can set up a time locked payment to a vanity URL, announce it publicly and let the bidders go at it.

**Comment by walidmujahid** [comment]
Is someone working on this issue or is it available for anyone to take?

**Comment by walidmujahid** [comment]
Is anyone working on this issue or is it open for anyone to grab right now?

**Comment by eukreign** [comment]
@walidmujahid PRs always welcome.

**Comment by tzarebczan** [comment]
Tag, you're it! Thanks for stopping by on Discord! 

Our codebase recently went though a python 2.7 > 3 upgrade as well as a new wallet, so the readme may be out of date (should be updated soon!). 

You'll most likely be looking at adding options to the [wallet send](https://lbryio.github.io/lbry/cli/#wallet_send) and [claim_new_support)(https://lbryio.github.io/lbry/#claim_new_support) commands.

**Comment by walidmujahid** [comment]
Understood @tzarebczan and thank you.

**Comment by kauffj** [comment]
IMO it should accept any valid LBRY URL.
