### ISSUE TITLE
Improve DHT contact_is_good metrics to tolerate packet loss

### ISSUE THREAD

**Issue by shyba** [lbryio/lbry#1498]
## The Issue

In order to use the DHT, 
as a bad internet connection user, 
I want "contact_is_good" to tolerate a good level of packet loss.

Research maximum packet loss on a still usable connection and check how could we adapt "contact_is_good" to tolerate that but still accounting for offline nodes

**Comment by lyoshenka** [comment]
@shyba is this still something we want? i'm not 100% sure i understand what you're asking for

**Comment by shyba** [comment]
@lyoshenka it came from a discussion with @jackrobison but we implemented retry instead and the whole DHT is refactored, so we can close and reopen later if it becomes a good idea again. I remember adjusting timeouts and doing retry was enough.
