### ISSUE TITLE
Content not viewable on Mac with v0.4.2 

### ISSUE THREAD

**Issue by dnpotter** [lbryio/lbry#150]
Mac OS X 15.6.0

0.4.2 installs and runs ok but no content will stream or download.  Tried lbry://what and a number of other videos and images.  Have 100 credits available.  Tried rebooting but problem persists.

**Comment by jobevers** [comment]
@dnpotter sorry for the late response - we've made a bunch of changes in the past month and are  currently up to v0.6.3.  Do you have the same issues on the new version?
