### ISSUE TITLE
Rebootstrap when routing table goes empty

### ISSUE THREAD

**Issue by shyba** [lbryio/lbry#1500]
## The Issue

In order to keep connected, 
as a user who just got an internet outage, 
I want DHT to recover.

### Steps to reproduce
1. Start daemon, wait for it to join DHT
2. Disable internet, wait some time, enable internet
3. Try to announce or download (without mirroring)

### Expected behaviour
DHT complains to nodes amount and re-join

### Actual behaviour
DHT complains to nodes amount but does nothing to recover

**Comment by tzarebczan** [comment]
Same as https://github.com/lbryio/lbry/issues/1277 ?

**Comment by shyba** [comment]
yes, closing as dupe
