### ISSUE TITLE
Convert all input/output amounts to decimal strings

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1504]
## The Issue
Building on top of https://github.com/lbryio/lbry/pull/1436 - continue fixing amounts everywhere they are used in the wallet/sdk to be uniform decimal strings. @eukreign is aware of this issue. 

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by tzarebczan** [comment]
Does https://github.com/lbryio/lbry/pull/1508 take care of all the required work for this ticket?

**Comment by tzarebczan** [comment]
@eukreign, still seeing issues on wallet_send:
`{"jsonrpc":"2.0","method":"wallet_send","params":{"claim_id":"7d3ae777a9afc0430e33d66c4932c40f41784269","amount":"0.1"},"id":1539122815431}`

```
      "builtins.ValueError: Invalid value for 'amount': ",
      "Decimal inputs require a value in the ones place and in the tenths place",
      "separated by a period. The value provided, '10000000', is not of the correct",
      "format.",
```

**Comment by tzarebczan** [comment]
@eukreign - the bid shows as dewies in the publish logs too :
`2018-10-10 11:46:47,907 INFO     lbrynet.daemon.Daemon:2329: Publish: {'name': 'test22', 'file_path': 'C:\\Users\\thoma\\Desktop\\31bee797cf27cd6b958094ce07121ab8e45746cc8de97124d4684b5696104b28.jpg', 'bid': 10000000, 'claim_address': None, 'change_address': None, 'claim_dict': {'version': '_0_0_1', 'claimType': 'streamType', 'stream': {'metadata': {'title': 'test2', 'nsfw': False, 'license': 'None', 'licenseUrl': '', 'language': 'en', 'thumbnail': '', 'version': '_0_1_0'}, 'version': '_0_0_1'}}, 'channel_id': '', 'channel_name': None}`

**Comment by tzarebczan** [comment]
Key fee payments also show incorrectly:
`2018-10-11 17:24:44,424 INFO     lbrynet.daemon.Downloader:137: Pay key fee 400000000.000000 --> bXJ3x47ZfUkHXouAyruo9Vgape65wSqoQZ`

**Comment by eukreign** [comment]
All of the mentioned issues above have been resolved.
