### ISSUE TITLE
Normalization hard fork testing

### ISSUE THREAD

**Issue by alyssaoc** [lbryio/lbry#1511]
## The Issue

With the blockchain upstream and normalization changes in the upcoming hard fork, 
as an sdk developer, 
I want to identify as many automated and manual tests as possible so that the hard fork does not break the sdk.

## DOD/Acceptance Criteria
Identify all interactions with the blockchain and document
Identify and document possible testing scenarios for those interactions

As a goal, we should build a test environment for repeatable testing of future changes

**Comment by eukreign** [comment]
normalization hard fork has come and gone
