### ISSUE TITLE
set gap on wallet after migration

### ISSUE THREAD

**Issue by eukreign** [lbryio/lbry#1519]
After wallet is migrated from pre-torba to torba format and we generate the same number of addresses to match the old number of addresses, we need to run `account.get_max_gap()` and update the users gap setting in their wallet to those values so that if they blow away their `blockchain.db` and we have to recreated in the future we can do it correctly. Without setting the correct gap and not having the old wallet available anymore (after migration) the gap setting is the only way we can reliably recreate the wallet with the same number of addresses.

Specifically the algorithm should be to use `account.get_max_gap()` values (add 1 to the gaps returned by `get_max_gap()`) if they are larger than the default gap values, otherwise if the max_gap is less than the default values, then keep the default values.

Continuation of https://github.com/lbryio/lbry/issues/1459

**Comment by eukreign** [comment]
Specifically the algorithm should be to use `account.get_max_gap()` values if they are larger than the default gap values, otherwise if the max_gap is less than the default values, then keep the default values.

**Comment by tzarebczan** [comment]
@shyba we didn't think of this case, definitely want to get this in before release.
