### ISSUE TITLE
Cannot access channels from non-default account when publishing

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1532]
## The Issue
Noticed this issue on spee.ch which has multiple accounts due to how the wallets were consolidated. Publishing fails when you try to sign with a channel that's in the non-default account (i.e. the @lbry one). 

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by eukreign** [comment]
done in https://github.com/lbryio/lbry/pull/1547
