### ISSUE TITLE
claim_list_mine never shows claim as confirmed if you stopped the daemon before confirming

### ISSUE THREAD

**Issue by seanyesmunt** [lbryio/lbry#1555]
## The Issue
If I publish something, it is returned in `claim_list_mine` with the key/value pair `confirmations: 0`. I can continue to call `claim_list_mine` and check if `confirmations` has increased to see if a publish is no longer pending.

If I stop the daemon before a claim is confirmed, then start it up again, the claim returned from `claim_list_mine` always has `confirmations: 0`. I can resolve the claim to see that it is actually confirmed, but the value is never updated when I call `claim_list_mine`.

### Steps to reproduce
1. Publish something
2. Stop the daemon before it's confirmed
3. Start the daemon and continue to call `claim_list_mine`. Notice that `confirmations` never increases.

### Expected behaviour
`confirmations` should accurately show the number of confirmations

### Actual behaviour
It is stuck at 0 indefinitely

## System Configuration
- LBRY Daemon version: 0.30.0
- Operating system: MacOS

**Comment by eukreign** [comment]
This was due to a wallet sync bug and has been resolved. Please try the latest daemon build.
