### ISSUE TITLE
fail graceful and resume wallet sync

### ISSUE THREAD

**Issue by shyba** [lbryio/lbry#1566]
This is a follow-up to #1531 
## The Issue

In order to have a synced wallet, 
as a user with unexpected claim errors or connection issues, 
I want the wallet to keep syncing whats left, handling the error.

### Steps to reproduce
1. claim "hello" in ascii or keep changing networks
2. sync the wallet

### Expected behaviour
It syncs.
The goal is to have a working usable wallet even after some failures.
Handling is ideal for cases we know about, but we should still skip/retry/log for ones that failed.

### Actual behaviour
Sync fails and the remaining (valid) history isnt synced.

## Anything Else
Cases we know about already (grow this list as more are discovered):
- connection lost (server switch during sync)
- invalid payload (DecodeError)

Cases I expect to happen but we dont know exactly how:
- claim with None in some attribute we didn't expect None
- malformed claims, like invalid updates

Cases to check what happens:
- orphan signed claims
- semi-valid claims (invalid names or some field missing or not in the expected format)

### Acceptance Criteria
1. Classic sync works even though claim parsing sync failed (you have your full balance and history, but some claims cant be listed, for instance)
2. Networking changes causes a resume in sync (maybe move to torba)
3. Exceptions during sync, if any, doesnt break the wallet component. (it's usable even though sync failed)

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
Closing in favor of https://github.com/lbryio/lbry/issues/1722
