### ISSUE TITLE
transaction_list discrepancies

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1569]
## The Issue
Running through some more thorough testing with transaction_list:

- [x] Incoming tip is shown as a support (need to check against known addresses?)
- [x] Outgoing classic support is shown with a positive value (i.e. +1 LBC instead of -1)
- [x] Outgoing tip is shown as a spend, doesn't have tip metadata (broken after using the new tip api call)
- [x] amount incorrect on smaller transactions (see below)
- [x] balance delta incorrect for claim updates when bid changes (See below for example)
- [x] abandon tx shows a negative amount, should be positive if funds are returned to the wallet
- [x] send transaction amount includes fee, it should not as we report it separately. 

amount issue on smaller tx:
https://explorer.lbry.io/tx/6f508acd15cd03fecb8a9ea872d6832bbec4b84b219ae41b9883b5701a2f9eb2
sent: 0.0000336 , fee: 0.0001576

```
  "abandon_info": [],
    "claim_info": [],
    "confirmations": 2,
    "date": "2018-11-08 13:29",
    "fee": "0.000124",
    "support_info": [],
    "timestamp": 1541701752,
    "txid": "6f508acd15cd03fecb8a9ea872d6832bbec4b84b219ae41b9883b5701a2f9eb2",
    "update_info": [],
    "value": "-0.0001576"
```

balance delta on claim update (https://explorer.lbry.io/tx/4317e4670f311a2f1de4d77845e3a86913134a7e4cee995a4db92da9eee26cb9)- it should show +16.9999 (or whatever the fee difference is) as the new claim bid was 0.0001 and original was 17.0001  
```    {
      "abandon_info": [],
      "claim_info": [],
      "confirmations": 390,
      "date": "2018-10-31 20:31",
      "fee": "0.0002345",
      "support_info": [],
      "timestamp": 1541032282,
      "txid": "4317e4670f311a2f1de4d77845e3a86913134a7e4cee995a4db92da9eee26cb9",
      "update_info": [
        {
          "address": "ba8dLGCYuPTM41zZi6FVezA9zkNThJM41J",
          "amount": "0.0001",
          "balance_delta": "-0.0001",
          "claim_id": "f9664d1c78a1011dd057bb9f11552527cde1f7fd",
          "claim_name": "spee-thumb-test",
          "nout": 0
        }
      ],
      "value": "-0.0002345"
    },
```

**Comment by eukreign** [comment]
done
