### ISSUE TITLE
Support unicode URIs

### ISSUE THREAD

**Issue by shyba** [lbryio/lbry#1591]
Currently, our schema rules for URIs limits names as `"[a-zA-Z0-9\-]" `
(https://github.com/lbryio/lbryschema/blob/master/lbryschema/uri.py#L131)

After [normalization](https://github.com/lbryio/lbrycrd/pull/159) gets deployed, we should reflect support for it here as well. Examples: `lbry://图书馆` or `lbry://☺`.

**Comment by BrannonKing** [comment]
The string normalization stuff will be ready for testing at higher levels by the end of this week. This kind of thing needs to go away: `name.encode('ISO-8859-1')`. It should be UTF8 on all calls.

This line will not work unless the uri has been updated to the original name, not the normalized name: https://github.com/lbryio/lbry/blob/8ba3575901bb8a8d8f58533e34c4ee4e53a7e1a1/lbrynet/extras/wallet/server/session.py#L316 
I don't understand this codebase well enough to know how to ensure that the URI reflects the original name, not the normalized name.

This line is no longer necessary (and is wrong now). The name is now included. https://github.com/lbryio/lbry/blob/8ba3575901bb8a8d8f58533e34c4ee4e53a7e1a1/lbrynet/extras/wallet/server/session.py#L291

**Comment by lyoshenka** [comment]
Adding support for unicode URIs in the sdk is not urgent. It's ok to be more restrictive here than the blockchain (for now). 

The changes Brannon pointed out should be made, so I'm gonna move them to a separate issue.

**Comment by eukreign** [comment]
@BrannonKing did this in his normalization PR (@shyba also confirms this is done).
