### ISSUE TITLE
Update the claim signatures scheme

### ISSUE THREAD

**Issue by shyba** [lbryio/lbry#1592]
New scheme defined here: https://hackmd.io/s/S1TlVP6xX

Blocks #44 

Related #39

Steps:
- [ ] - Restructure code in a way that doesn't break current but allow for a different way of decoding, signing and checking signatures
- [ ] - Add flags, as described in the document
- [ ] - Separate the binary from the signature and add decode support for that, also supporting current schema
- [ ] - Add tests and do the same for the signing and serializing methods

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by lyoshenka** [comment]
@nikooo777 @skhameneh this is the issue to watch for claim signature updates that are blocking adding fields to the metadata

**Comment by alyssaoc** [comment]
Jack is the buddy

**Comment by eukreign** [comment]
@shyba finished and pushed this
