### ISSUE TITLE
Include the source in the hash used for generating signatures

### ISSUE THREAD

**Issue by jackrobison** [lbryio/lbry#1594]
We'd also add a `certificateId` field to the stream descriptor format (this would go along with bringing it into lbryschema)

Currently the hash of the concatenated claim address, serialized value without a signature, and certificate claim id is what gets signed. If the `Source.source` is included in this hash and the `certificateId` is added to the lbry stream descriptor format, it will be possible to verify that a stream downloaded from a claim was created by the same person who made the claim.

The inclusion of the claim address in the hash prevents claims with cloned values from having valid signatures (which means in order to spam claims in a channel the spammer has to spend them to the control of the signer). Analogously, including the `source` would prove that a downloaded stream was also made by the signer of the claim it was downloaded from. This would raise the bar for duplicating streams to having to download and re-generate them.

**Comment by lyoshenka** [comment]
we haven't touched this in a year. i'm gonna close it. reopen if its still relevant.
