### ISSUE TITLE
Support conversion of imported certificates with torba

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1610]
## The Issue
If you import a channel certificate in a pre 0.30 daemon and then run 0.30+, the channel will fail to convert into the new wallet. This is because the migration process cannot find an address in the local wallet in order to create a single channel account. In this case, the migration should determine this address by querying the lbryum server to get the information required. 

`2018-11-06 14:52:40,229 WARNING  lbrynet.extras.wallet.account:85: Failed to migrate claim '0e918739eb10338517c072424aacbee908c33091', it's not associated with any of your addresses.`

Sample:
@MyLBRYChannel - 0e918739eb10338517c072424aacbee908c33091 
https://explorer.lbry.io/tx/d4984c62edb349a9a10802e17cbeee8526cc85397b17b2a8af2b65aca08a78c5

```lbrynet-cli channel_import 0e918739eb10338517c072424aacbee908c330912d2d2d2d2d424547494e2045432050524956415445204b45592d2d2d2d2d0a4d48514341514545494a592f774241354f7666783041547566574a7078486b6a5853796c534257734a664d596462504b6e7163756f416347425375424241414b0a6f55514451674145626a613351336b6968785a65422b307648474e63506c457242616155625862776330694765736934765a552f4e4b6d62554631364f446c5a0a5545364d444954696f452b797a4b3459703675466a5547485465384d47513d3d0a2d2d2d2d2d454e442045432050524956415445204b45592d2d2d2d2d0a```

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
@eukreign if we don't get this in for the next release, is there a manual method to copy the certificate over from old wallet to new?

**Comment by alyssaoc** [comment]
closing, conversion has passed, import/export might be a separate issue
