### ISSUE TITLE
Include claim confirmation time on all claim related metadata

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1622]
## The Issue
While building a relative timing solution for claims (i.e. this claim was posted 3 hours ago), we had to originally call block_show for each block height from the claim since timestamp information is not available along with claim data. We have a more performant workaround that uses estimates based on the current block height and height of the claim block, but the long-term solution would be to use a timestamp that's available in claim data. 

This should be included anywhere we list claim data. 

Format: unix timestamp

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by eukreign** [comment]
done in #2062
