### ISSUE TITLE
Check asyncio usages and make sure they work

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1626]
## The Issue
@jackrobison recently ran into scenarios where parts of the code weren't converted to asyncio or it wasn't working after the conversion. 

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by eukreign** [comment]
outdated
