### ISSUE TITLE
Syncing wallets across 2 daemons

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1629]
## The Issue
Ran through some testing running 2 daemons with the same wallet (with a gap and wallet reuse of 1). We should be able to keep 2 wallets in sync as transactions occur in both, even when new addresses are generated.  

Findings:

1) The daemon does not subscribe to an address that's created after all addresses within the current gap/max reuse parameters is created. I was able to publish something to an address outside of known address list and the daemon did not recognize the transaction.

2) After running into the above scenario one wallet #1, the address list increased. Daemon 2's address list was not adjusted properly and thus it did not subscribe to any of the new addresses. 

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by eukreign** [comment]
fixed in https://github.com/lbryio/torba/pull/39
