### ISSUE TITLE
Media Server and Range Requests

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry#1634]
(epic for media server)
SDK will be adding a media server, provided by the same HTTP server that already provides JSON-RPC endpoints
https://github.com/lbryio/lbry/issues/1634 will be used as epic for app and sdk changes related to this
Victor will own this for SDK team, Shawn K will create app-side issues for epic
First version of media server functionality will focus only on basics
Focus on getting interface correct
Only for files on disk, no dynamic blob requests
Media server should be only be a useful interface, it should not be making fundamentally different calls to the broader network or interacting with the network in a way that is not possible via the API
Some of Victor's desired improvements (not saving blobs, direct requests to blob servers), should be filed separately and are most likely changes to blob_get or other data network functionality

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by shyba** [comment]
## Streaming API
Endpoint: /stream/<sd_hash>

Structure:
```
GET /stream/<sd_hash> HTTP/1.1
Range: bytes=1234-5678
```

Expected reply:
1. Stream descriptor hash is known and blobs in the segment are on disk:
```
HTTP/1.1 206 Partial Content
Content-Range: bytes 1234-5678/40000000
Content-Length: 4445
...
(binary content)
```

2. Blobs are missing:
Server will block the request until blobs in the requested range are available. Optionally telling all downloader subsystems to skip to the requested point (that's an implementation detail).

3. The given stream descriptor hash is unknown.
Server will reply with 404. Client needs to `resolve` and/or `get` the file before using `stream`. It's not possible to know if the hash is really unavailable or just unknown, so 404 "Not found" tells it clearly.

4. Range requested doesn't match the file size.
Server will reply with 416: Range not satisfiable

**Comment by alyssaoc** [comment]
@lbryio/protocools @lbryio/appsquad @lbryio/api Please review and provide any input on this issue. Victor thinks this can be implemented relatively quickly, feedback ASAP

**Comment by nikooo777** [comment]
Question on 2:
Wouldn't blocking also block any other calls to the daemon? Isn't it better to respond with a 202 or similar instead and let the app retry?

(funny thing is I googled for "http try again later" and got a very similar problem: https://stackoverflow.com/questions/9794696/how-do-i-choose-a-http-status-code-in-rest-api-for-not-ready-yet-try-again-lat )

**Comment by eukreign** [comment]
@nikooo777 Answer on 2: No, it will not block the daemon. Daemon can support thousands of simultaneous requests.

**Comment by tiger5226** [comment]
I guess I am curious about the details. Should we be using the daemon directly? We do have the reflector and blobs on S3 already. Would it be better to add an api to the [reflector.go](https://github.com/lbryio/reflector.go/blob/master/peer/server.go) app? I presume this is for LBRY on the web. We have a peer server built in, we can spin up multiple instances, it scales etc. The daemon is mainly used by one user at a time. The reflector has already proved to be robust at delivering content effectively. Plus we can load balance smoothly with it by spinning up many peer servers with the addition of the API.

**Comment by tiger5226** [comment]
oic. All clear.

**Comment by alyssaoc** [comment]
I will add the minutes thank you lec

**Comment by kauffj** [comment]
@skhameneh @akinwale please either comment on @shyba or :+1: his comment if the proposed design looks good to you.

https://github.com/lbryio/lbry/issues/1634#issuecomment-439200749

**Comment by jessopb** [comment]
Above comment suggests local files only, not remote blobs. Is this still true or are we dynamically accessing blobs in tihs epic?
