### ISSUE TITLE
[Feature] Add Web Support

### ISSUE THREAD

**Issue by gjhklfdsa** [lbryio/lbry#1665]
**Feature**: Add Web Support
**Why**? Roughly 99% of all free-content videos watched are via the web browser. Currently LBRY only supports native applications. My request is to change this and make a web-only client as well.

**Comment by tzarebczan** [comment]
Hi, thanks for reaching out! An initial version of this is in the works, but that's not for this particular github repository. 

Keep in touch on our [Chat](https://chat.lbry.io) or [mailing list](https://lbry.io/list/subscribe) to be notified when we have something ready for preview.

**Comment by gjhklfdsa** [comment]
@tzarebczan Thank you so much for replying!

> Hi, thanks for reaching out! An initial version of this is in the works, but that's not for this particular github repository.

Ahh, ok. But it will be an end goal for [Libry.io](https://lbry.io/) to create a free software web client?

**Comment by tzarebczan** [comment]
@gjhklfdsa sorry for the delay in getting back to you. What do you mean by "free software". All software released by LBRY is open source and free. To transact on the network does require LBC in many cases, especially for things like publishing and purchasing content. Free content will be accessible without any LBC.
