### ISSUE TITLE
Can daemon_settings.yml have a fully populated example in it?

### ISSUE THREAD

**Issue by Leopere** [lbryio/lbry#1675]
https://github.com/lbryio/lbry/blob/master/example_daemon_settings.yml

Even if the settings are commented out by default it would be great to have a fully populated base template available as an example.  There seems to be a lot more options documented on https://lbry.tech/resources/daemon-settings also the examples values should be universally unique and static within the document itself.

**Comment by jessopb** [comment]
I assume the call for them being universally unique is to facilitate scripting their replacement.
