### ISSUE TITLE
transaction list and balance sync intermittent issues

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1681]
## The Issue
Since the new sync code was introduced, I've run into a few scenarios where my balance would be wrong or transaction list showed incorrect information - which is not fixed until the wallet is re-sycned by deleting blockchain.db. The most common one seems to be when abandoning a claim, it shows it as a Recieve.  I have corrupted blockchain.db files saved in case it's worth looking into that way. 

Others examples: 
a send claim was miscategorized as abandon abd balance was incorrect (didn't count change)
prefill wallet addresses showed addition to balance, but it's just a re-shuffle.

Adding blocker tag for now, but we can downgrade to high if this is hard to reproduce/fix. If we do plan to release as is, it will be a pain to tell MOST people how to delete their blockchain.db to fix their sync issues. 

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by eukreign** [comment]
solved sync issues in torba
