### ISSUE TITLE
Bring back claim resolve caching

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1705]
## The Issue
Based on conversations with @shyba, claim caching is currently disabled. This should be re-enabled as it will improve the app experience because the app makes many repeat calls to homepage and claim_list_by_channel to subscribed content. 

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by eukreign** [comment]
We're going to make the APIs faster instead.
