### ISSUE TITLE
Claim update not able to use existing deposit sometimes

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1724]
## The Issue
We have a community member that is unable to update their claim, which has a deposit of 4000 LBC, as the update process is not able to use the existing claim balance. He's told that he needs to decrease the claim amount to 60 LBC, which is his balance. He's able to update the claim by lowering the bid amount, and then update again using the 4000 LBC. You can see the chain here:https://explorer.lbry.io/tx/e84ea3eab102d3e64e9928f2c97ba094885254d9a5732dc22b6aa61b6e291376#output-0

I am not able to reproduce locally in a similar scenario but haven't tried higher LBC amounts.  The lookup happens here:
https://github.com/lbryio/lbry/blob/master/lbrynet/extras/daemon/Daemon.py#L2232

I originally thought this might be related to the RC wallet sync bug, but we re-synced from scratch and he still ran into the problem. 

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
Had another user run into this as well.

**Comment by eukreign** [comment]
The new `stream update` command actually tries to create the TX and thus is much more reliably in determining fees and available balance. Please re-open if this issue is still occurring.
