### ISSUE TITLE
Broadcast does not return errors: transactions rejected from mempool do not error out

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1731]
## The Issue
As we saw with https://github.com/lbryio/lbry/issues/1646, this is also happening on publish and other transactions that may be rejected after hitting the mempool. @nikooo777 and I ran into this today while publishing. The publish would go through without any problems, but the resulting txid was non-existant. Thanks for @shyba , we got the logs from lbryumx: ```INFO:electrumx.server.session.LBRYElectrumX:[273956] sendrawtransaction: 18: bad-txns-inputs-spent```.  

I understand that we are currently just generating most transactions and returning immediately, without checking if it's accepted into the mempool. I think the default behavior should be to check the mempool, but allow a flag that bypasses the checks. This is more pronounced on claim related transactions - if a regular wallet send fails, it can be reprocessed. When a publish fails like this, the blobs are sent to reflector as if it were a valid one. 

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by alyssaoc** [comment]
related to blocking RPC calls

**Comment by tzarebczan** [comment]
A user just ran into this, similar case, but this time it failed due to tx side because of a long description. Worst thing is that it tells you it published and reflects the blobs.

**Comment by tzarebczan** [comment]
Another user ran into this, related to https://github.com/lbryio/lbry/issues/2085
