### ISSUE TITLE
transferring a signed claim should re-sign to new address

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1757]
## The Issue
Transferring a claim should update it with a new signature based on the target address. Today, you'd need to resign the claim at the new wallet in order to re-validate the signature. This api is only available via the daemon now, so not many do it, but we'll need it for YouTube sync. 

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by alyssaoc** [comment]
@tzarebczan and @eukreign is this possible?

**Comment by tzarebczan** [comment]
Should be, and its blocking youtube sync transfers (one of many issues). Not sure if the recent protobuf changes affect this.

**Comment by eukreign** [comment]
`lbrynet stream update <claim_id> --claim_address=<new claim address>` will sign and send the claim to the new address.
