### ISSUE TITLE
Handle missing blobs / failed to reflect scenario

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1768]
## The Issue
Reopening as a new issue based on discussion in https://github.com/lbryio/lbry/issues/377. This still happens if the blob is not available for some reason, and we try to re-reflect it on each startup/after the re-flect interval. 

Per @shyba, we need to better handle this scenario.

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by eukreign** [comment]
@jackrobison still an issue with the new async reflector / blob exchange?
