### ISSUE TITLE
TypeError(findNode() takes exactly 2 arguments (5 given))

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1770]
## The Issue
During time to first byte script run:
```2019-01-14 23:55:01,846 WARNING  lbrynet.dht.protocol.protocol:237: Received error from 199.115.205.245:4444, but it isn't in response to a pending request: exceptions.TypeError(findNode() takes exactly 2 arguments (5 given))```

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by jackrobison** [comment]
This is where you get a backwards-compatibility error response but after the request has already timed out

**Comment by tzarebczan** [comment]
Not seeing this anymore
