### ISSUE TITLE
Implement async reflector client protocol

### ISSUE THREAD

**Issue by jackrobison** [lbryio/lbry#1776]
The reflector server component has been dropped from the daemon in the async rewrite, however the client is still needed to upload blobs to a reflector server (those used in the live network are running https://github.com/lbryio/reflector.go).

What is needed is a `ReflectorClientProtocol(asyncio.Protocol)` class and a method like:

```
async def reflect_stream(descriptor: StreamDescriptor, blob_manager: BlobFileManager, reflector_url: str) -> typing.List[str]:  # returns a list of blob hashes uploaded to the server
    ....
```

To create a ``ReflectorClientProtocol``, connect it to the reflector url, attempt to transfer the blobs, disconnect, and return a result indicating what was sent. Once done this can be integrated into `Daemon` for use in the `file_reflect` command and internally for reflecting new publishes.

**Comment by binaryflesh** [comment]
I am writing this with the perspective that escalation of this issue may rise before I can get fully functional and general feedback. Please reach out if there is code considered stable enough to implement and can be reused. I am currently defining `Reflector` to consist of following three namespaces.

- reflector(factory, queue, handle)

- ReflectorProtocol(asyncio.Protocol)

- reflect_stream (in jack's comment above)

reflector is a wrapper around (at the moment), three things I *should* define before starting a thread.
I emphasize *should* given most uses cases (just Daemon at the moment), `reflector` is an event loop, and not a transaction-based client.

```
def reflector(factory, queue, handle)
    @functools.wraps(handle)
    def callback(ctx):
        # Comprehension of expected call (ahead-of-time)
        # split '_' in response to get list of context vars for task
        # __* should not be used inside ReflectorProtocol
        if __VER in args:
            # call V2
        if __ITER in args:
            # needing_blobs
        if __BLOB in args:
            if __HASH in args:
                if __SIZE in args:
                    # client sending blob details
                    super().blob = await _request(args)
                # asyncio.wait_for(super().data_received, timeout=1.0)
            # server sending ACK
            super().blob = await _request(args)
        # standalone components will just be what I am calling Reflector (capitalized)
        # Reflector is yet-another wrapper that will initialize reflector that will stand-up client or server.
        # e.g. Reflector(default=client, watcher=reflect_stream)
        # _REQUEST = {_BLOB: _INFO}
        # _RESPONSE = {_PREFIX: _BASE}
        # _HANDSHAKE = {_VER: REFLECTOR_V2}
        # TODO: abstract method to call ReflectorCookieCutter.send(sd_blob/blob)
        # TODO: abstract method to call ReflectorCookieCutter(sd/blob)
        # TODO: abstract method to call ReflectorCookieCutter.NeedsBlobHashes()
  
    @functools.wraps(queue)
    def set_task_factory(blobs: typing.List):
        ...
    
    @functools.wraps(factory)
    def build_factory(client: typing.Optional[typing.Protocol], server: typing.Optional[typing.Protocol]):
        ...
    return build_factory
```

Working on previously mentioned `ReflectorClientProtocol`, I found that I could kill two birds with one by having the Protocol not handle context. This also makes using reflector in other code less of a hassle.

```
class ReflectorProtocol(asyncio.Protocol):
    # acceptable args: version, *blob, *blob_ blobs
    async def connection_made(self, transport: asyncio.Transport):
        return transport
    
    async def data_received(self, data: bytes):
        msg = await _response(data.decode())
        if 'needed' in msg.keys():
            ...  # missing blobs
        if True in msg.values():
            ...  # send_next_blob
        if False in msg.values():
            ...  # reupload
        # send, received, needed
        ...
    async def connection_lost(self, exc: typing.Optional[Exception]):
        raise exc if exc else log.info('reflected future')
```
an aside regarding reflect_stream, I'd like to propose renaming the original `reupload.py` to `reflect`.
( when stable of course). This will let usage look like:

```
from lbrynet.extras.reflector.reflect import reflect_stream
reflected_blob_hashes = await reflect_stream(loop, descriptor, blob_manager)
```

**Comment by binaryflesh** [comment]
Also to note I'm currently working on a ReflectorClientProtocol to quickly get reflector into master without twisted.

**Comment by binaryflesh** [comment]
I was a little confused by how remote tcp was interacting with different layers at time of last comment. Once testing is complete 91120c6  or later will resolve issue.

**Comment by binaryflesh** [comment]
As of now, I currently have the `daemon` passing `blob_manager` and `blobs` to `reflector.py`. It occurred to me that `ReflectorClientProtocol` could just be a generator for what the transport should send the reflector server and allow `Daemon.py` to have all moving parts in the scenario. Given there's no need for a stand-alone reflector server, I can make `reflector` a little easier to maintain by just taking the `blobs` to reflect and have `Daemon` handle the response, given `Daemon` already has a `client` this would be a good reuse of code. Thoughts?

**Comment by jackrobison** [comment]
reflector uploads after publish is added in https://github.com/lbryio/lbry/pull/1810
