### ISSUE TITLE
LBRY Wallets not encrypted - !!!

### ISSUE THREAD

**Issue by ELM4Ever** [lbryio/lbry#179]
After doing some investigation, I figured out that the LBRY GUI uses LBRYUM to generate its initial wallet (lbryio/lbryum), which is a kind of a clone of Electrum.  In addition, LBRY maintains three Electrum-LBRY-servers (lbryum1.lbry.io, lbryum2.lbry.io, lbryum3.lbry.io) to provide quick responses to newcomers in the LBRY ecosphere - all is good there!   

Where it is not good, is to create those Electrum type wallets without any type of encryption (back to 2010 again....).  

If LBRY had no value and was on TESNET, no problems here... this is not the case in October 2016 - people are putting real money in this experience ($1.6M market cap today?)... let's act like professionals here and put some basic protection in place !

**Comment by tombrandi2** [comment]
We are still in beta, but as we are getting closer to a "stable" release i'll talk with the team to get this working aswell! Thanks for noticing!// Slack mod Fillerino

**Comment by ELM4Ever** [comment]
Thanks for the prompt response tombrandi2:

Depending on who is talking about LBRY, it is in Alpha for some, Beta for others.  Regardless, this is why I provided my comment on Github and Slack (and nowhere else).  

However, this is major... travel back to 2010 with loss of wallet founds... 

I wouldn't be so nervous if the LBRY team had addressed my other comment dating back to July 5th (issue #59), which is still not fixed !

**Comment by jobevers** [comment]
@ELM4Ever thanks for the feedback. This is a feature that needs to be added. Balancing security with a good user experience is always difficult so we'll need to look at how to surface encryption to the user.  Having to type in a password each time a user wants to publish or download content creates friction in the process and is probably not something many users want.

I'll let you know when work starts on this.

**Comment by kaykurokawa** [comment]
Work in progress on https://github.com/lbryio/lbry/pull/212

**Comment by chriswanaka** [comment]
Hi

**Comment by lyoshenka** [comment]
Conversation has moved to #708, closing this
