### ISSUE TITLE
Allow account add and encryption in same command

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1806]
## The Issue
In order to support cross-device syncing and proper lbry-web handling of wallets, we need to support the adding of encrypted accounts. This includes both creating a new account without any parameters and adding one with an encrypted seed/private key (would require password to be passed in both scenarios). 

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by alyssaoc** [comment]
closing for xdevice sync
