### ISSUE TITLE
estimated fees for content

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#181]
Currently, the estimated fees don't look like they take into account media size when potential downloaders attempt to access files on LBRY.  I recently uploaded something 1.5GB in size and charged 5LBC, but when a friend downloaded it, it ended up charging him ~12LBC because of the .005 LBC per MB fee.  The content creator, when uploading, should see what these fees will be before hand, so they can possibly adjust their initial price, and the downloader should also see what the content fee is, in addition to the bandwidth fees.

**Comment by jobevers** [comment]
Bandwidth fees will very soon be dynamic, allowing hosts to change their pricing.  The price for data should drop.

For reference 0.005 LBC / MB = $.40 / GB.  Amazon EC2 charges less then $.09 / GB (https://aws.amazon.com/ec2/pricing/on-demand/)

We will be working on improving our estimates and incorporating the current data prices.  Thanks for the feedback!
