### ISSUE TITLE
Optimal event loop/task timeouts

### ISSUE THREAD

**Issue by binaryflesh** [lbryio/lbry#1819]
## The Issue

In order to prepare for potential threading error during I/O, may we (should we rather), add functionality in analytics to keep track of average Component calls so when creating a task, it can time-out and can there be an event to let all other loops know the component may die during interaction.
as a end user very picky about security, 
I want the functionality above to make it easier to stress test and sandbox future features.

### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by lyoshenka** [comment]
Can you explain more what this is for?

**Comment by eukreign** [comment]
"should we rather), add functionality in analytics to keep track of average Component calls"?

No, I don't think this is necessary at this time.
