### ISSUE TITLE
Support intra-protocol thumbnail publishing

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry#1842]
It is silly that we encourage thumbnails to be published/accessed over HTTP when we have a protocol that is designed to distribute data.

Trivially, thumbnails could also be published as claims, but this is expensive and creates blockchain bloat. Ideally, there would be a solution that allows the `thumbnail` metadata property to support fetching from the LBRY data network without an additional claim.

One idea for a solution is that the `thumbnail` property can simply be a blob hash. When performing a `resolve` or `get`, if the SDK sees a `thumbnail` that contains a valid blob hash, it would automatically fetch them. It would also verify that the blob is a valid image type and return a signature that includes the path to the thumbnail on local disk.

We should consider it a requirement that the SDK does not require any additional application-level calls to fetch thumbnails. Whatever the actual solution, all thumbnail fetching should happen behind the scenes.

**Comment by alyssaoc** [comment]
@lyoshenka What are the next steps for this?

**Comment by lyoshenka** [comment]
This is low priority
