### ISSUE TITLE
Adapt code to handle proto3 and legacy proto2

### ISSUE THREAD

**Issue by shyba** [lbryio/lbry#1870]
Completion blocked by https://github.com/lbryio/types/pull/17, but most of the work can be done before that is finished.

- [x] Check and adapt how claim dict would deal with missing and extra fields
- [x] Proto3 serialization helpers
- [x] Proto3 encode/decode to/from dict
- [x] Make smart_decode work with proto3 + flags, leave default unflagged as proto2
- [x] Add unsigned flag
- [x] Change signing and verification of detached signatures aware of protobuf version from flag
- [x] Cleanup, refactor, update API parameters and doc

**Comment by eukreign** [comment]
released in 0.35.0
