### ISSUE TITLE
SSL fails sometimes on segment (non-debian OS / Mac)

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1918]
## The Issue
Saw this on Windows 7/Mac VMs and another user running ```Linux-4.19.20-1-MANJARO-x86_64-with-arch-Manjaro-Linux```. Don't see any errors from the exchange rate manager, and I'm able to download USD priced videos. This is not the case on Mac/other distros...the exchange rate manager fails so no paid content can be downloaded.

It seems to be fine on Win 10 / Ubuntu. 

```2019-02-15 08:54:40,169 ERROR    lbrynet.extras.daemon.analytics:87: Encountered an exception while POSTing to https://api.segment.io/v1/track: 
Traceback (most recent call last):
  File "site-packages/aiohttp/connector.py", line 924, in _wrap_create_connection
  File "asyncio/base_events.py", line 975, in create_connection
  File "asyncio/base_events.py", line 1003, in _create_connection_transport
  File "asyncio/sslproto.py", line 526, in data_received
  File "asyncio/sslproto.py", line 189, in feed_ssldata
  File "ssl.py", line 763, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1051)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "lbrynet/extras/daemon/analytics.py", line 84, in _post
  File "site-packages/aiohttp/client.py", line 1043, in __aenter__
  File "site-packages/aiohttp/client.py", line 476, in _request
  File "site-packages/aiohttp/connector.py", line 522, in connect
  File "site-packages/aiohttp/connector.py", line 854, in _create_connection
  File "site-packages/aiohttp/connector.py", line 992, in _create_direct_connection
  File "site-packages/aiohttp/connector.py", line 974, in _create_direct_connection
  File "site-packages/aiohttp/connector.py", line 927, in _wrap_create_connection
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host api.segment.io:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1051)')]
```

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
This also causes https://github.com/lbryio/lbry/issues/1917 when we try to get the IP: https://github.com/lbryio/lbry/blob/master/lbrynet/extras/daemon/Components.py#L58

**Comment by tzarebczan** [comment]
The Windows error went away after browsing a few websites (which downloaded ssl certs required). The Manjaro error (and other non-debian distros) is different because of how SSL certs are handled by our current binary. When building from source, it goes away. We can investigate and improve this down the road.

**Comment by jessopb** [comment]
Suffering from this since upgrading to .32.2

**Comment by jessopb** [comment]
This seems like a likely candidate for mac users. https://stackoverflow.com/questions/44649449/brew-installation-of-python-3-6-1-ssl-certificate-verify-failed-certificate

**Comment by JoshStrobl** [comment]
I'm getting this as well during my testing with lbry-desktop 0.29.1 (which uses lbry 0.32.3) on Solus (Linux). Attempted to update my local `python-aiohttp` to check if that was the issue and it was not.

This will be a blocker for deploying the latest lbry-desktop on Solus, since it prevents the use of the client entirely.

**Comment by tzarebczan** [comment]
Thanks for the feedback @JoshStrobl...if you want some light (haha jk) reading around the topic, check out https://github.com/kennethreitz/requests/issues/2966

**Comment by jackrobison** [comment]
fixed by https://github.com/lbryio/lbry/pull/1965
