### ISSUE TITLE
Cleanly handle upnp timeout

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1923]
## The Issue
This happens when a upnp device is not avialble:
``` Daemon: Task exception was never retrieved
  future: <Task finished coro=<Gateway._discover_gateway() done, defined at aioupnp/gateway.py:157> exception=UPnPError('M-SEARCH for 192.168.1.1:1900 timed out')>
  Traceback (most recent call last):
    File "aioupnp/gateway.py", line 169, in _discover_gateway
    File "aioupnp/protocols/ssdp.py", line 173, in fuzzy_m_search
    File "aioupnp/protocols/ssdp.py", line 166, in _fuzzy_m_search
  aioupnp.fault.UPnPError: M-SEARCH for 192.168.1.1:1900 timed out
```

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by alyssaoc** [comment]
closing, has been fixed
