### ISSUE TITLE
Social Learning & Official/Unofficial Fan Groups

### ISSUE THREAD

**Issue by JaceG** [lbryio/lbry#1943]
## The Issue

In order to stay in touch with fans and connect with other fans, 
as a creator of content and fan of content creator, 
I want niche communities of human curation.

### Steps to reproduce
1. https://www.facebook.com/help/184985882229224?helpref=faq_content
2. https://newsroom.fb.com/news/2018/08/people-can-now-find-mentors-and-mentees-in-groups/
3. https://www.youtube.com/watch?v=-pXkNqO91ac&list=PLP6jtBr5eWhvCHJe1E1_o7hxy5epOi1ja

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
Hey @JaceG , thanks for opening the issue. This is better suited for lbry-desktop and I think it's covered under https://github.com/lbryio/lbry-desktop/issues/1957.  That's one of our goals for this year!
