### ISSUE TITLE
claim_new_support() allows me to edit other's content

### ISSUE THREAD

**Issue by upsided** [lbryio/lbry#1947]
Not sure if this is a desktop or SDK/daemon issue...

## The Issue
Using `claim_new_support()` with pybry, I can support someone else's claim, as usual. However:
* LBRY app then enables my EDIT button for that claim (**even though content is not mine**)
* LBRY app allows me to see and edit somebody else's claim on the PUBLISH page
* Also shows up in my **Publishes** list (see pic below)
* I haven't tried updating from publish page, (that'd be bad)...

### Steps to reproduce
I did these steps:
1.  `lbry.claim_new_support("three", "a3262732cd445ef6c06f4bf64bfe3facdf82dbea", "500.42")`
2. Visit the claim, `lbry://@Books#fa1c5e4636d4087018dfdbb10d5a4838a10f50dd/three`
3. See the edit button and click it, 
4. Admire the Publish page, with all its functionality for somebody else's content
5. but don't fool with it cuz it'd suck if I'd ruin `@Books'` $3000 claim.

### Expected behavior
Edit button shouldn't be enabled for content I did not create. A different option should be there to "abandon my support" if desired (like it is in the wallet interface) instead of a full edit (!)

### Actual behavior
I can edit somebody else's stuff (kinda). Not actually good?

 

```
{'build': 'qa',
  'lbrynet_version': '0.30.4',
  'lbryschema_version': '0.0.16',
  'os_release': '17.7.0',
  'os_system': 'Darwin',
  'platform': 'Darwin-17.7.0-x86_64-i386-64bit',
  'processor': 'i386',
  'python_version': '3.7.2'}
```

## Screenshots

Shouldn't be able to edit, as this is not my content:
![edit button](https://user-images.githubusercontent.com/27879146/53145521-19f60280-3566-11e9-822b-efe9262cc4a5.png)

Here's the publish page. I shouldn't be able to see it:
![hello there somebodys stuff](https://user-images.githubusercontent.com/27879146/53145520-19f60280-3566-11e9-8551-24ebe3481ec8.png)
Here's `@Books` channel in the popup, which I do NOT own:
![whoa i see your channel too](https://user-images.githubusercontent.com/27879146/53145519-19f60280-3566-11e9-87e0-9699f7f7fc4b.png)
I didn't publish this content, but it shows up amongst my publishes:
![hey i didnt publish you](https://user-images.githubusercontent.com/27879146/53147671-de5f3680-356d-11e9-99e0-5dfe3552b698.png)

**Comment by tzarebczan** [comment]
This is just a bug on the UI, which is why so don't allow classic supports yet. I'll link it in the am.

**Comment by tzarebczan** [comment]
https://github.com/lbryio/lbry-desktop/issues/2105
