### ISSUE TITLE
Mac release build shows QA status

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1953]
## The Issue

The latest build shows up as qa under the release attribute. Not sure about previous builds, haven't looked into it. Windows and Linux are fine.

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by lyoshenka** [comment]
if this comes back, its may be because its building from the branch and from the tag, and whichever happens first wins.
