### ISSUE TITLE
Populate new file/stream/video/tag claim metadata

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1981]
## The Issue
https://github.com/lbryio/types/blob/a6f2fd6d5f382f0012383b9076d650c1f6791ada/v2/proto/claim.proto#L29
This includes:
file hash/name/size
video height/width/duration (from video metadata?)
release time (is this set to the current time if left blank, or let apps handle that?)
tags

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by kauffj** [comment]
Is this ticket to update the `publish` API call? It looked like it might be, so I grouped it with the tag-based discovery epic. If I misunderstood, a ticket to update `publish` should be created and associated with the aforementioned epic.

**Comment by tzarebczan** [comment]
We are missing file hash, and adding more metadata to video/image/audio files

**Comment by tzarebczan** [comment]
This is now fixed in 0.36
