### ISSUE TITLE
Better support for shared signing keys

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#2033]
## The Issue
Currently, if 2 wallets share a signing key and 1 of the wallets updates the metadata, the other wallet's signing key will now point to an older outpoint which cannot be used to sign new claims. In this case, the sdk should automatically figure out there is a new outpoint for the channel claim and allow signing. 

This will be required to continue posting YouTube sync claims after a YouTuber edits the channel (vice versa, they have the cert now, and we update the metadata for them). 

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
This will be required once we start allowing users to edit their profiles (which is currently a work in progress on the app side), otherwise our YouTube sync process will fail.

**Comment by hackrush01** [comment]
To replicate
1) create 2 wallets
2) add same accounts in the two wallets
3) copy channel from wallet 1 to wallet 2 after creating
4) change description(or something) and update the channel from wallet 1
5) then publish something from wallet 2, it should fail
