### ISSUE TITLE
Comments megaissue

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#2049]
## The Issue

current APIs:
```
        Create and associate a comment with a claim using your channel identity.

        Usage:
            comment_create <claim_id> <channel_id> <message> [--parent_comment_id=<parent_comment_id>]

        Options:
            --parent_comment_id=<parent_comment_id>  : (int) The ID of a comment to make a response to

        Returns:
            (dict) Comment object if successfully made
```
```
        List comments associated with a claim.

        Usage:
            comment_list <claim_id> [--flat] [(--page=<page> --page_size=<page_size>)]
                         [--parent_comment_id=<parent_comment_id>]
                         [--max_replies_shown=<max_replies_shown>]

        Options:
            --flat  : (bool) Flag to indicate whether or not you want the
                                    replies to be flattened along with the rest of
                                    the comments attached to the claim. Off by default
            --parent_comment_id=<parent_comment_id>  : (int) The ID of an existing
                                                             comment to list replies from
            --max_replies_shown=<max_replies_shown>  : (int) For every comment that we pull replies from,
                                                             only retrieve up to this amount.
                                                             Note: This is not the same as page size.
            --page=<page>  : (int) The page you'd like to see in the comment list.
                             The first page is 1, second page is 2, and so on.
            --page_size=<page_size>  : (int) The amount of comments that you'd like to
                                       retrieve in one request

        Returns:
            (dict)  Dict containing the following schema:
            {
                "page":  (int) The page of comments as provided when limiting response to page_size.
                "page_size":  (int) Number of comments in the given page. -1 if page_size wasn't used
                "comments":  (list) Contains all the comments (as dicts) as provided by the specified parameters
            }
```

- [x] Fix doc strings / cli so that you can also pass parameters to comment list/create like this, which is consistent with other API calls we have (and these should be defined in the Options doc string): `lbrynet comment create --claim_id=xxx --channel_id=xxx --message=xxxxx`

- [x] Support channel_name as parameter, to be consistent with publish/other api calls that take channel id

- [x] consider renaming parent_comment_id (list/create). This will be a transaction id most likely when it comes to the blockchain/supports based solution. 

- [x] remove claim_id/comment_id/downvotes/upvotes/claim_index/omitted from create/list response. None of these will be valid in the supports based solution. They will be tx / metadata related

- [x] page size -1? 
```
C:\Users\thoma\Desktop>lbrynet comment list de90b0068c8f2d7a019b06ce000591172891658e
{
  "comments": [
    {
      "author": "41fd2f30939bfbcae26c7248c2ada7b6d9a7a3db",
      "claim_index": 14,
      "comment_id": 55,
      "downvotes": 0,
      "message": "heyyyyyyyyyyy",
      "omitted": 0,
      "reply_count": 0,
      "time_posted": 1556057203,
      "upvotes": 0
    }
  ],
  "page": 1,
  "page_size": -1
}
```

- [x] rename message > comment? 

- [ ] Actually sign the comment and include signed hex value of comment when creating/listing. This would allow us to republish any existing comments when we move to the blockchain solution. 

Would like to review these with @eukreign sometime this week.

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by osilkin98** [comment]
@tzarebczan `page_size = -1` is to signify that `page_size` wasn't specified. I don't know of any other universal way to signify that there's no limit/it's the full page, and using `"infinity"` makes things messier since you start having return type inconsistency. 

I've also considered setting it as the size of the page but if I did that then the person wouldn't be able to tell if it's being paginated or not in the response. 

We can just specify it as the default but when I was looking at other APIs, they all tried to just return as much as possible, and network latency didn't seem like an issue so it didn't make much sense. 

I can change that if you think it would make more sense to use something else. 

Also most of the other stuff if not all of it can be fixed at the server end which is what I'm going to do once I post this.

**Comment by osilkin98** [comment]
@tzarebczan Do you want `channel_name` to be used in place of `author`, or should I just change it to `channel_id`?

**Comment by osilkin98** [comment]
@BrannonKing Can you give me the metadata tags you're going to be working into supports? I can implement them in the prototype database which would give us something to also test and play around with.

**Comment by tzarebczan** [comment]
@osilkin98 - regarding page size, see the claim_search api - it shows the size as default. 

Regarding channel_name, see how the publish api uses it. If we are using author on the list side, it should be populated with the channel URI (name + claim ID) and then the app can show the name + link to URI of channel.

**Comment by osilkin98** [comment]
@tzarebczan. Will we want to be storing any additional metadata about the channel claim which will then be fetched, or is that all?

**Comment by tzarebczan** [comment]
Don't need to store it in the database, that channel metadata will come from resolving it in the app. So given what we are currently saving, you'd need to run a claim search with the claim id on each one to get the channel name which we wouldn't want to do.

**Comment by osilkin98** [comment]
Thanks for the clarification, I'll have it ready once I'm done with all my
final stuff at school.

**Comment by tzarebczan** [comment]
Still todo:

- [ ] claim signing and sending this signature to the comment server. The comment server will store it for now. We can validate later.
