### ISSUE TITLE
account add fails with private key

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#2068]
## The Issue
We have a community member working on a crypto puzzle, this should work as it does with a seed. Also, I noticed it won't add a single account key back as such without the param, but I'd assume it would work the same way.  Is there a way to tell it's a single key from the import? 

```
C:\Users\thoma\Desktop>lbrynet account add --account_name="test" --private_key="xprv9s21ZrQH143K3q2RStQdm5Q7b9XN57ACUkiZbVBjPLZJYPAa1wB6QJbihYZpefBXpMCgnLpS8mpqx8uGJgGby4Bvm77XZkGt7MvwTuLK5VQ"
{
  "code": -32500,
  "data": [
    "Traceback (most recent call last):",
    "  File \"lbrynet\\extras\\daemon\\Daemon.py\", line 579, in _process_rpc_call",
    "  File \"lbrynet\\extras\\daemon\\Daemon.py\", line 1059, in jsonrpc_account_add",
    "  File \"lbrynet\\wallet\\account.py\", line 188, in from_dict",
    "  File \"torba\\client\\baseaccount.py\", line 268, in from_dict",
    "  File \"torba\\client\\baseaccount.py\", line 263, in keys_from_dict",
    "  File \"torba\\client\\bip32.py\", line 261, in from_extended_key_string",
    "  File \"torba\\client\\hash.py\", line 243, in decode_check",
    "  File \"torba\\client\\hash.py\", line 201, in decode",
    "TypeError: a string is required",
    ""
  ],
  "message": "a string is required"
}
```

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by eukreign** [comment]
fixed in https://github.com/lbryio/torba/commit/e7beb6b1a7533d77da6534f60d32a4459d6198d9
