### ISSUE TITLE
single key addresses break wallet on import/restart & bug without --single_key

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#2078]
## The Issue
1) if you add a single key account, you'll get this on startup:
```
Traceback (most recent call last):
  File "c:\users\thoma\documents\lbry\lbrynet\extras\daemon\Component.py", line 55, in _setup
    result = await self.start()
  File "c:\users\thoma\documents\lbry\lbrynet\extras\daemon\Components.py", line 268, in start
    await self.wallet_manager.start()
  File "c:\users\thoma\documents\lbry\lbry-venv\lib\site-packages\torba\client\basemanager.py", line 73, in start
    l.start() for l in self.ledgers.values()
  File "c:\users\thoma\documents\lbry\lbrynet\wallet\ledger.py", line 69, in start
    await asyncio.gather(*(a.save_max_gap() for a in self.accounts))
  File "c:\users\thoma\documents\lbry\lbrynet\wallet\account.py", line 171, in save_max_gap
    self.receiving.gap = max(20, gap['max_receiving_gap'] + 1)
AttributeError: 'SingleKey' object has no attribute 'gap'
```

2. If you add an account without the --single_key paramater that was generated using single_key, you'll generate a bunch of addresses that aren't the single key. Not sure if / how this is preventable, but maybe it's at least possible to have one of those addresses be the single account one? 

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by eukreign** [comment]
1. fixed in #2080 
2. there is no way to tell the type of address generation strategy that was used from just looking at a seed or private key (user has to have know this prior and then used `--single-key` argument when adding the same account again)
