### ISSUE TITLE
Movies can be re-downloaded

### ISSUE THREAD

**Issue by jobevers** [lbryio/lbry#208]
Multiple users are reporting that they end up with duplicate downloaded files.

```
 <filename>.ext
 <filename>-1.ext
 <filename>-2.ext
```

etc...

**Comment by tzarebczan** [comment]
@jackrobison I hear this may be fixed in the latest version... Let's close it if so. I haven't tested, but I know it was an issue plaguing many users recently too.

**Comment by lyoshenka** [comment]
@tzarebczan can you please test this to verify that its fixed
