### ISSUE TITLE
bind on 127.0.0.1 instead of localhost?

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#2103]
## The Issue
We've seen some instances where lbrynet cannot bind on localhost due to python trying to resolve it to an IPV6 address. Would it be safer to bind to 127.0.0.1? 

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by eukreign** [comment]
If the OS is configured to resolve `localhost` to an IPv6 address and then the same OS has disabled IPv6. I don't think this is a problem with lbrynet. `localhost` is the universal default for local communication.
