### ISSUE TITLE
Add lbryumx4 (EU) to the wallet list

### ISSUE THREAD

**Issue by nikooo777** [lbryio/lbry#2132]
lbryumx4.lbry.com:50001

Please note that lbryumx3 is also available but meant only for lbryTV so it shouldn't be added to the list.
### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
This was completed.
