### ISSUE TITLE
Unconfirmed transactions give "Invalid Date"

### ISSUE THREAD

**Issue by jobevers** [lbryio/lbry#214]
![image](https://cloud.githubusercontent.com/assets/2380127/19784242/a3658c86-9c5a-11e6-8dc2-399135d075e3.png)

Instead of Invalid Date, better would be "Unconfirmed" or something of the like

**Comment by alexliebowitz** [comment]
Solved on the front end side with this PR: https://github.com/lbryio/lbry-web-ui/pull/79

**Comment by kaykurokawa** [comment]
Closing as this seems solved
