### ISSUE TITLE
Disable tipping/payment for non-commercially licensed content

### ISSUE THREAD

**Issue by erzatz** [lbryio/lbry#2240]
## The Issue

Content under licenses such as [Creative Commons Non-commercial](https://creativecommons.org/licenses/by-nc/4.0/) must be for non-commercial use only.

Further information: [Non-commercial interpretation](https://wiki.creativecommons.org/wiki/NonCommercial_interpretation)

As all LBRY publishes accept payment by default, sharing such content arguably breaks the terms of these licenses (either by rewards payment from LBRY, or from tippers). 

As an example - much content on archive.org is licensed in this way, and is therefore undistributable on LBRY.

### Steps to reproduce
1.
2.
3.

### Expected behaviour
When publishing, there should be an ability to select a license. Selecting non-commercial licenses should disable payment on such items. 

Alternately, the publisher could have the arbitrary ability to demonetize their publishes - or at least set a flag that could be respected in the apps.

### Actual behaviour
There is currently no way to comply with non-commercial licenses such as Creative Commons variants.

The consequence is that those who respect such licenses cannot yet share such content legally on LBRY.

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by tzarebczan** [comment]
Thanks for filing this, we'll do some more research on the subject.

**Comment by jsigwart** [comment]
When someone uploads Creative Commons Non-commercial, getting tips on a file isn't a problem as the uploader is not asking for payment for the files. Tips are voluntary, and a way to say "thank you" for content. A tip on a free file is not a payment. It is a voluntary gift.

If someone were to say in their file description, "Download this file and send me 10 LBC and I'll send you a Zip file of 100 more files like this," that would be inappropriate and in violation of the license.

**Comment by erzatz** [comment]
If the primary purpose of sharing is deriving a financial benefit, this is the problem. This is placing a tip jar on every item shared - monetizing it. If you combine this with any current or future payments from LBRY for views/downloads, this would be a clear breach.

There is a benefit going to the sharer that will upset the original content creator. I would not share such someone else's CC-non commercial content under such circumstances - it breaks the spirit of the license if nothing else. And that is surely not what LBRY is about.
