### ISSUE TITLE
Replace i18n call with one that supports interpolation

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry#2245]
Evidently the `__` call being used by the app does not all interpolation of values.

It should support strings that work or look something like this:

```
__('You have %amount% credits', { amount: 5 })
```

**Comment by seanyesmunt** [comment]
Issue moved to [lbryio/lbry-desktop #2555](https://github.com/lbryio/lbry-desktop/issues/2555) via [**ZenHub**](https://www.zenhub.com/)
