### ISSUE TITLE
wallet enhancement - grouping transactions/metadata

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#235]
Someone made a good comment a while ago on Slack regarding the wallet.  End users probably won't want to see every single transaction that happens over the course of a single download.  Right now, that's exactly what we see, usually a hosting fees associated with the content fees - sometimes like 5 transactions happen for a single download.  Maybe it would be a good idea to group those transactions by download, and also give the transaction some meta data about what was downloaded, when etc.  Same would go for any hosting credits one would get - they would show up under the Credits section of the grouped download.  

Think this would really improve the end user experience.

**Comment by kauffj** [comment]
:+1: this is a good idea!
