### ISSUE TITLE
Balance stuck at 0

### ISSUE THREAD

**Issue by bitspill** [lbryio/lbry#248]
Despite numerous confirmations lbrynet sees the account as having 0 balance running 0.7.5

```
user@Anastasia ~/.lbrynet # lbrynet-cli get_balance
0.0
user@Anastasia ~/.lbrynet # lbrynet-cli get_transaction_history
[{"confirmations": 452, "date": "2016-11-04 08:11", "label": "", "timestamp": 1478243470, "txid": "36b5e81812c597e7915243359db18add14b0b3892d0f9fd533de84a282d3f8b0", "value": 19.94}]
user@Anastasia ~/lbry # git rev-parse HEAD
fe7700d726dfa034969e8b15f793468edaf235e6
```

**Comment by kaykurokawa** [comment]
Would you mind sending us your log file located at ~/.lbrynet/lbrynet.log to kay@lbry.io ?
My suspicion is that the balance is stuck as reserved for some reason.

**Comment by bitspill** [comment]
Recent log sent

**Comment by bitspill** [comment]
Is #250 relevant here perhaps

~/.lbrynet/lbryum.log is 0 bytes on my system, could that be taken to assume lbryum is failing to start properly?

Although, then I would expect get_transaction_history and get_latest_blockhash to fail but they're both correct.

**Comment by kaykurokawa** [comment]
No, it looks like your wallet is connected loading fine. 
Have you made any publishes ? Amounts used for publishing are not included in balance 
You can check this by running "lbrynet-cli get_name_claims"  

You can also install and run lbryum directly https://github.com/lbryio/lbryum without lbry , which should give you the correct balance.

**Comment by bitspill** [comment]
I have not published anything yet.

I deleted my old installation, cloned master as of 0.7.5, generated a bunch of addresses by clicking the button in ?wallet page, sent coins from Polo, waited.

`user@Anastasia ~ # lbrynet-cli get_name_claims
[]`

**Comment by bitspill** [comment]
Installing lbryum as a standalone app, it does correctly interact with the wallet including showing the balance and sending coins.

Updated lbrynet again, still 0 balance
```
user@Anastasia ~/lbry # git rev-parse HEAD
0abc081edc9a827374f1336bfa71f2738bf3a03e
```
Responded to email with further information.

**Comment by jobevers** [comment]
@bitspill is this still a problem?

**Comment by bitspill** [comment]
Unfortunately, yes.


```
lbrynet-cli get_transaction_history
[
  {
    "confirmations": 13351,
    "date": "2016-11-04 08:11",
    "label": "",
    "timestamp": 1478243470,
    "txid": "36b5e81812c597e7915243359db18add14b0b3892d0f9fd533de84a282d3f8b0",
    "value": 19.94
  },
  {
    "confirmations": 9589,
    "date": "2016-11-11 08:08",
    "label": "",
    "timestamp": 1478848111,
    "txid": "a5c04597beab08c5af7876bec0d360979b5a605fc82c205bd5794d5079e37a69",
    "value": -0.000113
  }
]

~/lbry # lbrynet-cli get_balance
0.0

~/lbry # git rev-parse HEAD
9140c95a0cbdcd09d2043c8f10848945f56db4c1
```

**Comment by jobevers** [comment]
@kaykurokawa can you look at this?  This seems like a high priority bug.

**Comment by bitspill** [comment]
Not sure which commit fixed it but I can now see my balance after updating today.

```
~/lbry # git pull
-- SNIP --

~/lbry # git rev-parse HEAD
13d74d1f7660c488a98284358d645bf09f7527df

~/lbry # pip install -r requirements.txt --upgrade
-- SNIP --

 ~/lbry # lbrynet-cli get_balance
10.0
```

**Comment by jobevers** [comment]
thanks for the followup
