### ISSUE TITLE
When restarting LBRY after an incomplete download, the download starts over

### ISSUE THREAD

**Issue by jobevers** [lbryio/lbry#255]
I started downloading Bellflower, stopped lbry, started it back up again and went to My Files.  The downloading started back from zero.  Looking through the logs, its not re-downloading the blobs it already has, but it does seem that we should be able to let the user know that they have already downloaded 12% of a file more easily.

**Comment by lyoshenka** [comment]
@jackrobison do you know if this is still an issue?
