### ISSUE TITLE
lbrycrdd vs lbrynet-daemon

### ISSUE THREAD

**Issue by hrdwdmrbl** [lbryio/lbry#289]
I'm very confused about the difference? This post especially seems to conflate the two https://lbry.io/faq/how-to-run-lbry-with-lbrycrdd

**Comment by kaykurokawa** [comment]
lbrycrdd is a full node for the lbry cryptocurrency network
lbrynet-daemon is an interface to the lbry cryptocurrency network, and contains the lbry Distributed hash table network 

Closing this as this is not an issue related to the software, but if you have any more questions join our slack at lbry.slack.com or email me at kay@lbry.io
