### ISSUE TITLE
An error occurred while starting a lbry file: 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by kaykurokawa** [lbryio/lbry#305]
Getting multiples of these error messages on startup : 

ERROR    lbrynet.lbryfilemanager.EncryptedFileManager:85: An error occurred while starting a lbry file: 'NoneType' object has no attribute '__getitem__'

**Comment by kaykurokawa** [comment]
Error originates here :

https://github.com/lbryio/lbry/blob/master/lbrynet/lbryfilemanager/EncryptedFileDownloader.py#L48

self.wallet.get_claim_metadata_for_sd_hash(self.sd_hash) is returning None for some sd hashes

**Comment by kaykurokawa** [comment]
Discussion with Jack: EncryptedFiledDownloader should ideally be decoupled from wallet class , status of claims should not be relevant to decision making of this class.

**Comment by lyoshenka** [comment]
Does this error still happen? Please reproduce in the latest daemon version and reopen if it's still an issue.
