### ISSUE TITLE
Error (Image of Error)

### ISSUE THREAD

**Issue by seemqueues** [lbryio/lbry#307]
![image](https://cloud.githubusercontent.com/assets/24168780/20888127/208fae72-bac3-11e6-9090-aa3ac16909b4.png)

I tried publishing a file and I get this error.  Not sure what this means.  Thanks.

**Comment by seemqueues** [comment]
I also get this error when I click on the link _My Wallet_.

**Comment by kaykurokawa** [comment]
are you running the latest 0.7.8 release ( https://github.com/lbryio/lbry/releases )? what OS are you on?
