### ISSUE TITLE
My Files - "Loading..."

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#309]
Fresh wallet, latest build (0.7.8) no files downloaded - when I go into My files, (both Downloaded and Published), I just see "Loading ... " with a animated ellipsis.  I would expect it to come back and say something along the lines of "You have no files, go to discover" for the Downloaded page, and "You have no published content, go to Publish..." for Published.

**Comment by alexliebowitz** [comment]
This bug ended up being in the UI layer, and has been fixed since. Thanks!
