### ISSUE TITLE
indication of content availability to network sharing

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#392]
etoque made a good point recently on slack - we need some type of indication that the files we download are being shared and made available to the network.  We wouldn't know unless someone downloads it and we get a micropayment (then it's still hard to know which file was shared).  Is there a way to check if the blobs are being shared properly?

**Comment by jobevers** [comment]
An unsatisfying temporary solution  - you can check if port 3333 is open: http://www.canyouseeme.org/

If its not, you aren't able to share.

**Comment by tzarebczan** [comment]
Sure that's a temp work around, but this was more intended for people who
will be downloading content with the purpose of sharing it. I know we are
in beta, but I get blob errors from time to time and I assume this means
something is wrong with the blobs and they won't be shared when someone
goes to download the file. Can't we have some type of verification of the
blobs against the content that was downloaded? This may become tricky once
content changes claims, not sure what the path forward there is.

Tom

**Comment by lyoshenka** [comment]
This is a good idea. Marking as feature request and closing for now.
