### ISSUE TITLE
explorer

### ISSUE THREAD

**Issue by pmfrulez** [lbryio/lbry#398]
explorer stuck again can someone check that

**Comment by pmfrulez** [comment]
http://prntscr.com/dtwens

**Comment by pmfrulez** [comment]
for a while I notice that new transactions on my address does not see on explorer probably on other addresses too..the last time I informed jiggytom about that ....Network in GH/s,Difficulty,total Coin Supply and LBC/BTC price (can u change price to poloniex value ?) is regularly refreshes...

**Comment by lyoshenka** [comment]
@pmfrulez i think Job's comment was meant for me

explorer looks fine right now. here's what i'm seeing:

![](http://i.imgur.com/iGnmfhW.png)

**Comment by lyoshenka** [comment]
The explorer app we're using is a bit slow to update sometimes. If you want the most up-to-date information on your balance, you should use the [lbryum wallet](https://github.com/lbryio/lbryum) and import your addresses into it. It will get updates a lot faster than explorer.

**Comment by pmfrulez** [comment]
lating of 2-3 days  for correct balance is not normal I think @lyoshenka still incorect balance on explorer
