### ISSUE TITLE
Unhandled exceptions in daemon commands don't return results

### ISSUE THREAD

**Issue by kaykurokawa** [lbryio/lbry#418]
If there is an unhandled exception thrown while processing a daemon command that was requested through lbrynet-cli , lbrynet-cli will hang forever. 

There should probably be a function wrapper for all daemon commands that will catch exceptions and return them to the cli.

┆Attachments: <a href="https:&#x2F;&#x2F;app.asana.com&#x2F;app&#x2F;asana&#x2F;-&#x2F;download_asset?asset_id&#x3D;248620640632445">lbrynet api doesn&#39;t respond.mov</a>

**Comment by lyoshenka** [comment]
Fixed
