### ISSUE TITLE
missing lbry-daemon 

### ISSUE THREAD

**Issue by janellebradleyZ8p** [lbryio/lbry#425]
~/Downloads$ lbry --help
running lbrynet-daemon...
/usr/bin/lbry: line 31: /usr/share/python/lbrynet/bin/lbrynet-daemon: No such file or directory

installed from .deb package 

Ubuntu 14.04

**Comment by tzarebczan** [comment]
Many files were recently moved but the package doesn't have the new path.
 try this: /opt/venvs/lbrynet/bin/lbrynet-daemon

**Comment by janellebradleyZ8p** [comment]
thanks, there is lbrynet-daemon indeed but, it is exiting anyway.

This is how it looks over VNC

 /opt/venvs/lbrynet/bin/lbrynet-daemon
Starting lbrynet-daemon from command line
To view activity, view the log file here: /home/userpwfzutpfzlsicr/.lbrynet/lbrynet.log
Web UI is available at http://localhost:5279
JSONRPC API is available at http://localhost:5279/lbryapi
To quit press ctrl-c or call 'stop' via the API
Xlib:  extension "XInputExtension" missing on display ":562".
Xlib:  extension "XInputExtension" missing on display ":562".
Xlib:  extension "XInputExtension" missing on display ":562".
Xlib:  extension "XInputExtension" missing on display ":562".
libGL error: failed to load driver: swrast
[22536:22536:0118/210951:ERROR:gl_surface_glx.cc(386)] GLX 1.3 or later is required.
[22536:22536:0118/210951:ERROR:gl_initializer_x11.cc(20)] GLSurfaceGLX::InitializeOneOff failed.
[22536:22536:0118/210951:ERROR:gpu_child_thread.cc(390)] Exiting GPU process due to errors during initialization
[21524:22483:0118/210951:ERROR:browser_gpu_channel_host_factory.cc(119)] Failed to launch GPU process.

Closing lbrynet-daemon
................
This is how it looks in NO gui - terminal

 /opt/venvs/lbrynet/bin/lbrynet-daemon
Starting lbrynet-daemon from command line
To view activity, view the log file here: /home/userpwfzutpfzlsicr/.lbrynet/lbrynet.log
Web UI is available at http://localhost:5279
JSONRPC API is available at http://localhost:5279/lbryapi
To quit press ctrl-c or call 'stop' via the API

Closing lbrynet-daemon

**Comment by jobevers** [comment]
Try `/opt/venvs/lbrynet/bin/lbrynet-daemon --no-launch` if you don't have a gui.
