### ISSUE TITLE
DHT Hash Announcer is not annoucing some blobs if it has a lot of blobs

### ISSUE THREAD

**Issue by kaykurokawa** [lbryio/lbry#432]
There is a hash_reannounce_time set to 1 hour in DHTHashSupplier , which determines how often hashes are reannounced. 

If a server takes more than 1 hour to announce all of its  blobs, than  there is going to be a constant back log of un- reannounced blobs that piles up. This means that some blobs will never be announced.  

The fix would be to make  hash reannounce time dynamic , based on how large a server's blob database is.

**Comment by kaykurokawa** [comment]
each blob takes less than 1 second to announce, somewhere  around .2 to .7 seconds

**Comment by jobevers** [comment]
The hashes are placed into a queue though which is processed first-in first-out, so it seems that it should get through all of them.  Maybe not in a timely fashion, but should get through.

**Comment by kaykurokawa** [comment]
I think you are right, it should announce eventually, 
Its still a problem though because the queue will keep getting bigger without being cleared causing a memory leak.

**Comment by jobevers** [comment]
Threw together https://github.com/lbryio/lbry/pull/435 the help investigate this issue
