### ISSUE TITLE
Old lbrynets may have excessively large wallets

### ISSUE THREAD

**Issue by kaykurokawa** [lbryio/lbry#437]
Old Lbrynets without this patch https://github.com/lbryio/lbry/pull/427 ( v8.0rc2 and below would not have this patch ) would generate a large amount of addresses in its wallet if running for a long time and receiving lots of download requests.  Having large amount of addresses slows down startup by a considerable amount and takes up unnecessary space. To fix this without losing any credits that you may have in your wallet, perform the below steps: 

1. Send any credits you may have in your wallet to a temporary wallet. Below are ways you can do this:

a. Download https://github.com/lbryio/lbryum, Create a brand new wallet (make sure it is not loading your previous wallet ) and send your balance to the new wallet. 

b. Install lbrynet on a separate computer and send your balance to the new wallet created there 

2. Once you have made sure that the balance has arrived in your temporary wallet, back up and delete your old wallet file which is located under ~/.lbryum/wallets/default_wallet for linux and mac. 

3. Startup a new install of lbrynet with the patch.  This will create a new ~/.lbryum/wallet/default_wallet. Send you balance from the temporary wallet to the new wallet.

**Comment by jackrobison** [comment]
It's worth noting that any active claims/supports in an old wallet will not transfer to a new one with this process. I don't think there's really a clean way to move those over, however they can be abandoned and made again.

**Comment by tzarebczan** [comment]
This definitely needs to be a feature of the claim management system, not
very user friendly now.

**Comment by kaykurokawa** [comment]
There is no easy way to do this, but there is a rather complicated way to do so through Lbryum using the "update" command in the console ( https://github.com/lbryio/lbryum/blob/master/lib/commands.py#L947 )

The "update" command allows you to specify an optional "claim_addr" argument, which is where the new updated claim gets sent to. Thus, you can run the update command on your old wallet and obtain an address from your new wallet and specify that as the "claim_addr".

**Comment by tzarebczan** [comment]
The correct location of the commands.py is :https://github.com/lbryio/lbryum/blob/master/lbryum/commands.py

**Comment by Invariant-Change** [comment]
In situations like this, 2 addition **CLI commands** would be useful:

`claim_list_mine_simple` Only displays the url and amount(s).
`claim_abandon_all`: Abandon all claims.

Ultimately, this would be perfect within the application UI in a **claim management** section, which is something I'm discussing with @shaunthornburgh who is an API developer.
