### ISSUE TITLE
ConnectionManager issues

### ISSUE THREAD

**Issue by kaykurokawa** [lbryio/lbry#447]
This is a list of ConnectionManager issues. ConnectionManager is a class that establishes connection between peers in order to download files from them. This is a work in progress list.

1.  ~~We need unit test for Connecion Manager. There needs to tests written to test for cases where the ConnectionManager connects to some non responsive or misbehaving peers. We know from observation that it is somehow not handling bad peers properly, but we don't know why.~~

2. Connection Manager is needlessly overgeneralized and complicated. It has logic to handle multiple "request creators" , but this is not really needed. The only request creator that it needs is a request creator for downloading blobs. 

3. ~~The main loop of ConnectionManager gets called every second. In each loop, it will check if it has less than 5 connections open, and if so, it will try to find a list of peers to connect to through the DHT and make a single connection.
I think that Instead of making a single connection, it should attempt to fill the 5 connections, and the main loop should be called less often because it is unlikely to find any new peers through the DTH after one second.~~ 

4. ConnectionManager should return some metrics about the quality of its connections, so that we can determine if a download is not working due to the lack of connections. Things like how long it has been running for, and how many responsive peers it has found over that time.

5. ~~Connections do not timeout if peer is slow to respond~~

6. ClientProtocol (class that manages a single connection) should have no dependency on ConnectionManager

**Comment by kaykurokawa** [comment]
https://github.com/lbryio/lbry/pull/458  fixes 1)

**Comment by kaykurokawa** [comment]
https://github.com/lbryio/lbry/pull/497 fixes 5)

**Comment by kaykurokawa** [comment]
https://github.com/lbryio/lbry/pull/565 fixes 3

**Comment by alyssaoc** [comment]
@eukreign Could you please confirm if the remaining issues are still valid and open issues as necessary? Then close this issue.

**Comment by eukreign** [comment]
@shyba are you working on any of these things as part of porting the p2p stuff to python 3?

**Comment by shyba** [comment]
no, I'm just porting for now. Feel free to create them and if I start a refactor I will self-assign the one that fits.

**Comment by alyssaoc** [comment]
closing will reopen new issues if any are needed
