### ISSUE TITLE
Wrong wallet

### ISSUE THREAD

**Issue by sueofil56** [lbryio/lbry#462]
I was suppose to enter my litecoin wallet but I entered my Bitcoin wallet instead. Using the soChain I can see the transaction was successful but labelled my Bitcoin wallet as LTC. When I checked the transaction in my Bitcoin wallet the payment cannot be found. I was paid through the wrong wallet I typed so can there be a solution to transfer the funds still as litecoin to my litecoin wallet?

**Comment by kauffj** [comment]
Sorry to hear about your trouble, but I suspect you've made a mistake posting this here.

This project is neither Bitcoin nor Litecoin. I'm going to close this ticket.
