### ISSUE TITLE
Confusing behavior in get_lbry_file_by_uri() 

### ISSUE THREAD

**Issue by kaykurokawa** [lbryio/lbry#491]
This problem was introduced in https://github.com/lbryio/lbry/pull/485

Let's say you have two files (A and B) associated with two different claims for the same name "test". File A is currently associated with the winning claim. You call get_lbry_file_by_uri() and you get file A. Someone overtakes name "test" with some random file that you have not downloaded. You call get_lbry_file_by_uri() and you will either get file A or B depending on which one shows up first in the file manager. This is a very arbitrary behavior that's going to confuse the user.

We need a separate function, something like get_lbry_file_by_name() that does not attempt to resolve the name through the blockchain, an just looks up the name in the file manager. get_lbry_file_by_uri() should be for the winning claim, and if you don't have the winning claim it should return nothing.

We should also return a list of files that is associated with a description whether it be sd_hash, name, or filename, instead of returning whatever is the first one in the file manager.

**Comment by jackrobison** [comment]
Work in progress: https://github.com/lbryio/lbry/pull/492

>We need a separate function, something like get_lbry_file_by_name() that does not attempt to resolve the name through the blockchain

We can get rid of the name resolution in the file manager altogether - it was only necessary to populate the metadata, which is stored in the new db. In addition, the db tracks the state of the associated claim (whether it be active but not winning, active and winning, pending, abandoned or updated over).

>We should also return a list of files that is associated with a description whether it be sd_hash, name, or filename, instead of returning whatever is the first one in the file manager.

Will do - I think the json returned should also include a status code for the state of the associated claim (from the db).

**Comment by kaykurokawa** [comment]
Closing as fixed in https://github.com/lbryio/lbry/pull/512
