### ISSUE TITLE
daemon.waiting_on logic is incorrect

### ISSUE THREAD

**Issue by kaykurokawa** [lbryio/lbry#496]
Daemon has a waiting_on variable : https://github.com/lbryio/lbry/blob/master/lbrynet/lbrynet_daemon/Daemon.py#L259

The variable prevents downloading the same name twice by storing downloaded names in a dict. However this does not account for the fact that a name can be updated, and the user could be downloading a completely different file. 

This also does not account for the case where a user deletes the file from his lbrynet and wants to redownload it as deleting a file does not remove the name from waiting_on. 

In order to prevent the re-downloading of the same file, the daemon should probably check the file manager for the presence of the file, instead of trying to manage its own waiting_on variable. Alternateively, the file manager could just prevent the addition of the same file and throw an exception.

**Comment by alyssaoc** [comment]
fixed by https://github.com/lbryio/lbry/commit/c6e614ebec109f7fcdb061f5e44a4fd8c897417b
