### ISSUE TITLE
Exchange Rate Manager issues

### ISSUE THREAD

**Issue by kaykurokawa** [lbryio/lbry#502]
Max key fee is specified in USD, this means that if exchange rate conversion does not work (bittrex/coinbase/google finance is down) , you can't download anything even if its fees are specified in LBC since we always tries to convert max key fee to LBC before downloading. Max key fees should be specified in LBC. 

Google finance does not return exact USDBTC exchange values since it seems to round off to the nearest 4th decimal place (currently returning 0.0008 when it should be 0.0008368..) Should use coinbase to get the correct exchange rate.

**Comment by lyoshenka** [comment]
oops

**Comment by kauffj** [comment]
I'd like to retain this setting in other currencies. We can switch to api.lbry.io if it improves or simplifies things (possibly this should be a setting?).

I think it's fine to block downloads when it can't determine an exchange rate, though for max key fee I think using the last known value would also be fine.

**Comment by kauffj** [comment]
I'm going to close this, as we're not dropping USD-based publishing. This can be re-opened as a ticket just specifying improvements to exchange rate calculation, if desired.
