### ISSUE TITLE
StandaloneBlobDownloader needs to timeout and clean itself up 

### ISSUE THREAD

**Issue by kaykurokawa** [lbryio/lbry#504]
I noticed that when trying to download a name associated with a sd_hash that does not exist in the network, it leaves behind a perpetually running ConnectionManager that is trying to download the sd_hash which it will never find. ( Try running "lbrynet-cli get name=10mb") 

I think from lbrynet.core.StreamDescriptor.download_sd_blob which calls lbrynet.core.client.StandaloneBlobDownloader needs to have a time out and clean it self up.

**Comment by kaykurokawa** [comment]
The proper place for the timeout would be in the DownloadManager class, 
as it is used both by GetStream (used to download full files), and StandaloneBlobDownloader. 

This means that we should replace the timeout mechanism currently present in GetStream.

**Comment by alyssaoc** [comment]
fixed by #507
