### ISSUE TITLE
Lbryum should be launched as a seperate process

### ISSUE THREAD

**Issue by kaykurokawa** [lbryio/lbry#506]
Currently lbryum is launched in a separate thread and in lbrynet, but this is not good as crashes in lbrynet can cause unexpected behavior in lbryum (possible to lose addresses thus credits).

Lbryum needs to be launched as a seperate process and daemon needs to make rpc calls to it.

**Comment by lyoshenka** [comment]
we're leaning toward integrating lbryum into lbrynet
