### ISSUE TITLE
API issues 

### ISSUE THREAD

**Issue by kaykurokawa** [lbryio/lbry#509]
Consistency issues in the API should be written here : 

Formatting 
claim_show - nout of claims are returned as "n", wherer "nout" is used elsewhere. Needs fix from lbryum call. 

Remove
upload_log - deprecated, should be removed

log - deprecated, should be removed 

get_nametrie - not useful, should be removed

get_mean_availability - not useful, should be removed

reveal - not used in electron

open - not used in electron

Rename
send_amount_to_address - should be renamed to wallet_send 

resolve_name - should be renamed to resolve  

reveal - should be renamed to file_reveal

get_availability - should be renamed to resolve_availability , and resolve anything

**Comment by lyoshenka** [comment]
@kaykurokawa how much of this is done?
