### ISSUE TITLE
Firefox does not understand lbry:// links on Ubuntu

### ISSUE THREAD

**Issue by starrychloe** [lbryio/lbry#52]
After installing version lbrynet_0.3.1_amd64.deb and launching from the launcher, Firefox comes up with a list of videos. When I click 'Watch' it presents this dialog. See screenshot.

https://ipfs.pics/QmbtrxmNqBnAvr7ZeGRSZpoci45YEayT5bVPj4e6wbMT3z

![lbry-firefox.png](https://ipfs.pics/ipfs/QmbtrxmNqBnAvr7ZeGRSZpoci45YEayT5bVPj4e6wbMT3z)

Ubuntu 14.04.4 LTS

**Comment by jackrobison** [comment]
'ok' isn't clickable?

**Comment by starrychloe** [comment]
According to the screenshot, it doesn't appear to be. This should be automatic for the install anyways. I chose an application and I selected /usr/bin/firefox. That didn't work and just popped up the dialog again. Eventually I was able to select LBRY and I remembered the choice.

**Comment by jobevers** [comment]
Closing this as its old; please re-open if it still persists on the most recent version (0.6.3)
