### ISSUE TITLE
Fails GET requests

### ISSUE THREAD

**Issue by Boruch-Baum** [lbryio/lbry#533]
I just now downloaded the daemon, successfully curl'ed a "resolve_name" request and a "wallet_new_address" request, but can't get GET requests working.

### Steps to reproduce
1.  ./lbrynet-daemon &>./lbrynet-daemon.log &
2.  curl 'http://localhost:5279/lbryapi' --data '{"method":"get","params":{"name":"what"} }'

### Expected behaviour
Exit code 0, mp4 file appearing in my /home/---/Downloads folder.

### Actual behaviour
The command line issues a timeout message. The abbreviated log file is attached (It was created using awk '{$1=""; $2=""; print $0}' lbrynet-daemon.log | uniq -c > log2, so the first column indicates the number of consecutive duplicated messages)

## System Configuration
curl 'http://localhost:5279/lbryapi' --data '{"method":"version"}'
[
  {
    "lbrynet_update_available": false,
    "lbrynet_version": "0.9.0",
    "lbryum_version": "2.7.13",
    "os_release": "4.5.0-0.bpo.2-amd64",
    "os_system": "Linux",
    "platform": "Linux-4.5.0-0.bpo.2-amd64-x86_64-with-glibc2.3.4",
    "remote_lbrynet": "0.9.0",
    "ui_version": "not loaded yet"
  }
]

## Anything Else
1] Notice in the abbreviated log that the daemon is issuing thousands of messages: WARNING lbrynet.dht.protocol:262: Can't send data to dht: EWOULDBLOCK.

2] Please consider either moving your not-so-hidden configuration folders .lbrynet and .lbryum from users' home folders to ~/.config, or make their location configurable.

[log.txt](https://github.com/lbryio/lbry/files/849298/log.txt)

**Comment by aaronfrary** [comment]
I had a very similar issue: same steps to produce, same timeout message, but a few minutes later the download restarts in the background and completes successfully. I've attached my logs for the session; hope this is helpful.

#### System Configuration
built against master at commit c1a5806
```
[
  {
    "build": "dev",
    "ip": "2601:19b:4401:7320:41ec:8f14:e547:2307",
    "lbrynet_update_available": false,
    "lbrynet_version": "0.9.1",
    "lbryum_version": "2.7.13",
    "os_release": "15.6.0",
    "os_system": "Darwin",
    "platform": "Darwin-15.6.0-x86_64-i386-64bit",
    "processor": "i386",
    "python_version": "2.7.13",
    "remote_lbrynet": "0.9.1"
  }
]
```
[lbrynet-daemon.log.txt](https://github.com/lbryio/lbry/files/856752/lbrynet-daemon.log.txt)

**Comment by jackrobison** [comment]
>1] Notice in the abbreviated log that the daemon is issuing thousands of messages: WARNING lbrynet.dht.protocol:262: Can't send data to dht: EWOULDBLOCK.

I'll look into this, it appears to only be happening on linux.

>2] Please consider either moving your not-so-hidden configuration folders .lbrynet and .lbryum from users' home folders to ~/.config, or make their location configurable.

These can be set as environmental variables - pick the values you want to override from [conf.py](https://github.com/lbryio/lbry/blob/master/lbrynet/conf.py#L141), prefix with `LBRY_`, and export with the desired values.

**Comment by Boruch-Baum** [comment]
Thanks

**Comment by alx** [comment]
Same warning about dht here on linux :  `WARNING  lbrynet.dht.protocol:262: Can't send data to dht: EWOULDBLOCK`

```
lbrynet-daemon --version
{
  "build": "release",
  "installation_id": "689EG1XgCnXcZaToaNbbrBEgUkuUmWXgBdyGUHjR6tXu5fQQPbUQR4RgYBGgixeRCj",
  "lbrynet_version": "0.9.1",
  "lbryum_version": "2.7.13",
  "os_release": "3.16.0-4-amd64",
  "os_system": "Linux",
  "platform": "Linux-3.16.0-4-amd64-x86_64-with-debian-8.7",
  "processor": "",
  "python_version": "2.7.12"
}
```

**Comment by lyoshenka** [comment]
Can you please try again in the latest version (https://github.com/lbryio/lbry/releases/latest)? I believe this is fixed.
