### ISSUE TITLE
Downloads fail if no $HOME/Downloads dir

### ISSUE THREAD

**Issue by JasperWallace** [lbryio/lbry#539]
## The Issue

Downloads fail if the ~/Downloads dir does not exist. 

### Steps to reproduce
1. run lbry under a new user with an empty homedir
2. try to download something
3:

`2017-03-17 14:55:38,869 INFO     lbrynet.lbrynet_daemon.Downloader:176: Downloading lbry://what (d51692) --> /home/lbry/Downloads/LBRY100.mp4
2017-03-17 14:55:38,870 ERROR    lbrynet.lbryfile.client.EncryptedFileDownloader:239: Traceback (most recent call last):
  File "site-packages/lbrynet/lbryfile/client/EncryptedFileDownloader.py", line 236, in open_file
IOError: [Errno 2] No such file or directory: '/home/lbry/Downloads/LBRY100.mp4'
`

### Expected behaviour

~/Downloads should be created.

### Actual behaviour
The error in the logs above.

## System Configuration

 

- LBRY Daemon version: 
- LBRY App version:
[
  {
    "lbrynet_update_available": false,
    "lbrynet_version": "0.9.0",
    "lbryum_version": "2.7.13",
    "os_release": "3.16.0-4-amd64",
    "os_system": "Linux",
    "platform": "Linux-3.16.0-4-amd64-x86_64-with-debian-8.7",
    "remote_lbrynet": "0.9.0",
    "ui_version": "not loaded yet"
  }
]
- LBRY Installation ID: 7fVr48AreLoYHg2W8YxA
- Operating system: Debian jessie.

**Comment by kaykurokawa** [comment]
i can confirm that the Download folder does not get created by lbrynet

**Comment by kaykurokawa** [comment]
Fixing this to create the Downloads folder if it doesn't exist

**Comment by kaykurokawa** [comment]
https://github.com/lbryio/lbry/pull/545
