### ISSUE TITLE
LBRY search is not working

### ISSUE THREAD

**Issue by starrychloe** [lbryio/lbry#54]
The Wonderful Life movie is not being found. It was working 2 weeks ago with version 0.2.5.

https://ipfs.pics/QmUoBzo2FBnWmoChGFPzghDVLeKk4DTq6VCBa7qebfjp6G

Version 0.3.1.

**Comment by jackrobison** [comment]
I just haven't published it to the new blockchain yet, will do soon.

**Comment by jobevers** [comment]
Closing this as its old; please re-open if it still persists on the most recent version (0.6.3)
