### ISSUE TITLE
Unable to fetch content

### ISSUE THREAD

**Issue by rasheedmoore** [lbryio/lbry#541]
## The Issue

https://hastebin.com/ofopihiqut.coffeescript

### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

## System Configuration

 

'{"method":"version"}'
[
  {
    "build": "release",
    "ip": "72.203.69.62",
    "lbrynet_update_available": false,
    "lbrynet_version": "0.9.1",
    "lbryum_version": "2.7.13",
    "os_release": "15.6.0",
    "os_system": "Darwin",
    "platform": "Darwin-15.6.0-x86_64-i386-64bit",
    "processor": "i386",
    "python_version": "2.7.13",
    "remote_lbrynet": "0.9.1"
  }
]
- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system: mac OSX El Capitan

**Comment by jackrobison** [comment]
https://github.com/lbryio/lbry/issues/547

**Comment by lyoshenka** [comment]
@rasheedmoore thanks for reporting this. we're closing this because we're consolidating several tickets into one. #547 has the root cause of the bug.
