### ISSUE TITLE
lbrynet-cli prints a literal \n rather than newlines

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry#543]
## The Issue
Output via lbrynet-cli is misformatted, particularly with newlines.

### Steps to reproduce
1. Run ./lbrynet-cli publish

### Expected behaviour
A nicely formatted error notifying me I am missing parameters.

### Actual behaviour
A jumbled mess of an error notifying me I am missing parameters, including "\n" being printed rather than rendered as a newline.

**Comment by kaykurokawa** [comment]
fixed in https://github.com/lbryio/lbry/pull/546
