### ISSUE TITLE
Proof of Purchase

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry#547]
## Stories

- As a _downloader_, I want to avoid paying multiple times for the same thing, or paying for something I do not receive.
- As a _publisher_, I want to enforce key payments by downloaders.
- As a _host_, I want to enforce the data rates that downloaders agreed to pay me.
- As _LBRY Inc._, I want to reward users who have consumed certain content.
- As an _advertiser_, I want to subsidize content for users who have watched my ads.

## Problem cases

- user can be charged for content, even if content download fails. then user gets charged again in the future.
- user can delete content they paid for, then try to download it again. they will be charged again.
- user can switch computers
- content can change. in this case, user might NOT be charged again?

**Comment by lyoshenka** [comment]
Quick update - we're working on a solution for proof-of-purchase. So far we've found that there are several simple but wrong answers here. We have some ideas for a proper fix, but that will take us some time. We'll update this issues as we make progress.

**Comment by lyoshenka** [comment]
Jack wrote up his findings [here](https://github.com/lbryio/lbry/issues/782#issuecomment-316465257)

**Comment by alyssaoc** [comment]
part of LBRY proposal process
