### ISSUE TITLE
LBRY Keeps Asking For A Claim Code

### ISSUE THREAD

**Issue by starrychloe** [lbryio/lbry#55]
Everytime I launch LBRY or go to settings then return back, it is always asking for my claim code. I entered a code to get the new download link, then when it popped up asking to enter the code again, it said the code has already been used. So now it keeps asking for the claim code and always opens to localhost:5279/?claim   .

Ubuntu 14.04.4 LTS

**Comment by jobevers** [comment]
Closing this as its old; please re-open if it still persists on the most recent version (0.6.3)
