### ISSUE TITLE
osx sierra install from source -- Twisted dependency

### ISSUE THREAD

**Issue by academikuser** [lbryio/lbry#558]
pip install --editable .

returns: 

     No matching distribution found for Twisted (from lbrynet==0.9.2rc1)

**Comment by jackrobison** [comment]
try `pip install -r requirements.txt` first

**Comment by kauffj** [comment]
@jackrobison can you update INSTALL.md accordingly?

**Comment by benyomin** [comment]
pip install -r requirements.txt
Collecting git+https://github.com/lbryio/lbryum.git (from -r requirements.txt (line 13))
  Cloning https://github.com/lbryio/lbryum.git to /private/var/folders/wb/cfz8yrnd3gs8570lx2l291sh0000gn/T/pip-DU6iEQ-build
Collecting Twisted==16.6.0 (from -r requirements.txt (line 1))
  Downloading Twisted-16.6.0.tar.bz2 (3.0MB)
    100% |████████████████████████████████| 3.0MB 288kB/s
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.python.org/simple/incremental/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661) -- Some packages may not be found!
    Couldn't find index page for 'incremental' (maybe misspelled?)
    Download error on https://pypi.python.org/simple/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661) -- Some packages may not be found!
    No local packages or working download links found for incremental>=16.10.1
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/wb/cfz8yrnd3gs8570lx2l291sh0000gn/T/pip-build-Da2yuB/Twisted/setup.py", line 21, in <module>
        setuptools.setup(**_setup["getSetupArgs"]())
      File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 316, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 371, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 846, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1118, in best_match
        return self.obtain(req, installer)
      File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1130, in obtain
        return installer(requirement)
      File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 439, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 659, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('incremental>=16.10.1')

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/wb/cfz8yrnd3gs8570lx2l291sh0000gn/T/pip-build-Da2yuB/Twisted/

**Comment by smalltock** [comment]
I can confirm this ^^^

Here's my log.  You can view it with fancy colors (more readable) with `curl https://paste.pound-python.org/raw/akS8TdfLERZMZujvpibo/`, but also here's the plain text:



    smalltock@gentock > ~ > cd ~/prog/git     
    
    
    smalltock@gentock > ~/prog/git > git clone --depth 1 https://github.com/lbryio/lbry
    Cloning into 'lbry'...
    remote: Counting objects: 250, done.
    remote: Compressing objects: 100% (243/243), done.
    remote: Total 250 (delta 12), reused 66 (delta 0), pack-reused 0
    Receiving objects: 100% (250/250), 467.52 KiB | 0 bytes/s, done.
    Resolving deltas: 100% (12/12), done.
    
    
    smalltock@gentock > ~/prog/git > cd lbry 
    
    
    smalltock@gentock > ~/prog/git/lbry >  master > l
    total 108K
    drwxr-xr-x 1 smalltock smalltock  540 Mar 28 18:30 .
    drwxr-xr-x 1 smalltock smalltock  220 Mar 28 18:30 ..
    -rw-r--r-- 1 smalltock smalltock 8.2K Mar 28 18:30 app.icns
    -rw-r--r-- 1 smalltock smalltock  297 Mar 28 18:30 .appveyor.yml
    -rw-r--r-- 1 smalltock smalltock  413 Mar 28 18:30 .bumpversion.cfg
    -rw-r--r-- 1 smalltock smalltock 6.9K Mar 28 18:30 CHANGELOG.md
    -rw-r--r-- 1 smalltock smalltock  309 Mar 28 18:30 Dangerfile
    drwxr-xr-x 1 smalltock smalltock   28 Mar 28 18:30 docs
    -rw-r--r-- 1 smalltock smalltock  11K Mar 28 18:30 ez_setup.py
    -rw-r--r-- 1 smalltock smalltock 3.2K Mar 28 18:30 FAQ.md
    drwxr-xr-x 1 smalltock smalltock  136 Mar 28 18:30 .git
    -rw-r--r-- 1 smalltock smalltock   25 Mar 28 18:30 .gitattributes
    drwxr-xr-x 1 smalltock smalltock   34 Mar 28 18:30 .github
    -rw-r--r-- 1 smalltock smalltock  210 Mar 28 18:30 .gitignore
    -rw-r--r-- 1 smalltock smalltock    0 Mar 28 18:30 .gitmodules
    -rw-r--r-- 1 smalltock smalltock 2.9K Mar 28 18:30 INSTALL.md
    drwxr-xr-x 1 smalltock smalltock  504 Mar 28 18:30 lbrynet
    -rw-r--r-- 1 smalltock smalltock 1.1K Mar 28 18:30 LICENSE
    -rw-r--r-- 1 smalltock smalltock  460 Mar 28 18:30 mkdocs.yml
    drwxr-xr-x 1 smalltock smalltock   14 Mar 28 18:30 packaging
    -rw-r--r-- 1 smalltock smalltock  13K Mar 28 18:30 .pylintrc
    -rw-r--r-- 1 smalltock smalltock 2.3K Mar 28 18:30 README.md
    -rw-r--r-- 1 smalltock smalltock  465 Mar 28 18:30 requirements.txt
    -rwxr-xr-x 1 smalltock smalltock  482 Mar 28 18:30 run_pylint.sh
    -rwxr-xr-x 1 smalltock smalltock  143 Mar 28 18:30 run_tests.sh
    drwxr-xr-x 1 smalltock smalltock  460 Mar 28 18:30 scripts
    -rw-r--r-- 1 smalltock smalltock 1.9K Mar 28 18:30 setup.py
    drwxr-xr-x 1 smalltock smalltock   86 Mar 28 18:30 tests
    -rw-r--r-- 1 smalltock smalltock 1.4K Mar 28 18:30 .travis.yml
    drwxr-xr-x 1 smalltock smalltock   22 Mar 28 18:30 uri_handler
    
    
    smalltock@gentock > ~/prog/git/lbry >  master > virtualenv lbry-venv
    Using base prefix '/usr'
    New python executable in /home/smalltock/prog/git/lbry/lbry-venv/bin/python3.5
    Also creating executable in /home/smalltock/prog/git/lbry/lbry-venv/bin/python
    Installing setuptools, pip, wheel...done.
    
    
    smalltock@gentock > ~/prog/git/lbry >  master > source lbry-venv/bin/activate
    %                                                                                                                                                                                                                 (lbry-venv)  smalltock@gentock > ~/prog/git/lbry >  master > pip install -U -r requirements.txt
    Collecting git+https://github.com/lbryio/lbryum.git (from -r requirements.txt (line 13))
      Cloning https://github.com/lbryio/lbryum.git to /tmp/pip-zxzv7fcl-build
    Collecting Twisted==16.6.0 (from -r requirements.txt (line 1))
      Using cached Twisted-16.6.0.tar.bz2
    Collecting appdirs==1.4.0 (from -r requirements.txt (line 2))
      Using cached appdirs-1.4.0-py2.py3-none-any.whl
    Collecting argparse==1.2.1 (from -r requirements.txt (line 3))
      Using cached argparse-1.2.1.tar.gz
    Collecting base58==0.2.2 (from -r requirements.txt (line 4))
      Using cached base58-0.2.2.tar.gz
    Collecting colorama==0.3.7 (from -r requirements.txt (line 5))
      Using cached colorama-0.3.7-py2.py3-none-any.whl
    Collecting dnspython==1.12.0 (from -r requirements.txt (line 6))
      Using cached dnspython-1.12.0.zip
    Collecting ecdsa==0.13 (from -r requirements.txt (line 7))
      Using cached ecdsa-0.13-py2.py3-none-any.whl
    Collecting envparse==0.2.0 (from -r requirements.txt (line 8))
      Using cached envparse-0.2.0.tar.gz
    Collecting gmpy==1.17 (from -r requirements.txt (line 9))
      Using cached gmpy-1.17.zip
    Collecting jsonrpc==1.2 (from -r requirements.txt (line 10))
      Using cached jsonrpc-1.2.tar.gz
    Collecting jsonrpclib==0.1.7 (from -r requirements.txt (line 11))
      Using cached jsonrpclib-0.1.7.tar.gz
    Collecting jsonschema==2.5.1 (from -r requirements.txt (line 12))
      Using cached jsonschema-2.5.1-py2.py3-none-any.whl
    Collecting miniupnpc==1.9 (from -r requirements.txt (line 14))
      Using cached miniupnpc-1.9.tar.gz
    Collecting pbkdf2==1.3 (from -r requirements.txt (line 15))
      Using cached pbkdf2-1.3.tar.gz
    Collecting protobuf==3.0.0 (from -r requirements.txt (line 16))
      Using cached protobuf-3.0.0-cp35-cp35m-manylinux1_x86_64.whl
    Collecting pycrypto==2.6.1 (from -r requirements.txt (line 17))
      Using cached pycrypto-2.6.1.tar.gz
    Collecting pyyaml==3.12 (from -r requirements.txt (line 18))
      Using cached PyYAML-3.12.tar.gz
    Collecting qrcode==5.2.2 (from -r requirements.txt (line 19))
      Using cached qrcode-5.2.2-py2.py3-none-any.whl
    Collecting requests==2.9.1 (from -r requirements.txt (line 20))
      Using cached requests-2.9.1-py2.py3-none-any.whl
    Collecting txrequests==0.9.5 (from -r requirements.txt (line 21))
      Using cached txrequests-0.9.5.tar.gz
    Collecting seccure==0.3.1.3 (from -r requirements.txt (line 22))
      Using cached seccure-0.3.1.3.tar.gz
    Collecting service_identity==16.0.0 (from -r requirements.txt (line 23))
      Using cached service_identity-16.0.0-py2.py3-none-any.whl
    Requirement already up-to-date: six>=1.9.0 in ./lbry-venv/lib/python3.5/site-packages (from -r requirements.txt (line 24))
    Collecting slowaes==0.1a1 (from -r requirements.txt (line 25))
      Using cached slowaes-0.1a1.tar.gz
    Collecting txJSON-RPC==0.5 (from -r requirements.txt (line 26))
      Using cached txJSON-RPC-0.5.tar.gz
    Collecting wsgiref==0.1.2 (from -r requirements.txt (line 27))
      Using cached wsgiref-0.1.2.zip
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/tmp/pip-build-60nlhfyo/wsgiref/setup.py", line 5, in <module>
            import ez_setup
          File "/tmp/pip-build-60nlhfyo/wsgiref/ez_setup/__init__.py", line 170
            print "Setuptools version",version,"or greater has been installed."
                                     ^
        SyntaxError: Missing parentheses in call to 'print'
        
        ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-60nlhfyo/wsgiref/
    
    
    (lbry-venv)  ✘ smalltock@gentock > ~/prog/git/lbry >  master > exit

**Comment by smalltock** [comment]
I should clarify, I'm on Gentoo linux, not on OSX Sierra.

**Comment by sleepdefic1t** [comment]
openssl installed for you guys?

**Comment by academikuser** [comment]
using the same version of the source

    $ which openssl
    /usr/local/bin/openssl
~/Downloads/lbrynet/lbry $ pip install -r requirements.txt
Collecting git+https://github.com/lbryio/lbryum.git (from -r requirements.txt (line 13))
  Cloning https://github.com/lbryio/lbryum.git to /private/var/folders/wb/cfz8yrnd3gs8570lx2l291sh0000gn/T/pip-kJk3h5-build
Collecting Twisted==16.6.0 (from -r requirements.txt (line 1))
  Using cached Twisted-16.6.0.tar.bz2
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.python.org/simple/incremental/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661) -- Some packages may not be found!
    Couldn't find index page for 'incremental' (maybe misspelled?)
    Download error on https://pypi.python.org/simple/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661) -- Some packages may not be found!
    No local packages or working download links found for incremental>=16.10.1
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/wb/cfz8yrnd3gs8570lx2l291sh0000gn/T/pip-build-Oxg32Z/Twisted/setup.py", line 21, in <module>
        setuptools.setup(**_setup["getSetupArgs"]())
      File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 316, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 371, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 846, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1118, in best_match
        return self.obtain(req, installer)
      File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1130, in obtain
        return installer(requirement)
      File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 439, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 659, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('incremental>=16.10.1')
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/wb/cfz8yrnd3gs8570lx2l291sh0000gn/T/pip-build-Oxg32Z/Twisted/
