### ISSUE TITLE
nsfw=false is added as nsfw=true

### ISSUE THREAD

**Issue by alicebob** [lbryio/lbry#559]
### Steps to reproduce
1. Add a file with:
`$ ./lbrynet-cli publish name="rfc2616" title="RFC2616" description="Hypertext Transfer Protocol -- HTTP/1.1" author="The Internet Society" language="english" file_path=./rfc2616.txt nsfw=false bid=1 license=unknown`

### Expected behaviour
It should not be marked as 'nsfw'

### Actual behaviour
In `claim_list_mine` it now shows:
```
{
    "address": "bQfcTXBvkh3mfJURPQtGukEqhCad3QZXnm",
    "amount": 1.0,
    "blocks_to_expiration": 262974,
    "category": "claim",
    "claim_id": "f9d0655f590dec84772569b9a304ae1b72626e9e",
    "confirmations": 0,
    "expiration_height": 409406,
    "expired": false,
    "height": 146432,
    "is_spent": false,
    "name": "rfc2616",
    "nout": 0,
    "txid": "e14cf3e606ecaba65c7a31a00b96db31941376343326ba98f20333190cb889df",
    "value": "{
        \"ver\": \"0.0.3\", \"description\": \"Hypertext Transfer Protocol -- HTTP/1.1\", \"license\": \"unknown\", \"author\": \"The Internet Society\", \"title\": \"RFC2616\", \"language\": \"english\",
     \"nsfw\": true,
     \"content_type\": \"text/plain\", \"sources\": {\"lbry_sd_hash\": \"24bf292d72601e7ff2c62fa27c01624c60217bcafcf95f69b92d40ddaef9c4ac37f30c40c43a3ea9f424d55f67a9e3b1\"}}"
  },
```
(note the nsfw=true)

## System Configuration

 

  "lbrynet_update_available": false,
  "lbrynet_version": "0.9.1",

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by kaykurokawa** [comment]
Can confirm that boolean is not processed properly here: 
https://github.com/lbryio/lbry/blob/master/lbrynet/lbrynet_daemon/DaemonCLI.py#L96

Not sure we need that guess_type function, should just use json.loads( ) I think?

**Comment by lyoshenka** [comment]
json.loads() can deal with things like `0.9.1`. we could do 

```
    try:
        return json.loads(x)
    except ValueError:
        return x
```

but then we run the risk of malformed json just being treated as a string

**Comment by lyoshenka** [comment]
I fixed it in https://github.com/lbryio/lbry/commit/8fa2524e540554662ee10935a2b2b225f656eed3

**Comment by lyoshenka** [comment]
But I'm open to using `json.loads()` somehow if you have a suggestion. I'd prefer json.loads to guess_type

**Comment by alicebob** [comment]
Thanks!

**Comment by kauffj** [comment]
Thank you for a textbook report @alicebob! If you want a tip, DM kauffj on our Slack.
