### ISSUE TITLE
500 error https://lbry.io/quickstart/github/callback?code=

### ISSUE THREAD

**Issue by lestravo** [lbryio/lbry#567]
## 500 error https://lbry.io/quickstart/github/callback?code=

500 Error after login with github

## Screenshots

![image](https://cloud.githubusercontent.com/assets/10636132/24330517/bc5f2e50-11ed-11e7-8953-6e0cb63a27ac.png)
![image](https://cloud.githubusercontent.com/assets/10636132/24330563/a58ae830-11ee-11e7-982e-72d44c62b12a.png)

**Comment by lyoshenka** [comment]
@lestravo thanks for reporting the issue. I believe I fixed it. Please give it another try, and reopen if its still happening.
