### ISSUE TITLE
After OS X installation of lbry.app, error message "IOError: [Errno 2] No such file or directory: '/Users/[username]/Library/Application Support/lbrycrd/lbrycrd.conf'"

### ISSUE THREAD

**Issue by viktorbengtsson** [lbryio/lbry#57]
The problem is fixed by:
1. Creating the directory lbrycrd
2. Creating the file lbrycrd.conf by running "echo -e "rpcuser=lbryrpc\nrpcpassword=$(env LC_CTYPE=C LC_ALL=C tr -dc A-Za-z0-9 < /dev/urandom | head -c 16 | xargs)" > ~/Library/Application\ Support/lbrycrd/lbrycrd.conf"

This should be part of the initial run of the app after installation.

**Comment by bmoconno** [comment]
I think you got autocorrected to "lbrycard" when talking about creating the directory and file, it's a good typo though... because you need a Library Card to check anything out at the local Library.

**Comment by viktorbengtsson** [comment]
Thanks. Fixed tyope

**Comment by jobevers** [comment]
Thanks!  This should be fixed with: https://github.com/lbryio/lbry/commit/6d7608d85123c7c0a8c5cfa81c0dad307774ff5b

Please let us know if its still an issue.
