### ISSUE TITLE
make cli respond to help if deamon is not running

### ISSUE THREAD

**Issue by techtonik** [lbryio/lbry#577]
With LBRY 0.9.1 running client is not very --help ful.
```
>lbrynet-cli.exe -h
ERROR: Could not connect to daemon. Are you sure it's running?

>lbrynet-cli.exe --version
ERROR: Could not connect to daemon. Are you sure it's running?
```

**Comment by lyoshenka** [comment]
I think this is a legit request. The issue is that lbrynet-cli is a very thin wrapper around curl, and has almost no logic of its own. But we can add at least have it respond to `--version` with something useful.

**Comment by lyoshenka** [comment]
@jackrobison do your recent CLI changes fix this?

**Comment by techtonik** [comment]
@lyoshenka `-h` works now to display help. Slow to react, but works.

`--version` doesn't work.
```
>lbrynet-cli.exe --version
←[1m←[31mERROR: "--version" is not a valid command.←[0m
See `lbrynet-cli.exe help` for more information.
```

**Comment by lyoshenka** [comment]
we'll add that in
