### ISSUE TITLE
Move build code for lbrynet-daemon from lbry-app to this repo

### ISSUE THREAD

**Issue by techtonik** [lbryio/lbry#578]
I see that it is Python project, but I don't see the code that compiles Python scripts into .exe Where is it?

**Comment by lyoshenka** [comment]
This is in the lbry-app repo. Right now the exe is built at the same time as the lbry-app release. We should move that code into this repo.

See https://github.com/lbryio/lbry-app/blob/master/daemon/build.ps1

**Comment by techtonik** [comment]
Maybe close the issue when the code is moved here?

**Comment by lyoshenka** [comment]
@techtonik this is mostly done in https://github.com/lbryio/lbry/tree/build . will merge it in soon.
