### ISSUE TITLE
Linux Prerequisite Command Problem

### ISSUE THREAD

**Issue by tikolai** [lbryio/lbry#584]
## The Issue

Linux Prerequisites guide produces and error when installing dependencies with "python-pip" command. 

### Steps to reproduce
1. open Linux terminal 
2. run command "sudo apt-get install libgmp3-dev build-essential python2.7 python2.7-dev "
3.run command  "python-pip git python-virtualenv libssl-dev libffi-dev"

### Expected behaviour
Each command should download, extract, and install the dependencies from their respective packages. 

### Actual behaviour
When running the command " python-pip" it is returned with "python-pip: command not found"

- LBRY Daemon version: 0.9.1
- LBRY App version: 0.9.2
- Operating system: Linux-4.4.0-71-generic-x86_64-with-Ubuntu-16.04-xenial

## To Fix it

Change the Linux Prerequisites to : 

sudo apt-get install libgmp3-dev build-essential python2.7 python2.7-dev 

~~python-pip~~ **sudo apt-get install** git python-virtualenv libssl-dev libffi-dev

**Comment by lyoshenka** [comment]
@tikolai i think you misunderstood the instructions. that was all supposed to be part of one `apt-get install` command. It should look like this:

```
sudo apt-get install libgmp3-dev build-essential python2.7 python2.7-dev python-pip git python-virtualenv libssl-dev libffi-dev
```

I'll fix the instructions to put that all on one line, so it's clearer. Thanks for taking the time to report this.

**Comment by lyoshenka** [comment]
Fixed in https://github.com/lbryio/lbry/commit/7a798616d61cca54d20c0570cb8d7489654e0492
