### ISSUE TITLE
A Javascript error occured in the main process

### ISSUE THREAD

**Issue by Getron** [lbryio/lbry#585]
### Steps to reproduce
1. just start the App in KDE Manjaro rolling release 17
2. then close the app
3. the error apear after 2-3 seconds on screen

### Expected behaviour
App should close normally, without any error apearint

### Actual behaviour
After closing the App in Manjaro KDE 17.0 Stable Rolling release, this error apear:

A Javascript error occured in the main process

Uncaught Exception:
TypeError: Cannot read property 'loadURL' of null
    at ChildProcess.subpy.on (/opt/LBRY/resources/app/main.js:58:10)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

## System Configuration

 

About

Your copy of LBRY is up to date.

daemon (lbrynet)	0.9.1
wallet (lbryum)	2.7.13
interface	0.9.1
Platform	Linux (Linux-4.10.4-1-MANJARO-x86_64-with-ManjaroLinux-17.0-Gellivara)

## Screenshots

![auswahl_395](https://cloud.githubusercontent.com/assets/5913218/24585546/85e25500-178d-11e7-8e3c-47e070eec14b.png)

**Comment by kauffj** [comment]
Thanks for reporting! This sounds like it is an issue with the app, rather than the daemon itself, so I moved it here:

https://github.com/lbryio/lbry-app/issues/30

I'm marking this one as closed. Thanks!
