### ISSUE TITLE
Purchase not deducted on locked wallets - but media allowed to be downloaded

### ISSUE THREAD

**Issue by ELM4Ever** [lbryio/lbry#59]
OS:  Linux Ubuntu 16.04 LTS

If the wallet is encrypted and locked, provided a high enough balance in the wallet, requesting a media within LBRY will download its content, but the fees are not deducted.  If LBRY is stopped after the download - there is no memory of the outstanding transaction(s).   If the wallet is eventually unlocked (for mining, for example), again, the outstanding transaction is not processed.

**Comment by ELM4Ever** [comment]
Any update?   I see this a major impediment for the future media providers - free downloads...

**Comment by Fillerix99** [comment]
@ELM4Ever Forwarded to dev team

**Comment by kimihiro64** [comment]
Tracking this through the code, it looks like once the queued payments are removed to be sent over to rpc sendmany, we lose all record of the transaction. If any of the payments fail, like on RPC_WALLET_UNLOCK_NEEDED, we throw that error, but as I far as I can see, there's no way we handle a failed payment or retry. Is the solution to keep all queued payments stored on client after they've been sent, only removing after we get a successful response? And should we be holding up any downloading of the file until after we get the successful response, or are we assuming it's eventually going to succeed?

**Comment by sonatagreen** [comment]
Does this only download the encrypted data, or does it also unlock the decryption key? If the latter, there's something wrong on the seller side, not just the client.

**Comment by jackrobison** [comment]
@sonatagreen the decryption key is stored in the stream descriptor blob, which the host doesn't necessarily provide. So nothing is going wrong on the seller side.

This is a bug, in that the program shouldn't let you download something without paying. However, it will be a more complex solution down the road that gets this locked down to the point where editing some code (or stumbling on a bug like this) won't let you bypass payment.

**Comment by hdost** [comment]
Is this still a bug?

**Comment by lyoshenka** [comment]
related to #719

**Comment by lyoshenka** [comment]
fixed
