### ISSUE TITLE
In franklin, running check_name_availability.php a second time causes timeouts for every name

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry#591]
1. Run check_name_availability.php. It should work fine the first time (though it takes hours)
2. Run check_name_availability.php again. Every name times out with 
```
Failed to get response from server within timeout of 30 in /home/grin/franklin/vendor/lbryio/php-api/src/BaseApi.php:50
```

**Comment by lyoshenka** [comment]
I suspect DHT issues

**Comment by lyoshenka** [comment]
@kaykurokawa did you fix this? i seem to remember you working on this

**Comment by kauffj** [comment]
Wrong repo?
