### ISSUE TITLE
Maybe have the daemon print status a bit more frequently when loading the wallet?

### ISSUE THREAD

**Issue by mortie** [lbryio/lbry#595]
Hi, lbry seems great. I'm currently going through the quickstart guide on https://lbry.io/quickstart, and figured I'd provide some feedback.

I downloaded the daemon, and started it, and it printed some information. It then printed this line:

    2017-04-08 17:04:21,214 INFO     lbrynet.core.Wallet:930: Local Height: 52895, remote height: 155129, behind: 102234

and then nothing, for multiple minutes. It worked just fine, just took some time to synchronize, which is completely expected when it comes to blockchain technology. I just think it would make sense to print an update more frequently, instead of letting the daemon just sit there for multiple minutes. Or maybe just add a line to the quickstart guide about how it might take a while; currently the guide just pretends that the daemon is ready to be queried immediately after you start it.

I have ignored the predefined format for issues, as this isn't a bug report, just feedback on how the developer onboarding experience could be slightly improved for what seems to otherwise be a great project.

**Comment by lyoshenka** [comment]
@mortie thanks for the feedback. it's supposed to print the status more frequently, so this does sound like a bug. what OS are you on, and what version of the app are you using?
