### ISSUE TITLE
list of issues with Channels update

### ISSUE THREAD

**Issue by kaykurokawa** [lbryio/lbry#597]
list of issues introduced with channles update found by lbry in a box integration testing. All tested with current master as of 4/8/17 6:30 pm (below commits are the last commit on the repo) 

lbry https://github.com/lbryio/lbry/commit/c0ccfe204640ed362b2e1501fa621ecea73bcc64
lbryum https://github.com/lbryio/lbryum/commit/5c423c99ea696fe366d4dbe18d0c1b7d1b3f9a8c
lbryum-server https://github.com/lbryio/lbryum-server/commit/4988f25278426bfabba387bfe2eaf2c9d71f3568

1. updates via jronrpc_publish() seem to not be working. The original claim is abandoned but not updated. 

2. jsonrpc_resolve_name() no longer returns None for claims that does not exist (unclaimed name), it raises an unrelated exception.

3. jsonrpc_resolve() needs to clarify what should happen if a uri does not exist, currently it returns an unrelated exception same as jsonrpc_resolve_name() 

4. jsonrpc_claim_show() no longer contains a list of supports 

5. In jsonrpc_claim_list() , "amount" fields for claims are expressed in string instead of float now. "amount" should be consistently expressed as float. 

6. In jsonrpc_claim_list_mine(), "amount" field is wrong. If something is claimed for 1 credit, it is expressed as 1e-8 (mistakenly interpreting a credit as dewey somewhere)

**Comment by jackrobison** [comment]
Fixes 2-6: https://github.com/lbryio/lbry/pull/601

**Comment by kaykurokawa** [comment]
2.  is not fixed , this is the raised exception 

Traceback (most recent call last):
File "/app/lib/python2.7/site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks 
esult = g.send(result)
File "/app/lib/python2.7/site-packages/lbrynet/core/Wallet.py", line 496, in _handle_claim_result
raise Exception(results['error']) 
Exception: Proof was invalid 

3. is fixed

4. is not fixed 
{u'claim_sequence': 1, u'has_signature': False, u'name': u'supporttest', u'amount': 1.0, u'value': {u'version': u'_0_0_1', u'claimType': u'streamType', u'stream': {u'source': {u'source': u'354d31f079696ef20a7ce1dd21fca723e896e77ed31af5fa933673998083f5f82d92e40b81f4489802224100dc974150', u'version': u'_0_0_1', u'contentType': u'text/plain', u'sourceType': u'lbry_sd_hash'}, u'version': u'_0_0_1', u'metadata': {u'description': u'test_description', u'license': u'NASA', u'author': u'test_author', u'title': u'test_title', u'language': u'en', u'version': u'_0_1_0', u'nsfw': False, u'licenseUrl': u'', u'preview': u'', u'thumbnail': u''}}}, u'height': 187, u'depth': 11, u'effective_amount': 2.0, u'address': u'mxr1SKMYMktDArERNLbkj8aSxLgeoLWwef', u'nout': 0, u'txid': u'3c98fd69db5f0c5f29f940f68f45054524776153ba9046d855fc798660872bca', u'claim_id': u'c0acf9db9df93a11d42a1dab92664e318f73d79d', u'decoded_claim': True}

5. is not fixed 
{u'supports_without_claims': [], u'claims': [{u'claim_sequence': 1, u'has_signature': False, u'name': u'testname', u'supports': [], u'valid_at_height': 163, u'amount': u'1', u'value': {u'version': u'_0_0_1', u'claimType': u'streamType', u'stream': {u'source': {u'source': u'8232816e20bb351ee7bf99354e95c02f95f6fcf8436a288a6db5adf35fb4a26d83c04e34d0cf40e20a1ed33e92e4ead7', u'version': u'_0_0_1', u'contentType': u'text/plain', u'sourceType': u'lbry_sd_hash'}, u'version': u'_0_0_1', u'metadata': {u'description': u'test_description', u'license': u'NASA', u'author': u'test_author', u'title': u'test_title', u'language': u'en', u'version': u'_0_1_0', u'nsfw': False, u'licenseUrl': u'', u'preview': u'', u'thumbnail': u''}}}, u'height': 163, u'depth': 5, u'effective_amount': u'1', u'address': u'mgxMsbmCCCd66bd2RfXRNN85TpzgJnMjtU', u'nout': 0, u'txid': u'403eaf191a75fa39b50a0aa5f7ce59e72debc6b2acca8200701238d6a388e969', u'claim_id': u'4cedda43ca56a43a49af1d1eeac4fc9c7fbd93f1', u'decoded_claim': True}], u'last_takeover_height': 163}


6. is not fixed
 
[{u'category': u'claim', u'has_signature': False, u'name': u'testname', u'is_spent': False, u'expired': False, u'blocks_to_expiration': 262969, u'value': {u'version': u'_0_0_1', u'claimType': u'streamType', u'stream': {u'source': {u'source': u'3456cd95f156c0907676b309bb0073be8e6b3da9349338e418c1672a21435a802be147592e82aaeb056baea9b413217e', u'version': u'_0_0_1', u'contentType': u'text/plain', u'sourceType': u'lbry_sd_hash'}, u'version': u'_0_0_1', u'metadata': {u'description': u'test_description', u'license': u'NASA', u'author': u'test_author', u'title': u'test_title', u'language': u'en', u'version': u'_0_1_0', u'nsfw': False, u'licenseUrl': u'', u'preview': u'', u'thumbnail': u''}}}, u'height': 163, u'nout': 0, u'amount': 1e-08, u'confirmations': 5, u'expiration_height': 263137, u'address': u'n4fFrTcGmxyvr7M1Zm4c9newUsHywW3i1J', u'is_pending': False, u'txid': u'13c97048fdf75414ef52608e5ca19baa4ef808f61aa519ed03375821e5ed7f8a', u'claim_id': u'a1524b6913ea58f44f14372e6c27d3dd0423e0e3', u'decoded_claim': True}]

**Comment by kaykurokawa** [comment]
Reran tests from master as of 4/2017 1:37 

1. is fixed via https://github.com/lbryio/lbryum/pull/91

2. is not fixed in some cases, seems to not be consistent though. Sometimes it will return None other times will throw 

Traceback (most recent call last):
  File "/app/lib/python2.7/site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    result = g.send(result)
  File "/app/lib/python2.7/site-packages/lbrynet/core/Wallet.py", line 524, in _handle_claim_result
    raise Exception(results['error'])
Exception: Proof was invalid


3. is fixed 

4. is fixed

5. is fixed

6. is fixed


New issues I found: 

jsonrpc_claim_show() no longer returns False for claims that do not exist, will throw the same exception as 2 

jsonrpc_resolve() output is not as described in docstrings , it looks like this: {'claims': { dictionary described in docstrings } }. I also see in Wallet.py that it can return channel results as {'claims_in_channel': }. So looks like docstring needs clarification

**Comment by kaykurokawa** [comment]
It seems #2 is related to the handling of proof when the claimtrie is in a fresh state (no claims in it) so does not seem to be a major issue

**Comment by jackrobison** [comment]
@kaykurokawa 

`claim_show` returning false when nothing is found: https://github.com/lbryio/lbry/commit/31b5026570398daf2e24336af96837b6cc8853ca

`resolve` doc update: https://github.com/lbryio/lbry/commit/10dcc429f3008d096fc9ecccff2336d6d2d38759
