### ISSUE TITLE
Balance Issues 

### ISSUE THREAD

**Issue by kaykurokawa** [lbryio/lbry#611]
We have an issue in how wallet balance is updated. We use point reservation to reserve lbry credits that need to be sent, and schedule all the payments at once. Here is how balance is updated:

a) payment is scheduled, point reservation is updated
b) payment is sent to lbryum, point reservation is cancelled, lbryum does not update its balance until it receives the transaction from lbryum server. At this time, the balance is not correct (it is the original amount)
c) lbryum recieves transaction from lbryum server. The balance is correct.

Solution:
a) remove point reservation logic , we don't need this logic because data fee payments should be rare
b) have lbryum update its balance immediately, last time I looked into this , it wasn't trivial to fix.  
c) move point reservation logic into lbryum using payment request feature. 

Related issues:
https://github.com/lbryio/lbry/issues/538

**Comment by lyoshenka** [comment]
@kaykurokawa does #747 fix this?

**Comment by alyssaoc** [comment]
@eukreign Does the new wallet fix this issue? If so please close.

**Comment by eukreign** [comment]
New wallet reserves UTXO that are about to be spent. Closing this issue.
