### ISSUE TITLE
Publishing error

### ISSUE THREAD

**Issue by Snarkly** [lbryio/lbry#612]
I tried to publish a video of whales but I get an error message. I added all the information about the video and when I hit publish I get this error in this screenshot I took for you. Also I clicked on the OK button but nothing happens when you click on OK.  ![lbry5](https://cloud.githubusercontent.com/assets/8492776/25058006/537de754-2143-11e7-8135-363d77481567.jpg)

**Comment by kauffj** [comment]
Hi @Snarkly! This issue is simply because you do not have any credits in your wallet.

However, definitely poor user experience to come up as such. This is fixed in an upcoming release.
