### ISSUE TITLE
Build fails during pip install phase

### ISSUE THREAD

**Issue by eyalroz** [lbryio/lbry#613]
I just cloned and tried to build lbry on my Linux Mint 18.1 (up-to-date), as per the instructions in your README.md

## The Issue

The build fails during the `pip install --editable .`  phase.

### Steps to reproduce
1. clone revision e8bccec71c7424bf06d057904e4722d2d734fa3f
2. build as per the instructions in README.md
3. watch it fail

### Expected behaviour
The `pip install` should conclude successfully

### Actual behaviour
After succeeding with many eggs, the `pip install` fails as follows:

```
Collecting wsgiref==0.1.2 (from -r requirements.txt (line 28))
  Downloading wsgiref-0.1.2.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-4z9120u5/wsgiref/setup.py", line 5, in <module>
        import ez_setup
      File "/tmp/pip-build-4z9120u5/wsgiref/ez_setup/__init__.py", line 170
        print "Setuptools version",version,"or greater has been installed."
                                 ^
    SyntaxError: Missing parentheses in call to 'print'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-4z9120u5/wsgiref/
```

## System Configuration

It's GNU/Linux Mint 18.1 (Intel x86_64 processor). The code was changeset e8bccec71c7424bf06d057904e4722d2d734fa3f .

**Comment by lyoshenka** [comment]
@eyalroz what version of `python` and `pip` are you using?

**Comment by eyalroz** [comment]
Oh, sorry. I'm using Linux Mint 18.1, with:
```
$ python --version
Python 2.7.12
$ pip --version
pip 9.0.1 from /usr/local/lib/python3.5/dist-packages (python 3.5)```

**Comment by lyoshenka** [comment]
Weird. From my quick googling, it looks like some kind of python 2/3 version mismatch. Take a look at these:

https://github.com/skoczen/will/issues/148
https://teamtreehouse.com/community/why-cant-i-install-wsgiref-in-python-virtual-environment

Any chance that applies to you somehow?

**Comment by eyalroz** [comment]
I have no idea. I'm not much of a pythonista... and actually, now I'm getting different errors. I'm closing this for now.
