### ISSUE TITLE
Content + search settings keep resetting

### ISSUE THREAD

**Issue by PetSte** [lbryio/lbry#617]
## The Issue

Everytime I close and restart LBRY the boxes on 'content'  (NSFW) and 'search' need to be manually checked again in 'settings'. 

### Steps to reproduce
1. Check the boxes
2. Close LBRY
3. Open LBRY and see them unchecked again

### Expected behaviour
Tell us what should happen

LBRY should remember my preferences.  

### Actual behaviour
Tell us what happens instead

It doesn't remember my preferences. 

## System Configuration

 

- LBRY Daemon version: 0.9.1
- LBRY App version: 2.7.13
- LBRY Installation ID:
- Operating system: Windows 10

**Comment by kauffj** [comment]
@alexliebowitz is going to check this out, thanks for reporting!

**Comment by lyoshenka** [comment]
I believe this is fixed.
