### ISSUE TITLE
Cannot access LBRY from another computer on the same network

### ISSUE THREAD

**Issue by starrychloe** [lbryio/lbry#62]
When accessing http://192.168.16.106:5279/ from a different computer, it will say

```
This site can’t be reached

192.168.16.106 refused to connect.
```

Need a way to bind to an IP address instead of just localhost.

Ubuntu 14, LBRY 0.3.1

**Comment by lyoshenka** [comment]
I believe this is intentional. LBRY is not meant to be shared across the network, it's meant to be used locally.

However, this is a good feature request. I'll file it in our feature tracking system.
