### ISSUE TITLE
Calling `get` on a channel returns the wrong error

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry#623]
## The Issue

Calling `get` on a channel returns a "Failed to resolve" error, when it should instead say that channels are not `get`able.

## Steps to Reproduce

1. Run the daemon
2. `lbrynet-cli get @lbry`

**Comment by kaykurokawa** [comment]
What should it do? 
The behavior of get is to throw an exception if the uri does not exist. 
We could throw a more informative exception here , and the docstring should mention what happens on 'no-gettable' uri's.

**Comment by kauffj** [comment]
If the daemon uses exceptions as the proper way of responding to API calls, then maybe there should be two classes and/or a way of signalling the difference between two distinct cases:

- Exceptions that should be bundled and passed to the user as an error as a proper response for this call
- Exceptions that indicate unexpected behavior, assertions/checks that should never fail, etc.

**Comment by lyoshenka** [comment]
New error says 
```
Traceback (most recent call last):
  File "/home/grin/.virtualenvs/lbry/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 457, in callback
    self._startRunCallbacks(result)
  File "/home/grin/.virtualenvs/lbry/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 565, in _startRunCallbacks
    self._runCallbacks()
  File "/home/grin/.virtualenvs/lbry/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/grin/.virtualenvs/lbry/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1355, in gotResult
    _inlineCallbacks(r, g, deferred)
--- <exception caught here> ---
  File "/home/grin/.virtualenvs/lbry/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    result = g.send(result)
  File "/home/grin/code/lbry/lbry/lbrynet/daemon/Daemon.py", line 1545, in jsonrpc_get
    "Failed to resolve stream at lbry://{}".format(uri.replace("lbry://", "")))
exceptions.Exception: Failed to resolve stream at lbry://@alex
```

**Comment by lyoshenka** [comment]
Also, documentation tells me this should be possible:
```
 Usage:
            get <uri> [<file_name> | --file_name=<file_name>] [<timeout> | --timeout=<timeout>]
```

`lbry://@alex` is a uri

**Comment by KamilPiekutowski** [comment]
Is there an IDE anyone would recommend for debugging this code?

**Comment by eukreign** [comment]
@KamilPiekutowski the IDE most of us use at lbry is [PyCharm](https://www.jetbrains.com/pycharm/). The free community edition of the IDE may do what you want but I'd recommend the paid Professional version and if you don't want to pay for it you can try the Early Release Program which are free [alpha versions of the professional edition](https://confluence.jetbrains.com/pages/viewpage.action?pageId=23004355) (they are good for 30 days I think but you can just keep upgrading it to the most recent version indefinitely).

**Comment by KamilPiekutowski** [comment]
@eukreign Thank you very much for your insight. I already started using PyCharm community version just to test things out. I will probably go with paid version depending where the things go.
