### ISSUE TITLE
Claimed Reward But There's No Transaction into balance

### ISSUE THREAD

**Issue by gapracoolz** [lbryio/lbry#628]
I have claim reward but no transaction to my balance 
![dont get reward](https://cloud.githubusercontent.com/assets/16890609/25513121/09737baa-2bfd-11e7-8618-7b9e1acd4053.png)
![dont get reward 1](https://cloud.githubusercontent.com/assets/16890609/25513134/19e47c1e-2bfd-11e7-810f-8787eb4ac978.png)
![console error](https://cloud.githubusercontent.com/assets/16890609/25513143/23d822ac-2bfd-11e7-8193-6988492911ea.png)

**Comment by finer9** [comment]
version 10.0rc6
Windows 7 64-bit

I think the http 400 bad request is significant here?

**Comment by finer9** [comment]
Slack user @gapracoolz

**Comment by lyoshenka** [comment]
Moved to https://github.com/lbryio/lbry-app/issues/102
