### ISSUE TITLE
List of API Issues/ Suggestion for changes 

### ISSUE THREAD

**Issue by kaykurokawa** [lbryio/lbry#630]
Here we will list/discuss API issues, and suggestions for changes for the lbrynet daemon. 

1. Lbry credit amounts should be represented as decimal encoded strings instead of floats to avoid round off error. 

2. Better formatting of "resolve" function: If we're going to have `resolve` return different signatures based on claim type, we probably ought to have a top-level field indicating the claim type.

**Comment by kauffj** [comment]
String and not Decimal?

https://docs.python.org/2/library/decimal.html

**Comment by kaykurokawa** [comment]
yes meant to say "string encoded decimal, using Decimal class" not "decimal encoded strings"

**Comment by kauffj** [comment]
These should just be separate issues. I believe 1 is open, and making a separate one for #2.
