### ISSUE TITLE
Incorrect balance shown, and transactions do not succeed despite report

### ISSUE THREAD

**Issue by sprig** [lbryio/lbry#633]
## The Issue

After sending some funds the balance displayed is funky

### Steps to reproduce
``` bash
-> % lbrynet-cli wallet_balance
0.008187
-> % lbrynet-cli send_amount_to_address amount=0.00818 address=<my-address>
true
-> % lbrynet-cli wallet_balance
-0.008173
## Wait some time
-> % lbrynet-cli wallet_balance
0.008187
```

### Expected behaviour
1. I would expect the transaction to report failure or to succeed
2. I would expect the wallet to display correct amount at all times.

## System Configuration

On archlinux:
```
-> % lbrynet-cli version
{
  "build": "release",
  "ip": "Could not determine IP",
  "lbrynet_version": "0.10.2",
  "lbryschema_version": "0.0.4",
  "lbryum_version": "2.7.21",
  "os_release": "4.10.5-1-ARCH",
  "os_system": "Linux",
  "platform": "Linux-4.10.5-1-ARCH-x86_64-with-glibc2.3.4",
  "processor": "",
  "python_version": "2.7.12"
}
```

**Comment by sleepdefic1t** [comment]
```
./lbrynet-cli send_amount_to_address --amount=0.00818 --address=<my-address>
```

**Comment by kauffj** [comment]
I believe this is identical to #719, which has a more useful description for a developer to work on. Thanks for reporting though! This will change.

**Comment by sprig** [comment]
@kauffj there seem to be some similarities but I'm not sure it is the same issue.

Specifically, why would the wallet report a negative balance (regardless of having the transaction queued or not not having it queued)?

Moreover, why would sending an amount which is less than my current total fail? If it is due to transaction fees, perhaps there should be some indication of what is an appropriate fee that would be enough to get the transaction signed?
