### ISSUE TITLE
Pressing play sometimes hangs

### ISSUE THREAD

**Issue by finer9** [lbryio/lbry#637]
## The Issue
Tried to play a random video. Sits on the "awkward" loading screen indefinitely  
### Steps to reproduce
1. Pick a random video you dont already have
2. Click play
3.  Possibly be on Windows

### Expected behaviour
15-20 sec pause followed by streaming

### Actual behaviour
load screen hangs indefinitely yet file is downloading in Downloads
If you return to the specific file page after Downloads, it shows as downloading and plays fine

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:
Win 10

## Screenshots

![after play again](https://cloud.githubusercontent.com/assets/16390156/25961670/095dddf8-3649-11e7-9609-1507addfb4e3.PNG)
![there](https://cloud.githubusercontent.com/assets/16390156/25961669/095b36c0-3649-11e7-8c29-ee8fde3c5389.PNG)
![play hang](https://cloud.githubusercontent.com/assets/16390156/25961671/095f1218-3649-11e7-8c14-8a8c018add57.PNG)

**Comment by lyoshenka** [comment]
@finer9 this should be in the lbry-app repo. Moving it there: https://github.com/lbryio/lbry-app/issues/181
