### ISSUE TITLE
LBC not withdrown by calling get on the daemon

### ISSUE THREAD

**Issue by raycar5** [lbryio/lbry#640]
## The Issue
Money not withdrawn from account when getting content from daemon

### Steps to reproduce
1. Call get on the daemon with an uri as the argument
2. File gets downloaded
3. Money is not withdrawn from the account

### Expected behaviour
Money is transferred to the content creator when you download the content

### Actual behaviour
Money is not transferred to the content creator when you download the content

## System Configuration
{
  "build": "release",
  "lbrynet_version": "0.10.2",
  "lbryschema_version": "0.0.4",
  "lbryum_version": "2.7.21",
  "os_release": "4.4.0-75-generic",
  "os_system": "Linux",
  "platform": "Linux-4.4.0-75-generic-x86_64-with-Ubuntu-16.04-xenial",
  "processor": "x86_64",
  "python_version": "2.7.12"
}

## Anything Else
Only two transactions have been made from the wallet and they are both deposits in order to pay for the content

## Screenshots
[Transaction list and balance](https://gyazo.com/a6ab08d0e81ae7dd6bdee25e49bacddb)
[File](https://files.slack.com/files-tmb/T0AFFTU95-F59R4QZMZ-fd27ec601a/bug_1024.jpg)

**Comment by kauffj** [comment]
Is this happening for you reliably? We haven't been receiving regular reports of this, and there's little a developer can do from this description.

This is an issue we'd take very seriously if it's happening for you still, please let us know if it is.
