### ISSUE TITLE
"failed to get version from git" daemon first run

### ISSUE THREAD

**Issue by shuryukan** [lbryio/lbry#642]
![image](https://cloud.githubusercontent.com/assets/9072357/26040213/102813ea-391b-11e7-8c39-21ba59778714.png)

Just want to know what is happening, since I cannot enter commands after this displays. This is after running daemon for the first time to set up the API. The next thing I need to do is verify that the daemon is running correctly, but I can't type anything. Is it just a matter of waiting long enough? (It's been sitting there for 10 minutes).

Thanks!

**Comment by lyoshenka** [comment]
@shuryukan what version of the daemon are you using? run `lbrynet-daemon.exe --version` and paste the results here

**Comment by shuryukan** [comment]
![image](https://cloud.githubusercontent.com/assets/9072357/26171890/709c4442-3b3e-11e7-8643-8ca86709d9f3.png)

**Comment by lyoshenka** [comment]
Hmm. I thought I fixed this issue before v0.10.2, but maybe it was just after...

Can you try [the latest version](https://github.com/lbryio/lbry/releases/tag/v0.10.3rc3) and let me know if you're still getting that error?

Either way, this warning should not impact the usability of the daemon. But I appreciate that you took the time to open this issue :smile:

**Comment by lyoshenka** [comment]
Please reopen if you're still seeing that message.

**Comment by shuryukan** [comment]
Still seeing this with nothing happening
![image](https://cloud.githubusercontent.com/assets/9072357/26225747/ad49271a-3c20-11e7-9c63-dc3da3081ea4.png)

and here's the version log
![image](https://cloud.githubusercontent.com/assets/9072357/26225769/ca3853dc-3c20-11e7-8e3a-c786a84f9e35.png)
