### ISSUE TITLE
claim_show can return incorrect claim if name and outpoint are provided

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry#644]
(**Only number 1 exists, number 2 is fixed.**)

A few issues with `claim_show`:

1) `claim_show` requires name, which it then ignores if txid/nout or claim_id is provided. Example:

`./lbrynet-cli claim_show name=foo txid=e43ff68bb91df13df57b87e6a43c70f5c584e88feacf75789308b9c02ad2657b nout=0`

This returns a claim for name "chillin" (which is correct for the outpoint), but should not be returned if I provide the name "foo".

2) **(FIXED)** `claim_show` should not require a name if it's possible to resolve by claim_id and/or outpoint directly. I should be able to run:

`/lbrynet-cli claim_show txid=e43ff68bb91df13df57b87e6a43c70f5c584e88feacf75789308b9c02ad2657b nout=0`

But it currently tells me a name is required.

**Comment by kaykurokawa** [comment]
https://github.com/lbryio/lbry/pull/647 fixes 2, 

For 1, do you need it to filter by multiple arguments? (for example by both name and claim ID) 
Or should it only allow you to filter by one thing only , to be less confusing, (throw exception if you specify both name and claim id)

**Comment by kauffj** [comment]
I think it should be possible to filter by name and claim_id. When both are provided, you are essentially saying find a claim with this id iff it has this name. An example use case would be spee.ch, where it will support URLs like spee.ch/name/claimId.

**Comment by hackrush01** [comment]
@kauffj, I wanted to clarify point 1. So if a user provides both name and claim id or name and txid + nout then it should check whether the name returned by claim_show matches the name provided by the user, and if not then display some sort of error?

**Comment by kauffj** [comment]
Correct.

**Comment by hackrush01** [comment]
@kauffj This can be closed now I guess.

Fixed in #730
