### ISSUE TITLE
Miscommunication in "Published" section of UI

### ISSUE THREAD

**Issue by dirtybits** [lbryio/lbry#648]
## The Issue

Miscommunication in the "Publishes" tab in the "Downloads and Purchases section"

### Steps to reproduce
1. Click on "Downloads and Purchases" tab
2. Click on "Published"

### Expected behaviour
Should say something along the lines of, ""You haven't published anything to LBRY yet. Go publish your first work of art!"

### Actual behaviour
"You haven't downloaded anything from LBRY yet. Go search for your first download!"

## Screenshots

![publish error](https://cloud.githubusercontent.com/assets/28834908/26382084/233ec034-3fef-11e7-876a-b2287aa713ab.png)

**Comment by kauffj** [comment]
Thanks for reporting this. This is fixed [here](https://github.com/lbryio/lbry-app/commit/8ac2bcd6389e691d6dc11802b0cae1293d7653b7).

Please report future cosmetic/UI issues to the [lbry-app](https://github.com/lbryio/lbry-app) repo rather than this one.
