### ISSUE TITLE
can 'resolve' but not 'get'

### ISSUE THREAD

**Issue by iateadonut** [lbryio/lbry#649]
I can 'resolve' but cannot 'get' a url.

'get' returns a timeout.

### Steps to reproduce
$ lbrynet-cli resolve uri=what
{
  "claim": {
    "address": "bMavvzXG2XT5GRK4kgQCFop1B5XvHRJPye",
    "amount": "1",
...

$ lbrynet-cli get uri=what
{
  "error": "Timeout"
}

### Expected behaviour
I should download the uri.

### Actual behaviour
I get a timeout message

## System Configuration

$ lbrynet-cli version
{
  "build": "release",
  "ip": "***",
  "lbrynet_version": "0.10.3",
  "lbryschema_version": "0.0.4",
  "lbryum_version": "2.7.22",
  "os_release": "4.4.0-53-generic",
  "os_system": "Linux",
  "platform": "Linux-4.4.0-53-generic-x86_64-with-LinuxMint-18.1-serena",
  "processor": "x86_64",
  "python_version": "2.7.12"
}

- LBRY Daemon version: 0.10.3
- Operating system: Ubuntu 16.04 derivative (Mint 18.1)

**Comment by kauffj** [comment]
@jackrobison and/or @lyoshenka this is likely a network issue since many others are able to fetch this URI, but I wonder if we could build a tool or add some code to the daemon that debugs/detects network issues.

**Comment by iateadonut** [comment]
this is in the error log:

2017-05-26 01:00:00,380 ERROR    lbryum.interface:115: Failed to connect to (2, 1, 6, '', ('54.174.5.255', 50001))
Traceback (most recent call last):
  File "site-packages/lbryum/interface.py", line 110, in get_simple_socket
  File "socket.py", line 228, in meth
error: [Errno 111] Connection refused

This is an amazon server.  Is this one of your servers?  I wonder if the firewall is refusing connections from my area?

**Comment by kauffj** [comment]
@lyoshenka @iateadonut looked into this further and thought that we may have a security group rule blocking IPs from certain countries. I don't think we do, but can you confirm? He's interested in helping debug this, you can contact him on Slack under the same name.

**Comment by lyoshenka** [comment]
I dont believe we're blocking anything based on location. I do know our lbryum server has issues sometimes, and @jackrobison is gonna be working on fixes for it.

@iateadonut the daemon should have several lbryum servers in its list, and should try to connect to other servers if the first one fails. are you seeing that in the logs? does the daemon still work for you despite this error?

**Comment by iateadonut** [comment]
The daemon runs well.

The error in the logs that I posted happens when I execute a 'get' command.

Looking at the telnet response, it seems that the server is actively blocking my ip address.

**Comment by kauffj** [comment]
@iateadonut still seeing this? please re-open if so

**Comment by iateadonut** [comment]
still doesn't work.

i'll have to do some more testing to make sure i can set it up on a server in the States and watch it work.

**Comment by tzarebczan** [comment]
@iateadonut did you update to the latest version? Lbry.io/get

Please do so and then post the logs files here
