### ISSUE TITLE
Content availability function sucks

### ISSUE THREAD

**Issue by finer9** [lbryio/lbry#655]
## The Issue
The availability function seems unstable

### Steps to reproduce
1. Browse around, click to sub page and see if content avail/not
2. Sometimes even when it says unavail it is really avail
3.

### Expected behaviour
Says if content really is avail / not

### Actual behaviour
Randomly chooses a state ;)

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by kauffj** [comment]
I'm tempted to drop this from the UI at all, since a lot of content that shows unavailable is actually there. It is already being skipped on all video plays.

**Comment by tzarebczan** [comment]
It's nice to have that feature, just has to be more robust and accurate. Would be awesome if it knew how many hosts were available, general location, whether original host available, etc.

**Comment by finer9** [comment]
So are we dropping this @kauffj ?  Let's do it

**Comment by caseyparker** [comment]
The thing sucks _right now_. It's still a reference implementation, give us all some time.

**Comment by kauffj** [comment]
This was dropped from the UI.

**Comment by lyoshenka** [comment]
If its dropped, I'm closing it. Reopen if we need to do anything else here.
