### ISSUE TITLE
Issues with using the same app account on multiple devices

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry#666]
From `@anatzum` in slack #feedback

https://lbry.slack.com/archives/C544Q2RFS/p1495272158342646

> Since if you access lbry using the developer option and pay 1 lbc to gain entry it skips past email verification and currently there is no possible way to do this and it uses your hostname i'm guessing, how is this even going to work with most people having multiple devices? You can copy your wallet over to your other devices but are you going to need an email for every device you own? i'm seeing a lot of issues going forward with it being like this.

> I've tried deleting all config files as well as the application and reinstalling and i was automatically logged in. I tried changing my hostname and it prompted me again but given that what i'm using is a workstation with server services running that is not really an option for me. Since this worked, I'm assuming the hostname and possibly HWID info is stored by lbry

> On a separate computer, I did the access code route and everything worked as expected. I tried copying over the .lbrynet and .lbryum from that computer over to this one and the only thing that transferred was the wallet associated with the email but i still run into the same issues I was having before with for example claiming any rewards saying I need to verify my email. So i'm assuming the wallet and email/computer id are completely separate which will cause a ton of issues for people with multiple devices. Though I have not tried verifying with the same access code on multiple devices since my other device is the one that is unable to verify the email.

**Comment by kauffj** [comment]
The auth part specifically is fixed.

The ability to keep the same view/content across applications is a large project across a mix of repos, that won't be looked at until several sub-components are tackled on their own (like wallet import).
