### ISSUE TITLE
file_delete with no outpoint deletes ALL files

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry#671]
_From @6ea86b96 on June 4, 2017 16:46_

`lbry.file_delete({}, delete_target_file: true })` will delete all files (downloaded and published). Bug or feature?

_Copied from original issue: lbryio/lbry-app#193_

**Comment by kauffj** [comment]
Agreed with @6ea86b96 on this, `file_delete` with no parameters should not delete everything. Perhaps with an additional parameter like `delete_all` this would be fine.

**Comment by kaykurokawa** [comment]
There is a delete_all flag (-a), but it doesn't work , nor is it described properly in docstrings .

Also delete_target_file flag (-f) states "delete only from downloads, do not delete blobs" , However the behavior is that blobs are always deleted, and setting delete_target_file flag will delete from the downloads folder.

**Comment by kaykurokawa** [comment]
fixes here : https://github.com/lbryio/lbry/pull/672
