### ISSUE TITLE
test_double_download throws an error, but not always

### ISSUE THREAD

**Issue by jackrobison** [lbryio/lbry#675]
<img width="1320" alt="screen shot 2017-06-08 at 12 57 34 pm" src="https://user-images.githubusercontent.com/11979920/26940844-35ade846-4c4a-11e7-8414-05304ce2374f.png">
<img width="1239" alt="screen shot 2017-06-08 at 12 57 28 pm" src="https://user-images.githubusercontent.com/11979920/26940848-39ef14fc-4c4a-11e7-947c-f79d28cef981.png">

**Comment by kaykurokawa** [comment]
same issue as here: https://github.com/lbryio/lbry/issues/527

**Comment by jackrobison** [comment]
fixed in https://github.com/lbryio/lbry/pull/682
