### ISSUE TITLE
"The Daemon Has Shut Down Unexpectedly"

### ISSUE THREAD

**Issue by finer9** [lbryio/lbry#679]
## The Issue
Startup stops on the 'Daemon has shut down unexpectedly" splash screen

### Steps to reproduce
1. Start LBRY app
2.
3.

Windows 10 64 bit latest version of app

**Comment by lyoshenka** [comment]
Does this happen every single time?

**Comment by tzarebczan** [comment]
Does reinstalling help? Maybe some temp files are cleaned up?

**Comment by finer9** [comment]
Thought this log had some interesting errors and info - the user receives this error message

[lbrynet (3).log.txt](https://github.com/lbryio/lbry/files/1103576/lbrynet.3.log.txt)

**Comment by tzarebczan** [comment]
@finer9 that one was related to this port issue: https://github.com/lbryio/lbry/issues/710

The one you saw, which I've seen before as well, is related to the daemon_settings.yml file. If deleted, it starts to work.  I think I can reproduce this on my brother in law's PC if needed.
