### ISSUE TITLE
Newly published content requires a restart of the LBRY app to show up in the system.

### ISSUE THREAD

**Issue by AyiSoli** [lbryio/lbry#684]
## The Issue

Whenever I upload some new content, it does not show up immediately. Even on confirmation, it does not appear on the  "PUBLISHED" tab. I have to restart LBRY to find my uploaded content on the Published tab.

### Steps to reproduce
1. Create new content: Click on PUBLISH -> Select the files.
2. Select the price, access, licence , and also set the URL
3. Upload it. 
4. Ideally it should now appear under "PUBLISHED" tab when you click on the "Folder" button to the right on "PUBLISH". However it does not appear there.
5. Close LBRY. Make sure all the daemons are closed.
6. Restart LBRY. 
7. Now after loading the home page, click on "FOLDER" and select the Published tab.
8. The content appears now. 
9. Before playing it for the first time, the message "It seems you have moved this file. We are re-building it now" appears for a moment before playing. 

### Expected behaviour
The uploaded content should appear in the Published section after uploading. 

### Actual behaviour
It does not appear instantly. However, it only shows up after a restart. 

## System Configuration

daemon (lbrynet)	0.11.0rc3
wallet (lbryum)	2.7.25
interface	0.12.0rc7
Platform	Mac OS 16.0.0

**Comment by AyiSoli** [comment]
Not sure if this issue belongs in lbry or lbry-app

**Comment by tzarebczan** [comment]
Lbry app might be a better place. We try to keep lbry to daemon issues. If you aren't sure, lbry would be the default. 

This one does sound like an app issue

**Comment by AyiSoli** [comment]
[lbry-app-#227](https://github.com/lbryio/lbry-app/issues/227)
