### ISSUE TITLE
Extra characters in the OSX App [Cosmetic changes]

### ISSUE THREAD

**Issue by AyiSoli** [lbryio/lbry#685]
## The Issue

In Settings page, below "LANGUAGE" and above "SHARE DIAGNOSTIC DATA", few extra characters appear. 

### Steps to reproduce
1. Open LBRY.
2. Click on SETTINGS icon.
3. Scroll down
4. "*/}" appears .

![screen shot 2017-06-11 at 11 36 09 pm](https://user-images.githubusercontent.com/29357634/27013294-0019c8c8-4eff-11e7-8dc3-89b656d42d81.png)

daemon (lbrynet)	0.11.0rc3
wallet (lbryum)	2.7.25
interface	0.12.0rc7
Platform	Mac OS 16.0.0

**Comment by tzarebczan** [comment]
https://github.com/lbryio/lbry-app/issues/220 it will be fixed in the next version. Please mark as closed. 

Also, please be sure to check the lbry-app repo issues before posting.

**Comment by AyiSoli** [comment]
lbryio/lbry-app#220

**Linked issue, closed**
