### ISSUE TITLE
Resolving a channel should return "channel_claim_count" or similar, not number of pages

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry#691]
Run `./lbrynet-cli resolve @kauffj`. Receive:
```
"@kauffj": {
    "certificate": { ... },
    "claims_in_channel_pages": 1
}
```

Rather than give the number of pages, just give the number of items.

**Comment by hackrush01** [comment]
@kauffj

**Comment by tzarebczan** [comment]
Gonna re-open the original issue since it broke pagination: https://github.com/lbryio/lbry/pull/801#commitcomment-23706472

**Comment by kauffj** [comment]
Isn't lbry returning the correct fields? If so, there is no issue in this repo.

**Comment by tzarebczan** [comment]
I don't think it is, see: https://github.com/lbryio/lbry/pull/801#commitcomment-23706472 

lbrynet-cli claim_list_by_channel @IGNonLBRY --page 1 used to return something like this at the end:
```
],
     "claims_in_channel_pages": 2,
     "returned_page": 1
   }
```

now it just returns: 
```
     ],
     "returned_page": 1
   }
```

**Comment by lyoshenka** [comment]
Moved bug convo to https://github.com/lbryio/lbry/issues/868
