### ISSUE TITLE
The transaction_list API for lbry

### ISSUE THREAD

**Issue by liuxun1977** [lbryio/lbry#695]
I need to get the transaction record through the API, using the transaction_list command, not receiving the address, any other methods?

command:
./lbrynet-cli transaction_list

result:
[
  {
    "confirmations": 6797,
    "date": "2017-06-02 15:43",
    "label": "",
    "timestamp": 1496389394,
    "txid": "95001809afccede23ebc80df7f04d14fce96d4005e225471050201500ee2e2dd",
    "value": 14.99
  }
]

not receiving the address.

**Comment by kauffj** [comment]
Call `transaction_show` with the txid.

**Comment by liuxun1977** [comment]
./lbrynet-cli transaction_show txid=eeb23af0ff0c0d1e0ae413960ca84206e7eb225c0377f28ad9206222b53eca66
{
  "complete": true,
  "hex": "010000000187d12f8ce0cd229eec3823a97a169c3f20ba31af26d4e3975edf4f20566d4a1a010000006b483045022100cdfd7990a4d7363fc5c13d46dc83be31ccfbe53499a5a9b10e54ab5f4e41be610220652fc5e3b7bb8a4bc626efcd7db220d8fa1c99c4ee2b6a31aedac1b03a6364d9012103c9f29f0d7e0fd134c2d950e979bd545add50faf9f85ec574fe0058fd6a24f347ffffffff02c0c62d00000000001976a9140a1b7cecf1db6b3403fe0f5d97c5604e47a3cf1b88acb8ec3453000000001976a9146299198092405424aff22aaf246887f098d5136d88ac00000000"
}

How do I parse the return result？
