### ISSUE TITLE
Update download freezes when switching WiFi networks.

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry#701]
_From @sh4k4zulu on June 12, 2017 21:9_

### Steps to reproduce
1. Update LBRY w/update release.
2. Switch WiFi networks.

### Expected behaviour
It should just pick up where it left off when back in WiFi zone.

### Actual behaviour
It just freezes.

## System Configuration
This issue is I think universal. Not a priority but good for regular Joes who might one day want to use LBRY.

_Copied from original issue: lbryio/lbry-app#231_

**Comment by alyssaoc** [comment]
will watch with the new app

**Comment by kauffj** [comment]
I'm fairly confident this is still a real issue.

**Comment by tzarebczan** [comment]
We'll open an app side issue to check on the behavior. It would be part of the electron updater process for Win/Mac.
