### ISSUE TITLE
The transaction_show API for lbry

### ISSUE THREAD

**Issue by liuxun1977** [lbryio/lbry#702]
**./lbrynet-cli transaction_show** txid=eeb23af0ff0c0d1e0ae413960ca84206e7eb225c0377f28ad9206222b53eca66
{
"complete": true,
"hex": "010000000187d12f8ce0cd229eec3823a97a169c3f20ba31af26d4e3975edf4f20566d4a1a010000006b483045022100cdfd7990a4d7363fc5c13d46dc83be31ccfbe53499a5a9b10e54ab5f4e41be610220652fc5e3b7bb8a4bc626efcd7db220d8fa1c99c4ee2b6a31aedac1b03a6364d9012103c9f29f0d7e0fd134c2d950e979bd545add50faf9f85ec574fe0058fd6a24f347ffffffff02c0c62d00000000001976a9140a1b7cecf1db6b3403fe0f5d97c5604e47a3cf1b88acb8ec3453000000001976a9146299198092405424aff22aaf246887f098d5136d88ac00000000"
}

**How do I parse the return result？**

**Comment by kaykurokawa** [comment]
According to the docstring this function should be returning a parsed JSON formatted transaction, so this looks like a bug.

**Comment by liuxun1977** [comment]
I'd like to see the address in the transaction record. Is there any way?

**Comment by liuxun1977** [comment]
I'd like to see the address in the transaction record. Is there any way? @kaykurokawa

**Comment by kaykurokawa** [comment]
You can use lbrycrd's decoderawtransaction command for now

./lbrycrd-cli decoderawtransaction 

010000000187d12f8ce0cd229eec3823a97a169c3f20ba31af26d4e3975edf4f20566d4a1a010000006b483045022100cdfd7990a4d7363fc5c13d46dc83be31ccfbe53499a5a9b10e54ab5f4e41be610220652fc5e3b7bb8a4bc626efcd7db220d8fa1c99c4ee2b6a31aedac1b03a6364d9012103c9f29f0d7e0fd134c2d950e979bd545add50faf9f85ec574fe0058fd6a24f347ffffffff02c0c62d00000000001976a9140a1b7cecf1db6b3403fe0f5d97c5604e47a3cf1b88acb8ec3453000000001976a9146299198092405424aff22aaf246887f098d5136d88ac00000000
{
  "txid": "eeb23af0ff0c0d1e0ae413960ca84206e7eb225c0377f28ad9206222b53eca66",
  "size": 226,
  "version": 1,
  "locktime": 0,
  "vin": [
    {
      "txid": "1a4a6d56204fdf5e97e3d426af31ba203f9c167aa92338ec9e22cde08c2fd187",
      "vout": 1,
      "scriptSig": {
        "asm": "3045022100cdfd7990a4d7363fc5c13d46dc83be31ccfbe53499a5a9b10e54ab5f4e41be610220652fc5e3b7bb8a4bc626efcd7db220d8fa1c99c4ee2b6a31aedac1b03a6364d9[ALL] 03c9f29f0d7e0fd134c2d950e979bd545add50faf9f85ec574fe0058fd6a24f347",
        "hex": "483045022100cdfd7990a4d7363fc5c13d46dc83be31ccfbe53499a5a9b10e54ab5f4e41be610220652fc5e3b7bb8a4bc626efcd7db220d8fa1c99c4ee2b6a31aedac1b03a6364d9012103c9f29f0d7e0fd134c2d950e979bd545add50faf9f85ec574fe0058fd6a24f347"
      },
      "sequence": 4294967295
    }
  ],
  "vout": [
    {
      "value": 0.03000000,
      "n": 0,
      "scriptPubKey": {
        "asm": "OP_DUP OP_HASH160 0a1b7cecf1db6b3403fe0f5d97c5604e47a3cf1b OP_EQUALVERIFY OP_CHECKSIG",
        "hex": "76a9140a1b7cecf1db6b3403fe0f5d97c5604e47a3cf1b88ac",
        "reqSigs": 1,
        "type": "pubkeyhash",
        "addresses": [
          "bDeiP3k7Jvpt9Hd3rw3ZstoveNWuCHDAxZ"
        ]
      }
    }, 
    {
      "value": 13.95977400,
      "n": 1,
      "scriptPubKey": {
        "asm": "OP_DUP OP_HASH160 6299198092405424aff22aaf246887f098d5136d OP_EQUALVERIFY OP_CHECKSIG",
        "hex": "76a9146299198092405424aff22aaf246887f098d5136d88ac",
        "reqSigs": 1,
        "type": "pubkeyhash",
        "addresses": [
          "bMicKaUvZXwjqC6VgV1P3FUxpVM5rqHYnG"
        ]
      }
    }
  ]
}

**Comment by liuxun1977** [comment]
/ lbrycrd-cli can be called by API? @kaykurokawa

**Comment by liuxun1977** [comment]
I need to query the transaction record in the Java project. @kaykurokawa

**Comment by kaykurokawa** [comment]
You need to download lbrycrd https://github.com/lbryio/lbrycrd to use lbrycrd-cli
Another option is downloading lbryum and running the "deserialize" command in console https://github.com/lbryio/lbryum

**Comment by liuxun1977** [comment]
Do these two methods provide an API? @kaykurokawa

**Comment by kaykurokawa** [comment]
Yes they are both JSON RPC interfaces 
fixed in https://github.com/lbryio/lbryum/pull/114

**Comment by jackrobison** [comment]
fixed in https://github.com/lbryio/lbryum/pull/114
