### ISSUE TITLE
Enable wallet encryption

### ISSUE THREAD

**Issue by dskvr** [lbryio/lbry#708]
#179 was opened and then addressed some time later in #212 which was then closed because it would require refactoring. I cannot find any evidence that this is being worked on.

It's a matter of history that an unencrypted wallet is asking for trouble. Steps to using hot wallets:
- Download wallet
- Encrypt Wallet with high entropy
- Don't forget to encrypt wallet

It would be my opinion, that having a wallet where one can store LBC tokens with some level of confidence is probably one of the most important aspects of any blockchain related project. Otherwise, we're forced to rely on centralized exchanges for our security. 

*We all know how that ends.*

![88047347gy1fd0eujpr7ng20b4069npd](https://user-images.githubusercontent.com/299465/27265918-2cbb4d14-549c-11e7-9c25-27ef666758cc.gif)

Thanks for your response on #212. 
- Is there presently a bounty reward for the person responsible? 
- Can we pool the bounty to incentivize this to get done sooner? (last progress update was ~6 months ago) 
- Is there anything the community can do to help push this up on the list?

**Comment by tzarebczan** [comment]
Take a look at https://github.com/lbryio/lbry/pull/631 for most recent update. 

Adding encryption adds a layer of inconvenience to the users, which needs to be dealt with carefully so as not to disrupt the UX.

We've recommended creating a separate wallet (generated, zipped and password protected) for storing large amounts of LBC. 

We also were recently integrated to Coinomi, which should be coming to Ios and desktop soon. This is not the best solution as it doesn't allow the wallet to integrate the app, but it's a safe haven nonetheless. 

We understand your concerns, thanks for your research and suggestions. I'm sure this will become a bigger priority once the app improves functionality wise.

**Comment by dskvr** [comment]
As someone who has a day job that consists of standing between marketers who want to destroy UX and backend devs who do everything they can to make it difficult, I empathize

However, anything that deals with storing and/or transmitting cryptocurrency is essentially a bank. This argument is not much different from saying that password strength requirements are an encumbrance to conversion rates, and thus shouldn't be enforced because UX. 

UX doesn't mean anything if the entire value metric that your technologies lies upon is compromised and subsequently sinks the community as well. 

The solution seems obvious to me, as this is how it was done in the early days. Encryption is optional, users decide whether or not they want to encrypt their wallets. They either choose convenience or security, and are thus responsible for their decision. **I for one don't mind entering my password**

**Comment by tzarebczan** [comment]
I'll share your concerns with the team, in the case they don't read this. 

Coinomi with LBC is available for Android right now and from what we hear, ios and desktop projects are around the corner.

**Comment by filipnyquist** [comment]
And it's being worked on aswell :)

**Comment by kaykurokawa** [comment]
I set up a description for password interface for anyone that wants to work on this https://github.com/lbryio/lbry/pull/712

**Comment by lyoshenka** [comment]
closed by #783
