### ISSUE TITLE
-6: Insufficient funds

### ISSUE THREAD

**Issue by kimvuchannel** [lbryio/lbry#709]
Please help me
https://uphinhnhanh.com/image/LJ4vf

**Comment by tzarebczan** [comment]
Looks like you have 0 in your wallet. 

Please stop opening an issue here for your errors. Please use #help channel on slack first, and he will ask you to open a github issue if required.

**Comment by tzarebczan** [comment]
If you have a really old install, it's recommend to start with a new wallet

**Comment by tzarebczan** [comment]
Looks like our hot wallet is kicked, please give us some time to replenish.
