### ISSUE TITLE
wrong formatting for amount in resolve

### ISSUE THREAD

**Issue by nikooo777** [lbryio/lbry#713]
## The Issue
the output of the resolve method is not properly formatted/parsed when it comes to amounts.

### Steps to reproduce
1. run lbrynet-daemon
2. execute `./lbrynet-cli resolve sl-mER9f5zfk-Y`
3. observe the first certificate object

### Expected behaviour
amount should equal to 0.01 and be a string (probably)

### Actual behaviour
amount shows as 1000000

## System Configuration

```
{
  "id": null,
  "jsonrpc": "2.0",
  "result": {
    "build": "rc",
    "ip": "**************",
    "lbrynet_version": "0.13.1rc1",
    "lbryschema_version": "0.0.7",
    "lbryum_version": "2.8.2",
    "os_release": "4.4.0-79-generic",
    "os_system": "Linux",
    "platform": "Linux-4.4.0-79-generic-x86_64-with-Ubuntu-16.04-xenial",
    "processor": "x86_64",
    "python_version": "2.7.12"
  }
}
```

## Screenshots
https://scrn.storni.info/2017-06-20_02-47-08-779758431.png

**Comment by billbitt** [comment]
I got the same issue: 
`
$ curl 'http://localhost:5279/lbryapi' --data '{"method":"resolve","params":{"uri":"deer"}}'
{
  "id": null,
  "jsonrpc": "2.0",
  "result": {
    "deer": {
      "claim": {
        "address": "xxxxx",
        "amount": "0.1",
        "claim_id": "fba48bba5daef3824848d962af8d65429935c4f6",
        "claim_sequence": 1,
        "decoded_claim": true,
        "depth": 11481,
        "effective_amount": "0.1",
        "has_signature": false,
        "height": 183954,
        "hex": "080110011a8e0108011246080410011a0464656572221a64656572207075626c
69736865642076696120737065652e63682a07737065652e6368320d5075626c696320446f6d6169
6e38004a0052005a001a42080110011a304ddaf9fc823de6ed453a0abb17e6ce9bebba5adaae995c
2c3fc995433abcbdac4d1bfeffb5490c5d2f83154a2f13dc33220a696d6167652f6a706567",
        "name": "deer",
        "nout": 0,
        "supports": [],
        "txid": "92d549d2ac9dce4a6b57e1f4319b9b7ce8823865e0d499130f1795e5d4811f0
0",
        "value": {
          "claimType": "streamType",
          "stream": {
            "metadata": {
              "author": "spee.ch",
              "description": "deer published via spee.ch",
              "language": "en",
              "license": "Public Domain",
              "licenseUrl": "",
              "nsfw": false,
              "preview": "",
              "thumbnail": "",
              "title": "deer",
              "version": "_0_1_0"
            },
            "source": {
              "contentType": "image/jpeg",
              "source": "4ddaf9fc823de6ed453a0abb17e6ce9bebba5adaae995c2c3fc9954
33abcbdac4d1bfeffb5490c5d2f83154a2f13dc33",
              "sourceType": "lbry_sd_hash",
              "version": "_0_0_1"
            },
            "version": "_0_0_1"
          },
          "version": "_0_0_1"
        }
      }
    }
  }
}`

next resolve:

`
$ curl 'http://localhost:5279/lbryapi' --data '{"method":"resolve","params":{"uri":"deer#fba48bba5daef3824848d962af8d65429935c4f6"}}'
{
  "id": null,
  "jsonrpc": "2.0",
  "result": {
    "deer#fba48bba5daef3824848d962af8d65429935c4f6": {
      "claim": {
        "address": "xxxxxxxx",
        "amount": 10000000,
        "claim_id": "fba48bba5daef3824848d962af8d65429935c4f6",
        "claim_sequence": 1,
        "decoded_claim": true,
        "depth": 11481,
        "effective_amount": 10000000,
        "has_signature": false,
        "height": 183954,
        "hex": "080110011a8e0108011246080410011a0464656572221a64656572207075626c
69736865642076696120737065652e63682a07737065652e6368320d5075626c696320446f6d6169
6e38004a0052005a001a42080110011a304ddaf9fc823de6ed453a0abb17e6ce9bebba5adaae995c
2c3fc995433abcbdac4d1bfeffb5490c5d2f83154a2f13dc33220a696d6167652f6a706567",
        "name": "deer",
        "nout": 0,
        "supports": [],
        "txid": "92d549d2ac9dce4a6b57e1f4319b9b7ce8823865e0d499130f1795e5d4811f0
0",
        "valid_at_height": 183954,
        "value": {
          "claimType": "streamType",
          "stream": {
            "metadata": {
              "author": "spee.ch",
              "description": "deer published via spee.ch",
              "language": "en",
              "license": "Public Domain",
              "licenseUrl": "",
              "nsfw": false,
              "preview": "",
              "thumbnail": "",
              "title": "deer",
              "version": "_0_1_0"
            },
            "source": {
              "contentType": "image/jpeg",
              "source": "4ddaf9fc823de6ed453a0abb17e6ce9bebba5adaae995c2c3fc9954
33abcbdac4d1bfeffb5490c5d2f83154a2f13dc33",
              "sourceType": "lbry_sd_hash",
              "version": "_0_0_1"
            },
            "version": "_0_0_1"
          },
          "version": "_0_0_1"
        }
      }
    }
  }
}
`
