### ISSUE TITLE
Daemon hangs after timeout on get request

### ISSUE THREAD

**Issue by billbitt** [lbryio/lbry#716]
## The Issue
After making a 'get' request that times out, when the daemon reaches the end of the timeout it hangs without responding to the curl request.

### Steps to reproduce
1. open the daemon
2. use curl to perform a 'get' request on a url that will time out. Example: 
`$ curl 'http://localhost:5279/lbryapi' --data '{"method":"get","params":{"uri":
"fucksiacoin"}}'`
3. wait for the deamon to timeout

### Expected behaviour
I expect to receive a response from the daemon once it times out

### Actual behaviour
daemon just hangs and does not respond. (see attached screenshots)

## System Configuration

$ curl 'http://localhost:5279/lbryapi' --data '{"method":"version"}'
{
  "id": null,
  "jsonrpc": "2.0",
  "result": {
    "build": "release",
    "ip": "********",
    "lbrynet_version": "0.13.1",
    "lbryschema_version": "0.0.7",
    "lbryum_version": "2.8.4",
    "os_release": "7",
    "os_system": "Windows",
    "platform": "Windows-7-6.1.7601-SP1",
    "processor": "Intel64 Family 6 Model 61 Stepping 4, GenuineIntel",
    "python_version": "2.7.13"
  }
}

## Screenshots

![screenshot 2017-06-19 19 12 24](https://user-images.githubusercontent.com/19243959/27313625-b0f1815c-5523-11e7-964b-40d4f8b88405.png)

**Comment by billbitt** [comment]
follow up... if you do a new curl request after the hang, the result is as follows:

second curl request:
`$ curl 'http://localhost:5279/lbryapi' --data '{"method":"get","params":{"uri":
"fucksiacoin"}}'
{
  "id": null,
  "jsonrpc": "2.0",
  "result": null
}`

new output in daemon:
`2017-06-19 19:39:26,036 INFO     lbrynet.core.Wallet:809: Resolving fucksiacoin`
`2017-06-19 19:39:26,503 INFO     lbrynet.lbrynet_daemon.Daemon:1511: Already waiting on lbry://fucksiacoin to start downloading`

**Comment by kaykurokawa** [comment]
Can confirm that if get timeouts before it downloads a sd blob, the daemon will hang.

**Comment by billbitt** [comment]
same thing is happening when getting the claim for `boni#8315fa0b7a3ba2b7806a4411214b0bf5bfc31677`
