### ISSUE TITLE
Uncaught Exception ENOENT

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry#728]
Reported by user

![error](https://user-images.githubusercontent.com/362784/27454412-d5e80508-5767-11e7-854a-ed4fc3d4cfc7.jpg)

**Comment by tzarebczan** [comment]
That's the same issue we had before where the daemon is deleted by windows for some reason. We could not reproduce. It happened to me when my pc shut down on me once. 

User needs to reinstall latest version and the problem is fixed.
