### ISSUE TITLE
I generated a lot of lbry addresses

### ISSUE THREAD

**Issue by liuxun1977** [lbryio/lbry#735]
I generated a lot of lbry addresses,The wallet starts slowly and the wallet receives no trade．why?

**Comment by tzarebczan** [comment]
Please see https://github.com/lbryio/lbry/issues/437

**Comment by liuxun1977** [comment]
I need these addresses. I can't delete them

**Comment by tzarebczan** [comment]
That's the only fix we have right now. It's cumbersome because if you uploaded content, it needs to be re-uploaded and/or reclaimed. Is this your case, where you have many uploaded files?

**Comment by liuxun1977** [comment]
I don't need to upload a file. I need to assign a lbry address to each user for the filling @tzarebczan

**Comment by tzarebczan** [comment]
What is it exactly you are working through?

**Comment by liuxun1977** [comment]
A transaction LBC currency website, like https://www.poloniex.com/ @tzarebczan

**Comment by kaykurokawa** [comment]
i suggest you used lbrycrd which handles large numbers of addresses https://github.com/lbryio/lbrycrd without problems.
