### ISSUE TITLE
Error: Rejected by Network Rules (18: bad-txns-inputs-spent)

### ISSUE THREAD

**Issue by billbitt** [lbryio/lbry#737]
## The Issue
When publishing a file, the transaction is rejected and I receive the following error message `error: The transaction was rejected by network rules.(18: bad-txns-inputs-spent)`

Possible reasoning: This issue is occurring on spee.ch, which publishes many claims and updates from the same wallet address.  So far this seems to only happen on the spee.ch daemon.  I cannot reproduce locally.

troubleshooting notes:
The error still happens when I try publishing different files to different names.
The error still happens after restarting the daemon.
The error still happens when I try publishing using a different wallet address (setting `claim_address` and `change_address`).

### Steps to reproduce
1. publish  an image via spee.ch

spee.ch will make a `publish` method call to the daemon with the following `params` (in this example I am publishing `flower.jpg` to `wildflowers `):

```
{ name: 'wildflowers',
  file_path: '/home/lbry/Downloads/flower.jpg',
  bid: 0.01,
  metadata:
   { description: 'wildflowers published via spee.ch',
     title: 'wildflowers',
     author: 'spee.ch',
     language: 'en',
     license: 'Public Domain',
     nsfw: false },
  claim_address: 'bJr******',
  change_address: 'bJr******' 
}
```
2. wait for the daemon to respond with the error message.

### Expected behavior

I should receive the transaction information confirming that the transaction was successfully published.

### Actual behavior

I receive the following error:
```
{	"code":-32500,
	"data": {
		"traceback": [
			"Traceback (most recent call last):",
			" File \"site-packages/twisted/internet/defer.py\", line 1445, in unwindGenerator",
			" ",
			" File \"site-packages/twisted/internet/defer.py\", line 1299, in _inlineCallbacks",
			" ",
			" File \"site-packages/lbrynet/lbrynet_daemon/Publisher.py\", line 65, in make_claim",
			" ",
			" File \"site-packages/twisted/internet/defer.py\", line 1445, in unwindGenerator",
			" ",
			"--- ---",
			" File \"site-packages/twisted/internet/defer.py\", line 1299, in _inlineCallbacks",
			" ",
			" File \"site-packages/lbrynet/core/Wallet.py\", line 931, in claim_name",
			" ",
			"exceptions.Exception: Claim to name prettybird failed: error: The transaction was rejected by network rules.(18: bad-txns-inputs-spent)",
			"[0100000002cb92c01539f77a8bc2f1025fc01d5fd99bb530791431f7e68489bbc43dc5eeea000000006a473044022067ae3f9364bedbc5fcd09a3dcf817c71b6c3e31279ab0bf94da7e8c361c7780c02200fda5f2d156262035ebae447bf2048538c9c0b82eb6b8dbafa29ffa00fccbdc60121029295131e6b6e6bd6fc6c0b66c2ae0414106e993fa5af7b146f52afaa79336906ffffffff74eeb33ed261bfbd394c569bcf3b4b65e61292572474f3519d2c2894b7a7bcf1000000006a473044022079325f1c5d5d8bfc15ca4133e8880a807546d131ef8ce756feba4e3569eb39d302203ca8016781cf2b2bb48fa725ddb43e7a8d466e51883eb8576df7fa56626ec0380121029295131e6b6e6bd6fc6c0b66c2ae0414106e993fa5af7b146f52afaa79336906ffffffff02fc990500000000001976a914c394acf83c92429898b017dcee51a75cb9512fcf88ac40420f0000000000cab50a707265747479626972644ca1080110011a9a0108011252080410011a0a70726574747962697264222070726574747962697264207075626c69736865642076696120737065652e63682a07737065652e6368320d5075626c696320446f6d61696e38004a0052005a001a42080110011a307e35821fb1d287a21dffdd772502cc1bd411d263cc5d6a0151b7827306dad24df45dd224897d694daf70c8cf5f03cb93220a696d6167652f6a7065676d7576a914c394acf83c92429898b017dcee51a75cb9512fcf88ac00000000]",
			""
		]
	},
	"message":"Claim to name prettybird failed: error: The transaction was rejected by network rules.(18: bad-txns-inputs-spent)\n[0100000002cb92c01539f77a8bc2f1025fc01d5fd99bb530791431f7e68489bbc43dc5eeea000000006a473044022067ae3f9364bedbc5fcd09a3dcf817c71b6c3e31279ab0bf94da7e8c361c7780c02200fda5f2d156262035ebae447bf2048538c9c0b82eb6b8dbafa29ffa00fccbdc60121029295131e6b6e6bd6fc6c0b66c2ae0414106e993fa5af7b146f52afaa79336906ffffffff74eeb33ed261bfbd394c569bcf3b4b65e61292572474f3519d2c2894b7a7bcf1000000006a473044022079325f1c5d5d8bfc15ca4133e8880a807546d131ef8ce756feba4e3569eb39d302203ca8016781cf2b2bb48fa725ddb43e7a8d466e51883eb8576df7fa56626ec0380121029295131e6b6e6bd6fc6c0b66c2ae0414106e993fa5af7b146f52afaa79336906ffffffff02fc990500000000001976a914c394acf83c92429898b017dcee51a75cb9512fcf88ac40420f0000000000cab50a707265747479626972644ca1080110011a9a0108011252080410011a0a70726574747962697264222070726574747962697264207075626c69736865642076696120737065652e63682a07737065652e6368320d5075626c696320446f6d61696e38004a0052005a001a42080110011a307e35821fb1d287a21dffdd772502cc1bd411d263cc5d6a0151b7827306dad24df45dd224897d694daf70c8cf5f03cb93220a696d6167652f6a7065676d7576a914c394acf83c92429898b017dcee51a75cb9512fcf88ac00000000]"
}
```

## System Configuration

  "build": "release",
  "ip": "*****",
  "lbrynet_version": "0.13.1",
  "lbryschema_version": "0.0.7",
  "lbryum_version": "2.8.4",
  "os_release": "4.4.0-64-generic",
  "os_system": "Linux",
  "platform": "Linux-4.4.0-64-generic-x86_64-with-Ubuntu-16.04-xenial",
  "processor": "x86_64",
  "python_version": "2.7.12"

**Comment by billbitt** [comment]
This issue may be related to: https://github.com/lbryio/lbry/issues/552

**Comment by billbitt** [comment]
UPDATE: after the issue was recurring for about 12 hours, it seems to have fixed itself.  Spee.ch is now publishing without receiving the error.

**Comment by finer9** [comment]
Because the unconfirmed transactions became confirmed?

**Comment by billbitt** [comment]
@finer9 I had to delete that update because it actually looks like it isn't fixed.  I'm doing some more testing to figure out why that one publish went through when others are getting rejected.

**Comment by billbitt** [comment]
ADDITIONAL INFORMATION: 
The above error only occurs when publishing a new claim.  If spee.ch is used to publish an image to a name that it has previously published to, the deamon recognizes this and makes an update to the previous claim rather than publishing a new claim.  In this case, the daemon successfully updates the claim and returns the transaction information.

For example:  `duckling#7070914a15d09261d7a6f6989298dcd3a36e5819` is a uri for a claim previously made by spee.ch.   Therefore, using spee.ch to make a `publish` method call to the daemon with the following `params`  will result in a successful update to that claim rather than the error reported above.

`{ name: 'duckling',`
  `file_path: '/home/lbry/Downloads/duckling.jpeg',`
  `bid: 0.01,`
  `metadata:`
   `{ description: 'duckling published via spee.ch',`
     `title: 'duckling',`
     `author: 'spee.ch',`
     `language: 'en',`
     `license: 'Public Domain',`
     `nsfw: false },`
  `claim_address: 'bJr************************',`
  `change_address: 'bJr************************' }`

**Comment by billbitt** [comment]
@tzarebczan I was able to circumvent/fix the issue by removing my wallet and creating a new one.

**Comment by kauffj** [comment]
I labeled this P2 since it seemed like it wasn't blocking @billbitt. If this is affecting more typical usage, this should be P1.

**Comment by billbitt** [comment]
@kauffj correct no longer blocking.  I will re-raise the issue if I see it again.  Still a long term issue for use cases like Speech (and I imagine the Berkely videos), but agreed not urgent.

**Comment by billbitt** [comment]
@kauffj ...and just on cue after it not appearing for the last day it came back.  Multiple users in slack are reporting the same error when trying to publish just now.  According to the data, the first publish that failed had an error of `error: transaction already in block chain` which might have created the bug for the rest of them.  See screenshot below.

![screenshot 2017-06-30 11 58 11](https://user-images.githubusercontent.com/19243959/27750169-849b113e-5d8b-11e7-82ac-d08fdaa628c2.png)

**Comment by lyoshenka** [comment]
related to #747

**Comment by jackrobison** [comment]
The vin for the rejected tx `eaeec53dc4bb8984e6f731147930b59bd95f1dc05f02f1c28b7af73915c092cb:0` was to the address `bWZQZoaLcfu4CAriT4JhhnBSyh4YtjqrJL`, which is one of the addresses affected by https://github.com/lbryio/lbryum-server/issues/36
