### ISSUE TITLE
First Publish Claim Error

### ISSUE THREAD

**Issue by kimvuchannel** [lbryio/lbry#738]
i have error
http://sv1.upsieutoc.com/2017/06/29/haizzz.jpg
but i don't receive 10 credit :( my account only max 28 credit. Help me

**Comment by tzarebczan** [comment]
Before posting issues in Github, please check with us on Slack (slack.lbry.io) so we can help you figure it out. I am closing this for now, please see below and let us know on Slack if you have any other issues. 

It sounds like you may have claimed some LBC for your channel or published item. To get this back, you need to follow:
https://www.youtube.com/watch?v=l1eqoE9xNsg

API for reference: https://lbryio.github.io/lbry/

Windows users: If you are using CURL, you need to properly escape quotes - here: curl "http://localhost:5279/lbryapi" --data "{\"method\":\"get\",\"params\":{\"uri\":\"what\"} }"  

Or via PowerShell: Invoke-RestMethod -Uri 'http://localhost:5279/lbryapi' -Body '{"method":"resolve","params":{"uri":"what"}}' -Method POST | ConvertTo-Json

Above are just examples, you need to follow the video with correct API calls.
