### ISSUE TITLE
Feature request: Need a way to report NSFW content

### ISSUE THREAD

**Issue by fcbrandon** [lbryio/lbry#740]
Found a video that is NSFW, but is not marked so, and there is no way in the UX to report is as NSFW - current reporting only allows for rights infringement.

Video in question -> lbry://@oscopelabs/thelovewitch-trailer.

I currently don't have the NSFW box checked, but this is the only thing I see, so I'm just guessing it isn't marked as such.

It's not super NSFW, but borderline PG-13/R for almost nudity :D

- LBRY App version: 0.13.0
- Operating system: Windows 10

**Comment by tzarebczan** [comment]
Right now, NSFW flag is control by the person publishing the file. No one but the uploader can change this setting for that particular claim. 

On the 6/22 call, something similar to this was discussed, but the question is how to do it correctly in a decentralized way.

**Comment by fcbrandon** [comment]
What about the mechanism that's used to blacklist content that infringes copyright? Seems like that could be used as well.

**Comment by tzarebczan** [comment]
Right now that has to be done manually (with human intervention) via the report process. Also not a trial task to do in a decentralized way via app.

**Comment by kauffj** [comment]
The real solution to this is [community tagging](https://github.com/lbryio/lbry/issues/744).

I'd like to avoid an interim solution, but if we do it would be centralized and a lbry-app based solution.
