### ISSUE TITLE
Community Tagging

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry#744]
Supporting tagging (or categories) is fairly straightforward if we allow the publisher full control, but the ideal solution for tagging is one that allows community consensus. That is, there is some sort of consensus or voting mechanism that does not give the publisher full control over the tags applied to their content.

Community-based tagging would also solve issues surrounding adult content being improperly indicated.

**Comment by wallermadev** [comment]
I like the idea of everyone OTHER than the publisher applying tags.

**Comment by kauffj** [comment]
@wallermadev they're pretty much equivalent in terms of functionality -- the system wouldn't be able to prevent the author from applying tags in any meaningful way.

**Comment by wallermadev** [comment]
is_claim_mine.

I realized after my first comment that I need the ability to tag a file
with ue4-asset

**Comment by jsigwart** [comment]
As a publisher, I want to be able to add relevant tags to my video for better results in search engines. I'm worried about others gaming the system. Like a competitor getting a bunch of folks to down vote relevant tags and up vote irrelevant ones.

**Comment by btzr-io** [comment]
See: https://github.com/lbryio/lighthouse/issues/49#issuecomment-375987417

**Comment by alyssaoc** [comment]
this is currently part of proposals
