### ISSUE TITLE
resolve API call should indicate claim type

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry#745]
Content and channel claims have different signatures, but a claim entry does not contain a first-class field specifying the claim type. For example, if I resolve by claim ID, I have to make inferences based on the data structure to determine what type of claim I have.

Instead, we should set a `type` or `claim_type` property when returning claim data.

**Comment by tzarebczan** [comment]
@kauffj will add more information, along with an example.

**Comment by kauffj** [comment]
I'm wrong about this, we have `value.claimType` already in the claim info.
