### ISSUE TITLE
Cannot update claims larger than wallet balance

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry#748]
Originally lbry-app [#117](https://github.com/lbryio/lbry-app/issues/117)

**Comment by tzarebczan** [comment]
An option for the user during claim update would make sense if it's technically possible.

**Comment by kauffj** [comment]
An option would exist at the app/UI level, not the API level.

**Comment by tzarebczan** [comment]
This is a pretty big UX issue at the moment, maybe we can bump the priority @kauffj 

We would need @kaykurokawa 's fixes from #747 which would allow the daemon to realize that it can use the original deposit amount during an update. So really only any difference in LBC (in case they are increasing the bid) needs to be in your balance (plus tx fees obviously).

**Comment by tzarebczan** [comment]
@lyoshenka anyway we can bump this up the queue? Sounds like it would need some lbryum changes too.

**Comment by hackrush01** [comment]
I am assigning it to myself currently, as I think I can solve it.

**Comment by tzarebczan** [comment]
Thanks @hackrush01 . This might be related, or at least part of the same code, please keep it in mind: https://github.com/lbryio/lbry/issues/855
