### ISSUE TITLE
Fix running of integration tests on appveyor Windows build

### ISSUE THREAD

**Issue by kaykurokawa** [lbryio/lbry#752]
Integration tests in tests/integration folder fails (lbrynet does not seem to startup) on appveyor which does the Windows build.

**Comment by alyssaoc** [comment]
@eukreign @nikooo777 Can you make sure these work as expected on the new CI solution?

**Comment by eukreign** [comment]
This is actually referring to integration tests that were deleted (since the ticket is old), the new stuff will have this working. I don't think we need a separate issue for this, #1298 will address this.
