### ISSUE TITLE
Stuck on "Requesting stream"

### ISSUE THREAD

**Issue by rubenbryon** [lbryio/lbry#758]
## The Issue
When opening any video on the latest LBRY 0.13, I get stuck on "requesting stream... it may sit here....". I have not tried earlier versions.

### Steps to reproduce
1. Open LBRY application
2. Click video
3. Keeps showing "requesting stream"

### Expected behaviour
I would expect the video to start playing after several seconds. Even waiting for 30 minutes makes no difference.

### Actual behaviour
The application stays responsive but the video won't load. Download doesn't work either.

## System Configuration
daemon (lbrynet)	0.13.1
wallet (lbryum)	2.8.4
interface	0.13.0
Platform	Windows (Windows-8.1-6.3.9600)
Installation ID	3KBpKGuNJrjEKKVipsHJLcNFLay18jX81Nd2ScpUGVUvejkv7RhNPsCENHtNAQ3ie

## Anything Else
-I have a recent router that has uPnP
-I tried manually forwarding port 3333 & 4444 and checked online if they were actually open
-Both lbry and lbry-daemon are allowed in the firewall
-I tried running the application as administrator
-I have tried on another device on my network with a different account that has early access
-I have tried connecting via 4g usb tethering and confirmed that I was using a different network
-Attatched is my lbrynet.log:
[lbrynet.zip](https://github.com/lbryio/lbry/files/1121532/lbrynet.zip)

## Screenshots
![capture](https://user-images.githubusercontent.com/9782903/27823513-ab689478-60a9-11e7-9f86-ecda0d8c7788.PNG)

**Comment by zestyr** [comment]
To anyone looking at this, the relevant parts of the log looks like this:
```log
lbrynet.lbrynet_daemon.Daemon:2523: Need sd blob
lbrynet.core.client.ConnectionManager:38: Connection Manager 
8abb1d449ecbae5e7df22690281906972722f17b616bbc7130de5a02ccc135f76f629e96c3034a7c8d89ee6f351e648f initialized
lbrynet.lbrynet_daemon.Downloader:104: Download lbry://linked-ep5 status changed to initializing
lbrynet.lbrynet_daemon.Downloader:97: Downloading stream descriptor blob (1 seconds)
lbrynet.lbrynet_daemon.Downloader:104: Download lbry://linked-ep5 status changed to 
downloading_metadata
lbrynet.core.client.ConnectionManager:38: Connection Manager 
8abb1d449ecbae5e7df22690281906972722f17b616bbc7130de5a02ccc135f76f629e96c3034a7c8d89ee6f351e648f initialized
lbrynet.lbrynet_daemon.Downloader:97: Downloading stream descriptor blob (2 seconds)
lbrynet.lbrynet_daemon.Downloader:97: Downloading stream descriptor blob (3 seconds)
lbrynet.lbrynet_daemon.Daemon:2532: Blob (8abb1d449ecbae5e7df2) download timed out
lbrynet.lbrynet_daemon.Downloader:97: Downloading stream descriptor blob (4 seconds)
lbrynet.lbrynet_daemon.Downloader:97: Downloading stream descriptor blob (5 seconds)
lbrynet.lbrynet_daemon.Downloader:97: Downloading stream descriptor blob (6 seconds)
lbrynet.lbrynet_daemon.Downloader:97: Downloading stream descriptor blob (7 seconds)
lbrynet.lbrynet_daemon.Downloader:97: Downloading stream descriptor blob (8 seconds)
lbrynet.lbrynet_daemon.Downloader:97: Downloading stream descriptor blob (9 seconds)
```
After timing out, it just keeps counting up. In the log he tries a few times, and in one of them it times out, waits a bit, and tries to download another blob which also times out.

**Comment by tzarebczan** [comment]
Is there anything else using up port 3333 in port forwarding or upnp? Is it possible for you to connect directly to modem and try (I know you tried 4g)?

**Comment by rubenbryon** [comment]
I have to disconnect my mining operation in order to connect straight to modem so that's not an option. None of my network devices are using 3333 as far as I know but I'm not sure how I can make sure. (I checked all devices via netstat -a)

When i check netstat -a on the device that is trying to stream a video this appears in the list:
![capture](https://user-images.githubusercontent.com/9782903/27832156-f293e6f8-60cd-11e7-890c-b1ba2fd7e4b9.PNG)

**Comment by tzarebczan** [comment]
We'll keep looking into it, right now I don't have any suggestions except to double check upnp settings and port forwarding to make sure no other IP because the lbry pc is getting 3333.

**Comment by rubenbryon** [comment]
Ok, thanks! I'll keep trying and post if I can figure it out.

**Comment by nicknitewolf** [comment]
I have this issue too with all previous versions (starting from lbry app 0.8 when I first installed lbry) and current version of the lbry app (0.13.0) daemon (0.13.1) and wallet (2.84).

My OS is however Linux Ubuntu 17.04 "zesty" running the kernel version 4.12 (mainline) and hence this is not an OS dependent issue.

Furthermore, through the help of some help of certain LBRY mods on Slack, I have already opened up port 3333 and port 4444 on both TCP and UDP protocols. I have even tried disabling my custom port forwarding and tried UPNP based on one of the mods suggestions.

The logs seem standard and give little to know issue like the original log above so I don't think posting my similar looking log would help that much anyways.

In an event that this happens, after timing out, the daemon will still continue to try to download the Stream descriptor blob continuously to no end. Like a loopback.

**Comment by 98farhan94** [comment]
<img width="553" alt="screen shot 2017-07-10 at 2 21 12 am" src="https://user-images.githubusercontent.com/5463117/27997528-34cc94e6-6517-11e7-9dfc-2b358c09dc20.png">

Same issue. Downloads the blobs to eternity after the initial timeout.

**Comment by rubenbryon** [comment]
Without changing anything, it suddenly appears to work for the first time.

[lbrynet - log.zip](https://github.com/lbryio/lbry/files/1139760/lbrynet.-.log.zip)

**Comment by tzarebczan** [comment]
@rubenbryon - are you sure nothing changed in your network or pc settings?

**Comment by rubenbryon** [comment]
yes, and I haven't gotten it to work anymore since.

**Comment by kauffj** [comment]
@tzarebczan please re-open if you can work with @rubenbryon to get this issue into a workable state.

**Comment by tzarebczan** [comment]
@rubenbryon - I noticed that in the time it worked, upnp had failed (7-11 19:33:36,197 WARNING  lbrynet.core.Session:243: UPnP failed. Reason: UnknownError) - which is even more strange.  Do you know anything on your end that would have caused this to happen? Can you try disabling UPNP and not forward 3333 - try like this first, and then try forwarding it.

**Comment by fasternnet** [comment]
I trying with using port 3333 
Success:  I can see your service on 197.246.242.176 on port (3333)
Your ISP is not blocking port 3333 ..
but same problem then I tried to make UPNP disable but still not working !

**Comment by olokos** [comment]
Exact same issue here and another relevent issue is closed, this really makes me wanna sell all my LBRY coins and just give up.

**Comment by tzarebczan** [comment]
We have thousands of users, but only a handful are reporting download issues. It's likely tied to some local network, port or firewall issues . 

We will be working on a troubleshooting guide which will show all ports to check in order to ensure a good connection to lbrynet. Typically you want to check 3333 (tcp)  4444 (UDP) 50001 5279 (local ports) 

Sorry for your trouble, we will continue to work with you. What is the video you are trying to stream?

Also, let's please keep price/market talk away from github...not the correct forum.

**Comment by olokos** [comment]
I picked the craziest, most twisted video on the main page just to see if even so weird content is available.
lbry://six
Couldn't care less about the video itself, but I was quite sure there'll be problems if I try to open that and I wasn't wrong.

**Comment by tzarebczan** [comment]
@olokos Can you try six or seven again today? I updated them with my uploads. Were you able to stream any other videos on the home page?

**Comment by olokos** [comment]
Those uploads look much better now, lol.

https://pastebin.com/btYuurCb

Seems to get stuck on 51%, could be due to me mining LBRY atm, but it shouldn't matter too much.

**Comment by tzarebczan** [comment]
I reached out to you on Slack :)

**Comment by tzarebczan** [comment]
For those who had issues downloading ANY file from LBRY, I may have figured it out. It's most likely related to the DHT port which is used to share the content. Possibly something else is using it on 4444 or its blocked on your ISP.

Give this a try:
Download this daemon_settings.yml file: https://www.dropbox.com/s/tkqelvkvwqw237k/daemon_settings.yml?dl=0

Steps - 
1 - Close LBRY
2 - Copy daemon_settings.yml to lbrynet folder (find the folder: https://lbry.io/faq/lbry-directories)
*If you already have a daemon_settings.yml file here, open it with notepad, add a new line at the end and type:
dht_node_port: 44444
3 - Start LBRY
4 - Try downloading the top left video, be patient. If it fails, go to home, and try again.

Depending on your network, you may need port 44444 UDP (the new port that was just setup) forwarded. Also, for file sharing to work properly, you may need port 3333 (TCP) open/forwarded (check canyouseeme.org for 3333. 44444 will fail since its UDP). Also, you may need to check firewall settings.

**Comment by kauffj** [comment]
@jackrobison can we add a startup check for this?

**Comment by rubenbryon** [comment]
It seems to be resolved on my end without changing anything. I am often switching between pools and algorithms so it might have been related to other services using ports 3333 or 4444.
