### ISSUE TITLE
Add updating API documentation to build process

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry#762]
[lbry.io/api](https://lbry.io/api) is currently manually updated and regularly forgotten during the release process.

**Comment by lyoshenka** [comment]
talked to @zestyr about this. he wants to tackle it after he's done with the api testing he's doing now

**Comment by kauffj** [comment]
@zestyr still want to tackle this?

**Comment by lyoshenka** [comment]
At the very least we can have builds fail when the API docs are out of date. Have travis run the api  build script and error if there are any changes.

**Comment by zestyr** [comment]
Sure, didn't @jackrobison add this to the release tool though?
