### ISSUE TITLE
Getting charged for free data

### ISSUE THREAD

**Issue by 98farhan94** [lbryio/lbry#764]
## The Issue
I am getting charged for data while viewing free items.

### Steps to reproduce
1. Install LBRY, browse content, maybe watch a video.
2. ???
3. See LBC flowing out of your account in transaction history.

### Expected behaviour
I believe I should not be charged for browsing data, I was told it would be free unless I am opening paid content.

### Actual behaviour
I am charged.

## System Configuration

Version 0.13.0 (0.13.0.1389)

    "build": "release",
    "lbrynet_version": "0.13.1",
    "lbryschema_version": "0.0.7",
    "lbryum_version": "2.8.4",
    "os_release": "16.6.0",
    "os_system": "Darwin",
    "platform": "Darwin-16.6.0-x86_64-i386-64bit",
    "processor": "i386",
    "python_version": "2.7.13"

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system: macOS Sierra 10.12.5

## Anything Else

    {
      "confirmations": 102,
      "date": "2017-07-07 05:30",
      "label": "",
      "timestamp": 1499385629,
      "txid": "104b3972fc8d431a66157a7c215d5c8e26fd0945857b9e813fdcc93fa080ea09",
      "value": -0.00017016
    },
    {
      "confirmations": 91,
      "date": "2017-07-07 05:57",
      "label": "",
      "timestamp": 1499387263,
      "txid": "ca3f1f085f52eb31243a7b3fbe31e481b6028fc5cbb56e0c9ee273ad41f49a58",
      "value": -0.000257
    },
    {
      "confirmations": 20,
      "date": "2017-07-07 09:10",
      "label": "",
      "timestamp": 1499398854,
      "txid": "8ef8895ad2a38aee5fb22395a1a0b335cd78ac73c7bc3d6b22b16c51ac199479",
      "value": -0.000178
    }

**Comment by tzarebczan** [comment]
Do you know which videos you clicked on? Can you send your lbrynet.log file from the lbry folder (might be hidden) https://lbry.io/faq/lbry-directories

**Comment by 98farhan94** [comment]
Changed it to TXT to attach here...
[lbrynet.txt](https://github.com/lbryio/lbry/files/1130080/lbrynet.txt)

**Comment by tzarebczan** [comment]
I don't see anything in the log about paying for downloads. I see you published some files? When this happens, there is a small transaction fee... So maybe those are the charges? 

Please confirm and close.

**Comment by 98farhan94** [comment]
@tzarebczan Yes I did publish some files! I wasn't aware it costs, thanks for clarifying.
