### ISSUE TITLE
blank .lbrynet folder created in Users directory

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#767]
## The Issue
Minor and doesn't affect anything, but a blank .lbrynet folder is created in users directory i.e. C:\Users\Tom-LaptopVM\.lbrynet 

### Steps to reproduce
1. Install LBRY
2. Go to user folder
3. see blank .lbrynet folder

### Expected behaviour
folder should not be created

### Actual behaviour
blank folder is created

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by zestyr** [comment]
Seems like it didn't recognize the OS properly. `~/.lbrynet` would expand to `C:\Users\Tom-LaptopVM\.lbrynet` on Windows. Can you post the version info?

**Comment by tzarebczan** [comment]
I'm on 0.13 right now, but this happened on all my installs over the last couple of months. It's not a big deal, but more of an annoyance.

**Comment by kaykurokawa** [comment]
should be fixed https://github.com/lbryio/lbry/pull/755, 
due to the scattered mkdir that should be in conf
