### ISSUE TITLE
Allow abandoning of publishes even if it loses LBC

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry#768]
_From @98farhan94 on July 9, 2017 22:15_

 

## The Issue
When a claim is created with a fractional LBC low enough to be lower than the Tx fee, you cannot abandon the claim.

### Steps to reproduce
1. Create a claim with 0.00001 LBC amount allotted to it.
2. Publish.
3. Try to abandon claim.

### Expected behaviour
Claim should abandon.

### Actual behaviour
"Cannot abandon claim because Tx fee is higher than claim amount."

## System Configuration

 

    "build": "release",
    "lbrynet_version": "0.13.1",
    "lbryschema_version": "0.0.7",
    "lbryum_version": "2.8.4",
    "os_release": "16.6.0",
    "os_system": "Darwin",
    "platform": "Darwin-16.6.0-x86_64-i386-64bit",
    "processor": "i386",

## Screenshots

Claim Details:
<img width="406" alt="screen shot 2017-07-10 at 3 43 41 am" src="https://user-images.githubusercontent.com/5463117/27998035-1b373b48-6522-11e7-88c0-38fa5e5bb658.png">

Claim Abandon Attempt:
<img width="577" alt="screen shot 2017-07-10 at 3 44 02 am" src="https://user-images.githubusercontent.com/5463117/27998037-268409ea-6522-11e7-8a6e-fa02e2576e66.png">

Error in Log File:
<img width="562" alt="screen shot 2017-07-10 at 3 44 10 am" src="https://user-images.githubusercontent.com/5463117/27998038-30a919a6-6522-11e7-8638-37ee4f1f8d72.png">

_Copied from original issue: lbryio/lbry-app#343_

**Comment by kaykurokawa** [comment]
This is intentional. The logic is that since you pay more in tx fee than you get back, your net gain is zero, so why bother to abandon. 
 
I could see the argument for this being removed though, and downgraded to a warning or something like that.

**Comment by kauffj** [comment]
Abandoning is the analog of unpublishing, so IMO it should be allowed even if it had a positive cost.

**Comment by tzarebczan** [comment]
@kaykurokawa that's what I originally thought as well, but Jeremy has a point. Can the tx fees be taken from another transaction, or they have to come from that one?  One would still need to have a wallet balance high enough to abandon right?

**Comment by tzarebczan** [comment]
The minimum amount is actually 0.000097. as 0.000096 fails with the below. 0.000096 is the tx fee for publishing. 
`2017-08-03 14:20:33,407 ERROR    lbryum:115: adding signature for ff0488b21e000000000000000000b1c759c39f4f70eb4c99e91b5e48d1a1228ea20ec62d0b489f0141d8ba624184030a956c8d0aac626372ed6e26ac48bde116ba7bb1f7e030c895561f862f3f608f00005806

2017-08-03 14:20:33,888 ERROR    lbryum:115: is_complete True

2017-08-03 14:20:34,164 WARNING  lbrynet.daemon.Daemon:1882: Abandon of 182c6ef1e2c5d22c06eebe9f87baa63e37ed441f failed: error: The transaction was rejected by network rules.(64: dust)
[0100000001101a35dbc7c60426bdd20b1863d6eeec23db81ae446e9ba8386c06284f639279000000006a47304402205ed94327a0c35e423f72379e29c2cc9729e7ec2f2acf737271172a7550f9758e022030c0c71b2eefba31e85772a7f7c4f4e94d774fa89584f0ea60f0153c7471ad15012103be327adddbf705c863115dfaad45f3dceab48bccf58406b74a33595695867d0affffffff0100000000000000001976a9144714cf0284d8f2aea1f05cfa55e783493667dd5c88ac00000000]`

**Comment by btzr-io** [comment]
I think a prompt / modal would be annoying :upside_down_face:

**Comment by btzr-io** [comment]
![minimum](https://user-images.githubusercontent.com/14793624/28996917-97b629e6-79c6-11e7-81d0-6133ccb0dc3f.gif)

**Comment by MSFTserver** [comment]
app now only allows a minimum of .01 lbc deposit upon publishing it doesnt tell me i need to put a higher deposit just highlights the div

**Comment by tzarebczan** [comment]
@kaykurokawa  / @jackrobison  - do you think we should allow users to abandon claims by using inputs from another UTXO?

**Comment by eukreign** [comment]
Done in lbryio/lbryum#198

**Comment by tzarebczan** [comment]
I'm going to re-open this since I've run into a possible edge case. The claim in question is found in the tx here: https://explorer.lbry.io/tx/7992634f28066c38a89b6e44ae81db23eceed663180bd2bd2604c6c7db351a10

```
c:\Program Files (x86)\LBRY\resources\static\daemon>lbrynet-cli claim_abandon --claim_id=182c6ef1e2c5d22c06eebe9f87baa63e37ed441f
ERROR: Abandon of 182c6ef1e2c5d22c06eebe9f87baa63e37ed441f/None:None failed: error: The transaction was rejected by network rules.(64: dust)
[0100000001101a35dbc7c60426bdd20b1863d6eeec23db81ae446e9ba8386c06284f639279000000006b483045022100dc3fc3d565ef852e94d05f69b852c1d36b1079603a5f42aaff2cae49a08495a402205530fe6170096e7d33ab6e44d88836824bebe787e0780b52c6d0eec3b6de9bef012103be327adddbf705c863115dfaad45f3dceab48bccf58406b74a33595695867d0affffffff0100000000000000001976a91481a05dc24d35355bc880ed9998e1cc57e191bca088ac00000000]
```
Claim info:
```
c:\Program Files (x86)\LBRY\resources\static\daemon>lbrynet-cli claim_show --claim_id=182c6ef1e2c5d22c06eebe9f87baa63e37ed441f
{
  "address": "bTehgxDZBJfPncRTKsrjQcfVVk5EB97juR",
  "amount": 9.6e-05,
  "claim_id": "182c6ef1e2c5d22c06eebe9f87baa63e37ed441f",
  "claim_sequence": 1,
  "decoded_claim": true,
  "depth": 107806,
  "effective_amount": 9.6e-05,
  "has_signature": false,
  "height": 217544,
  "hex": "080110011a6008011218080410011a047465737422002a00320038004a0052005a001a42080110011a30f080387db984215c5c8f8491212b650dd440d773745c2c5f65056732ba4cf89dfc59154e235fc56b864152bd2ada57a8220a696d6167652f6a706567",
  "name": "internalerror",
  "nout": 0,
  "permanent_url": "internalerror#182c6ef1e2c5d22c06eebe9f87baa63e37ed441f",
  "supports": [],
  "txid": "7992634f28066c38a89b6e44ae81db23eceed663180bd2bd2604c6c7db351a10",
  "valid_at_height": 217544,
  "value": {
    "claimType": "streamType",
    "stream": {
      "metadata": {
        "author": "",
        "description": "",
        "language": "en",
        "license": "",
        "licenseUrl": "",
        "nsfw": false,
        "preview": "",
        "thumbnail": "",
        "title": "test",
        "version": "_0_1_0"
      },
      "source": {
        "contentType": "image/jpeg",
        "source": "f080387db984215c5c8f8491212b650dd440d773745c2c5f65056732ba4cf89dfc59154e235fc56b864152bd2ada57a8",
        "sourceType": "lbry_sd_hash",
        "version": "_0_0_1"
      },
      "version": "_0_0_1"
    },
    "version": "_0_0_1"
  }
}
```
I was able to abandon this: https://explorer.lbry.io/tx/3568224321ecda70349e81aa4a5daca9b0d102b70eacc66860ee13e7c364b4ff which had even a lower LBC

**Comment by jackrobison** [comment]
@eukreign decoding the failing raw transaction shows that it is indeed dust:

```{
  "txid": "6a78ecf9cc7ed8ce700075ebc0f6598aec0e3d969703c5d8ec3dbc6d115fb2fc",
  "size": 192,
  "version": 1,
  "locktime": 0,
  "vin": [
    {
      "txid": "7992634f28066c38a89b6e44ae81db23eceed663180bd2bd2604c6c7db351a10",
      "vout": 0,
      "scriptSig": {
        "asm": "3045022100dc3fc3d565ef852e94d05f69b852c1d36b1079603a5f42aaff2cae49a08495a402205530fe6170096e7d33ab6e44d88836824bebe787e0780b52c6d0eec3b6de9bef[ALL] 03be327adddbf705c863115dfaad45f3dceab48bccf58406b74a33595695867d0a",
        "hex": "483045022100dc3fc3d565ef852e94d05f69b852c1d36b1079603a5f42aaff2cae49a08495a402205530fe6170096e7d33ab6e44d88836824bebe787e0780b52c6d0eec3b6de9bef012103be327adddbf705c863115dfaad45f3dceab48bccf58406b74a33595695867d0a"
      },
      "sequence": 4294967295
    }
  ],
  "vout": [
    {
      "value": 0.00000000,
      "n": 0,
      "scriptPubKey": {
        "asm": "OP_DUP OP_HASH160 81a05dc24d35355bc880ed9998e1cc57e191bca0 OP_EQUALVERIFY OP_CHECKSIG",
        "hex": "76a91481a05dc24d35355bc880ed9998e1cc57e191bca088ac",
        "reqSigs": 1,
        "type": "pubkeyhash",
        "addresses": [
          "bQYfyRFjJ1xwx3qqtdb9htdHuv45KE8dAT"
        ]
      }
    }
  ]
}
```

**Comment by alyssaoc** [comment]
@eukreign Please see findings https://github.com/lbryio/lbrycrd/issues/98#issuecomment-374082302
and determine path forward

**Comment by eukreign** [comment]
This is fixed in new wallet, here is the relevant unit tests that allows spending a UTXO where it costs more to spend it than you get from spending it:
https://github.com/lbryio/torba/blob/f5515e5e77c599a86817d5b34384b7e4670ee27f/tests/unit/test_transaction.py#L277-L285

**Comment by tzarebczan** [comment]
@eukreign we still had an edge case with https://github.com/lbryio/lbry/issues/768#issuecomment-367110131 - can you try that exact amount (9.6e-05)? Maybe we should just open this on lbrycrd?

**Comment by eukreign** [comment]
@tzarebczan jack posted the deserialized version of the transaction you were trying to send, it has just the one input and an output, both very low (0). in the unit tests I linked to, an additional input is added and thus there is substantial change as well, this should allow the TX to pass through the dust detector. if it still doesn't then there is nothing we can do on the wallet side to make it work, it would be up to lbrycrd to not kick it out.
