### ISSUE TITLE
lbrycrd-cli Info still says "BTC" 

### ISSUE THREAD

**Issue by theunrealtok** [lbryio/lbry#77]
error message:
getwalletinfo
Returns an object containing various wallet state info.

Result:
{
  "walletversion": xxxxx,     (numeric) the wallet version
  "balance": xxxxxxx,         (numeric) the total confirmed balance of the wallet in BTC
  "unconfirmed_balance": xxx, (numeric) the total unconfirmed balance of the wallet in BTC
  "immature_balance": xxxxxx, (numeric) the total immature balance of the wallet in BTC
  "txcount": xxxxxxx,         (numeric) the total number of transactions in the wallet
  "keypoololdest": xxxxxx,    (numeric) the timestamp (seconds since GMT epoch) of the oldest pre-generated key in the key pool
  "keypoolsize": xxxx,        (numeric) how many new keys are pre-generated
  "unlocked_until": ttt,      (numeric) the timestamp in seconds since epoch (midnight Jan 1 1970 GMT) that the wallet is unlocked for transfers, or 0 if the wallet is locked
  "paytxfee": x.xxxx,         (numeric) the transaction fee configuration, set in BTC/kB
}

**Comment by kaykurokawa** [comment]
I'm closing this and moving it to https://github.com/lbryio/lbrycrd/issues
