### ISSUE TITLE
Lbryum does not share config settings promised by lbrynet

### ISSUE THREAD

**Issue by filipnyquist** [lbryio/lbry#770]
While looking at the config file: https://github.com/lbryio/lbry/blob/master/lbrynet/conf.py#L162 it says that these settings can be changed.

Sadly the lbryum part does not get these configs: https://github.com/lbryio/lbry/blob/master/lbrynet/conf.py#L162.

This means that it´s not possible to change the "lbryum_wallet_dir" settings from ENV.

**Comment by lyoshenka** [comment]
related to #1056

**Comment by alyssaoc** [comment]
does not apply with the new wallet, closing
