### ISSUE TITLE
Abandoning a channel claim with publishes breaks wallets

### ISSUE THREAD

**Issue by 98farhan94** [lbryio/lbry#771]
## The Issue
Cannot view/publish claims related to my account. Any attempt to work with claims results in an exception.

### Steps to reproduce
1. Create an identity.
2. Publish something with that identity.
3. claim_abandon the identity.

### Expected behaviour
Identity should be abandoned and claims transferred to anonymous, or the user should be warned that identity cannot be deleted since it has claims attached to it.

### Actual behaviour
Identity gets abandoned, orphaning the claims that were a part of the identity leading to claim exception error.

## System Configuration

 

"build": "release",
    "lbrynet_version": "0.13.1",
    "lbryschema_version": "0.0.7",
    "lbryum_version": "2.8.4",
    "os_release": "16.6.0",
    "os_system": "Darwin",
    "platform": "Darwin-16.6.0-x86_64-i386-64bit",
    "processor": "i386",
    "python_version": "2.7.13"

## Anything Else

Log entry:
> 2017-07-10 04:03:56,014 ERROR    lbrynet.lbrynet_daemon.auth.server:346: Failed to process claim_list_mine: Certificate claim 6a0eac1b916754ae295227dcffa4c889c1120eff not found

## Screenshots

<img width="472" alt="screen shot 2017-07-10 at 6 37 21 am" src="https://user-images.githubusercontent.com/5463117/28043364-3102c8ca-65ef-11e7-8e6d-eafb31af3c48.png">
<img width="516" alt="screen shot 2017-07-10 at 6 45 36 am" src="https://user-images.githubusercontent.com/5463117/28043369-36dfe426-65ef-11e7-9c40-47c774a8cb0e.png">
<img width="686" alt="screen shot 2017-07-10 at 6 47 28 am" src="https://user-images.githubusercontent.com/5463117/28043372-3cc27e9e-65ef-11e7-9a5c-19a1664fb1f3.png">
<img width="581" alt="screen shot 2017-07-10 at 4 04 40 am" src="https://user-images.githubusercontent.com/5463117/28043400-5541b200-65ef-11e7-9d0b-1f036ae3bb7c.png">

**Comment by tzarebczan** [comment]
@lyoshenka recommend that this is added to next sprint if possible.

**Comment by kauffj** [comment]
@14bd4bed had this happen to him as well, and he said it prevented interaction from the wallet completely afterwards.

**Comment by 98farhan94** [comment]
In my case, I am able to send/receive LBC but cannot publish new claims/see existing claims/do anything claim-related.

**Comment by codingisforyou** [comment]
I have this same issue also... after using the API to publish and release claims.

{
    "error": {
        "code": -32500,
        "data": {
            "traceback": [
                "Traceback (most recent call last):",
                "  File \"site-packages\\twisted\\web\\server.py\", line 190, in process",
                "    ",
                "  File \"site-packages\\twisted\\web\\server.py\", line 241, in render",
                "    ",
                "  File \"site-packages\\lbrynet\\daemon\\auth\\server.py\", line 249, in render",
                "    ",
                "  File \"site-packages\\lbrynet\\daemon\\auth\\server.py\", line 387, in _render",
                "    ",
                "--- <exception caught here> ---",
                "  File \"site-packages\\twisted\\internet\\defer.py\", line 150, in maybeDeferred",
                "    ",
                "  File \"site-packages\\lbrynet\\daemon\\Daemon.py\", line 1974, in jsonrpc_claim_list_mine",
                "    ",
                "  File \"site-packages\\lbrynet\\core\\Wallet.py\", line 1360, in get_name_claims",
                "    ",
                "  File \"site-packages\\lbrynet\\core\\Wallet.py\", line 1288, in _run_cmd_as_defer_succeed",
                "    ",
                "  File \"site-packages\\lbryum\\commands.py\", line 141, in func_wrapper",
                "    ",
                "  File \"site-packages\\lbryum\\commands.py\", line 1304, in getnameclaims",
                "    ",
                "  File \"site-packages\\lbryum\\commands.py\", line 739, in parse_and_validate_claim_result",
                "    ",
                "exceptions.Exception: Certificate claim ede48f9106d1f3d793478290edc06853c0aa1e91 not found",
                ""
            ]
        },
        "message": "Certificate claim ede48f9106d1f3d793478290edc06853c0aa1e91 not found"
    },
    "id": null,
    "jsonrpc": "2.0"
}

**Comment by jackrobison** [comment]
fixed in https://github.com/lbryio/lbryum/pull/157
