### ISSUE TITLE
running blob_delete on the same blob a second time should tell you the blob does not exist. instead it says the blob has been deleted

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry#786]
## Steps to reproduce
1. Run `blob_delete HASH` using any HASH that you have
2. Run the above command again.

### Expected behaviour
Daemon responds with "dont have this blob" the second time

### Actual behaviour
Daemon responds with "blob deleted" the second time too

## System Configuration

```
{
  "build": "release",
  "lbrynet_version": "0.14.1",
  "lbryschema_version": "0.0.7",
  "lbryum_version": "3.1.3",
  "os_release": "4.4.0-83-generic",
  "os_system": "Linux",
  "platform": "Linux-4.4.0-83-generic-x86_64-with-Ubuntu-16.04-xenial",
  "processor": "x86_64",
  "python_version": "2.7.12"
}
```

**Comment by tzarebczan** [comment]
Fixed by https://github.com/lbryio/lbry/pull/989
