### ISSUE TITLE
test_delete_open_blob fails occasionally

### ISSUE THREAD

**Issue by jackrobison** [lbryio/lbry#787]
Possibly related to https://github.com/lbryio/lbry/issues/786

Here's where it failed:

![screen shot 2017-07-19 at 12 15 56 pm](https://user-images.githubusercontent.com/11979920/28377844-1d4a4a68-6c7c-11e7-8102-1bc7729950e4.png)

However, it didn't fail when run again: https://travis-ci.org/lbryio/lbry/builds/255315646

**Comment by alyssaoc** [comment]
@jackrobison the other issue ref here #786 is closed. Can we close this or are we still seeing this failure?
