### ISSUE TITLE
Improve blob announcement process

### ISSUE THREAD

**Issue by kaykurokawa** [lbryio/lbry#792]
a) First step : need an API command that will announce specific file/sd_hash so we can debug announcement problems , and force announce of specific files that is being announced for whatever reason ( i.e. server has a large backlog of unannounced blobs) 

b) Second step: blob announcement needs to be reworked to minimize the number of blobs being announced. Announcing every single blob for a large file is probably not sustainable.

**Comment by kauffj** [comment]
Can we further explore potential strategies to keep all blobs announced before giving up on it?

**Comment by kaykurokawa** [comment]
Here is a good solution. 

The default behavior is for seeders (clients serving blobs) to only announce the first blob of a file, but they can announce blobs individually if they wanted to or if they had blobs without knowing what file they are associated with. 

The default behavior for downloaders is to only look for the first blob when downloading a file. If they are unable to download all the blobs this way, they will start looking specifically for individual blobs they don't have. So for clients, finding peers for a file look like this currently:

find_peers():
  Look at the first blob we don't have yet, search for a peer on this blob on the DHT

They need to be changed to this. 

find_peers():
  Look at the first blob to download, search for a peer on this blob on the DHT, 
  If there is no peer that exist, or if we've already connected to all returned peers and downloaded everything available from them,  look at first blob we don't have yet, search for a peer on this blob on the DHT.

**Comment by kauffj** [comment]
@kaykurokawa in the case you propose, wouldn't it still make sense to look for the blob directly first? And only if we can't find a route to them, look for peers of the first blob and ask them?

**Comment by lyoshenka** [comment]
_I'm splitting reflector work out of this issue. This is for blob work only now._

**Comment by kaykurokawa** [comment]
Its more efficient to look for the head blob first if that's the announcement strategy that a majority of the seeders are using. If the majority of seeders are announcing individual blobs, its more efficient to look at individual blobs first. 

Since presumably reflector is going to adopt announce head blob only, it would be more efficient to look at the head blob first.
