### ISSUE TITLE
Introduce Bandwidth Limit Functionality

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#798]
## The Issue
When setting a BW limit in App > Settings, it either does not get saved, or if it does, it is not functional (does not limit) as per discussions with @kaykurokawa.  This setting will go away temporarily as the limiting functionality needs to be built into the daemon. This ticket can be used to track the daemon development.

### Steps to reproduce
1. Go to Settings
2. Set BW limit
3. Nothing happens or radio button does not work

### Expected behaviour
Daemon Should allow for BW limit settings and enforce them

### Actual behaviour
Does not allow for settings and does not enforce.

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by lyoshenka** [comment]
There are two issues here
1 - bandwidth limits dont work and should not be in the UI
2 - it would be nice to have bandwidth limits that work

We're not gonna get to 2 for a while, so I'm gonna tag this as a feature request and close it. I'll file an issue for 1 in the app repo.

**Comment by tzarebczan** [comment]
@lyoshenka - yup, I originally opened one on the app side.. feel free to edit or create a new one to remove the limits settings. https://github.com/lbryio/lbry-app/issues/372

**Comment by kauffj** [comment]
They are gone from the UI in master already.

**Comment by tzarebczan** [comment]
Ah yes, forgot about that! I have to get myself a Linux dev build from
master going...

**Comment by kauffj** [comment]
not a priority

**Comment by eukreign** [comment]
Will re-create this as a more specific issue when we get to working on it.
