### ISSUE TITLE
lbrynet-daemon imports lbryum unnecessarily

### ISSUE THREAD

**Issue by sonatagreen** [lbryio/lbry#80]
Using lbrynet-daemon at all requires that lbryum be available, even for commands like `lbrynet-daemon --wallet=lbrycrd` or `lbrynet-daemon --help`. This is annoying and counterintuitive.

**Comment by jobevers** [comment]
It looks like we'll be moving to lbryum being more and more of a dependency.  Closing this unless that changes.
