### ISSUE TITLE
Introduce Custom Ports and use higher default ports

### ISSUE THREAD

**Issue by nicknitewolf** [lbryio/lbry#808]
Certain ISPs block ports ranging <10k.
My suggestion is to allow the end user to set their own ports and use higher default ports (>10k) instead of 5555 and 4444.

**Comment by hackrush01** [comment]
We have an (Faq entry)[https://lbry.io/faq/how-to-change-port] regarding this. I guess this addresses your issue.

**Comment by nicknitewolf** [comment]
@hackrush01 I'll change my issue then. There should be a UI function to do so too as it is harder to run it comparatively from cmdline in Windows than Linux.

The current default ports should also be changed to something which is higher too so that more end users do not need to have the hassle of changing the ports themselves

**Comment by hackrush01** [comment]
Introducing this feature to UI needs the app to be up and running, which in turn needs to connect through the default ports. From UI you could only change the port for the next run onwards(Although having an option to change this before daemon start up must not be impossible, but I'm unaware of the feasibility). Summoning @kauffj 

As for higher default ports by default, I grab the attention of appropriate people: @jackrobison @kaykurokawa.

**Comment by kauffj** [comment]
It makes the most sense to change the daemon defaults first if we're going to do this, but I'm not sure what the consequences are of switching this.

**Comment by alyssaoc** [comment]
@eukreign and @jackrobison do we want to proceed with this or can we close?

**Comment by eukreign** [comment]
I think if we're going to change defaults we should do some more research. I expect such a change could be distruptive to the network until everyone updates. So if we're going to do such a disruption hopefuly it's only needed once and actually has the intended benefit.

1. Which ISPs block <10k ports?
1. Do any major / popular ones do this?
1. What do other P2P apps do to resolve this?
1. BitTorrent is 6881-6889, does bittorrent not work for folks with such ISPs?

If only a small number of ISPs do this then I'd rather keep the defaults as-is.

@jackrobison thoughts?

**Comment by jackrobison** [comment]
@eukreign @alyssaoc closing this issue

I don't think we need to change defaults, just make them more accessible: https://github.com/lbryio/lbry/issues/1374

This will also require the app be updated to provide access to these settings.
