### ISSUE TITLE
Link card and finish: Unresponsive

### ISSUE THREAD

**Issue by OwenRay** [lbryio/lbry#809]
### Steps to reproduce
1. Download and install v0.14.2 to macOS Sierra (10.12.5)
2. Fill in an email adres
3. Verify the email adres by pasting the code from the email
4. Click Get welcome credits
5. Click Link card and finish

### Expected behaviour
Going to  screen where you can verify your wallet

### Actual behaviour
Nothing,
The button is non responsive.

## System Configuration

- LBRY Daemon version: 0.14.2
- LBRY App version: 0.14.0rc2
- LBRY Installation ID: 6k3mYX9gDGTkX55duifR1cUM6JTD9AccVs4GeTSUb1Wid3j1YJ6MyvYGDKaDfVpuP2
- Operating system: macOS Sierra (10.12.5)

## Anything Else
- When I press the home button and go to an item that can be bought, the problem still persists.
- The problem persists after a restart of LBRY

**Comment by tzarebczan** [comment]
Which button is unresponsive? We are aware of some credit card linking issues, working on them at the moment. Were you able to link successfully and something broke afterwards? Can you enable the developer console in the App and provide any screenshots when this happens?

**Comment by OwenRay** [comment]
Button that says "Link card and finish" I'll take some screenshots and enable the dev console, once I get the chance (later today)

**Comment by kauffj** [comment]
Please wait until the next release to further investigate this.

**Comment by OwenRay** [comment]
Ok, I will, thanks for the heads up.

**Comment by OwenRay** [comment]
this is fixed in v0.14.0rc4
