### ISSUE TITLE
Limit max number of simultaneous connections

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry#817]
As discussed in https://github.com/lbryio/lbry/issues/810, the daemon creates too many connections when downloading content. Often these connections are to the same server. I looked at speech at one point and it had about 468 connections to the same reflector server (not sure if those connections are downloads or uploads). This doesn't scale, and it can hit the max open file limit on some systems. 

Two thoughts:

1. Can the daemon use a single connection per server?
2. Can we limit how many simultaneous connections the daemon makes in total?

**Comment by kauffj** [comment]
Is it possible this reflects a deeper bug? I think the majority of content accessed on spee.ch should either already be on spee.ch or was submitted directly to spee.ch. Is spee.ch really needing to download such significant amounts of content? Or is this from images submitted to spee.ch getting uploaded elsewhere?

**Comment by kaykurokawa** [comment]
Upon daemon startup, it tries to reflect all the files it has so for each file, it will create a reflector connection for each one simultaneously, which is not good if there are a lot of files. 

It also tries to reflect every hour, and if it takes more than 1 hour to reflect everything you will start to accumulate a backlog of reflect commands. 

relevant file: https://github.com/lbryio/lbry/blob/master/lbrynet/file_manager/EncryptedFileManager.py

**Comment by billbitt** [comment]
FYI after @lyoshenka raised the limit I got the 'too many files open' error again today. log and file list below
[21745.docx.txt](https://github.com/lbryio/lbry/files/1198644/21745.docx.txt)
[lbrynet-8-3-17.docx.txt](https://github.com/lbryio/lbry/files/1198643/lbrynet-8-3-17.docx.txt)

**Comment by kaykurokawa** [comment]
Firstly I think there should be an option to turn the scheduled and startup re-reflecting completely off , but keep the initial reflecting on for publishes. I think this will be an easy fix to your problems.  

Secondly there should be a fix for how it auto reflects (limit number of files to reflect at a time).

**Comment by kaykurokawa** [comment]
once this is merged https://github.com/lbryio/lbry/pull/826 , set 'auto_re_reflect' in your config file to False

**Comment by alyssaoc** [comment]
@tzarebczan and @billbitt can you check how many open connections spee.ch still has? Is this an open/closed issue?

**Comment by tzarebczan** [comment]
@jackrobison / @lyoshenka  - do we feel that the changes to reflection (doing it only once per 12 hours, having ability to turn off) solve this ticket or should we be digging in more. The issues on spee.ch with multiple files being open have not re-surfaced.

**Comment by lyoshenka** [comment]
For reflection, the real fix is to put a reasonable limit there - either max simultaneous uploads, max connections per server, max upload bandwidth, or some combo of these. But its not high on the list right now. 

For speech, the fix has to be on speech's end. Either serving static content directly without hitting the node server, or a cache in front of speech, a CDN, etc. I'm guessing part of the problem was having the same URL return different content to different user-agents, which required the direct URLs to still go through node. Now that we dropped that, speech may no longer have a problem at all.

**Comment by lyoshenka** [comment]
In summary, I'm closing this. Please reopen if I'm mistaken and it's still an issue.
