### ISSUE TITLE
Alpha testers have executables that might be earlier in the path

### ISSUE THREAD

**Issue by jobevers** [lbryio/lbry#82]
A user on slack who was an alpha tester had an executable at `/usr/local/bin/lbrynet-daemon`
which was taking precedence over the newer version.

https://lbry.slack.com/archives/tech/p1468805299000607

**Comment by RdeWilde** [comment]
Build from source vs debian package. Uninstall using pip.

**Comment by lyoshenka** [comment]
i think @RdeWilde may be right. debian package always puts that binary in /usr/share/python/lbrynet. he must have compiled from source.
