### ISSUE TITLE
[Windows] Fuzzy Text

### ISSUE THREAD

**Issue by zQueal** [lbryio/lbry#821]
### Steps to reproduce
1. Hover over any thumbnail content

### Expected behaviour
Text should be clear

### Actual behaviour
Text is fuzzy

## System Configuration

Resolution: 1920x1080

```json
{
  "id": null,
  "jsonrpc": "2.0",
  "result": {
    "build": "release",
    "ip": "---.---.---.---",
    "lbrynet_version": "0.14.2",
    "lbryschema_version": "0.0.9",
    "lbryum_version": "3.1.4",
    "os_release": "10",
    "os_system": "Windows",
    "platform": "Windows-10-10.0.14393",
    "processor": "AMD64 Family 21 Model 1 Stepping 2, AuthenticAMD",
    "python_version": "2.7.13"
  }
}
```

- LBRY Daemon version: `0.14.2`
- LBRY App version: `0.14.2`
- LBRY Installation ID: `4QzeH1PfDujXvAMqL3RWAyEaek1DB4GTvmBWdMJpgMQNLKZ1GfYR5SrRjqX1zrLctW`
- Operating system: `Windows-10-10.0.14393`

## Anything Else
N/A

## Screenshots
![zmdes](https://user-images.githubusercontent.com/239193/28897487-f26d9b68-77ae-11e7-9884-3d1ef3cf75af.png)

**Comment by tzarebczan** [comment]
We are aware of this already, have a PR pending to fix it. Please check with us in slack.lbry.io before submitting an issue if you can! Thanks!
