### ISSUE TITLE
Daemon should enforce file type

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#823]
## The Issue
Per discussion in Slack, daemon should enforce file type. 
kauffj [4:57 PM] 
I don't think the daemon enforces files are the promised types, which would be the first step
jack
[5:00 PM] 
even with that though we cant fix a windows media player or video codec vulnerability
kauffj [5:01 PM] 
sure, that's fine, I don't think we have to promise we cover that at this stage
[5:01] 
I think we should cover basic type checking
[5:01] 
if it's being streamed in the app, you're completely covered atm

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by kaykurokawa** [comment]
Not really sure what this is trying to say. 
You want to check file extensions?

**Comment by lyoshenka** [comment]
gonna close this. not sure what this is asking for
