### ISSUE TITLE
send_amount_to_address should reject invalid wallet addresses

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry#828]
## The Issue
It is possible to submit an invalid wallet address to `send_amount_to_address`.

### Steps to reproduce
1. ./lbrynet-cli send_amount_to_address --amount=0.00001 --address=aaa

### Expected behaviour
An error response informing me "aaa" is an invalid address.

### Actual behaviour
It returns true.

**Comment by KamilPiekutowski** [comment]
When you say valid, do you mean if it exists or if the format is valid?

**Comment by tzarebczan** [comment]
This was fixed in https://github.com/lbryio/lbry-app/pull/522

There's another ticket for general input validations somewhere...

**Comment by kauffj** [comment]
@tzarebczan this ticket was for a fix daemon side, but it appears that it has been fixed there as well:

```
./lbrynet-cli wallet_send --amount=0.00001 --address=aaa
ERROR: Invalid address length: 3
...
```
