### ISSUE TITLE
Publish queued, never completes

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#830]
## The Issue
User @death916 on slack reported his published item did not show up in the Publises screen after submitting a new publication. By looking at this log files, it seems like the publish starts correctly and then gets added to a queue, but never ends up executing.  What would cause the publish to go into a queue?  There are some DB locking warnings in the logs, not sure if that could affect it. 

Relevant lines:
`2017-08-05 00:23:51,989 INFO     lbrynet.daemon.Daemon:1838: Publish: {'claim_address': None, 'name': u'pathofexile', 'bid': 0.0001, 'claim_dict': {'version': '_0_0_1', 'claimType': 'streamType', 'stream': {'version': '_0_0_1', 'metadata': {u'fee': {u'currency': u'LBC', u'amount': 0.5, 'version': '_0_0_1', u'address': u'bX4W7wcr6Rs9mSMyUB8jWYm8xRpk3LiHi6'}, u'description': u'Rolled a Scion for the new league. Still trying to figure out a build though. Been waiting for this patch for a long time enjoying it so far.', u'license': u'', u'title': u'Path of Exile Fall of Oriath Act 1 Hardcore', u'language': u'en', 'version': '_0_1_0', u'nsfw': False, u'licenseUrl': None, u'thumbnail': u'https://spee.ch/0/holycrap.jpg'}}}, 'file_path': u'C:\\Users\\Trent.DESKTOP-3E0UBD7\\Videos\\2017-08-04_18-00-09.mp4', 'change_address': None}
2017-08-05 00:23:51,993 INFO     lbrynet.daemon.Publisher:27: Starting publish for pathofexile`

and then:

`2017-08-05 00:26:39,042 INFO     lbrynet.daemon.auth.server:393: queued publish`

Full Log: https://gist.githubusercontent.com/Death916/1cecdcf6e6c5235c020dc69e96f16dbb/raw/57c78eeaf91d475ded8119a5270ce9e904be2abb/lbrylogfile

### Steps to reproduce
1. Publish item
2. Item gets queued (not sure why/how)
3. Item is never published

### Expected behaviour
Content should be published

### Actual behaviour
Content is not published

## System Configuration

 

- LBRY Daemon version: 0.14.2
- LBRY App version: 0.14.3
- LBRY Installation ID:
- Operating system: Win 10

**Comment by kaykurokawa** [comment]
Looking at the logs, looks like user shut down the daemon 20 seconds after publishing, which probablly killed the publish while it was in the middle of something.

**Comment by tzarebczan** [comment]
Thanks, closing for now. I should have caught that :p
