### ISSUE TITLE
Better claim management required for `claim_tip_send` feature.

### ISSUE THREAD

**Issue by hackrush01** [lbryio/lbry#831]
Upon testing the feature, @jackrobison, @tzarebczan and I talked about this on hangouts as there was some undesirable behaviour, and ultimately, reached the conclusion that it needs some changes in the daemon on a deeper level. The changes would include(might not be an exhaustive list)
1. A "new" wallet specifically for support balance
2. A better claim management system(the point is kind of vague but I guess Jack could explain this better)
3. Some other changes that I might have overlooked.

Required for lbryio/lbry-app#355

**Comment by kauffj** [comment]
Subsumed by #846 and #845
