### ISSUE TITLE
Low LBC fee for content creates discrepancies

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#832]
## The Issue
If Publishing content with a small LBC fee (I'm not sure what the breakage threshold is yet), the fee does not properly get set exactly to the desired amount. For instance, setting a fee of 0.01 LBC and then later checking the claim, the fee shows as:  0.009999999776482582 in resolve/claim_list_mine/claim_show (claimid = b0f204c4eaaed281be6e0c2f74cc02f719fe6f7b)

Another example was setting the fee to 0.1, but claim_list_mine/resolve shows: 0.10000000149011612 (claimid=6071f6d5796906c3f743393a74a3e5697866e648)

Most likely related to floating point: https://docs.python.org/2/tutorial/floatingpoint.html (thanks @hackrush01 !)

### Steps to reproduce
1. Create a publish with small claim amount, like 0.1 
2. Check result of resolve/claim_show/claim_list_mine afterwards

### Expected behaviour
Fee should be set exactly to the desired amount

### Actual behaviour
Fee is set to something slightly smaller/larger than the original amount.

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by kauffj** [comment]
@tzarebczan did you verify this happens via a CLI publish to eliminate any possibility that it is an app issue? (I think it is probably not, but it's good to make sure.)

**Comment by kaykurokawa** [comment]
I've seen this before in the daemon, yes its a floating point issue.

**Comment by hackrush01** [comment]
We could use [`Decimal`](https://docs.python.org/2/library/decimal.html) module to represent those number as it provides accurate floating point arithmetic, just like Java's [`BigDecimal`](https://docs.oracle.com/javase/7/docs/api/java/math/BigDecimal.html).

**Comment by kauffj** [comment]
Given there is not arbitrary precision of credit amounts, shouldn't we be using `Decimal` type for all LBC values?

**Comment by hackrush01** [comment]
As I am given to understand LBC is divisible to 8 decimal places, and max amount possible in circulation will be 10<sup>9</sup>(not sure, but still I can make my point). So that would mean the max precision should be 17 with scale of 8. So `Decimal` could be(and should be) used for handling all LBC values. Though I might be missing something here :-|

**Comment by tzarebczan** [comment]
@kauffj just to be safe, confirmed it with a manual publish, same result. 

Publish:
`'{"method":"publish", "params": { "name": "testmanualpublish", "file_path": "C:\\ccsetup532.exe", "bid": 0.0011, "metadata":  { "description": "Some interesting content", "fee": {"currency": "LBC", "amount": 0.01}, "title": "Test manual upload", "language": "en", "license": "test Inc", "nsfw": false }}}'`

Resolve:
fee": {
              "address": "bRHR79gQTo7iHokbNqqN68tnmW6jiyp8gV",
              "amount": 0.009999999776482582,
              "currency": "LBC",
              "version": "_0_0_1"

**Comment by kauffj** [comment]
Too slow @tzarebczan, @kaykurokawa already opened a PR to fix this :stuck_out_tongue:

**Comment by tzarebczan** [comment]
Well, at least I got to do my first publish via CLI :)

**Comment by KamilPiekutowski** [comment]
I have changed floating point to be represented with string here:
`https://github.com/lbryio/lbryschema/pull/26`

**Comment by tzarebczan** [comment]
I believe there was already some work on this, was just never merged/finished. https://github.com/lbryio/lbry/pull/835

**Comment by KamilPiekutowski** [comment]
@tzarebczan You are right and @kaykurokawa requested a change in the lbryschema. I just wanted to point out that it is done, but I am not sure if it works.

**Comment by tzarebczan** [comment]
@KamilPiekutowski just going through some old issues and noticed this one. Looks like https://github.com/lbryio/lbryschema/pull/26 was caught up in other changes. Did you want to work on the lbryschema changes required for https://github.com/lbryio/lbry/pull/835 ?

**Comment by KamilPiekutowski** [comment]
I don't think they were happy with my solution.
I got a very little feedback, so if this is fixed, no reason
for me to work on it.

Thanks for asking.

**Comment by KamilPiekutowski** [comment]
The only solution I was able to come up with was using 3rd party python
module that would generate duration of mp4.
However duration would only be added to newly uploaded videos with blry
version that supports  The videos that were uploaded with older lbry would
not support duration
unless we make lbry reload the claim info.

I think you guys did not want that solution.
I am not exactly sure how we can invoke other peers system to send us
duration info
before at least file header with all info is loaded.

I am open for suggestions,
or questions if I was not clear enough.

Thanks.

**Comment by alyssaoc** [comment]
no longer an issue
