### ISSUE TITLE
Build failed on OSX 10.11.6

### ISSUE THREAD

**Issue by avoloshko** [lbryio/lbry#834]
```
sh autogen.sh
./configure --without-gui --enable-debug
make install

```
RESULT:
Making install in src
  CXXLD    libbitcoinconsensus.la
clang: warning: argument unused during compilation: '-pthread'
clang: warning: argument unused during compilation: '-pthread'
Undefined symbols for architecture x86_64:
  "memory_cleanse(void*, unsigned long)", referenced from:
      zero_after_free_allocator<char>::deallocate(char*, unsigned long) in libbitcoinconsensus_la-block.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libbitcoinconsensus.la] Error 1
make[1]: *** [install-recursive] Error 1
make: *** [install-recursive] Error 1

**Comment by kauffj** [comment]
Did you mean to file this on `lbrycrd` instead? I'm fairly certain you did, and the issue exists: https://github.com/lbryio/lbrycrd/issues/64

If I'm wrong, please clarify and re-open.
