### ISSUE TITLE
Add additional fields to transaction_list to support tipping

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry#845]
`transaction_list` needs to add additional fields:

- `type` : (`support`, `claim`, `update`, "`unbound`")
- `claim_id` : (claim_id of support/content/channel)
- `is_tip` (true if type=support and sent to address that matches address of claim)

**Comment by kauffj** [comment]
And drop `label`

**Comment by kauffj** [comment]
Rename `value` to `amount` (but keep `value` for now)

**Comment by kauffj** [comment]
Add `fee`

**Comment by hackrush01** [comment]
Right now `value` has to be kept as it is, right?

**Comment by kauffj** [comment]
Discussed on Slack. Moving back to In Progress.

**Comment by hackrush01** [comment]
Update(23 Aug, '17): being worked on in lbryio/lbryum#148
