### ISSUE TITLE
Publish call reports success with invalid descriptions

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry#847]
**Edit by Jeremy:** Original ticket is below. The daemon needs to reject `publish` calls with invalid descriptions.

_From @MSFTserver on August 7, 2017 21:37_

 

## The Issue
when setting a long description inside the app it will say it has published and is pending but looking at the transaction history no trans has been made but the video pop up in published area saying still pending but the daemon has already rejected it for having to long of a description 
### Steps to reproduce
1. Create a Long Description for a URI (for this i used a nice Wiki Article to test)
2. After pressing publish it says the file is pending for approval 
4. the video file stays in published saying pending
5. no tx records for that publish
### Expected behaviour
it should have a max character count so we dont go over this limit or if the daemon throws that character count error for the app to also throw a error and delete the file from pending as it will never make it and it should throw a try to re-upload error

### Actual behaviour
the file doesn't get published and stays in published section saying pending for about 5minuntes
no errors outputs for this yet....

## System Configuration

 

- LBRY Daemon version: 0.14.2
- LBRY App version: 0.14.3
- LBRY Installation ID: 9JKT6nrdGYoFKshVLmjnbfUdqNvHRkzWmsLXk5xNdbXzGEwpraZ6MVg1KoD5jrBrf2
- Operating system: Windows 10

## Screenshots

![image](https://user-images.githubusercontent.com/18357967/29046704-7ceaa444-7b7d-11e7-936b-c61f7f094296.png)
![image](https://user-images.githubusercontent.com/18357967/29046734-9a299812-7b7d-11e7-8556-d3e5ad987033.png)
![image](https://user-images.githubusercontent.com/18357967/29046748-abcb952a-7b7d-11e7-97ad-d7192074ddb0.png)
![image](https://user-images.githubusercontent.com/18357967/29046761-b774d4b8-7b7d-11e7-8913-ac51e8941d65.png)
![image](https://user-images.githubusercontent.com/18357967/29046623-2780c560-7b7d-11e7-94bf-1f2e54e7e1f6.png)
![image](https://user-images.githubusercontent.com/18357967/29046646-3a0dd4d4-7b7d-11e7-8f9c-a5475da3b7fa.png)

_Copied from original issue: lbryio/lbry-app#452_

**Comment by alyssaoc** [comment]
@eukreign Is this resolved with the new wallet?

**Comment by alyssaoc** [comment]
@tzarebczan can you confirm this is handled correctly

**Comment by tzarebczan** [comment]
This is currently handled better in the sense that the publish call fails with a ```Claiming of name testlongdesc failed: error: the transaction was rejected by network rules. 16: bad-txns-claimscriptsize-toolarge ``` (that's what the user also sees in an error box) but I think we can still do a better job at estimating the claim size before even submitting the publish.

@eukreign , will the publish call have a no broadcast option we can leverage? Would we know what the max size is during this time?

**Comment by eukreign** [comment]
Adding a `--broadcast` flag to publish command is doable. In fact, I think all commands that deal with TXs should have a `--broadcast` flag with default being do not broadcast and then if you want to broadcast you must pass the flag?

Closing this since the original issue (of no error to user) has been resolved.

A new issue should be created to add a `--broadcast` flag to `publish` so that it is possible to simulate a publish without actually broadcasting.

**Comment by tzarebczan** [comment]
I agree, but I think the default should be to broadcast (which matches current functionality) and a flag to not broadcast (I could be convinced otherwise if other team members agree with your approach!).
