### ISSUE TITLE
Feature Request: Commenting and Rating functionality

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#851]
## The Issue
For both content creators and consumers, a commenting and rating feature is important for content discovery and collaboration. 

I know this was discussed in passing, but I wanted to get it down as an issue for further comments.

**Comment by jsigwart** [comment]
I know the tipping system is another feature request, and it would be nice to have the tip feature integrated with the commenting system.

**Comment by aayanl** [comment]
One thing to consider is, should comments be pushed to the blockchain or not. Pushing them to the blockchain is decentralized but costs tx fees and is slow. The other option is sending them to lbry servers and they host it but that's centralized

**Comment by jsigwart** [comment]
I think it would be too expensive to push comments to the blockchain. Yeah, comments would be centralized, but still anybody can build an app on top of LBRY. The LBRY blockchain itself should be analogous to what the card file used to be to big libraries: something that tells you where to find a specific book (piece of content) on the shelves (servers).

**Comment by alyssaoc** [comment]
this is being discussed as an internal proposal/improvement, needs priority assignment

**Comment by alyssaoc** [comment]
closing for larger epic
