### ISSUE TITLE
Unit & integration tests for Prism

### ISSUE THREAD

**Issue by kaykurokawa** [lbryio/lbry#853]
Prism reflector needs to announce by head blob only , 

Right now it just sends arbitrary blobs to each lbrynet reflector instances it feeds, but it needs to be aware of streams and distribute blobs so that lbrynet reflector instances have complete streams most of the time. 

- [x] twisted unit tests (1 day)
- [x] lbry-in-a-box integration tests (2-3 days)

later:

- [ ] set up testing aws cluster to make sure everything is working, and to measure how much better availability is (2-3 days)
- [ ] enable head blob announce in prism (? days)
- [ ] make sure the hosts know about head blobs, which blobs to announce (? days)

**Comment by lyoshenka** [comment]
Part 2 in https://github.com/lbryio/lbry/issues/887
