### ISSUE TITLE
Solve/design the general approach for making daemon calls asynchronous

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#854]
@tzarebczan commented on [Tue Aug 15 2017](https://github.com/lbryio/lbry-app/issues/475)

 

## The Issue
As a Publisher, when I upload files to LBRY, the current process is fairly uninformative after the Publish button is clicked. There is no indication that the file is being processed or when it's finished uploading (besides the URI being available).  This is a bigger issue with larger files as they take some time to upload.  

Feel free to add/comment. 

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

## Screenshots

---

@kauffj commented on [Tue Aug 15 2017](https://github.com/lbryio/lbry-app/issues/475#issuecomment-322553552)

This isn't an app issue. If you want, you can re-open on lbryio/lbry as "Make publish and get calls asynchronous"

**Comment by lyoshenka** [comment]
Next step: figure out if Websockets is the right solution to this

**Comment by lyoshenka** [comment]
Related: http://wamp-proto.org/

**Comment by kauffj** [comment]
@lyoshenka I think this possibly conflates two different issues. We don't need sockets or the ability for the daemon to push data to apps to solve this (though this is a great idea!).

Currently, existing apps _already_ regularly poll `get` and `file_list` to determine state. This change is simply to have `get` and `publish` return immediately, with some kind of field indicating their status ("pending" or whatever).

**Comment by lyoshenka** [comment]
Thought about this some. I think there are times when we want it to return right away, and there are times when we want it to return when its done. I think the latter is more common, so we should add a `--return-immediately` flag.

**Comment by eukreign** [comment]
`publish` is significantly faster with the new wallet, closing this as the original issue may no longer be valid.

**Comment by tzarebczan** [comment]
I don't think we want to close this just becuase publish reruns faster, there are still valid reasons for this requirement. If a file is large, we would want a way to return a loading status.

This ticket also included a similar feature for the get command. 

@lyoshenka / @jack thoughts?

**Comment by eukreign** [comment]
Would it suffice to say that adding a websockets API would solve this problem? I made an epic: https://github.com/lbryio/lbry/issues/1649

**Comment by kauffj** [comment]
@eukreign yes, we can use that moving forward
