### ISSUE TITLE
Internal Error when trying to Publish/Create channel with an insufficient balance

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#855]
@tzarebczan commented on [Thu Aug 03 2017](https://github.com/lbryio/lbry-app/issues/427)

 

## The Issue
When trying to create a channel for more LBC than exists in your wallet, you get an internal error as opposed to a better insufficient funds message.  We should also make a note of TX and Publish fees, because if someone has 10 LBC, they most likely won't be able to claim for 10. 

Updated: If this happens when creating a channel, the channel is shown as being available but users cannot publish to it. 

Log shows:
```shell
2017-08-03 08:23:38,674 ERROR    lbrynet.daemon.auth.server:353: Failed to process channel_new: Invalid amount
Traceback (most recent call last):
  File "site-packages\twisted\internet\defer.py", line 1299, in _inlineCallbacks
  File "site-packages\lbrynet\daemon\Daemon.py", line 1663, in jsonrpc_channel_new
Exception: Invalid amount
2017-08-03 08:24:45,992 ERROR    lbrynet.daemon.auth.server:353: Failed to process channel_new: 
Traceback (most recent call last):
  File "site-packages\twisted\internet\defer.py", line 1299, in _inlineCallbacks
  File "site-packages\lbrynet\daemon\Daemon.py", line 1665, in jsonrpc_channel_new
InsufficientFundsError
```

### Steps to reproduce
1. Publish something for more LBC than you have in your wallet
2. See internal error
![internal error](https://user-images.githubusercontent.com/8120721/28929666-94609080-783e-11e7-8f35-39b954e5e3d8.JPG)
3.

### Expected behaviour
Should be told insufficient funds

### Actual behaviour
Internal error

## System Configuration

 

- LBRY Daemon version: 0.14.2
- LBRY App version:0.14.3rc2
- LBRY Installation ID:
- Operating system: Win 10

## Screenshots

---

@kauffj commented on [Tue Aug 08 2017](https://github.com/lbryio/lbry-app/issues/427#issuecomment-320962240)

@tzarebczan any time the daemon throws an exception rather than cleanly returning a signature that indicates an error, it's a bug in the daemon.

---

@tzarebczan commented on [Tue Aug 15 2017](https://github.com/lbryio/lbry-app/issues/427#issuecomment-322602095)

Sorry, just saw this now - reopening on the lbry side.

**Comment by kennethreitz** [comment]
This hit me today.

**Comment by tzarebczan** [comment]
in @kennethreitz 's case, he was able to see his channel in the dropdown and attempt to publish using it. Entire log is here: https://gist.github.com/kennethreitz/7c8cf7b9540fe45f8991c658e1e21abd

**Comment by alexliebowitz** [comment]
@kauffj: Well, technically most of the "clean" error responses from the daemon are still exceptions. You just include a human friendly message when you throw the error and it gets passed along in the `message` field in the response. So to fix the daemon side of this, I would think that we just need to add a message here: https://github.com/lbryio/lbry/blob/master/lbrynet/daemon/Daemon.py#L1735 Although I might be missing something.

Anyway, once this is fixed we still need to fix the UI side to 1) pass along the error message from the daemon instead of the vague "internal error" message and 2) not allow you to try to publish with a channel that wasn't successfully created (the problem that @kennethreitz had)

**Comment by tzarebczan** [comment]
@alexliebowitz any progress on this? We want to get the app side patched up to fix this asap... It's an ugly error that's causing confusion.

**Comment by tzarebczan** [comment]
Although a band-aid was made on the app side to check for user balance, the daemon should really be returning this information. Probably needs to be fixed in conjunction with https://github.com/lbryio/lbry/issues/748

**Comment by lyoshenka** [comment]
For now the app should handle this error in a custom way. We are planning to overhaul errors soon (issue )
