### ISSUE TITLE
Improve DHT wire format

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry#859]
There are several improvements to make. My guess is that we need to roll out a v2 of the DHT message format and make all nodes switch to it. But if we don't want to make BC changes, we can do at least the first two items in a BC way.

## DHT uses integer keys in bencoded messages, while spec requires bytestring keys

See http://www.bittorrent.org/beps/bep_0003.html#bencoding (bullet 4) for spec. This makes our bencoding not compatible with other libraries. In fact we should switch to the standard Bittorrent way of encoding messages (using keys like `t`, `q`, etc) instead of the current numbered indices. 

## rpcID need only be 2-3 bytes, not 48 bytes

http://www.bittorrent.org/beps/bep_0005.html#krpc-protocol recommends 2 chars for the `t` value. 48 bytes wastes bandwidth.

## Args format should be consistent across different request methods

The `headerArgs` field is sometimes a string, sometimes a list of contact triples, sometimes a dict, etc. The format should be consistent (probably a string) for all request types. We should use contact encoding (aka compact node info) instead of contact triples.

## Use standard error types

Error types are defined in http://www.bittorrent.org/beps/bep_0005.html#errors. There's no reason to send the exception type and exception message in responses.

## All the DHT code is confusing as fuck

... and needs to be refactored.

**Comment by lyoshenka** [comment]
most of this may be invalid, since I thought our implementation was closer to Bittorrent when it's actually closer to the original Kademlia paper

**Comment by ordex** [comment]
@lyoshenka Are planning to be fully compatible with other DHT libraries? If not, the first point is probably not really needed, while the others all sound meaningful.

This said, shortening the `rpcID` and refactoring the `headerArgs` could probably go in now, but I'd wait before considering the rest as they may introduce more inconsistencies in our DHT.

OTOH, since #1007 is going to break BC, we might want to hold it a bit longer and implement more changes, but I am not sure this is a good idea.

What do you think?

**Comment by ordex** [comment]
Speaking about DHTv2: is there any plan to port the DHT to a different language? I have seen that Go is becoming popular among the team, but I am not sure what's the plan going forward.

**Comment by lyoshenka** [comment]
It's ok if we're not compatible with other libraries, but I'd like us to be compatible with other languages (like Go), which generally requires being more consistent with our return types. If we sometimes return a string, and sometimes an int, and  sometimes None, that's annoying to handle in strongly-typed languages.

We are indeed working on a Go implementation of the DHT. Are you interested in helping with that? I've already a little in https://github.com/lbryio/lbry.go/tree/master/dht, but its been a struggle because our DHT protocol is not well-documented, so I've mostly been sending/receiving messages and then figuring out how to handle what I get.

**Comment by alyssaoc** [comment]
@lyoshenka any updates on this?

**Comment by lyoshenka** [comment]
jack refactored a lot of the dht code, and some of this is wrong, so it can be closed. there's one part that's real. ill file a separate issue for it
