### ISSUE TITLE
Content page not refreshed after Download removed from LBRY

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry#864]
_From @tzarebczan on August 17, 2017 19:22_

 

## The Issue
Content still shown as "downloaded" after removal from LBRY - the Open button shown.  This does not happen every time, but I've seen it enough times to think there is an issue somewhere. If I reload the content page after removal, then it goes back to an unwatched/undownloaded state where the Download button is shown. Another work around is to remove it again. The other option is just to click stream. 

### Steps to reproduce
1. Download Content, then proceed to remove it - you are knocked out of the page
2. Go back to the same content URL immediately
3. Still shows Open button as if the File was downloaded

### Expected behaviour
Should show Download link

### Actual behaviour
Need to refresh or remove again. 

## System Configuration

 

- LBRY Daemon version: 0.14.2
- LBRY App version: 0.14.3
- LBRY Installation ID:
- Operating system: Windows

## Screenshots

_Copied from original issue: lbryio/lbry-app#485_

**Comment by tzarebczan** [comment]
Closing this, it's not happening anymore and think it was an app issue to begin with.
