### ISSUE TITLE
HashBlob Invalid Length, download continues infinitely

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#866]
## The Issue
Somehow I got into a situation where a LBRY file continued to grow in the downloads directory until it maxed out my VM hard drive (~100 GB).  Going back through my log files, I started downloading 
 lbry://theinternetsownboy and then lbry://eight.  eight finished downloading but theinternetsownboy continued.

It looks like I had a hard daemon crash in the middle of a download. On the subsequent bootup, I see this error message:
lbrynet.core.HashBlob:106: Got an invalid length. Previous length: 2097152, Invalid length: 2031616

It starts to download blobs and create the mp4, but then it starts throwing these errors:
2017-08-17 15:46:26,449 WARNING  lbrynet.core.client.StreamProgressManager:157: Error occurred in the output loop. Error: string index out of range

I left it running unknowingly and then it filled up my entire HD by continually appending to the mp4 file. I deleted the file, restarted LBRY and it continued to do the same again. Attaching my lbrynet directory here: https://www.dropbox.com/s/evnm7qco23yjjst/lbrynet.zip?dl=0

### Steps to reproduce
1. Download file
2. Hard quit/crash during download
3. Upon restart, LBRY file downloads infinitely 

### Expected behaviour
LBRY should recover from such an error and self correct

### Actual behaviour
Hard drive ded

## System Configuration

 

- LBRY Daemon version: 0.15.x
- LBRY App version: master
- LBRY Installation ID:
- Operating system: Ubuntu

**Comment by alyssaoc** [comment]
@tzarebczan can you check for this on loggly?

**Comment by alyssaoc** [comment]
closing, reopen if this is still an issue
