### ISSUE TITLE
Fix regression in claim_list_by_channel

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry#868]
PR for https://github.com/lbryio/lbry/issues/691 (https://github.com/lbryio/lbryum/pull/138) contains a regression. See discussion on issuea and at https://github.com/lbryio/lbry/pull/801#commitcomment-23706472

**Comment by hackrush01** [comment]
If it is caused due to a duplicate name/tuple, could this be solved by just renaming `claims_in_channel` to `no_of_claims_in_channel` or something similar?

**Comment by kauffj** [comment]
This is fixed in the app, though I'm not in love with the daemon's approach/design here.
