### ISSUE TITLE
`claim_new_support` should not require a name arg

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry#871]
It already requires claim_id, so it can look up the claim from that

**Comment by MSFTserver** [comment]
upon entering a different name for this command it generates a new url and replaces the old one within the publishes section of the app and doesn't know what to so with itself, the name I think should be allocated from the id I would presume?
[.GIF of Issue](https://files.slack.com/files-pri/T0AFFTU95-F6UFHL6Q3/5.gif)

**Comment by tzarebczan** [comment]
Yea that's a nasty one. I think part of it is fixed by @hackrush01 in master already.

This is also related: https://github.com/lbryio/lbry/issues/812

**Comment by alyssaoc** [comment]
closing as a duplicate of #812
