### ISSUE TITLE
Add Pagination to Downloads/Publishes/Wallet pages

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#876]
## The Issue
As LBRY usage grows, users will accumulate many items in Downloads, Publishes and in their wallet.  The app should have the ability to paginate on these screens.  This should also make the user experience more pleasant as less data needs to be loaded on each refresh.  Sorting/filtering options would be nice in all the areas as well.

### Expected behaviour
Paginate through LBRY areas

### Actual behaviour
Each page loads all data

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by lyoshenka** [comment]
Issue moved to [lbryio/lbry-app #626](https://github.com/lbryio/lbry-app/issues/626) via [**ZenHub**](https://www.zenhub.com/)

**Comment by kauffj** [comment]
This is likely an issue at the daemon level as well. It needs to provide an API that supports paging.
