### ISSUE TITLE
Port to Python 3

### ISSUE THREAD

**Issue by kennethreitz** [lbryio/lbry#880]
I might take this on :)

**Comment by kauffj** [comment]
@kennethreitz I'm inclined to icebox this unless you (or someone) let us know you want to take it on.

**Comment by lyoshenka** [comment]
I talked to @kennethreitz last week. He said he's interested in doing this, but he's not making any promises about timelines or finishing. Some of our code may be tricky to convert. That said, I'd love to hear updates on how it's going.

**Comment by lyoshenka** [comment]
gonna close this. I think we're more likely to switch to Go than Python3 at this point

**Comment by eukreign** [comment]
from @hackrush01 on slack: https://medium.com/@boxed/moving-a-large-and-old-codebase-to-python3-33a5a13f8c99

**Comment by eukreign** [comment]
Going to re-open this to keep attention on it. Having it closed might discourage someone from trying.

Several of the other lbry libraries are already Python 3, so porting lbrynet to Python 3 isn't as far fetched.

**Comment by hackrush01** [comment]
Closed. Will be tracked in #1273
