### ISSUE TITLE
Download timeout prompt to should show title instead of sdhash

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#883]
## The Issue
When a download times out, the current message shows the sdhash of the failed file. This is non-descriptive to users and thus should be replaced with the title of the content they tried to download.

For instance, a failed download shows the sdhash
`Error message: Failed to download 8a455fb52ac158ec8bb80737dd9dc1e70c25dcd7b6966bc358cc466b78fdcc22c646616ba3decdba906d27f06730ac49 within timeout`

Originally thought it might be fixed here -https://github.com/lbryio/lbry-app/pull/490, but the error seems like it's coming from the daemon: https://github.com/lbryio/lbry/blob/master/scripts/name.py#L47

See other discussions here: https://github.com/lbryio/lbry-app/issues/328#issuecomment-320524216 where we discussed that the title would be a better option.

### Steps to reproduce
1. Try to download  lbry://ucberkeley-pulauDjH1KM
2. Wait a minute or two
3. See popup error message

### Expected behaviour
Show title of failed download

### Actual behaviour
Shows sdhash

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by zestyr** [comment]
This error comes from here: 
https://github.com/lbryio/lbry/blob/master/lbrynet/daemon/Daemon.py#L643

A few lines above it logs that it failed, then the error message, which looks like this ```lbrynet.daemon.Daemon:640: Failed to get <URI>: Failed to download <blob> within timeout```

The error message returned comes from the timeout error here. 
https://github.com/lbryio/lbry/blob/master/lbrynet/core/client/StandaloneBlobDownloader.py#L139

Since the daemon needs to handle multiple kinds of errors, and StandaloneBlobDownloader only knows about the blobs, as far as I can tell, I can't find a simple way to fix this.

**Comment by MSFTserver** [comment]
we could possibly get the name by making a function to run file_list with sd hash then parse out name
![image](https://user-images.githubusercontent.com/18357967/29999584-41674af4-9003-11e7-9ac6-ca3f0ced54b1.png)

**Comment by tzarebczan** [comment]
@lyoshenka can we get this bumped up in priority? Would be nice for users to see the title of the failed content downloads instead of the sdhash which means nothing to them.  Not sure if there's anything we can do on the app side in the meantime (see discussion above)

**Comment by tzarebczan** [comment]
Looks like something was fixed recently and the daemon now reports the LBRY URL as well as the sdhash (this is an example after getting the sdblob, but it also shows it for sdblob timeouts too)

2017-12-02 12:59:26,348 WARNING  lbrynet.daemon.Daemon:686: Failed to get two (Failed to download data blobs for sd hash 837eb8651c9b7755fb2972b77933435ed6c9d217e41782d31ab10401f5b59219988a68ec1f10fb16c6a9c0cc5f5408d8 within timeout)

The in app error still shows only the sd-hash
![error](https://user-images.githubusercontent.com/8120721/33518327-05b67e3a-d761-11e7-87c8-ee1ac2a048b3.png)

How do we feel about showing the URL vs something more common like the title? I guess we should take this as a win for now and show the URL on the app side.

**Comment by lyoshenka** [comment]
closed in https://github.com/lbryio/lbry-app/pull/822
