### ISSUE TITLE
Add purchase and received payment information to wallet / separate area?

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#884]
## The Issue
As both a publisher and consumer of content via the LBRY app, I would like to be able to track what content purchase was associated with my wallet transactions and also what incoming payments are associated with my published items when they are downloaded.  

Currently, when you download something that has a key fee, the only trace of it is the fact that it appears in your downloads directory. If you looked at the TX for the purchase, you can't tell which item it was for.  Also, when someone purchases content you have set a key fee for, you can see the key payments coming into your wallet, but again, you can't tell which content it's for.  

This would either be shown in the TX history or possibly a new area which just tracks paid download / receiving transactions. 

This builds on top of:
https://github.com/lbryio/lbry-app/issues/379
https://github.com/lbryio/lbry/issues/845

and possibly: 
https://github.com/lbryio/lbry/issues/803

**Comment by kauffj** [comment]
I think this is basically #803 - we don't have this information right now, it's not a matter of adding it.

You (or someone) could update #803 to specify the additional API changes required to the `transaction_XXX` methods.
