### ISSUE TITLE
Integrate blob announce changes into prism

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry#887]
From https://github.com/lbryio/lbry/issues/853

- [ ] set up testing aws cluster to make sure everything is working, and to measure how much better availability is (2-3 days)
- [ ] enable head blob announce in prism (? days)
- [ ] make sure the hosts know about head blobs, which blobs to announce (? days)

**Comment by kaykurokawa** [comment]
Going to add some more details 

- [ ]  Need finished review from Jack on https://github.com/lbryio/lbry/pull/872, https://github.com/lbryio/reflector-cluster/pull/3, https://github.com/lbryio/reflector-cluster/pull/5 , merge required

- [ ] Ansible reflector cluster setup , Need host setup.  Need to import the redis database from old reflecter cluster (I think we want to do this to prevent old files from being re-reflected to the new reflector cluster) 

- [ ] Merge https://github.com/lbryio/lbry/pull/889 to turn head blob seek for clients on, also change reflector address to the new reflector cluster ( We should keep reflector.lbry.io pointed to the old cluster). Make a release candidate so team members can test . Fix things if necessary

- [ ] If everything ok, point reflector.lbry.io to the new reflector cluster. Make a release for public consumption. 

- [ ] We need to migrate the blobs in the old reflector cluster to the new reflector cluster.
