### ISSUE TITLE
Add better user feedback to Youtube verification process

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#888]
## The Issue
Currently, the Youtube Verification page allows any Youtube account to be sent the LBRY and the response is "Thanks for Syncing".  

This message should be shown if the user meets our Youtube sync qualifications along with an additional comment to tell the user they will be verified for rewards.  If a user does not qualify, they need to get a different message stating the fact that their account doesn't meet the minimum criteria.  Another idea might be to disable the Youtube Sync button if the process fails more than once to prevent spamming with different accounts.

### Steps to reproduce
1. Go to verification page and try Youtube sync with a bare minimum YT account
2. You are told thanks for syncing, no other feedback.  The account is not verified if the channel doesn't meet qualifications. 
3. Complain :)

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by reillysmith** [comment]
I'm going to add to this: YouTube "verification" should not be associated with ID verification at all. This needs to be a totally separate feature in the app for publishers. The criteria being passed for verification is not, "is this a real person?" It's "do you meet the threshold for being in the YouTube sync pipeline." Less than 1% of users of LBRY will need to use this button.

**Comment by tzarebczan** [comment]
Or separate out Youtube verification and YouTube Sync.  Maybe give those with X amount of videos/views a link to Youtube Sync after they verify if they want to get their content synced on LBRY automatically (has to be explicit)

**Comment by tzarebczan** [comment]
Issue moved to [lbryio/internal-issues #26](https://github.com/lbryio/internal-issues/issues/26) via [**ZenHub**](https://www.zenhub.com/)
