### ISSUE TITLE
Google BTC to USD feed failing

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#890]
## The Issue
The Google BTC to USD feed is failing because http://finance.google.com/finance/info?q=CURRENCY:BTC doesn't work anymore.  https://www.google.com/finance?q=CURRENCY:BTC does. In the short term, this link needs to be fixed. In the long term, we need to have redundant APIs for all conversion calls. 

Daemon throws: `2017-09-07 11:46:05,375 WARNING  lbrynet.daemon.ExchangeRateManager:69: There was a problem updating USDBTC exchange rate information from Coinbase via Google finance`

Code:
https://github.com/lbryio/lbry/blob/aef31991f9bf2751d5d980b0a2074caf19af1b14/lbrynet/daemon/ExchangeRateManager.py

### Expected behaviour
Price API should work or fall back to backup(s)

### Actual behaviour
Price API call fails

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by jackrobison** [comment]
A patch release for 0.15.1 (broken latest release) is [here](https://github.com/lbryio/lbry/tree/v0.15.2)

The fix on master is [here](https://github.com/lbryio/lbry/commit/1f4dfe1f933e5da2b677c26e9e81c04eb4ee187a)
