### ISSUE TITLE
weird issue on localhost:5279 (No Such Resource  File not found)

### ISSUE THREAD

**Issue by 0x0482** [lbryio/lbry#90]
Hello. 
I am experiencing a weird issue on a lot of computers while running lbry. 
There is a massage displayed on the screen saying ("No Such Resource
File not found").
I have tried everything to fix this problem, and nothing is working. I am probably missing something.

**Comment by 0x0482** [comment]
Problem was fixed after I got a new IP and registered again. Now a new problem - after running the command "lbrycrd-cli listaccounts" It says that the server isn't running which is not correct as I'm connected..

**Comment by kimihiro64** [comment]
This issue was fixed today. The new version does not use lbrycrd-cli, it uses lbryum, so use lbrynet-cli. Although I don't think it supports accounts (they are likely to be deprecated even in bitcoind and lbrycrd soon).

**Comment by 0x0482** [comment]
What Jonas suggested is the solution to this problem, If anyone needs help with understanding how the model works, just type lbrynet-cli help. Don't forget it's the commands here takes JSON only. 
lbrynet-cli located in the following path: `/usr/share/python/lbrynet'bin'lbrynet-cli`
