### ISSUE TITLE
`publish` returns useless error

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry#901]
Run `lbrynet-cli publish stuff 1`. The daemon responds with `ERROR: 'source'`. That's it. What does that mean? What am I supposed to do about that?

**Comment by mirgee** [comment]
It seems that this call should make stream type name claim which is required to contain 'source' in its metadata at several places. Can anyone please explain the difference between certificate and stream type name claims?

**Comment by jackrobison** [comment]
@mirgee 

https://github.com/lbryio/lbryschema/blob/master/docs/schema.md

https://github.com/lbryio/lbryschema/blob/master/docs/signing.md

**Comment by lyoshenka** [comment]
Fixed in https://github.com/lbryio/lbry/issues/913
