### ISSUE TITLE
Consider raising store expiration time

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry#909]
We don't have that many hosts right now. Connecting to hosts that go offline is less of an issue than DHT entries expiring because some hosts have a lot of content. As long as DHT can intelligently remove hosts that don't respond, raising announce expiration to a week or more will help with availability from large stable hosts (e.g. reflector cluster).

**Comment by tzarebczan** [comment]
The re-announce time should be changed accordingly as well.

**Comment by jackrobison** [comment]
The `DHTHashAnnouncer.ANNOUNCE_CHECK_INTERVAL` and `DHTHashAnnouncer.CONCURRENT_ANNOUNCERS` constants also need to be updated for https://github.com/lbryio/lbry/pull/961

**Comment by lyoshenka** [comment]
jack will work on this soon
