### ISSUE TITLE
Incorrect Total LBC Balance Showing in LBC Browser on Ubuntu

### ISSUE THREAD

**Issue by chrishobcroft** [lbryio/lbry#914]
The balance in my LBC Browser on Ubuntu is showing the incorrect amount, based on the sum of my transaction history.

The browser shows that I have 8 LBC, but the transactions show a total of around 1278.

See attached for screenshot...

Understandably I'm confused about why it's not showing the full balance!

Incidentally, this occurred after restoring the wallet from another installation (LBRY on Windows 7) - but I don't expect this has anything to do with it, as all the transactions are showing accurately.

![image](https://user-images.githubusercontent.com/2212651/30711892-1234409e-9f02-11e7-983f-ca9f584e935d.png)

 

### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by tzarebczan** [comment]
@chrishobcroft sorry you are having trouble. Can you try this:
1) Close LBRY
2) Delete blockchain_headers from lbryum folder ( https://lbry.io/faq/lbry-directories) 
3) Start LBRY again.

**Comment by chrishobcroft** [comment]
Thanks @tzarebczan but the same behaviour persists :(

**Comment by tzarebczan** [comment]
@chrishobcroft I reached out to you on Slack, maybe we can do a remote session to figure this out.

**Comment by tzarebczan** [comment]
Chris used an older wallet backup which didn't have newly generated addresses.  He's attempting to generate new addresses with the hopes of recreating addresses that have the remainder of his balance. 

Will try to reproduce the same on my side.
