### ISSUE TITLE
Publish deposit to low no error ouput

### ISSUE THREAD

**Issue by MSFTserver** [lbryio/lbry#920]
## The Issue
Publish page doesnt throw error if deposit amount to low just selects the deposit div but doesnt tell em anything lowest possible in app deposit is now .01 
### Steps to reproduce
1. go to publish page
2. publish something but put deposit as .001
3. pressing publish just highlights the div but no error for to low

### Expected behaviour

to tell me my deposit amount is to low, or increase the in app lowest purchase price as we have been telling people .00001 is safe amount when thats not possible anymore
### Actual behaviour

just highlights the div 

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by MSFTserver** [comment]
haha wrong area im an idiot sometimes

**Comment by tzarebczan** [comment]
Similar to https://github.com/lbryio/lbry-app/issues/604 - this was inadvertently introduced in the current version. Alerting the user about minimums would be a must.  Probably relies on this discussion too: https://github.com/lbryio/lbry/issues/768

Also relevant: https://github.com/lbryio/lbry-app/issues/214
