### ISSUE TITLE
Add "Release Date" attribute to content 

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#921]
## The Issue
The need to have a release date tag arose during LBRY YouTube sync discussions with @reillysmith .  Oftentimes users will want the need to display videos on a channel according to their release date. Right now, all videos are sorted by publish date, which equates to the block they were published or updated on - this may not always be the desired sort order.  

The requirement would be to add a Release Date attribute to uploaded content. If not populated, it should default to publish date (original block date if update later) - open to discussion. 

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by kauffj** [comment]
This issue was moved to lbryio/lbryschema#19
