### ISSUE TITLE
LBRY forgets specified destination filenames when daemon restarted

### ISSUE THREAD

**Issue by stevenmos** [lbryio/lbry#926]
## The Issue
If a file has been downloaded with a specified filename, after stopping and starting the daemon lbrynet-cli file_list shows the "suggested filename" in the "filename", and "download path" fields.  The name of the actual file in the download directory is unchanged.

### Steps to reproduce
1.  Download a file and specify a filename:
      lbrynet-cli get [name] --file_name="myname"
2.  Stop and start the daemon: lbrynet-cli daemon_stop; lbrynet-daemon &
3.  run lbrynet-cli flie_list | grep file_name  and contrast with ls /download/directory/

### Expected behaviour
When a destination filename is specified, lbrynet-cli file_list should show it, not the suggested one, regardless of whether the daemon has been restarted.

### Actual behaviour
After the daemon restarts, lbry forgets that a destination filename was specified.

## System Configuration
{
  "build": "release",
  "lbrynet_version": "0.15.2",
  "lbryschema_version": "0.0.10",
  "lbryum_version": "3.1.6",
  "os_release": "4.12.14-21.current",
  "os_system": "Linux",
  "platform": "Linux-4.12.14-21.current-x86_64-with-Solus-3-shannon",
  "processor": "",
  "python_version": "2.7.12"
}

- LBRY Daemon version: 
- LBRY App version:
- LBRY Installation ID:  
- Operating system:

**Comment by tzarebczan** [comment]
Can confirm this is occurring: 
```
    "download_directory": "C:\\Users\\SoloDolo\\Downloads",
    "download_path": "C:\\Users\\SoloDolo\\Downloads\\test.mp4",
    "file_name": "test.mp4",
```

After restart: 

 ```
   "download_directory": "C:\\Users\\SoloDolo\\Downloads",
    "download_path": "C:\\Users\\SoloDolo\\Downloads\\U9aHFLBVdt4.mp4",
    "file_name": "U9aHFLBVdt4.mp4",
```

**Comment by tzarebczan** [comment]
@stevenmos thanks for the report, please check out https://lbry.io/faq/tips

**Comment by stevenmos** [comment]
Thanks.  I found a workaround for myself but I didn't think it should work like that.

**Comment by tzarebczan** [comment]
Want to try looking into it and submitting a pr here?

**Comment by stevenmos** [comment]
I didn't do anything sophisticated.  In my script I already force the downloaded file name to come from the "name" field, rather than the "suggested_file_name".
I just made sure that when I list the files I still use "name" rather than "file_name", which changes.

**Comment by lyoshenka** [comment]
i believe this may be fixed by #505

**Comment by lyoshenka** [comment]
i meant #1025

**Comment by tzarebczan** [comment]
Closing, not happening anymore.
