### ISSUE TITLE
Move tests package into lbrynet package

### ISSUE THREAD

**Issue by akinwale** [lbryio/lbry#927]
At the moment, the `tests` package excluded in `setup.py` which makes it impossible to run the tests making use of the Twisted test runner on Android. The `tests` package needs to be moved into `lbrynet` so that it can be imported for testing on Android.

**Comment by akinwale** [comment]
Successfully moved, but need to fix the numerous pylint errors before creating a pull request.

**Comment by kaykurokawa** [comment]
closing because fix has been merged https://github.com/lbryio/lbry/commit/33a95abeacf8e22e58610a862b57c62aec518c0c
