### ISSUE TITLE
Invalid Invitation code from a correct code

### ISSUE THREAD

**Issue by 0x0482** [lbryio/lbry#93]
Looks like there is a problem happening to a lot of people in the last 2 days that they are receiving an invitation code on the email and when trying to activate it shows this error message: "You've entered an invalid code, or one that's already been claimed. Please check your code and try again". 
I have no idea why this is happening.. If anyone can explain a little bit about the invitation system and why this problem is occurring?

**Comment by jobevers** [comment]
Closing this as its old; please re-open if it still persists on the most recent version
