### ISSUE TITLE
Re-visit get_availability command functionality / accuracy 

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#942]
## The Issue
We used to utilize the [get availability](https://lbryio.github.io/lbry/cli/#get_availability) call on claim pages before allowing users to download content. We noticed that the results were very inconsistent and it was removed from the app.  This could have been due to the DHT/content availability issues, so we should revisit this function to see if it needs any changes and then determine if it should be used in the app again.

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by kauffj** [comment]
I'd advise a PyDoc change here in the interim, to indicate this function is experimental or not supported.

**Comment by alyssaoc** [comment]
@jackrobison can we revisit this after the network has stabilized?

**Comment by jackrobison** [comment]
@alyssaoc :+1:
