### ISSUE TITLE
Cannot stream/download content that was updated (if it was previously downloaded)

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#951]
## The Issue
Today I noticed I'm having trouble streaming lbry://one - the app didn't recognize it as a previously downloaded file, but I know I had it in the past and it shows up in my Downloads section. If I try to stream it, it also fails - just get's stuck on the loading icon after geting a completed notification and the daemon shows - `lbrynet.daemon.Daemon:1571: Already have a file for one`. If I click Download, it shows connecting and then goes back to showing the download button - the daemon shows the same message about having the file. This claim was recently updated by Oakie so I checked the file_list and noticed that the outpoint is incorrect on the broken install and shows correctly on working install (not sure how one updated but not the other).  I'm hoping the streaming issue is also related to an incorrect endpoint, but not sure.  Both installs had the file downloaded well before the outpoint was changed. 

So as a more general question, can we check the functionality of file_list and when/how it is updated? 

Update: Now I'm not even sure how the laptop received the updated endpoint. My current testing shows this will happen anytime a claim is updated and the filename remains the same. This causes a mess for anyone that downloaded the content but then the claim is updated - cannot download the new content without deleting the file manually (using file_delete, not sure about deleting the file in the downloads directory yet - haven't tested). 
main PC (broken)
```
  {
    "claim_id": "008401a48cecef2a13cf5376b696169bb36b18c6",
    "completed": true,
    "download_directory": "D:\\LBRY Downloads Main PC",
    "download_path": "D:\\LBRY Downloads Main PC\\Happy Working Song - Enchanted - Holly Oakey-lZ5ZL0VSlC4.mp4",
    "file_name": "Happy Working Song - Enchanted - Holly Oakey-lZ5ZL0VSlC4.mp4",
    "has_signature": false,
    "key": "abf7fb30e4bb9d683ffa635617ee0974",
    "message": null,
    "metadata": {
      "claimType": "streamType",
      "stream": {
        "metadata": {
          "author": "",
          "description": "All proceeds go to holly for buying toys, i will post the video with those toys on Xmas day",
          "language": "en",
          "license": "All rights reserved.",
          "licenseUrl": "",
          "nsfw": false,
          "preview": "",
          "thumbnail": "http://www.thetoydiscounter.com/happy.jpg",
          "title": "Holly singing The Happy Working Song",
          "version": "_0_1_0"
        },
        "source": {
          "contentType": "video/mp4",
          "source": "92b8aae7a901c56901fd5602c1f1acc0e63fb5492ef2a3cd5b9c631d92cab2e060e2a908baa922c24dee6c5229a98136",
          "sourceType": "lbry_sd_hash",
          "version": "_0_0_1"
        },
        "version": "_0_0_1"
      },
      "version": "_0_0_1"
    },
    "mime_type": "video/mp4",
    "name": "one",
    "outpoint": "8e5d6945d238e8508520364d5eae7885b0db15d77d6d5cffee3f860dc13f0b45:0",
    "points_paid": 0.0,
    "sd_hash": "92b8aae7a901c56901fd5602c1f1acc0e63fb5492ef2a3cd5b9c631d92cab2e060e2a908baa922c24dee6c5229a98136",
    "stopped": true,
    "stream_hash": "bb4dc73b33652ca5a2bbaecdbd36831a2301791967801576049644fd79f26d6b57c605702d0f15da7118505679d21a08",
    "stream_name": "Happy Working Song - Enchanted - Holly Oakey-lZ5ZL0VSlC4.mp4",
    "suggested_file_name": "Happy Working Song - Enchanted - Holly Oakey-lZ5ZL0VSlC4.mp4",
    "total_bytes": null,
    "written_bytes": 9227338
  }
```

Laptop(correct)
```
 {
    "claim_id": "008401a48cecef2a13cf5376b696169bb36b18c6",
    "completed": true,
    "download_directory": "C:\\Users\\SoloDolo\\Downloads",
    "download_path": "C:\\Users\\SoloDolo\\Downloads\\Happy Working Song - Enchanted - Holly Oakey-lZ5ZL0VSlC4.mp4",
    "file_name": "Happy Working Song - Enchanted - Holly Oakey-lZ5ZL0VSlC4.mp4",
    "has_signature": false,
    "key": "abf7fb30e4bb9d683ffa635617ee0974",
    "message": null,
    "metadata": {
      "claimType": "streamType",
      "stream": {
        "metadata": {
          "author": "",
          "description": "All proceeds go to holly for buying toys, i will post the video with those toys on Xmas day",
          "language": "en",
          "license": "All rights reserved.",
          "licenseUrl": "",
          "nsfw": false,
          "preview": "",
          "thumbnail": "http://www.thetoydiscounter.com/happy.jpg",
          "title": "Holly singing The Happy Working Song",
          "version": "_0_1_0"
        },
        "source": {
          "contentType": "video/mp4",
          "source": "92b8aae7a901c56901fd5602c1f1acc0e63fb5492ef2a3cd5b9c631d92cab2e060e2a908baa922c24dee6c5229a98136",
          "sourceType": "lbry_sd_hash",
          "version": "_0_0_1"
        },
        "version": "_0_0_1"
      },
      "version": "_0_0_1"
    },
    "mime_type": "video/mp4",
    "name": "one",
    "outpoint": "0a173a57e6949a06af01638fa1e53f84120ff6fc05083f3a3c60b6df1446347f:0",
    "points_paid": 0.0,
    "sd_hash": "92b8aae7a901c56901fd5602c1f1acc0e63fb5492ef2a3cd5b9c631d92cab2e060e2a908baa922c24dee6c5229a98136",
    "stopped": true,
    "stream_hash": "bb4dc73b33652ca5a2bbaecdbd36831a2301791967801576049644fd79f26d6b57c605702d0f15da7118505679d21a08",
    "stream_name": "Happy Working Song - Enchanted - Holly Oakey-lZ5ZL0VSlC4.mp4",
    "suggested_file_name": "Happy Working Song - Enchanted - Holly Oakey-lZ5ZL0VSlC4.mp4",
    "total_bytes": null,
    "written_bytes": 9227338
  }
```

### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by kaykurokawa** [comment]
https://github.com/lbryio/lbry/blob/master/lbrynet/daemon/Daemon.py#L1564
Is checking if it already has the file by looking up the file by claim ID. 
This is wrong, as updates preserve claim ID and could change the stream.

**Comment by tzarebczan** [comment]
I'll rename this issue to be more generic related to the download / file list issues.

**Comment by kauffj** [comment]
When a claim is updated but the claim id does not change, this is the publisher indicating that it is the same content that was there previously. Therefore the data should be re-downloaded, but there should be no subsequent charge for the download.

An update without a claim id change should be the equivalent of a fixing a typo (or, if you stretch it, making Greedo shoot first).

Right now more substantial edits may be taking place without a claim id change (imagine a user publishing a much different piece of content over `lbry://one`). This probably requires some updates to the publish, to indicate a certain publish to the same name should involve a regeneration of claim id.

**Comment by tzarebczan** [comment]
The main problem right now is that any edit to the claim changes the outpoint (since its a new tx), so we have these various downstream issues on the download and publishing side.  I agree that a new claim ID should be generated in certain instances -  sounds difficult to do automatically so will need to be a clearly explained user option.  

Would the re-download functionality be an app side issue or daemon also?
