### ISSUE TITLE
Allow multiple claims to the same name

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry#953]
Currently, the daemon treats any publish to an existing name as an edit. Instead, the daemon should support multiple publishes to the same claim name. 

spee.ch is severely hindered by this limitation, as it means each URL can only be used once.

**Comment by kauffj** [comment]
(I also thought this was already filed, but could not find it)

**Comment by alyssaoc** [comment]
@alyssaoc needs a priority

**Comment by eukreign** [comment]
@alyssaoc This is still a valid feature request and should be relatively easy to implement with the new wallet.
