### ISSUE TITLE
Channel import/export

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry#954]
## Story

As a content creator who had their content uploaded by LBRY, I want to get access to my channel in an easy way. I almost certainly don't want to republish/rekey the hundreds of videos that were published for me.

## Proposed Solution

Add two RPC calls: `channel_export` and `channel_import`:

- `channel_export` takes a channel name. it creates a single file that contains everything you need to own a channel (private key, certs, whatever info the import would need, etc)
- `channel_import` takes a path to a file and imports the channel contained in the file

Stretch goal: export can optionally take a password param to encrypt the channel file. then import would require that password.

**Comment by kauffj** [comment]
If this did not move any credits, but simply gave authorization to publish under an identity, could this be reduced to a single value?

**Comment by tzarebczan** [comment]
Also, depending on how the content was published (to a single address or multiple different addresses), those addresses would need to be available in the wallet for the user to see/edit them in their published area. Giving authorization is only part of the problem... I'm sure they want to see the published items as well.

**Comment by kauffj** [comment]
Good point. But if we imagine multiple channels being used inside of the same wallet, is it even possible to cleanly separate these via an export without also issuing blockchain transactions?

**Comment by lyoshenka** [comment]
What do you mean by "could this be reduced to a single value"?

Good point about the content. I believe that's gonna be part of importing the private key for the addresses involved. When you import the key, its like you made the transactions, and therefore the content should show up as if you published it.

If a single address was used to publish multiple channels, then you're right that we would need to re-key all the published content into its own address first, then export that address. For now, I'm ok with the daemon simply detecting this case and returning an error saying that this is not supported yet.

**Comment by kauffj** [comment]
By reduced to a single value I meant that could we reduce all that is needed to transfer a channel down to a single key. If so, this would mean it can be entered via a UI rather than requiring moving files.

**Comment by lyoshenka** [comment]
It may be possible, but it would be a long string.

**Comment by jackrobison** [comment]
`channel_export(<claim_id>)` could return the signing key as PEM encoded text, and `channel_import(<claim_id>, <private_key>)` could load it into the wallet.

To sign and make claims to the channel only the channel private key is needed, the channel claim does not have to be in the wallet.

**Comment by jackrobison** [comment]
added in lbryio/lbry#1003
