### ISSUE TITLE
Enhance blob_announce to use head blob only based on config setting

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#964]
## The Issue
Currently, clients are configured with the head blob announce setting which is used during automated announcements.  The blob_announce command was not updated to utilize this setting, which is especially important if using stream_hash / sd_hash. It should default to the client setting and possibly allow a -headblobonly (Y-default/N) parameter.

**Comment by eukreign** [comment]
@jackrobison does the new asyncio DHT solve this?
