### ISSUE TITLE
Don't store private IPs in the DHT

### ISSUE THREAD

**Issue by ordex** [lbryio/lbry#974]
IPs belonging to private classes should not be stored in the DHT as they won't be usable by other peers on the Internet.

Private classes are:
- 127.0.0.0/8
- 10.0.0.0/8
- 172.16.0.0/12
- 192.168.0.0/16

A warning informing the user about this misbehaviour should be printed if the node tries to store any of those IPs.

**Comment by lyoshenka** [comment]
@ordex there's a PR out to fix this, right?

**Comment by lyoshenka** [comment]
is it #1007 ?

**Comment by hellbeast222** [comment]
please help me get this thing off of my os

**Comment by ordex** [comment]
@lyoshenka correct, it's #1007

**Comment by alyssaoc** [comment]
@jackrobison please confirm new UPnP solution fixes this?

**Comment by jackrobison** [comment]
@alyssaoc I don't think this can happen now without running a custom dht node, intentionally choosing a LAN address (the upnp changes didn't effect this in either direction). Additionally, blocking or warning on LAN ips would complicate testing.
