### ISSUE TITLE
store RPC call should save the external IP instead of the packet sender IP

### ISSUE THREAD

**Issue by ordex** [lbryio/lbry#977]
When receiving a `store` RCP call, a node currently uses the datagram sender IP address to compute the data to append to the peer list for the given hash.
This means that if a peer receives a `store` from another node in the same LAN, it will save the LAN IP in the DHT. This is not correct as this IP won't be usable by other nodes in the DHT that are not in the same LAN.

A node handling a `store` should always save the external IP of the announcing node.
This probably means changing the packet format and ensuring that the external IP is sent along with the `store` request.

**Comment by ordex** [comment]
This issue is related to #974 as this is the logic for storing IPs in the DHT.

**Comment by lyoshenka** [comment]
does #1007 fix this?

**Comment by ordex** [comment]
@lyoshenka yes

**Comment by alyssaoc** [comment]
@jackrobison does the new UPnP solve this?

**Comment by jackrobison** [comment]
@alyssaoc no, but I'm not sure that this issue will actually happen anyway. The case that I imagine is broken is where a node is behind multiple layers of UPnP gateways, but that's an edge case probably not worrying about immediately. I'll test if the incoming ip of a node in our lan sending us a `store` is the external or lan ip when in mht this week.

**Comment by lyoshenka** [comment]
why is this a blocker?

**Comment by eukreign** [comment]
@jackrobison if this is a valid issue can we add integration tests for it?

**Comment by eukreign** [comment]
oop, didn't mean to close

**Comment by alyssaoc** [comment]
this is related to hole punching, which address and port you have vs what you expect to have
