### ISSUE TITLE
publish() does not execute until after all streams have been resumed

### ISSUE THREAD

**Issue by jackrobison** [lbryio/lbry#980]
The spee.ch `lbrynet-daemon` instance starts up quickly and starts accepting `publish` calls as expected. However, they do not execute until all of the streams in the file manager have been resumed - this adds considerable delay to publishes made to spee.ch shortly after a restart.

**Comment by MSFTserver** [comment]
also i uploaded to of the same images at different times to the same name during this process and after they bot they showed the same url, not sure if this will be an issue if 2 people try to post the same claim during this process with different images as mine were the same

**Comment by tzarebczan** [comment]
@MSFTserver just saw this while reviewing issues. If you can get this to reproduce consistently, please file an issue in the spee.ch repository.

**Comment by alyssaoc** [comment]
@hackrush01 Do the components updates fix this?

**Comment by hackrush01** [comment]
The publish commands still requires file manager component to be started. So it probably needs all the streams to be resumed. But I'm not sure if @jackrobison made some recent change to it which affects this.
