### ISSUE TITLE
Do not associate claim information with files 

### ISSUE THREAD

**Issue by kaykurokawa** [lbryio/lbry#981]
When calling API command file_list , various claim information is attached onto the file from the wallet

see Daemon._get_lbry_file_dict() : https://github.com/lbryio/lbry/blob/master/lbrynet/daemon/Daemon.py#L863

and ManagedEncryptedFileDownloader.load_file_attributes()
https://github.com/lbryio/lbry/blob/master/lbrynet/file_manager/EncryptedFileDownloader.py#L111

This is wrong, because the claim information at the time of download can be completely different from the claim information at the time of checking the claim information. Resulting in confusion and bugs when claims get updated and abandoned. Further more, files can and do exist without having any claim information attached to them at all (for example , files that have been uploaded to reflector. Calling file_list on reflector takes forever because it has to fetch all the claim information from lbryum-server since it doesn't have the information in the wallet cache). 

This has resulted in numerous bugs in the app side and daemon side, when claims get abandoned and updated ( see:  https://github.com/lbryio/lbry/issues/944, https://github.com/lbryio/lbry-app/issues/694 ) 

We need to completely remove claim information from the file_list and also file_delete API command. Below is the exact API change that will happen: 

Individual files in the output of API command file_list will no longer contain fields "name", "outpoint", "claim_id", "metadata", "channel_name", "has_signature", "signature_is_valid" 

 "claim_id", "outpoint", "name" is no longer a valid argument to search for files for API command file_list, file_delete, and file_reflect

**Comment by kauffj** [comment]
:+1: from me. This will be relatively trivial to adjust app-side.

**Comment by jackrobison** [comment]
merged here https://github.com/lbryio/lbry/commit/188822ef201d38b511472d01a1a7e370029e070a
