### ISSUE TITLE
Dynamic blob sizing?

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#982]
## The Issue
We should start thinking about a better way of splitting up blob files - dynamically and possibly based on file type (was thinking streamable videos would be handled differently if we ever think the in-app player would support seeking).  Currently, LBRY splits up all files into 2MB blobs.

One recent case that came up which prompted me to open this issue was the 1080p uploads of Cop Chronicles.  When trying to stream the files, the first 2MB chunk would come in, the file would play for a second and then pause because the 2nd blob was not yet completed.  This even happened on a fairly fast internet connection, but I could see it being even worse on slower ones.  As a temporary fix, we should resume playback on the app side when additional data is written (will open issue) 

Someone had mentioned taking a Fibonacci sequence approach to this and I came across this: https://patentimages.storage.googleapis.com/pdfs/US6018359.pdf. It might make sense for file types that are not streamable as you don't have to skip ahead as you would with a video (which our current in-app player does not support).

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by lyoshenka** [comment]
@tzarebczan good idea for the future, but we're not gonna be able to get to this for a while

**Comment by eukreign** [comment]
closing as we'll not get to it for a while
