### ISSUE TITLE
Issue template comment still refers to slack, rather than discord

### ISSUE THREAD

**Issue by stevenmos** [lbryio/lbry#986]
## The Issue

The issue template comment still refers to slack, rather than discord:
```
Thanks for reporting an issue to LBRY and helping us improve! 

To make it possible for us to help you, please fill out below information carefully.

Before reporting any issues, please make sure that you're using the latest version.
- App releases: https://github.com/lbryio/lbry-app/releases
- Standalone daemon: https://github.com/lbryio/lbry/releases

We are also available on Slack at https://slack.lbry.io    <----------
```

c.f. https://github.com/lbryio/lbry/pull/978

### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by lyoshenka** [comment]
:+1:
