### ISSUE TITLE
Issues catching up with blockchain and negative blocks behind

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry#991]
When starting the app this morning, I noticed some weird behavior while downloading block headers, with blocks behind briefly flashing to `None`.

Daemon output:

```
2017-11-07 09:04:37,687 INFO     lbrynet.core.Wallet:1261: Local Height: 268607, remote height: 268683, behind: 75
2017-11-07 09:04:51,350 INFO     lbrynet.core.Wallet:1261: Local Height: 268607, remote height: 268683, behind: 50
2017-11-07 09:05:37,606 INFO     lbrynet.core.Wallet:1261: Local Height: 268607, remote height: 0, behind: None
2017-11-07 09:05:37,739 INFO     lbrynet.core.Wallet:1261: Local Height: 268607, remote height: 268683, behind: 49
```

When behind was briefly `None`, the `status` call returned a negative block height:
```
{
  "id": 94,
  "jsonrpc": "2.0",
  "result": {
    "blockchain_status": {
      "best_blockhash": "ed75410d2bbb274b8e6c0267c2c13567b6ff64fba5aaa91a621e8122713b0f97",
      "blocks": 268607,
      "blocks_behind": -268607
    },
    "blocks_behind": -268607,
    "connection_status": {
      "code": "connected",
      "message": "No connection problems detected"
    },
    "installation_id": "5keR6W9oCaxVUeWDXuas1EL8jfc1MH7hMB8EAUx5tVpNKJb9xKe868vmMAJb3u9yeg",
    "is_first_run": false,
    "is_running": false,
    "lbry_id": "6a7Pv3y9g4NDv87FoptGwVJ81rDwdkrt7qbkx3ktU9yKWyeNB2LnZKnCFtaURKf16",
    "startup_status": {
      "code": "loading_wallet",
      "message": "Catching up with the blockchain"
    }
  }
}
```

**Comment by kaykurokawa** [comment]
This is actually normal behavior but somewhat confusing output so should be documented (maybe blocks_behind should be set to None in this case). It happens because below reason: 

local height is whatever it was when you last started
sever height is zero because lbryum has not yet recieved this information yet 
blocks behind is negative local height because it is calculated as server height - local height

**Comment by kauffj** [comment]
@kaykurokawa I would argue if it hasn't received server height yet then server height isn't zero, it's null/undefined. And null/undefined minus zero should also be null/undefined (if not an error outright).

**Comment by lyoshenka** [comment]
@eukreign will your lbryum work or victor's lbryumx work fix this? should I make a new label for "will be fixed by txlbryum/lbryumx changes" so we can check all these issues after your code is merged?

**Comment by alyssaoc** [comment]
@eukreign and @shyba Can you confirm this is no longer and issue?

**Comment by eukreign** [comment]
I have not experienced this issue in the new wallet. It defaults to downloading 2000 headers at a time, so most of the time when you sync it'll do so in a single request/response and the message is pretty clear of how many was downloaded and the new height.
