### ISSUE TITLE
Timeout missing on downloads that start, but don't complete due to missing blobs

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#995]
## The Issue
Downloads that start streaming but cannot complete due to missing blobs (or possibly other reasons?) never produce a timeout.  This causes the app to continually keep checking for additonal data which bogs it down (separate issue).  Also, I'd consider this a failure, but it's not logged as such in our statistics. 

One good example right now is:

lbry://cultural-appropriation-on-halloween#097a6365dc2c0327a030921047905a6ca3e251dc

### Steps to reproduce
1. Find content that's incomplete on the network (lbry://cultural-appropriation-on-halloween#097a6365dc2c0327a030921047905a6ca3e251dc)
2. Download / stream
3. Get's to a certain percentage but never finishes or times out

### Expected behaviour
Would time out and retry on restart or via retry button (separate issue logged)

### Actual behaviour
Stays in incomplete state and app keeps sending file_list requests until its closed. 

## System Configuration

 

- LBRY Daemon version: 0.18.1
- LBRY App version: 0.18.0rc2
- LBRY Installation ID:
- Operating system: Windows

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
This is still happening to files like lbry://vareprver which only a few blobs are hosted correctly.

**Comment by eukreign** [comment]
@jackrobison is this solved in the new async blob exchange implementation?
